//By greatguys1
//Best viewed in EditPlus with the ms.stx applied

//Generic menus

#scope server

{ game_menu_getoptions

	local L_PLAYER_ID PARAM1
	
	if ( QUEST_MODE equals QUEST_WAITING )
	{
		local reg.mitem.title QUEST_WAITING_TEXT
		local reg.mitem.type callback
		local reg.mitem.data L_PLAYER_ID
		local reg.mitem.callback quest_intro_check
		menuitem.register
	}
	else if ( QUEST_MODE equals QUEST_ASKING )
	{
		local reg.mitem.title QUEST_ASKING_TEXT
		local reg.mitem.type callback
		local reg.mitem.data L_PLAYER_ID
		local reg.mitem.callback quest_activate_check
		menuitem.register
	}
	else if ( QUEST_MODE equals QUEST_ACTIVE )
	{
		if ( QUEST_ACTIVE_TEXT !equals '0' )
		{
			if ( QUEST_SHOW_PROGRESS )
			{
				local L_QUEST_ACTIVE_TEXT QUEST_ACTIVE_TEXT
				stradd L_QUEST_ACTIVE_TEXT " ("
				stradd L_QUEST_ACTIVE_TEXT $int(QUEST_PROGRESS_VAR)
				stradd L_QUEST_ACTIVE_TEXT "/"
				stradd L_QUEST_ACTIVE_TEXT $int(QUEST_PROGRESS_MAX)
				stradd L_QUEST_ACTIVE_TEXT ")"
				local reg.mitem.title L_QUEST_ACTIVE_TEXT
			}
			else
			{
				local reg.mitem.title QUEST_ACTIVE_TEXT
			}
			local reg.mitem.type disabled
			menuitem.register
		}
	}
}