//This is an older script and may have some bad conventions as a result.

//Thothie - for MS 1.35 compatitbility - and because mini-bosses are kewl! ;)
//Notable Differences from Calrian <hp <gold sounds model size trigger text

//Bloodreaver (from Calrian)

{
   setvar ANIM_RUN walk
   setvar ANIM_WALK walk
   setvar ANIM_IDLE idle1
   setvard CAN_HUNT 1
   setvard HUNT_AGRO 0
   setvard ANIM_ATTACK attack1
	setvard MOVE_RANGE 40
   const ATTACK_DAMAGE 30
   setvard ATTACK_RANGE 100
   setvard ATTACK_HITRANGE 200
   const ATTACK_HITCHANCE 85%
   const SOUND_STRUCK1 garg/gar_pain1.wav
   const SOUND_STRUCK2 garg/gar_pain2.wav
   const SOUND_STRUCK3 garg/gar_pain3.wav
   const SOUND_PAIN garg/gar_pain3.wav
   const SOUND_ATTACK1 controller/con_attack1.wav
   const SOUND_ATTACK2 controller/con_attack2.wav
   const SOUND_DEATH garg/gar_die1.wav
   const SOUND_IDLE1 controller/con_attack3.wav
   const SOUND_SPAWN monsters/skeleton/calrian2.wav
   setvard MY_ENEMY enemy	//base_npc_attack - Premptive attack
   setvard RETALIATE_CHANCE 75%  //base_npc_attack - Automatically switch targets to the last damaging player
   setvard CAN_FLEE 0		//base_npc_attack - Whether I run away at low health
   setvard DROP_GOLD 		1
   setvard DROP_GOLD_MIN		100
   setvard DROP_GOLD_MAX		240
 
   //Precache
   precache SOUND_DEATH //This sound must be explicitly precached since
			//the play command for it isn't in this file (it's
			//in base_monster.script)
}

#include monsters/base_monster_new

{
   eventname npc_spawn

	setvard I_AM_TURNABLE 0

   name Blood Reaver
   roam 0
   hearingsensitivity 8
   setvard NPC_GIVE_EXP 200
   race undead
   setmodel monsters/skeleton3.mdl
   setmodelbody	1 0
   hp 2000
   width 64
   height 128
   takedmg all 0.65
	takedmg holy 2.0
	takedmg fire 0.0
	takedmg blunt 0.5
	setvard IMMUNE_FIRE 1
   setidleanim idle1
   setmoveanim ANIM_WALK
   playanim ANIM_IDLE
   setidleanim ANIM_IDLE
   roam 0

   volume 10
   playsound 2 SOUND_SPAWN
   giveitem scroll2_summon_undead
}

{ npcatk_targetvalidate

	if $get(ent_me,relationship,PARAM1) equals enemy
	roam 1
}

{ attack_1

   dodamage ent_lastseen ATTACK_HITRANGE ATTACK_DAMAGE ATTACK_HITCHANCE

   if( $rand(0,1) == 0 )
   {
   	volume 5
   	playrandomsound 2 SOUND_ATTACK1 SOUND_ATTACK2
   }
}

   //Hit by someone
{ npc_struck
 
   roam 1  
   volume 5
   playrandomsound 2 SOUND_PAIN SOUND_PAIN SOUND_STRUCK1 SOUND_STRUCK2 SOUND_STRUCK3
}

{ npc_death

   playsound 2 SOUND_DEATH
   playsound 2 SND_DEATH2
   usetrigger bloodreaver_die
   saytextrange 1024
   saytext After all this time, alas... I can rest.
}