//Map settings
{
	const MAP_NAME 		'edanasewers'
	const MAP_WEATHER 	"fog_green;fog_green;fog_green;fog_green;fog_red;fog_red"
	const MAP_ALLOWNIGHT 	0

	setvarg G_MAP_NAME "The Sewers of Edana"
	setvarg G_MAP_DESC "These sewers predate the town above by hundreds of years and are now the haunted remnants of a once great city"
	setvarg G_MAP_DIFF "Levels 5-10 / 50-100hp"
	setvarg G_WARN_HP 0 //Map is too low level to consider warning
}

#include worlditems/map_startup

{ [client] game_newlevel	//PARAM1 = Mapname

	//Setup map-specific reflections

	local reg.texture.name		'reflective'
	local reg.texture.reflect	1
	local reg.texture.reflect.blend	1
	local reg.texture.reflect.color	1;1;1;0.2
	local reg.texture.reflect.range	256
	local reg.texture.reflect.world	0
	local reg.texture.water		0
	registertexture
}
