#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(5,20)
	//           |Store name|  |Item name|  	|Quantity| |cost|
	addstoreitem  STORENAME      health_mpotion 	 1          0
	if ( $rand(1,15) == 1 ) addstoreitem STORENAME swords_nkatana 1 0
	addstoreitem  STORENAME      item_log	 1          0

	if ( $rand(1,25) == 1 ) callevent add_great_item
	
	if ( $rand(1,50) == 1 ) callevent add_epic_arrows
	if ( $rand(1,50) == 1 ) callevent add_epic_arrows
	if ( $rand(1,50) == 1 ) callevent add_epic_arrows
	if ( $rand(1,50) == 1 ) callevent add_epic_arrows
}
