#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(5,20)
	//           |Store name|  |Item name|  	|Quantity| |cost|
	addstoreitem  STORENAME      item_torch 	 1          0
	addstoreitem  STORENAME      axes_battleaxe 	 1          0
	addstoreitem  STORENAME      blunt_hammer1 	 1          0
	addstoreitem  STORENAME      shields_buckler 	 1          0
	
	if ( $rand(1,10) ) addstoreitem  STORENAME      shields_lironshield 	 1          0
}