{
	const STORENAME eight
}

#include items/base_treasurechest

{ treasure_spawn

   name a|Treasure Chest STORENAME
   //gold $rand(1,15)
}

{ chest_additems

	callevent add_gold 5 15 5
	//           |Store name|  |Item name|  	|Quantity| |cost|
	addstoreitem  STORENAME      health_mpotion 	 1          0
	callevent get_chance 5 50 100 50 //<single_player%> <%chance_per_player> [max_chance] [hp_req] //returns GIVE_PRIZE and TC_CHANCE   
	if ( GIVE_PRIZE ) addstoreitem STORENAME swords_nkatana 1 0
	addstoreitem  STORENAME      item_log	 1          0

	if ( game.players.totalhp >= 800 )
	{
		callevent add_epic_arrows
		callevent add_epic_arrows
		callevent add_epic_arrows
		callevent add_epic_arrows
		callevent add_great_item
	}
}
