{
	const STORENAME one
}

#include items/base_treasurechest

{ treasure_spawn

   name a|Treasure Chest STORENAME
   //gold $rand(1,15)
}

{ chest_additems
   
	callevent get_players 50
	if ( TC_NPLAYERS > 1 ) callevent add_gold 5 50 5

	if ( TC_NPLAYERS == 1 ) gold $rand(1,5)

   //           |Store name|  |Item name|  	|Quantity| |cost|
   if ( $rand(1,2) == 1 ) addstoreitem  STORENAME       scroll2_glow 	 1          0
   addstoreitem  STORENAME       mana_mpotion 	 	1          0
}