{
	const STORENAME eleven
}

#include items/base_treasurechest

{ treasure_spawn

   name a|Treasure Chest STORENAME
   //gold $rand(1,4)
}

{ chest_additems
   
   //           |Store name|  |Item name|  	|Quantity| |cost|
	callevent add_gold 5 50 5 
   	addstoreitem  STORENAME health_lpotion 	 1          0
   	addstoreitem  STORENAME	smallarms_dirk   1	    0
	if ( $rand(1,30) == 1 ) addstoreitem  STORENAME	scroll2_summon_rat   1	    0
}