// *** This script is for Darrelin in the Dark Caves ***
//

// Spawn properties
#scope server

{
	const NO_JOB 1
	const NO_RUMOR 1 
	const NO_HAIL 1
}

{ [shared] game_spawn

	setvard REQ_QUEST_NOTDONE 1

   hp 20/20    
   gold 3    
   name Darrelin
   //ov 30
   width 32
   height 72
   race human
   roam 0
   setmodel    npc/human1.mdl
   setmoveanim walk
   invincible  1
   setvar      CANCHAT 1

   catchspeech say_hi hello hail greet hi

   catchspeech say_orc orc

   catchspeech say_myth myth   

   catchspeech say_acting act

   catchspeech say_orc orc

   catchspeech say_myth myth   

   catchspeech say_acting act

   catchspeech say_name name

   catchspeech say_goblins goblin

   catchspeech say_river river
}

#include [server] monsters/base_chat

{ say_hi
	if ( $get(PARAM1,isplayer) )
	{
		local L_LAST_SPOKE PARAM1
	}
	else
	{
		local L_LAST_SPOKE $get(ent_lastspoke,id)
	}

	if ( BUSY_CHATTING )
	{
		//callevent 1.0 say_hi
		callevent chat_warning L_LAST_SPOKE
	}
	if !BUSY_CHATTING

	playsound 2 10 voices/mscave/actor-say_hi.wav

	setvard NO_MOUTH_MOVE 1
	say [.3] [.1] [.1] [.3] [.02] [.2] [.1] [.3] [.3] [.3] [.1] [.1] [.1] [.1] [.1] [.1] [.1] [.1]

	setvard CHAT_STEP1 "Hail Traveller! Welcome to... THE DARK CAVES......!"
	setvard ANIM_STEP1 studycart
	setvard CHAT_DELAY_STEP1 9.4

	callevent 9.3 restore_mouth_move

	setvard CHAT_STEP2 "Sorry about that, I used to be an [actor]... I still am, in a way."
	setvard CHAT_DELAY_STEP2 4.7

	setvard CHAT_STEP3 "Anyway, the [Orcs] have taken over the caves, so be careful if you plan on going through them."
	setvard CHAT_DELAY_STEP3 7.0

	setvard CHAT_STEP4 "You may also be interested to hear about a [goblin] town near here."
	setvard CHAT_DELAY_STEP4 3.0

	setvard CHAT_STEPS 4

	callevent chat_loop
}

{ restore_mouth_move
	setvard NO_MOUTH_MOVE 0
	callevent bchat_auto_mouth_move 4.7
}

{ say_orc
	if ( BUSY_CHATTING )
	{
		callevent 1.0 say_orc
		callevent chat_warning $get(ent_lastspoke,id)
	}
	if !BUSY_CHATTING 

	playsound 2 10 voices/mscave/actor-say_orc.wav

	setvard CHAT_STEP1 "Well, as you probably know, the Orcs have been growing in number faster than usual."
	setvard CHAT_DELAY_STEP1 5.4

	setvard CHAT_STEP2 "Since they therefor need more land they use shamans to come in and lock down an area using magic."
	setvard CHAT_DELAY_STEP2 5.0

	setvard CHAT_STEP3 "This allows their warriors to march in and absolutely massacre all the men, women, and children of entire towns. It's terribly frightful!"
	setvard CHAT_DELAY_STEP3 8.6

	setvard CHAT_STEP4 "Unfortunately for us, this is a rather successful tactic, except... Eh, there is one thing..."
	setvard CHAT_DELAY_STEP4 7.6

	setvard CHAT_STEP5 "Theres a [myth] of sorts surrounding these caves, and I don't think the orcs are using the caves just to store their loot."
	setvard ANIM_STEP5 pondering
	setvard CHAT_DELAY_STEP5 6.3

	setvard CHAT_STEPS 5

	callevent chat_loop
}

{ say_myth

	if ( BUSY_CHATTING )
	{
		callevent 1.0 say_myth
		callevent chat_warning $get(ent_lastspoke,id)
	}
	if !BUSY_CHATTING

	playsound 2 10 voices/mscave/actor-say_myth.wav

	setvard CHAT_STEP1 "Well, theres supposed to be some kind of building that's tucked away deep inside the caverns."
	setvard CHAT_DELAY_STEP1 6.3

	setvard CHAT_STEP2 "It's probably ancient history now, but it was a fortress literally powered by magic itself, except..."
	setvard CHAT_DELAY_STEP2 5.7

	setvard CHAT_STEP3 "I can't help wondering why it isn't active... Nobody seems to know why..."
	setvard CHAT_DELAY_STEP3 4.9

	setvard CHAT_STEP4 "Though the path to the fort is clear, its silent, closed, so I guess whatever's in there, we're doomed to it... I guess."
	setvard CHAT_DELAY_STEP4 6.4

	setvard CHAT_STEPS 4

	callevent chat_loop
}

{ say_acting

	if ( BUSY_CHATTING )
	{
		callevent 1.0 say_acting
		callevent chat_warning $get(ent_lastspoke,id)
	}
	if !BUSY_CHATTING

	playsound 2 10 voices/mscave/actor-say_acting.wav

	setvard CHAT_STEP1 "Oh I'm sure you must've heard the [name] of Darrelino the Greatest Actor in ALL of Daragoth, nay the WORLD!"
	setvard ANIM_STEP1 converse1
	setvard CHAT_DELAY_STEP1 5.5

	setvard CHAT_STEP2 "You haven't!?!..."
	setvard CHAT_DELAY_STEP2 2.5

	setvard CHAT_STEP3 "Oh well, that's your loss then."
	setvard ANIM_STEP3 no
	setvard CHAT_DELAY_STEP3 2.8

	setvard CHAT_STEPS 3

	callevent chat_loop
}

{ say_name

	if ( BUSY_CHATTING )
	{
		callevent 1.0 say_name
		callevent chat_warning $get(ent_lastspoke,id)
	}
	if !BUSY_CHATTING

	playsound 2 10 voices/mscave/actor-say_name-say_script.wav

	setvard CHAT_STEP1 "Well, my stage name is Darrelino Var and I happen to think it's a very good name, thank you very much!"
	setvard CHAT_DELAY_STEP1 5.6

	setvard CHAT_STEP2 "Too bad I can't practice for the big performance! I don't have my script anymore! I used to go practice my lines in the forest, you see."
	setvard CHAT_DELAY_STEP2 8.4

	setvard CHAT_STEP3 "...and then one night, as I was practicing my lines... Something attacked me!"
	setvard CHAT_DELAY_STEP3 4.3

	setvard CHAT_STEP4 "It lunged at me! I had no idea what it was. I thought it was a thief, maybe waiting in the shadows to steal all my belongings!"
	setvard CHAT_DELAY_STEP4 5.9

	setvard CHAT_STEP5 "So I managed to run, away from it, but then I heard all kinds of sounds rustling behind me in the bushes."
	setvard CHAT_DELAY_STEP5 5.4

	setvard CHAT_STEP6 "So did the first thing that came to mind: I hid all my belongings in a hollow tree, and covered it with some leaves."
	setvard CHAT_DELAY_STEP6 6.1

	setvard CHAT_STEP7 "But, on the way out, nobody came and attacked me! I turned around to look, and I could swear I saw pale figures walking in the forest. So I turned and ran away."
	setvard CHAT_DELAY_STEP7 9.2

	setvard CHAT_STEP8 "I hear it's really dangerous in the forest now. It turns out that what attacked me wasn't actually a thief, but the living dead itself!" //had to cut this one short, message too long
	setvard CHAT_DELAY_STEP8 12.3

	setvard CHAT_STEP9 "Oh do you think you could find my manuscript for me? I'm sure it's still in that hollow tree covered by the leaves." //same here
	setvard CHAT_DELAY_STEP9 10.1

	setvard CHAT_STEPS 9

	callevent chat_loop
}


{ say_goblins

	if ( BUSY_CHATTING )
	{
		callevent 1.0 say_goblins
		callevent chat_warning $get(ent_lastspoke,id)
	}
	if !BUSY_CHATTING

	playsound 2 10 voices/mscave/actor-say_goblins.wav

	setvard CHAT_STEP1 "The Goblins have a town carved into the mountains through the caves, near a [river] dried up by a dam."
	setvard CHAT_DELAY_STEP1 6.0

	setvard CHAT_STEP2 "You'll find one of the goblins to be an extremely tough opponent.... He seems to be their leader, of sorts"
	setvard CHAT_DELAY_STEP2 5.8

	setvard CHAT_STEP3 "It wouldn't be so bad but they like attacking in large groups! So, do be careful."
	setvard CHAT_DELAY_STEP3 6.4

	setvard CHAT_STEPS 3

	callevent chat_loop
}

{ say_river

	if ( BUSY_CHATTING )
	{
		callevent 1.0 say_river
		callevent chat_warning $get(ent_lastspoke,id)
	}
	if !BUSY_CHATTING

	playsound 2 10 voices/mscave/actor-say_river.wav

	setvard CHAT_STEP1 "I learnt recently that the Orcs have decided to block the river. It's a prelude to invading the Goblins to weaken them."
	setvard CHAT_DELAY_STEP1 5.4

	setvard CHAT_STEP2 "I don't know which is worse... Those damned Goblins or the Orcs!"
	setvard CHAT_DELAY_STEP2 3.0
	
	setvard CHAT_STEPS 2

	callevent chat_loop
}

{ give_manuscript

	if ( $get(PARAM1,isalive) )
	{
		setvard QUEST_COMPLETER PARAM1
		setvard REQ_QUEST_NOTDONE 0
	}
	if ( BUSY_CHATTING )
	{
		callevent 1.0 give_manuscript
		callevent chat_warning $get(PARAM1,id)
	}
	if !BUSY_CHATTING

	playsound 0 10 voices/mscave/actor-give_manuscript.wav

	setvard CHAT_STEP1 "You found my manuscript! Thank you so much, "
	stradd CHAT_STEP1 $get(QUEST_COMPLETER,name)
	stradd CHAT_STEP1 ", I can continue practicing!"
	setvard ANIM_STEP1 eye_wipe
	setvard CHAT_DELAY_STEP1 4.5

	setvard CHAT_STEP2 "Oh, I should reward you... Wait... Here, take this... It's a gold pouch. It's not much, but it's the best I can do."
	setvard CHAT_DELAY_STEP2 6.4
	setvard CHAT_EVENT_STEP2 give_manuscript_reward

	setvard CHAT_STEPS 2

	callevent chat_loop
}

{ give_manuscript_reward
	offer QUEST_COMPLETER gold $rand(30,60)
}

{ game_menu_getoptions
	local reg.mitem.title	"Say Hello"
	local reg.mitem.type	say

	local l.say $rand(1,4)
	if( l.say == 1 )	local reg.mitem.data 'Hello'
	else if( l.say == 2 )	local reg.mitem.data 'Hi'
	else if( l.say == 3 )	local reg.mitem.data "Hail" 
	else if( l.say == 4 )	local reg.mitem.data 'Greetings!'
	menuitem.register

	if( $item_exists(PARAM1,item_manuscript) )
	{
		local reg.mitem.title 	"Return manuscript"
		local reg.mitem.type 	payment
		local reg.mitem.data 	item_manuscript
		local reg.mitem.callback give_manuscript
		menuitem.register
	}
}

{ chat_warning
	if game.time > NEXT_CHAT_WARN
	setvard NEXT_CHAT_WARN game.time
	add NEXT_CHAT_WARN 20.0
	dplayermessage PARAM1 "Darrelin is still chatting about something else..."
}