{ game_spawn
	if ( !$get(GAME_MASTER,exists) ) createnpc game_master $vec(20000,-10000,-20000)

	fly 1
	roam 0
	gravity 0
}

{ game_postspawn //<unused> <unused> <unused> <index;trigger>

	local TOKEN_PARAMS PARAM4
	local MY_LOC $get(ent_me,origin)
	callexternal GAME_MASTER set_shad_tele_point MY_LOC $get_token(TOKEN_PARAMS,0) $get_token(TOKEN_PARAMS,1)
	callevent 1.0 remove_me
}

{ remove_me
	deleteent ent_me
}
