{
	const NO_RUMOR 1
	const NO_JOB 1
}

#include monsters/base_chat

{ spawn

   hp		1
   name		Captain Charon
   //fov		180
   width	32
   height	72
   race		beloved
   roam		0
   setmodel    	npc/human1.mdl
   invincible  	1
   setmodelbody 0 1
   setmodelbody 1 2

   setvar SOUND_IDLE1 voices/human/male_idle4.wav
   setvar SOUND_IDLE2 voices/human/male_idle5.wav
   setvar SOUND_IDLE3 voices/human/male_idle6.wav


   catchspeech say_hi hi hello hail greet 'ello j0
	catchspeech say_orc orc
	callevent 0.1 post_spawn
}

{ post_spawn
	setvard ORC_TIME game.time
	add ORC_TIME 120.0
}

{ say_hi

	if ( game.time < ORC_TIME )
	{
		playanim critical pondering
		saytext Oh, I don't like this. It's far too quiet... No one in sight. Something is up, something BAD.
	}

	if ( game.time >= ORC_TIME )
	{
		playanim once checktie
		if ( $get(PARAM1,isalive) ) callevent face_speaker PARAM1
		if ( $get(ent_lastspoke,isalive) ) callevent face_speaker $get(ent_lastspoke,id)
		saytext Orcs!? Blast! Get in there and see if you can save any potential customers!
		saytext I'll stay here and guard the ship.
	}
}

{ say_orc
	playanim critical pondering2
	if ( $get(ent_lastheard,isalive) ) callevent face_speaker $get(ent_lastspoke,id)
	saytext Awfully brazen these days. Orcs in Helena is one thing... Orcs in Ara is unheard of!
}

{ game_menu_getoptions

	local reg.mitem.title 	"Sail Back to Deralia"
	local reg.mitem.type 	callback
	local reg.mitem.callback vote_deralia
	menuitem.register
}

{ vote_deralia
	saytext I suppose this town is a bust - sorry for wasting your time.
	usetrigger touch_trans_deralia
	gplayermessage PARAM1 Starting AMX vote for Deralia...
}
