//Thothie mscave almost entirely underground - no rail plzktnx
//Setup the map's weather
//
{ [shared]

	const MAP_NAME 		'highlands_msc'
	const MAP_WEATHER 	"clear;clear;clear;clear;clear;clear"
	const MAP_ALLOWNIGHT 	1

	setvarg G_MAP_NAME "Curse of the Bear Gods: Highlands by Crow"
	setvarg G_MAP_DESC "These tall mesas hold many secrets and many orcs."
	setvarg G_MAP_DIFF "Levels 15-25 / 150-400hp"
	setvarg G_WARN_HP 150
}

#include worlditems/map_startup
