{
	const FX_SCRIPT none
	setvar ANIM_IDLE 	iceblade_idle
	const SPAWNER_MODEL	weapons/P_weapons1.mdl
	const MODEL_OFSET	8
	const SOUND_SPAWN 	magic/ice_powerup.wav
	const SPELL_MAKER_HEIGHT 32 //this SHOULD be half player height, but comes up at eye level as intended :\

	const REMOVE_DELAY 5.0
	const SHOW_FX 0
	const NO_FADE 0

	const FX_GLOW 1
	const GLOW_COLOR (128,128,255)

	precache SOUND_SPAWN
}

#include monsters/companion/spell_maker_base