// *** Sitting human script ***
//

{ 
	const NO_CHAT 1
}

#include monsters/base_npc

{ npc_spawn

   hp		1
   width	32
   height	72
   race		human
   name		Commoner
   roam		1
   setmodel	npc/human1.mdl
   setmodelbody 0 $rand(0,2)
   setmodelbody 1 $rand(0,5)
   setmoveanim	coffee
   invincible	1
}

{
   repeatdelay 30

  see ally 128
  setmovedest ent_lastseen 128
  volume 2
  say chitchat[50] *[20] *[55] *[55] *[23] *[22]
}