// Harbor Master
#include monsters/base_chat
{ spawn

	hp		1
	name		Captain Charon
	//fov		180
	width	32
	height	72
	race		beloved
	roam		0
	setmodel    	npc/human1.mdl
	invincible  	1
	setmodelbody 0 1
	setmodelbody 1 2

	setvar SOUND_IDLE1 voices/human/male_idle4.wav
	setvar SOUND_IDLE2 voices/human/male_idle5.wav
	setvar SOUND_IDLE3 voices/human/male_idle6.wav


	catchspeech say_hi hi hello hail greet ello j0
	catchspeech say_job job work money gold
	catchspeech say_ship boat ship
	catchspeech say_ara ara
	catchspeech say_rumour rumours news happenings rumour rumor
}

{ say_rumor
	callevent say_rumour //spellinks
}

//Idling
{ idle

   repeatdelay $randf(30,40)
   volume 3
   playrandomsound 2 SOUND_IDLE1 SOUND_IDLE2 SOUND_IDLE3
}

{ say_hi

  saytext "Ahoy! What you doin' around the harbor mate?"
}
{ gossip_1

  saytext "The winds be tellin' me about some trouble around here."
}

//Rumours
{ say_rumour
  playanim once pondering
  saytext Rumour has it, the wind will be changing to the other side. Aye.
}
//Job
{ say_job
	saytext "I've got a shipment to get to Ara, could always use some good hands."
	callevent 2 say_job2
}

{ say_job2
	saytext Business has been mighty slow, so the best I can offer for a wage is free passage.
}

//Ship
{ say_ship
   saytext "That ship can take you out into the sea if you want. Joins up with Ron's Galleon about 20 leagues out."
   calleventtimed 4 say_ship2
}
{ say_ship2
   saytext "But beware, it be a crazy place out thar!"
   calleventtimed 2 say_ship3
}
{ say_ship3
	saytext "This time of year be icy, so the only place I can trade goods is Port Ara."
	calleventtimed 2 say_ship4
}
{ say_ship4
	saytext "Ye are welcome to come along, if ye like."
}

{ game_menu_getoptions

	local reg.mitem.title "Join Crew"
	local reg.mitem.type callback
	local reg.mitem.callback vote_ara
	menuitem.register
}

{ vote_ara
	saytext "It'll be a fine thing indeed to have ye aboard."
	callexternal GAME_MASTER gm_create_vote gm_votemap "Yes!:oceancrossing;No!:0" "Do you wish to travel the ocean blue?"
	callexternal players ext_set_map oceancrossing from_deralia from_deralia
}

{ say_ara
	saytext "It's a prosperous little trade town up the coast, last one before Verath."
	callevent 2 say_ara2
}
{ say_ara2
	saytext "Too dangerous to go any farther than that with the ice flows this time of year."
	callevent 2 say_ara3
}
{ say_ara3
	saytext "I could use a hand with the boat. Would ye be volunteering?"
}