//Map settings
//
{ [shared]

	const MAP_NAME 		'deralia'
	const MAP_WEATHER 	clear;clear;clear;clear;clear;fog_blue
	const MAP_ALLOWNIGHT 	0

	setvarg G_MAP_NAME "The City of Deralia"
	setvarg G_MAP_DESC "The Human capital is known as the Jewel of Daragoth."
	setvarg G_MAP_DIFF "(Beginner/Safe Area)"
	setvarg G_WARN_HP 0
}

#include worlditems/map_startup

{ [client] game_newlevel	//PARAM1 = Mapname
	//Setup map-specific reflections

	local reg.texture.name		'reflective'
	local reg.texture.reflect	1
	local reg.texture.reflect.blend	1
	local reg.texture.reflect.color	1;1;1;0.4
	local reg.texture.reflect.range	512
	local reg.texture.reflect.world	1
	local reg.texture.water		0
	registertexture
}
