//Map settings
//
{ [shared]

	const MAP_NAME 		'deralia'
	const MAP_WEATHER 	clear;clear;clear;clear;clear;fog_blue
	const MAP_ALLOWNIGHT 	0

	setvarg MAP_CON 1

	setvarg G_MAP_NAME "The City of Deralia"
	setvarg G_MAP_DESC "Known as the Jewel of Daragoth, the human capital of Deralia is the largest city in the lands"
	setvarg G_MAP_DIFF "(Beginner/Safe Area)"
}

#include worlditems/map_startup

{ [client] game_newlevel	//PARAM1 = Mapname

	if PARAM1 equals MAP_NAME

	//Setup map-specific reflections

	local reg.texture.name		'reflective'
	local reg.texture.reflect	1
	local reg.texture.reflect.blend	1
	local reg.texture.reflect.color	1;1;1;0.4
	local reg.texture.reflect.range	512
	local reg.texture.reflect.world	1
	local reg.texture.water		0
	registertexture
}
