// Novice alchemist by Dridmar

{
	setvar STORE_NAME Alchemy
	setvar STORE_TRIGGERTEXT "store buy purchase"
	setvar STORE_SELLMENU 0
	const NO_JOB 1
	const NO_HAIL 1
}

#include monsters/base_npc
#include monsters/base_chat
#include monsters/base_npc_vendor
#include monsters/base_npc_vendor_confirm

{ game_spawn

	hp 25
	gold 0
	name Potion Seller
	width 32
	height 72
	race human
	roam 0
	setmodel npc/human1.mdl
	invincible 1
	
	catchspeech say_easteregg strongest
}

{ say_easteregg 
	playanim once converse1
	callevent bchat_mouth_move
	playsound 5 10 voices/deralia/potiondeny.wav
	saytext My potions are too strong for you, traveller.
	}