//PARAM1 == Duration
//PARAM2 == Damage accept ratio (1.0: accept all 0.0: Accept none)

{    [server]
   const EFFECT_ID         effect_iceshield
   const EFFECT_NAME      "Ice Shield"
   const EFFECT_ACTIONTYPE      nostack
   const EFFECT_SCRIPT      $currentscript

   setvard game.effect.id      EFFECT_ID
   setvard game.effect.displayname   EFFECT_NAME
   setvard game.effect.type   EFFECT_ACTIONTYPE
}

#include effects/effect_base

{    [server] game_activate

   setvard local.effect.duration    PARAM1
   setvard local.effect.damage    PARAM2

   if ( $get(ent_me,isplayer) ) clientevent new ent_me $currentscript local.effect.duration
   setvard local.effect.clientscript game.script.last_sent_id

   local GLOW_TARG $get(ent_me,id)
   //if ( $get(GLOW_TARG,isplayer) ) local GLOW_TARG $get(ent_me,scriptvar,MY_BODY)
   effect glow GLOW_TARG (0,0,192) 72 local.effect.duration local.effect.duration
   playsound game.sound.item game.sound.maxvol magic/heal_strike.wav

   if ( $get(ent_me,isplayer) )
   {
      hud.addstatusicon ent_me alpha_iceshield iceshield local.effect.duration
   }

   gplayermessage $get(ent_me,id) You are protected by a shield of ice.
   callexternal $get(ent_me,id) ice_shield_on local.effect.duration

   callevent local.effect.duration effect_die
}

{ check_death

   local TIME_REMAIN $get(ent_me,scriptvar,ICE_SHIELD_TIME)
   if ( TIME_REMAIN > 1 )
   {
      add TIME_REMAIN 1
      callevent TIME_REMAIN check_death
   }
   if TIME_REMAIN <= 1
   callevent effect_die
}

{    [server] game_damaged

   if PARAM2 > 0

   clientevent update ent_me local.effect.clientscript shield_absorb
   return local.effect.damage

   volume 5
   playsound 2 player/pl_metal2.wav
}



{    [shared] effect_die

   callexternal $get(ent_me,id) ice_shield_off
   volume 5
   playsound 2 debris/bustglass2.wav
   effect tempent trail blueflare1.spr $relpos(0,0,0) $relpos(0,0,40) 10 2 5 10 20
   bplayermessage $get(ent_me,id) Your ice shield has collapsed!
}

{ ice_shield_explode
	callevent effect_die
}
// ===========
// Client Side
// ===========

{   [client]
   const BURN_SCREEN_DELAY      0.5
   const BURN_SCREEN_ALPHA      40
}

{   [client] client_activate

   callevent PARAM1 effect_die
}

{   [client] shield_absorb

   setvard game.cleffect.screenfade.newfade 1
   setvard game.cleffect.screenfade.alphalimit BURN_SCREEN_ALPHA   //Only use this fade if current fade is under this limit
   setvard game.cleffect.screenfade.color (0,0,192)
   setvard game.cleffect.screenfade.alpha BURN_SCREEN_ALPHA
   setvard game.cleffect.screenfade.duration BURN_SCREEN_DELAY
   setvard game.cleffect.screenfade.blendduration BURN_SCREEN_DELAY
   setvard game.cleffect.screenfade.type fadein
}
