{
	const CHAT_AUTO_HAIL 1
	
	const SKEL_HP 1000
	const ATTACK_HITCHANCE 80%
	const ATTACK_DAMAGE_LOW 20
	const ATTACK_DAMAGE_HIGH 50
	setvard NPC_GIVE_EXP 400
	
	const SKEL_RESPAWN_CHANCE 0
	const SKEL_RESPAWN_LIVES 0

	setvard DROP_GOLD 1
	setvard DROP_GOLD_MIN 10
	setvard DROP_GOLD_MAX 15
}

#include monsters/base_chat_array
#include monsters/skeleton_base

{ skel_setup_body

	name "The Survivor|Alfgar"
	name_unique alfgar
	
	invincible 1
	race beloved
	
	roam 0
	
	setmodel npc/guard1.mdl
	playanim hold 89
	
	width 32
	height 72
	
	menu.autoopen 1

	catchspeech say_madness madness
	catchspeech say_lost lost
}

{ say_hi

	if !ZOMBIFIED
	if !CHAT_BUSY
	callevent chat_now "URDUAL'S BEARD!!! Adventurers? It's so good to see a friendly face here."
	callevent chat_now "Well, may this humble soldier welcome you to Idemark's Tower."
	callevent chat_now "My platoon was sent here to gather reconnaissance on the area, to relay to King Deralia our standing here."
	callevent chat_now "This tower, it seems to be an anchor for the [Lost], a baited hook in a dark ocean that draws predators unknown to us mortals."
	callevent chat_now "Evil energy lurks here, as my dear friends and I found out the hard way. Please heed my warnings, take care to not join the Undead or Lost armies here."
	callevent chat_now "My soldiers were overtaken by a [madness], once we fought our way towards the inner courtyard."
	callevent chat_now "I began to feel it myself, a resonating hum, drawing me deeper, tickling my brain..."
	callevent chat_now "No. I can't return. If you absolutely must venture forth, I would suggest using the highest caution."
}

{ say_lost
	if !ZOMBIFIED
	if !CHAT_BUSY
	callevent chat_now "Makes me wish that I had more of an interest in our histories growing up."
	callevent chat_now "I can tell you that this name is misleading. They are purposeful creatures, of that I am sure."
}

{ say_madness
	if !ZOMBIFIED
	if !CHAT_BUSY
	callevent chat_now "The sight of it is seared in my mind. Even when I blink, I am haunted by flashes of the scene."
	callevent chat_now "It was slow to onset at first, some of the men were confused, and had to be turned toward the fight."
	callevent chat_now "Before long they were digging at their wounds. Have you ever dug out a splinter, me lad?"
	callevent chat_now "I imagine it was like that burning, hurting desire to be freed of something... foreign to yourself."
	callevent chat_now "There are a lot of fates worse than death to be found here."
	callevent chat_now "I'm not ashamed to say that I screamed and took off running. By that point, I was the only one hanging onto any sanity, though I fear I speak too soon."
}

{ ext_zombify //trigger hostile & undead

	if !ZOMBIFIED
	setvard ZOMBIFIED 1
	setvard CHAT_MENU_ON 0 //disable say_hi
	
	setmodel monsters/skeleton2.mdl
	setbbox npcsize
	
	roam 1
	race undead
	takedmg holy 1
	invincible 0
}