// Guard

{
   setvar	ATTACK_RANGE 150
   setvar	MOVE_RANGE 90
   setvar	CAN_ATTACK 0
   setvar	ATTACK_PERCENTAGE 95%
   setvar	ANIM_WALK walk
   setvar	ANIM_RUN run
   setvar	ANIM_ATTACK attack
   setvar	CAN_HUNT 0
   setvar	CAN_FLEE 0
   setvar	CAN_RETALIATE 1
   setvar	RETALIATE_CHANGETARGET_CHANCE 75%
}

#include monsters/base_npc_attack

{
   eventname npc_spawn

   hp		100/100	
   gold		10	
   //ov		180
   width	32
   height	72
   race		neutral
   name	        Guard
   roam		1
   setmodel	npc/guard1.mdl
   setmoveanim	walk
   invincible	0

}

// Greet player and other NPCs
{

   repeatdelay 30

   see ally 128

   setmovedest ent_lastseen 128

   volume 2
   say hello1[50] *[20] *[55] *[55] *[23] *[22]
}

{
   // Deal damage
   eventname attack_1

   dodamage ent_lastseen ATTACK_RANGE $randf(5.0,8.0) ATTACK_PERCENTAGE
}

{
   eventname npc_struck

   setvard CAN_STTACK 1
}