//Crest Master by Thothie, for giving people crests on 

{
   eventname spawn

   hp 1
   gold 0
   name Fenrin, the Crest Keeper
   //ov 30
   width 32
   height 72
   race human
   roam 0      //Don't go roaming around
   setmodel    npc/balancepriest1.mdl
   invincible  1
   setvar      CANCHAT 1
   saytextrange 1024

   catchspeech say_hi hello hail greet
   catchspeech give_crow "nevermore poe"
   catchspeech give_cwog "mel gibson"
   catchspeech give_darktide "kmx234t"
   catchspeech give_forestcroth "hug trees"
   catchspeech give_hov "pheonix down"
   catchspeech give_pirates arrrg
   catchspeech give_torkalath "drows rule"
   catchspeech give_valor "morgan ironwolf"
   catchspeech give_wildfire "burn baby"
   catchspeech give_bou "ilikefgd"
   catchspeech give_gag "fck me"
   catchspeech give_fmu stf
   catchspeech give_yoku "inuyasha eats babies"
	catchspeech give_rip "deathbecomesme"
	catchspeech give_gow "arespwns"
	catchspeech give_tdp "bowbee"
	catchspeech give_crew "bohemond"
	catchspeech give_wario "shroomie"
	catchspeech give_tfl "cant_get_up"
	catchspeech give_justice "justice"
	catchspeech give_revenge "revenge"
	catchspeech give_socialist "nsehls"
	catchspeech give_pos "redundantgods"
	catchspeech give_barnum "ringmaster"
	catchspeech give_fellowship "aic300"
	catchspeech give_hod "159753"
	catchspeech give_tdk "annemccaffrey4evr"
	catchspeech give_torkie "calleiksdafire"
   catchspeech cheater_guessing edana blades urdual fmu torkalath darktide bou pirates crest guild thoth
	catchspeech give_orochi krizarid

   precache npc/balancepriest1.mdl
   precache voices/human/male_idle2.wav		//seems to be internal to the model?

   setvard PROXY_SPOKE 0

	callevent 0.1 check_central
}

{ check_central

	if game.central equals 0
	if !G_DEVELOPER_MODE
	infomsg all FENRIN_FN_ONLY "You must be connected to [FN] to use the Guild Master"
	deleteent ent_me
}

#include monsters/base_npc

{ repeatdelay 1
	
	if !PROXY_SPOKE
	if ( $cansee(player,512) == 1 ) callevent say_hi
	setvard PROXY_SPOKE 1
}

{ eventname say_hi

 volume 10
 saytext Greetings, I am Fenrin, the Master of Guilds.
 playanim once talkleft
 calleventtimed 5 say_hi2
}

{ eventname say_hi2

  volume 10
  saytext Speak your guild's password, and I shall grant thee the proper crest.
}

{ eventname gave_crest

 playanim once kneel
 volume 10
 saytext There's your crest, honored guildmaster.
}

{ eventname cheater_guessing

 playanim once retina
 volume 10
 race orc
 saytext You know, you can leave, or I could just delete your character right now.
}

{ eventname give_crow

 offer ent_lastspoke crest_crow
 callevent 1 gave_crest
}

{ eventname give_cwog

 offer ent_lastspoke crest_cwog
 callevent 1 gave_crest
}

{ eventname give_darktide

  offer ent_lastspoke crest_darktide
  callevent 1 gave_crest
}

{ eventname give_forestcroth

  offer ent_lastspoke crest_forestcroth
  callevent 1 gave_crest
}

{ eventname give_hov

  offer ent_lastspoke crest_hov
  callevent 1 gave_crest
}

{ eventname give_pirates

  offer ent_lastspoke crest_pirates
  callevent 1 gave_crest
}

{ eventname give_torkalath

  offer ent_lastspoke crest_torkalath
  callevent 1 gave_crest
}

{ eventname give_valor

  offer ent_lastspoke crest_valor
  callevent 1 gave_crest
}

{ eventname give_wildfire

  offer ent_lastspoke crest_wildfire
  callevent 1 gave_crest
}

{ eventname give_bou

  offer ent_lastspoke crest_bou
  callevent 1 gave_crest
}

{ eventname give_gag

  offer ent_lastspoke crest_gag
  callevent 1 gave_crest
}

{ eventname give_fmu

  offer ent_lastspoke crest_fmu
  callevent 1 gave_crest
}

{ eventname give_yoku

  offer ent_lastspoke crest_yoku
  callevent 1 gave_crest
}

{ eventname give_rip

  offer ent_lastspoke crest_rip100
  callevent 1 gave_crest
}

{ eventname give_gow

  offer ent_lastspoke crest_gow
  callevent 1 gave_crest
}

{ eventname give_tdp

  offer ent_lastspoke crest_tdp333
  callevent 1 gave_crest
}

{ eventname give_orochi

  offer ent_lastspoke crest_cloak_blue
  callevent 1 gave_crest
}

{ eventname give_crew

  offer ent_lastspoke crest_crew
  callevent 1 gave_crest
}

{ eventname give_wario

  offer ent_lastspoke crest_wario
  callevent 1 gave_crest
}

{ eventname give_tfl

  offer ent_lastspoke crest_tfl
  callevent 1 gave_crest
}

{ eventname give_justice

  offer ent_lastspoke crest_justice
  callevent 1 gave_crest
}

{ eventname give_revenge

  offer ent_lastspoke crest_revenge
  callevent 1 gave_crest
}

{ eventname give_socialist

  offer ent_lastspoke crest_socialist
  callevent 1 gave_crest
}

{ eventname give_pos

  offer ent_lastspoke crest_pathos
  callevent 1 gave_crest
}

{ eventname give_barnum

  offer ent_lastspoke crest_barnum
  callevent 1 gave_crest
}

{ eventname give_fellowship
  offer ent_lastspoke crest_fellowship
  callevent 1 gave_crest
}

{ eventname give_hod
  offer ent_lastspoke crest_hod
  callevent 1 gave_crest
}

{ eventname give_tdk
  offer ent_lastspoke crest_tdk
  callevent 1 gave_crest
}

{ eventname give_torkie
  offer ent_lastspoke crest_torkie
  callevent 1 gave_crest
}

