//Thothie - tired of dealing with the weirdness from these old guard scripts
//making some new guard scripts from scratch - will include/adjust ext scripts as needed

{
	const SOUND_STRUCK body/flesh1.wav
	const SOUND_WARCRY voices/human/male_guard_shout2.wav
	const SOUND_ATTACK weapons/bow/bowslow.wav
	const SOUND_DEATH voices/human/male_die.wav

	precache SOUND_DEATH //handled in base_monster

	setvar ANIM_IDLE idle1
	setvar ANIM_RUN run
	setvar ANIM_WALK walk
	setvard ANIM_DEATH diebackward
	setvard ANIM_ATTACK swordswing1_l

	setvard MOVE_RANGE 65
	setvard ATTACK_RANGE 85
	setvard ATTACK_HITRANGE 130
	const ATTACK_HITCHANCE 85%
	const ATTACK_DAMAGE '$randf(5.0,8.0)'

	//setvard CAN_FLINCH 1
	//setvard FLINCH_DELAY 4
	//const FLEE_HEALTH 10
	//const FLEE_CHANCE 15%

	setvard CAN_HUNT 1
	setvard CAN_ATTACK 1
	setvard HUNT_AGRO 1
	setvard CAN_RETALIATE 1

	setvard NPC_GIVE_EXP 0
}

#include monsters/base_monster_new
#include monsters/base_guard_friendly_new

{ npc_spawn	//in helena 	name_unique	Archer

	if !CUSTOM_GUARD

	name	a|Guard
	hp	170
	//ov	359
	hearingsensitivity	12
	width	32
	height	85
	race	hguard
	roam	0
	setmodel npc/guard1.mdl
	takedmg all .9
	setmodelbody	2 2
	setstat parry 10
	movespeed 0.0
	//helena only: setangle	face $vec(0,180,0) (delay, re-read angles for base_guard_friendly)

	if game.serverside
	if $lcase(game.map.name) equals foutpost
	race human
	setvard NPC_NO_PLAYER_DMG 1 //foutpost guards maybe forced to work amongst AOE player spells
}

{
   // Deal damage
   eventname attack_1

	setvard FINAL_HITCHANCE ATTACK_HITRANGE
	setvard FINAL_DAMAGE ATTACK_DAMAGE
	callevent basenpc_adj_attack
	dodamage ent_lastseen ATTACK_HITRANGE FINAL_DAMAGE FINAL_HITCHANCE
}

{ npc_struck

	playsound 0 5 SOUND_STRUCK
}

{ baseguard_tobattle //called from base_guard_friendly

	playsound 0 10 SOUND_WARCRY
}