//Thothie - the dynamic weather control long cried out for by Crow, Jester, etc
//untested
{

	const WEATHER_SPRITE rain.spr
	const SPRITE_SPLASH rain_splash.spr
	const SPRITE_MIST rain_mist.spr
	const SPRITE_RIPPLE rain_ripple.spr
	const SOUND_RAIN weather/rain.wav
	precache WEATHER_SPRITE
	precache SPRITE_SPLASH
	precache SPRITE_MIST
	precache SPRITE_RIPPLE
	precache SOUND_RAIN

	callexternal all game_playercmd_setweather rain 0 0
}

#include monsters/base_temporary