

{ dev_command

	if !game.central
	if G_DEVELOPER_MODE

	if ( PARAM1 equals 'helloworld' )
	{
		if ( game.serverside )
		{
			clientcmd ent_currentplayer "echo Hello world!"
			infomsg ent_currentplayer "Hello" "world!"
		}
	}

	if ( PARAM1 equals 'clmsgtest' ) //Sends an infomsg to the player if cleffect ce goes through. optional param to send data through.
	{
		clientevent new ent_currentplayer developer/clmsgtest $get(ent_currentplayer,index) PARAM2 //Should call clmsg_test event on the gm
	}

	if ( PARAM1 equals 'func' ) //Uses a func then displays the results
	{
		setvard FUNC_USED 0
		local L_RESULT $func(func_test,10,1231)
		local L_RESULT2 $func(func_test,11,22)

		if ( FUNC_USED )
		{
			infomsg all L_RESULT L_RESULT2
		}
		else
		{
			infomsg all "Func was not used" "nothing"
		}
	}
}

{ func_test //adds two numbers and returns it

	setvard FUNC_USED 1

	local L_RETURN $math(add,PARAM1,PARAM2)
	return **clear
	return L_RETURN
}