//Map settings
//
{ [shared]

	const MAP_NAME 		'b_castle'
	const MAP_WEATHER 	clear;clear;clear;clear;clear;clear
	const MAP_ALLOWNIGHT 	1

	setvarg G_CONTROL_MAP 1

	setvarg G_MAP_NAME "The Castle by P.Barnum"
	setvarg G_MAP_DESC "The warriors of this cursed castle are animated by an ancient magic."
	setvarg G_MAP_DIFF "Levels 25-35 / 450-700hp"

	setvarg MAP_CON 1
}

#include worlditems/map_startup