//This is an older script and may have some bad conventions as a result

// *** Random bandit script ***
//

{
	setvard CONTAINER_DROP_CHANCE 10% 
	setvard CONTAINER_SCRIPT chests/quiver_of_poison
	const SOUND_PAIN		player/chesthit1.wav
	const SOUND_PAIN2		player/armhit1.wav
	const SOUND_BOW weapons/bow/bow.wav
	setvar ANIM_IDLE		idle
	setvar ANIM_RUN		run
	setvar ANIM_WALK		walk2
	setvard ANIM_DEATH		die_simple
	setvard CAN_HUNT		1
	setvard HUNT_AGRO		1
	setvard CAN_ATTACK		1
	setvard CAN_RETALIATE		1
	const RETALIATE_CHANGETARGET_CHANCE	75%
	setvard CAN_HEAR		1
	setvard NPC_GIVE_EXP		120

	//attempts to improve bandit aim by Thothie
	const AIM_RATIO 50
	const ARROW_DAMAGE '$rand(15,40)'

	callevent bowey
	callevent fistey
	callevent daggerey
	callevent swordey
	callevent axey
	callevent macey
}

#include monsters/base_monster
#include monsters/base_aim_proj

// Spawn properties
{
   eventname npc_spawn


	if ( WEAPON equals 'WEAPON' ) setvard WEAPON $rand(0,5)
   gold			$rand(23,37)
   //fov			220
   width		32
   height		92
   race			rogue
   takedmg		all 0.6
   hearingsensitivity	3
   roam			1
   setmodel		npc/rogue.mdl
   setidleanim		ANIM_IDLE
   setmoveanim		ANIM_WALK

}
{
	eventname bowey
	if WEAPON == 0
	name a|Trained Bandit Archer
	hp 190
	setvar ATTACK_SPEED 1200
	setvard MOVE_RANGE ATTACK_SPEED
	setvard ATTACK_RANGE ATTACK_SPEED
	setvar ATTACK_COF 0
	setvard ANIM_ATTACK shootbow
	setactionanim ANIM_ATTACK
	setmodelbody 1 5
	setvard TOO_CLOSE 0
	setvard DROPS_CONTAINER 1
	setvard NO_STUCK_CHECKS 1
}
{
	eventname daggerey
	if WEAPON == 1
	name a|Trained Bandit Rogue
	hp 190
	setvard MOVE_RANGE 50
	setvard ATTACK_RANGE 90
	setvar ATTACK1_DAMAGE $randf(10.5,12.0)
	setvar ATTACK_PERCENTAGE 80%
	setvard ANIM_ATTACK swordjab1_R
	setactionanim ANIM_ATTACK
	setmodelbody 1 1
	setvard DROP_ITEM1 smallarms_fangstooth //Used by base_monster
   	setvard DROP_ITEM1_CHANCE 5%		//Used by base_monster
}
{
	eventname fistey
	if WEAPON == 2
	name a|Trained Bandit Martial Artist
	hp 220
	setvard MOVE_RANGE 50
	setvard ATTACK_RANGE 80
	setvar ATTACK1_DAMAGE $randf(8.5,10.0)
	setvar ATTACK_PERCENTAGE 80%
	setvard ANIM_ATTACK aim_punch1
	setactionanim ANIM_ATTACK
	setmodelbody 1 0
}
{
	eventname swordey
	if WEAPON == 3
	name a|Trained Bandit Swordsman
	hp 220
	setvard MOVE_RANGE 80
	setvard ATTACK_RANGE 120
	setvar ATTACK1_DAMAGE $randf(10.5,12.0)
	setvar ATTACK_PERCENTAGE 85%
	setvard ANIM_ATTACK swordswing2_R
	setactionanim ANIM_ATTACK
	setmodelbody 1 4
}
{
	eventname axey
	if WEAPON == 4
	name a|Trained Bandit Axeman
	hp 260
	setvard MOVE_RANGE 80
	setvard ATTACK_RANGE 120
	setvar ATTACK1_DAMAGE $randf(11.5,13.0)
	setvar ATTACK_PERCENTAGE 85%
	setvard ANIM_ATTACK battleaxe_swing1_R
	setactionanim ANIM_ATTACK
	setmodelbody 1 3
}
{
	eventname macey
	if WEAPON == 5
	name a|Trained Bandit Berserker
	hp 260
	setvard MOVE_RANGE 80
	setvard ATTACK_RANGE 130
	setvar ATTACK1_DAMAGE $randf(11.5,13.0)
	setvar ATTACK_PERCENTAGE 85%
	setvard ANIM_ATTACK battleaxe_swing1_R
	setactionanim ANIM_ATTACK
	setmodelbody 1 2
}

{
   // Deal damage
   eventname attack

	if !IS_FLEEING

   if( WEAPON == 0 )
   {
  		//local AIM_ANGLE $get(ent_lastseen,dist)		//Aim up a bit
	   	//divide AIM_ANGLE AIM_RATIO				//
   		//setangle add_view.x AIM_ANGLE			//

	  	//local TARGET_POS $get(ent_lastseen,origin) //combine with final
	  	//local TARGET_DIST $get(ent_lastseen,range)
		//local TARGET_Z $vec.z(TARGET_POS) //not used
		//local FINAL_TARGET TARGET_POS
		//vectoradd FINAL_TARGET $relpos($vec(0,0,0),$vec(0,0,TARGET_DIST)) 
		//divide TARGET_DIST 100
		//setangle add_view.pitch TARGET_DIST
		//callevent baseaim_adjust_angles
		setangle add_view.pitch 5 //fires in such a shallow arc, no need to adj based on distance
		setvard FINAL_DAMAGE ARROW_DAMAGE
		callevent npcatk_adj_attack
		setvard AS_ATTACKING game.time
		
		//<projectile scriptname> <"view"|(src_origin)> <target|(targ_origin)|none> <speed> <damage> <cof> <skill|none> //Converted to use new tossprojectile //greatguys1@FEB2022
      	tossprojectile "proj_arrow_poison" $relpos(0,0,2) none ATTACK_SPEED FINAL_DAMAGE ATTACK_COF none 
	  	callexternal $get(ent_lastprojectile,id) ext_lighten 0.4
      	playsound 2 SOUND_BOW

   }
   else
   {
      dodamage ent_lastseen ATTACK_RANGE ATTACK1_DAMAGE ATTACK_PERCENTAGE

		//bandit dagger now using fangtooth
	  	if ( WEAPON == 1 )
		{
   			if( $rand(1,3) == 1 ) applyeffect ent_laststruckbyme effects/effect_poison 5 ent_me $rand(3,5)
		}
   }
}

{ check_attack

	//trained archers move away from melee - thothie
	if WEAPON == 0

	if !IS_FLEEING

	////dbg ChangPos CHANGE_POSITION

	if ( CHANGE_POSITION > 3 )
	{
		setvard CHANGE_POSITION 0
		playanim break
		playanim critical ANIM_RUN
		//setvard PURE_FLEE 1
		//callevent npcatk_flee ent_lastseen 1000 5
		callevent chicken_run 3
	}

	if $cansee(enemy)

	if ( $get(ent_lastseen,range) < 100 ) add TOO_CLOSE 0.1

	if ( TOO_CLOSE > 5 )
	{
		//dbg Too close for too long, backing off
		setvard TOO_CLOSE 0
		setvard PURE_FLEE 1
		callevent npcatk_flee ent_lastseen 600 5
	}
}

{ npc_struck
   
	volume 5
	playrandomsound 2 SOUND_PAIN SOUND_PAIN2 none none
}

{ npc_death
   
	local L_DEATHANIM $rand(0,6)
	if( L_DEATHANIM equals 0 )	setvard ANIM_DEATH die_simple
	if( L_DEATHANIM equals 1 )	setvard ANIM_DEATH die_backwards1
	if( L_DEATHANIM equals 2 )	setvard ANIM_DEATH die_backwards
	if( L_DEATHANIM equals 3 )	setvard ANIM_DEATH die_forwards
	if( L_DEATHANIM equals 4 )	setvard ANIM_DEATH headshot
	if( L_DEATHANIM equals 5 )	setvard ANIM_DEATH die_spin
	if( L_DEATHANIM equals 6 )	setvard ANIM_DEATH gutshot
}

{ game_dodamage //1: Attack Hit (1/0)  2: Entity Attack hit  3:  Start Position  4:  End Position

	//trained archers move if can't hit - thothie
	if WEAPON == 0
	if ( !PARAM1 ) add CHANGE_POSITION 1
	//if ( $get(PARAM2,isplayer) == 0 ) add CHANGE_POSITION 1
	if ( PARAM1 )
	{
		if ( $get(PARAM2,isplayer) == 1 ) setvard CHANGE_POSITION -2
		if ( CHANGE_POSITION < -5 ) setvard CHANGE_POSITION 0
	}
}

{ npc_struck

	//trained archers move if hit
	if WEAPON == 0
	if $get(ent_laststruck,isplayer) add CHANGE_POSITION 1
}

{ npc_targetsighted
	//archer
	if WEAPON == 0
	if !IS_FLEEING
	if $cansee(PARAM1)
	playanim once ANIM_ATTACK
}

{ game_death
	setsolid none
	setbbox none
}