//Suicide Explosion base by greatguys1

//Call do_explode from the top script to have the monster explode.
//Initiate any cleffects from a do_explode in the top script.

//Cutomizable vars
// const EXPLOSION_DISTANCE [num] default: 120 "The radius of the explosion"
// const EXPLOSION_DAMAGE [num] default: 300 "How much damage will the explosion do"
// const EXPLOSION_DAMAGE_FALLOFF [0-1] default: 0.2 "How much less damage will do from the center; 1 will do no damage at the very edge of the radius."
// const EXPLOSION_FORCE [num] default: 300 "How much force people caught in the radius will be pushed"
// const EXPLOSION_TYPE [damage type] default: blunt_effect "Which element to use when damaging enemies"

#scope server

{
	const EXPLOSION_DISTANCE 120
	const EXPLOSION_DAMAGE 300
	const EXPLOSION_DAMAGE_FALLOFF 0.2
	const EXPLOSION_FORCE 300
	const EXPLOSION_TYPE blunt_effect
}

{ do_explode

	if ( EXPLOSION_DAMAGE )
	{
		xdodamage $get(ent_me,origin) EXPLOSION_DISTANCE EXPLOSION_DAMAGE EXPLOSION_DAMAGE_FALLOFF ent_me ent_me none EXPLOSION_TYPE dmgevent:beam //<target|(src_origin)> <range|aoe|(dest_origin)|direct> <damage> <cth|fall_off> <attacker> <inflciter> <skill|none> <dmg_type> [flag_string]
	}
}

{ beam_dodamage //PARAM1=hit:0|1 PARAM2=ent_hit PARAM3=(start) PARAM4=(end) PARAM5=DmgType PARAM6=DmgAmt //Thanks Thothie!

	if ( PARAM1 )
	{
		local L_TARGET PARAM2

		if ( $get(L_TARGET,relationship,ent_me) equals enemy )
		{
			if ( EXPLOSION_FORCE != 0 )
			{
				local L_YAW $angles($get(ent_me,origin),$get(L_TARGET,origin))
				addvelocity L_TARGET $relvel($vec(0,L_YAW,0),$vec(0,EXPLOSION_FORCE,$math(divide,EXPLOSION_FORCE,1.3)))
			}
		}
	}
}