//This is semi-defunct, only for NPCs that do not have base_npc or base_npc_vendor
//
//Monsters that react to common events, such
//as seeing the player
//
//
{
	///Defaults
	const NPC_REACT_SEETARGET player
	const NPC_REACT_SEETARGET_RANGE 128
	setvard NPC_REACTS 1
}

{
   repeatdelay 1

	if ( $cansee(NPC_REACT_SEETARGET,NPC_REACT_SEETARGET_RANGE) )
	{
		//don't scream at the same player repeatedly, annoying
		if $get(ent_lastseen,id) isnot NPC_REACT_LAST_TARGET
		setvard NPC_REACT_LAST_TARGET $get(ent_lastseen,id)
		setvard NPC_REACT_RESET_TARGET_TIME game.time
		add NPC_REACT_RESET_TARGET_TIME 60.0
		if ( !NPC_REACT_CANSEETARGET ) callevent npcreact_targetsighted NPC_REACT_LAST_TARGET
		setvard NPC_REACT_CANSEETARGET 1
	}
	else
	{
		if ( NPC_REACT_CANSEETARGET ) callevent npc_react_sightlost
		setvard NPC_REACT_CANSEETARGET 0
		if game.time > NPC_REACT_RESET_TARGET_TIME
		setvard NPC_REACT_LAST_TARGET 0
		
	}
}
