//For "ghostly" monsters

{
	setvar NPC_HACKED_MOVE_SPEED 1
}

#include monsters/base_propelled

{ game_spawn
	callevent basenoclip_flight
}

{ basenoclip_flight
	callevent 0.1 basenoclip_flight

	local MY_ORG game.monster.origin
	vectoradd MY_ORG $relvel(0,FWD_SPEED,0)
	setorigin ent_me MY_ORG

	if ( !IS_FLEEING )
	{
		setmovedest NPC_NOCLIP_DEST ATTACK_MOVERANGE
	}
	else
	{
		setmovedest NPC_NOCLIP_DEST 0
	}
}