//Script side XP system
//- just in case
{
	//skill idx
	const NPC_HITDATA_SWORDSMANSHIP 0
	const NPC_HITDATA_MARTIALARTS 1
	const NPC_HITDATA_AXEHANDLING 2
	const NPC_HITDATA_SMALLARMS 3
	const NPC_HITDATA_ARCHERY 4
	const NPC_HITDATA_SPELLS_FIRE 5
	const NPC_HITDATA_SPELLS_ICE 6
	const NPC_HITDATA_SPELLS_LIGHTNING 7
	const NPC_HITDATA_SPELLS_EARTH 8
	const NPC_HITDATA_SPELLS_SUMMON 9
	const NPC_HITDATA_SPELLS_DIVINATION 10
	const NPC_HITDATA_SPELLS_AFFLICTION 11
	const NPC_HITDATA_INIT_SKILLS "0;0;0;0;0;0;0;0;0;0;0;0"
	const NPC_SKILLS_LIST "swordsmanship;martialarts;axehandling;bluntarms;smallarms;archery;spellcasting.fire;spellcasting.ice;spellcasting.lightning;spellcasting.earth;spellcasting.summon;spellcasting.divination;spellcasting.affliction"
}

{ game_spawn
	setvard NPC_HITDATA_IDS ''
	setvard NPC_HITDATA_DMG ''
	setvard NPC_TOTAL_DAMAGE ''
}

{ game_damaged //PARAM1=attacker PARAM2=dmg PARAM3=dmg_type PARAM4=AccuracyRoll PARAM5=skill_type

	local PLR_ATTACKER PARAM1
	local INC_DMG PARAM2
	local INC_DMG_TYPE PARAM3
	local ACC_ROLL PARAM4
	local SKILL_TYPE PARAM5

	//hande parry here
	//parrystuff
	//parrystuff
	//parrystuff

	setvard NPC_ADJUSTED_DMG INC_DMG

	callevent npc_resist_damage PLR_ATTACKER INC_DMG INC_DMG_TYPE //handle any dmg resists here, return NPC_ADJUSTED_DMG

	local INC_DMG NPC_ADJUSTED_DMG

	//handle XP
	if SKILL_TYPE isnot none
	if INC_DMG > 0
	if $get(PLR_ATTACKER,isplayer)

	local PLAYER_HITDATA_IDX $get_find_token(NPC_HITDATA_IDS,PLR_ATTACKER)

	if ( PLAYER_HITDATA_IDX == -1 )
	{
		//init new player
		local PLAYER_HITDATA_IDX $get_token_amt(NPC_HITDATA_IDS)

		//I can only track up to 10 players hitting me, try to drop one
		if ( PLAYER_HITDATA_IDX > 15 )
		{
			calleventloop PLAYER_HITDATA_IDX npcexp_drop_exp_counter
			setvard FOUND_EMPTY_SLOT -1
			calleventloop PLAYER_HITDATA_IDX npcexp_find_empty_slot
		}

		if ( PLAYER_HITDATA_IDX >= 10 ) playermessage PLR_ATTACKER "XP Sys Warning:" $get(ent_me,name) cannot find anymore XP slots
	
		if PLAYER_HITDATA_IDX < 10

		token.add NPC_HITDATA_IDS PLR_ATTACKER	
	}

	local SKILL_IDX $get_find_token(NPC_SKILLS_LIST,SKILL_TYPE)

	if ( PLAYER_HITDATA_IDX == 0 ) local GET_AMT $get_token(PLAYER_HITDATA_SKILLS_0,SKILL_IDX)
	if ( PLAYER_HITDATA_IDX == 1 ) local GET_AMT $get_token(PLAYER_HITDATA_SKILLS_1,SKILL_IDX)
	if ( PLAYER_HITDATA_IDX == 2 ) local GET_AMT $get_token(PLAYER_HITDATA_SKILLS_2,SKILL_IDX)
	if ( PLAYER_HITDATA_IDX == 3 ) local GET_AMT $get_token(PLAYER_HITDATA_SKILLS_3,SKILL_IDX)
	if ( PLAYER_HITDATA_IDX == 4 ) local GET_AMT $get_token(PLAYER_HITDATA_SKILLS_4,SKILL_IDX)
	if ( PLAYER_HITDATA_IDX == 5 ) local GET_AMT $get_token(PLAYER_HITDATA_SKILLS_5,SKILL_IDX)
	if ( PLAYER_HITDATA_IDX == 6 ) local GET_AMT $get_token(PLAYER_HITDATA_SKILLS_6,SKILL_IDX)
	if ( PLAYER_HITDATA_IDX == 7 ) local GET_AMT $get_token(PLAYER_HITDATA_SKILLS_7,SKILL_IDX)
	if ( PLAYER_HITDATA_IDX == 8 ) local GET_AMT $get_token(PLAYER_HITDATA_SKILLS_8,SKILL_IDX)
	if ( PLAYER_HITDATA_IDX == 9 ) local GET_AMT $get_token(PLAYER_HITDATA_SKILLS_9,SKILL_IDX)

	add GET_AMT INC_DMG

	if ( PLAYER_HITDATA_IDX == 0 ) token.set PLAYER_HITDATA_SKILLS_0 SKILL_IDX GET_AMT
	if ( PLAYER_HITDATA_IDX == 1 ) token.set PLAYER_HITDATA_SKILLS_1 SKILL_IDX GET_AMT
	if ( PLAYER_HITDATA_IDX == 2 ) token.set PLAYER_HITDATA_SKILLS_2 SKILL_IDX GET_AMT
	if ( PLAYER_HITDATA_IDX == 3 ) token.set PLAYER_HITDATA_SKILLS_3 SKILL_IDX GET_AMT
	if ( PLAYER_HITDATA_IDX == 4 ) token.set PLAYER_HITDATA_SKILLS_4 SKILL_IDX GET_AMT
	if ( PLAYER_HITDATA_IDX == 5 ) token.set PLAYER_HITDATA_SKILLS_5 SKILL_IDX GET_AMT
	if ( PLAYER_HITDATA_IDX == 6 ) token.set PLAYER_HITDATA_SKILLS_6 SKILL_IDX GET_AMT
	if ( PLAYER_HITDATA_IDX == 7 ) token.set PLAYER_HITDATA_SKILLS_7 SKILL_IDX GET_AMT
	if ( PLAYER_HITDATA_IDX == 8 ) token.set PLAYER_HITDATA_SKILLS_8 SKILL_IDX GET_AMT
	if ( PLAYER_HITDATA_IDX == 9 ) token.set PLAYER_HITDATA_SKILLS_9 SKILL_IDX GET_AMT

	local GET_TOTAL_AMT $get_token(NPC_HITDATA_DMG,PLAYER_HITDATA_IDX)
	add GET_TOTAL_AMT INC_DMG

	token.set NPC_HITDATA_DMG PLAYER_HITDATA_IDX GET_TOTAL_AMT
}

{ npcexp_drop_exp_counter
	local CUR_EXP_PLAYER $get_token(NPC_HITDATA_IDS,game.script.iteration)
	local DROP_THIS_PLAYER 0
	if ( !$get(CUR_EXP_PLAYER,exists) ) local DROP_THIS_PLAYER 1
	if ( !$get(CUR_EXP_PLAYER,isplayer) ) local DROP_THIS_PLAYER 1
	if DROP_THIS_PLAYER
	callevent npcexp_reset_skills CUR_EXP_PLAYER
}

{ npcexp_find_empty_slot
	if FOUND_EMPTY_SLOT < 0
	local CUR_EXP_PLAYER $get_token(NPC_HITDATA_IDS,game.script.iteration)
	if ( CUR_EXP_PLAYER equals 0 ) setvard FOUND_EMPTY_SLOT game.script.iteration
}

{ player_left
	local PLAYER_HITDATA_IDX $get_find_token(NPC_HITDATA_IDS,game.script.iteration)
	if PLAYER_HITDATA_IDX > -1
	callevent npcexp_reset_skills PLAYER_HITDATA_IDX
}

{ npcexp_reset_skills
	//(re)init player skill data
	token.set NPC_HITDATA_DMG PARAM1 0
	token.set NPC_HITDATA_IDS PARAM1 0
	if ( PARAM1 == 0 ) setvard PLAYER_HITDATA_SKILLS_0 NPC_HITDATA_INIT_SKILLS
	if ( PARAM1 == 1 ) setvard PLAYER_HITDATA_SKILLS_1 NPC_HITDATA_INIT_SKILLS
	if ( PARAM1 == 2 ) setvard PLAYER_HITDATA_SKILLS_2 NPC_HITDATA_INIT_SKILLS
	if ( PARAM1 == 3 ) setvard PLAYER_HITDATA_SKILLS_3 NPC_HITDATA_INIT_SKILLS
	if ( PARAM1 == 4 ) setvard PLAYER_HITDATA_SKILLS_4 NPC_HITDATA_INIT_SKILLS
	if ( PARAM1 == 5 ) setvard PLAYER_HITDATA_SKILLS_5 NPC_HITDATA_INIT_SKILLS
	if ( PARAM1 == 6 ) setvard PLAYER_HITDATA_SKILLS_6 NPC_HITDATA_INIT_SKILLS
	if ( PARAM1 == 7 ) setvard PLAYER_HITDATA_SKILLS_7 NPC_HITDATA_INIT_SKILLS
	if ( PARAM1 == 8 ) setvard PLAYER_HITDATA_SKILLS_8 NPC_HITDATA_INIT_SKILLS
	if ( PARAM1 == 9 ) setvard PLAYER_HITDATA_SKILLS_9 NPC_HITDATA_INIT_SKILLS
}

{ game_death

	if NPC_GIVE_EXP > 0
	calleventloop $get_token_amt(NPC_HITDATA_IDS,PLR_ATTACKER) npcexp_dish_out_exp

}

{ npcexp_dish_out_exp

	//proc each player
	local CUR_IDX game.script.iteration
	local CUR_PLAYER $get_token(NPC_HITDATA_IDS,CUR_IDX)
	local CUR_DMG $get_token(NPC_HITDATA_DMG,CUR_IDX)

	if ( CUR_IDX == 0 ) setvard T_SKILL_LIST PLAYER_HITDATA_SKILLS_0
	if ( CUR_IDX == 1 ) setvard T_SKILL_LIST PLAYER_HITDATA_SKILLS_1
	if ( CUR_IDX == 2 ) setvard T_SKILL_LIST PLAYER_HITDATA_SKILLS_2
	if ( CUR_IDX == 3 ) setvard T_SKILL_LIST PLAYER_HITDATA_SKILLS_3
	if ( CUR_IDX == 4 ) setvard T_SKILL_LIST PLAYER_HITDATA_SKILLS_4
	if ( CUR_IDX == 5 ) setvard T_SKILL_LIST PLAYER_HITDATA_SKILLS_5
	if ( CUR_IDX == 6 ) setvard T_SKILL_LIST PLAYER_HITDATA_SKILLS_6
	if ( CUR_IDX == 7 ) setvard T_SKILL_LIST PLAYER_HITDATA_SKILLS_7
	if ( CUR_IDX == 8 ) setvard T_SKILL_LIST PLAYER_HITDATA_SKILLS_8
	if ( CUR_IDX == 9 ) setvard T_SKILL_LIST PLAYER_HITDATA_SKILLS_9

	//player did less than all the damage to me, adjust
	setvard TOTAL_XP_TO_GIVE NPC_GIVE_EXP
	local MY_HP game.monster.maxhp
	if ( CUR_DMG < MY_HP )
	{
		divide CUR_DMG MY_HP
		multiply TOTAL_XP_TO_GIVE CUR_DMG
	}

	//player did more damage than I had hp (prob due to regen/whatnot), adjust (give him my max exp)
	if ( CUR_DMG > MY_HP )
	{
		setvard TOTAL_XP_TO_GIVE NPC_GIVE_EXP //redundant
	}

	setvard OUT_IDX CUR_IDX

	//proc each skill
	calleventloop $get_token_amt(T_SKILL_LIST) npcexp_learn_skill
}

{ npcexp_learn_skill
	

	local THIS_PLAYER $get_token(NPC_HITDATA_IDS,OUT_IDX)
	local TOTAL_DMG $get_token(NPC_HITDATA_DMG,OUT_IDX)

	local SKILL_IDX game.script.iteration
	local DMG_WITH_THIS_SKILL $get_token(T_SKILL_LIST,SKILL_IDX)

	local PERCENT_DMG_DONE_W_SKILL DMG_WITH_THIS_SKILL
	divide PERCENT_DMG_DONE_W_SKILL TOTAL_DMG
	
	local SKILL_POINTS_TO_GIVE_SKILL TOTAL_XP_TO_GIVE
	multiply SKILL_POINTS_TO_GIVE_SKILL PERCENT_DMG_DONE_W_SKILL
	learnskill THIS_PLAYER $get_token(PLAYER_SKILLS_LIST,SKILL_IDX) SKILL_POINTS_TO_GIVE_SKILL
}