//Bat summoned by giant bat

{
   setvard NPC_GIVE_EXP 5
   setvard CAN_FLEE 0
   //const DELETE_ON_DEATH 1	//effs with giant bat summon
}


#include monsters/bat

{  game_dynamically_created
   
	setvard BAT_ATTACK_DMG PARAM2
	setmovedest PARAM3 9999
	callevent PARAM1 bat_die
}

{  bat_die

	setvard CAN_ATTACK 0
	setvard CAN_HUNT 0
	setvard CAN_HEAR 0
	deleteent ent_me fade
}

{  bat_spawn

   	name a|Summoned Bat
   	hp 20
   	width 1
   	height 1
   	hearingsensitivity 3.5
   	setidleanim ANIM_IDLE_FLY
   	setmoveanim ANIM_WALK
}

{  [override] bat_hang

	//This event is here so I don't spawn hanging
}
  
{  [override] bite1			// Deal damage

   dodamage ent_lastseen ATTACK_RANGE BAT_ATTACK_DMG ATTACK_HITCHANCE
}
