//Thothie - once again, to keep game compatible (no need to dump all custom maps with every update)
//Same as blackbearcub, cept white
//Standard Black Bear Cub

{
   setvard MOVE_RANGE 60
   setvard ATTACK_RANGE 70
   setvard ATTACK_HITRANGE 120
 
   const ATTACK_DAMAGE '$rand(5,8)'  // Little harder than a hard boar
   const ATTACK_HITCHANCE 60%
   const NPC_BASE_EXP	20
  
   setvard DROP_ITEM1 skin_bear 	//base_monster - Item Drop #1
   setvard DROP_ITEM1_CHANCE 50%	//base_monster - Chance of item drop #1

	setvard IMMUNE_COLD 1
}

#include monsters/bear_base
#include monsters/base_ice_race

{  npc_spawn

   	hp 80
   	//ov 120
   	width 40
   	height 80
   	name a|Polar Bear Cub
   	hearingsensitivity 2
	takedmg cold 0.0

   	setmodel monsters/bearcub.mdl
   	setmodelbody	0 0
}
