//Thothie - Model didn't seem to set skin, so attempted adjustment through setmodel
//Giant Black Bear

{
	setvar ANIM_IDLE	idle	//This is a workaround	
	setvar ANIM_WALK	walk	//because I use these as variables
	setvar ANIM_RUN	run	//while bear_base uses them as
	setvard ANIM_ATTACK	attack	//consts

   const ATTACK_NORMAL_DAMAGE 	30
   const ATTACK_STANDING_DAMAGE $randf(18,33)
   const ATTACK_STOMPRANGE 	225
   const ATTACK_STOMPDMG 	30
   const ATTACK_HITCHANCE 	70%
   const NPC_BASE_EXP		190
}

#include monsters/bear_base_giant

{  npc_spawn

   hp 500
   //ov 165
   name a|Giant Black bear

   setmodelbody	0 2
}
