//weekest of the beetles

{
	setvard NPC_GIVE_EXP 300
	const BBET_SIZE 1
	const BBET_CAN_FLY 1
	const BBET_CAN_LEAP 1
	const BBET_CAN_SLAM 0
	const BBET_GORE_PUSH_STR 300
	const BBET_FAKE_DEATH 1

	const DMG_SLASH 20
	const DMG_GORE 30
	const DMG_LEAP 50
}

{ game_precache
	precache monsters/beetles.mdl
}

#include monsters/beetle_base

{ beetle_spawn
	name a|Horned Beetle
	hp 500
	setmodelbody 0 0 //0=Horned 1=Venom 2=Fire
}