//adapted from phlames/phlame_wing_cl and monsters/gbear_polar_cl

{ client_activate
	setvard FX_OWNER PARAM1
	setvard FX_DURATION PARAM2
	setvard FX_ACTIVE 1
	callevent fire_breath_loop
	callevent FX_DURATION end_fx
}

{ fire_breath_loop
	if FX_ACTIVE
	callevent 0.2 fire_breath_loop
	setvard CLOUD_YAW $getcl(FX_OWNER,angles.yaw)
	cleffect tempent sprite rain_mist.spr $getcl(FX_OWNER,attachment0) setup_fire_cloud update_fire_cloud
	cleffect tempent sprite rain_mist.spr $getcl(FX_OWNER,attachment0) setup_fire_cloud update_fire_cloud
	cleffect tempent sprite rain_mist.spr $getcl(FX_OWNER,attachment0) setup_fire_cloud update_fire_cloud
}

{ end_fx
	setvard FX_ACTIVE 0
	callevent 1.0 remove_fx
}

{ remove_fx
	removescript
}

{ update_fire_cloud
	local CUR_SCALE game.tempent.fuser1
	if ( CUR_SCALE < 2 )
	{
		add CUR_SCALE 0.05
		cleffect tempent set_current_prop fuser1 CUR_SCALE
		cleffect tempent set_current_prop scale CUR_SCALE 
	}
}

{ setup_fire_cloud

	cleffect tempent set_current_prop death_delay 1.0
	cleffect tempent set_current_prop framerate 10
	cleffect tempent set_current_prop frames 9
	cleffect tempent set_current_prop bouncefactor 0
	cleffect tempent set_current_prop scale  0.01
	cleffect tempent set_current_prop rendermode add
	cleffect tempent set_current_prop renderamt 255
	cleffect tempent set_current_prop rendercolor (128,128,255)
	cleffect tempent set_current_prop gravity .005
	cleffect tempent set_current_prop collide none
	cleffect tempent set_current_prop fuser1 0.01

	local RND_RL $randf(-20,20)
	local RND_UD $randf(-20,20)
	local CLOUD_VEL $relvel($vec(0,CLOUD_YAW,0),$vec(RND_RL,$randf(300,400),RND_UD))
	cleffect tempent set_current_prop velocity CLOUD_VEL
}