#scope server
{
	const MONSTER_NAME "an|Icewing"
	const MONSTER_SKIN_IDX 2
	const SPIT_PROJECTILE proj_ice_bolt
	const DOT_EFFECT effects/dot_cold

	const MONSTER_HP 1000

	const DMG_CLAW 100
	const DOT_DMG 20
	const DMG_SPIT 50

	const NPC_BASE_EXP 200

	takedmg cold 0.5
	takedmg fire 1.25

	const SOUND_SPIT magic/ice_strike.wav
}

#include monsters/demonwing_venom

{ game_dynamically_created
	callevent 0.05 scale_down
}

{ scale_down
	setprop ent_me scale 0.5
}