{
	setvar IS_UNHOLY 1

	const NO_DIVE 1 //dive is broken
	const DMG_DOT_BURN $rand(20,40)
	const DMG_ATTACK $randf(10,40)
	setvard NPC_GIVE_EXP 250
}

#include monsters/eagle_base

{ npc_spawn

	name a|Fowl Demon
	race demon
	hp 600
	width 32
	height 32
	setmodel monsters/eagle.mdl
	setidleanim flapping
	setmoveanim flapping
	hearingsensitivity 11
	roam 1
	fly 1
	takedmg poison 1.0
	takedmg cold 3.0
	takedmg holy 3.0
	takedmg fire 0.0
	setprop ent_me skin 1
}

{ game_dodamage

	dbg game_dodamage

	if ( MELEE_ATTACK )
	{
		if PARAM1
		if ( $rand(1,5) == 1 )
		{
			applyeffect PARAM2 effects/dot_fire 5 $get(ent_me,id) DMG_DOT_BURN
		}

		if !$get(PARAM2,scriptvar,'IMMUNE_PUSH')
		addvelocity PARAM2 $relvel(20,200,10)
	}
	setvard MELEE_ATTACK 0
}


{ phlames_eagle
	setvard AM_PHLAMES 1
	add G_FLAMES_EAGLES 1
	add G_NPC_SUMMON_COUNT 1
	setvard NPC_SUMMON 1
	dbg set_summon G_NPC_SUMMON_COUNT
}

{ game_death
	subtract G_FLAMES_EAGLES 1
}