{
	setvar IS_UNHOLY 1

	const NO_DIVE 1 //dive is broken
	const DMG_ATTACK $randf(20,60)
	setvard NPC_GIVE_EXP 300
	const SOUND_STRUCK weapons/axemetal1.wav
	const SOUND_PAIN weapons/axemetal2.wav
	const SOUND_PAIN2 debris/concrete1.wav
}

#include monsters/eagle_base

{ npc_spawn

	name an|Eagle made of stone
	race demon
	hp 600
	blood none
	width 32
	height 32
	setmodel monsters/eagle.mdl
	setidleanim flapping
	setmoveanim flapping
	hearingsensitivity 11
	roam 1
	fly 1
	takedmg all 0.75
	takedmg poison 0.0
	takedmg holy 2.0
	takedmg lightning 0.5
	setprop ent_me skin 3
}

{ game_dodamage

	if PARAM1
	if !$get(PARAM2,scriptvar,'IMMUNE_PUSH')
	addvelocity PARAM2 $relvel(30,300,30)

}

