{
	const NO_DIVE 1 //dive is broken
	const DMG_DOT_BURN $rand(5,20)
	const DMG_ATTACK $randf(10,40)
	setvard NPC_GIVE_EXP 250
}

#include monsters/eagle_base

{ npc_spawn

	name a|Plague Bird
	race demon
	hp 600
	width 32
	height 32
	setmodel monsters/eagle.mdl
	setidleanim flapping
	setmoveanim flapping
	hearingsensitivity 11
	roam 1
	fly 1
	takedmg poison 1.0
	setprop ent_me skin 2
}

{ game_dodamage

	if ( MELEE_ATTACK )
	{
		if PARAM1
		if ( $rand(1,5) == 1 )
		{
			applyeffect PARAM2 effects/dot_poison 20 $get(ent_me,id) DMG_DOT_BURN 1
		}

		if !$get(PARAM2,scriptvar,'IMMUNE_PUSH')
		addvelocity PARAM2 $relvel(20,200,10)
	}
	setvard MELEE_ATTACK 0

}

