//This is an older script and may have some bad conventions as a result.

//Lesser Fire Elemental by Thothie (From Screatch)
//- Throws three fire balls, approaches player, uses Circle of Fire spell, repeats
{
	setvar AS_SUMMON_TELE_CHECK 1

	setvar IS_UNHOLY 1
	setvard IMMUNE_VAMPIRE 1
	setvard ATTACK_RANGE 1024
	const SWIPE_RANGE 100
	const SNOWBALL_RANGE 600
	const SNOWBALL_DAMAGE 100
	const SNOWBALL_FREQ 45.0
	setvard SNOWBALL_DURATION 10.0 //read by proj_snow_ball
	const SOUND_SNOWBALL zombie/claw_miss1.wav
	setvard ATTACK_HITRANGE 150
	setvard MOVE_RANGE 65
	const ATTACK_HITCHANCE 0.8
	const SWIPE_MOVERANGE 65
	const SWIPE_RANGE 100
	const SWIPE_HITRANGE 150

	const ATTACK_ACCURACY 80%
	const CIRCLE_RANGE 2048
    const AIM_RATIO 50

	const AMB_FROST_DAMAGE '$rand(30,60)' //frost damage inflicted when struck @ close range
	const FROST_DAMAGE '$rand(60,80)' //frost effect damage from strike
	const STRIKE_DAMAGE '$rand(100,250)' //actual impact damage from strike
	const ICESEAL_DAMAGE 200 //spell frost damage per pulse

	setvar ANIM_IDLE idle1
	setvar ANIM_WALK idle1
	setvar ANIM_RUN idle1
	setvard ANIM_ATTACK attack1	
	const ANIM_SWIPE attack1
	setvard ANIM_FLINCH flinch
	setvard ANIM_DEATH die1

	const ANIM_BASEIDLE idle1
	const ANIM_FLOAT idle1
	const ANIM_BUGIDLE_A idle1	//letters here as weird behavior I am the gettingz
	const ANIM_BUGIDLE_B idle2
	const ANIM_BUGIDLE_C dunno
	const ANIM_CHARGE float

	const ANIM_SWIPE attack1

	const ANIM_ALERT yes
	const ANIM_GLOAT no
	const ANIM_SEARCH dunno

	const ANIM_TOCHARGE tocharge
	const ANIM_CHARGEIDLE charging
	const ANIM_FROMCHARGE fromcharge

	const SOUND_ALERT agrunt/ag_alert5.wav
	const SOUND_IDLE1 agrunt/ag_alert1.wav
	const SOUND_IDLE2 agrunt/ag_die1.wav
	const SOUND_IDLE3 agrunt/ag_idle1.wav
	const SOUND_SWIPE weapons/debris1.wav
	const SOUND_SWIPEHIT magic/frost_reverse.wav //check
	const SOUND_DEATH garg/gar_die1.wav
	const SOUND_PAIN0 debris/glass1.wav		//most common
	const SOUND_PAIN1 agrunt/ag_pain1.wav	//rare > 50%
	const SOUND_PAIN2 agrunt/ag_pain4.wav	//rare < 50%
	const SOUND_GLOAT x/x_laugh1.wav
	const SOUND_CIRCLE_READY debris/beamstart1.wav
	const SOUND_WAVE_GO ambience/flameburst1.wav
	const SOUND_HOVER fans/fan3on.wav

	const PLAYTIME_HOVER 3.0

	const CIRCLE_FREQ 30.0 //will be 30

	const NO_VICTORY_HEAL 1


	//shouldn't have to do this crap, but it's refusing to precache externally! ><
	const CIRCLE_SCRIPT monsters/summon/ice_wave

	setvard DROP_GOLD 1
	setvard DROP_GOLD_MIN 10
	setvard DROP_GOLD_MAX 40

	const I_AM_TURNABLE 0

	const MOVE_FAST 200
	const MOVE_NORMAL 100
	setvard NPC_HACKED_MOVE_SPEED MOVE_NORMAL //for basepropelled

	//Immunities: 1 = Immune, <>1 = Multiply Damage (1.5=take 150%, 0.5=take 50%)
	//Only affects Effect damage (not weapon damage)
	setvard IMMUNE_FIRE 1
	setvard IMMUNE_POISON 1
	setvard IMMUNE_COLD 1

	precache 

	const MONSTER_MODEL monsters/elementals_greater.mdl
	precache MONSTER_MODEL	//for older SC.DLL users
}

#include monsters/base_monster_new


{ npc_spawn

	name a|Greater Ice Elemental
	hp 1750
	width 32
	height 48
	race demon
	takedmg all 0.4
	takedmg holy 1.5
	takedmg fire 0.0
	takedmg cold 0.0
	takedmg ice 0.0
	takedmg poison 0.0
	//ov 80
	roam 1
	setidleanim ANIM_IDLE
	setmoveanim ANIM_WALK
	hearingsensitivity 3
	precache MONSTER_MODEL //for old version clients
	setmodel MONSTER_MODEL
	setmodelbody 0 1
	blood none

	setvard CIRCLE_DELAY 1
	callevent 15.0 reset_circle_delay

	setvard NPC_GIVE_EXP 400
	callevent 1.0 idle_sounds
   	setstat parry 40

	setvard MY_HURT_STAGE $get(ent_me,maxhp)
	multiply MY_HURT_STAGE 0.5
}

{ npc_struck //called from base_npc_attack - param1 damage taken as of 22/Aug/2006 14:50

	local MY_HEALTH $get(ent_me,hp)

	if ( MY_HEALTH >= MY_HURT_STAGE ) playrandomsound 0 10 SOUND_PAIN0 SOUND_PAIN0 SOUND_PAIN1
	if ( MY_HEALTH <= MY_HURT_STAGE ) playrandomsound 0 10 SOUND_PAIN0 SOUND_PAIN0 SOUND_PAIN2

	if ( PARAM1 > 40 ) addvelocity ent_me $relpos(1,-10,1) //float around when struck hard

	//If enemy that hit me is close, he will be frozen
	if $get(ent_laststruck,range) < MOVE_RANGE
	applyeffect ent_laststruck effects/effect_frostbite_dmg 1 $get(ent_me,id) AMB_FROST_DAMAGE
}

{ idle_sounds

	local NEXT_SOUND $randf(5,15)

	callevent NEXT_SOUND idle_sounds

	if !IS_HUNTING
	local RAND_ANIM $rand(1,3)
	if ( RAND_ANIM == 1 ) playanim once ANIM_BUGIDLE_A	//was having some odd bug with idle anims, hence odd names
	if ( RAND_ANIM == 2 ) playanim once ANIM_BUGIDLE_B
	if ( RAND_ANIM == 3 ) playanim once ANIM_BUGIDLE_C

	playrandomsound 0 10 SOUND_IDLE1 SOUND_IDLE2 SOUND_IDLE3
}

{ game_dodamage //1: Attack Hit (1/0)  2: Entity Attack hit  3:  Start Position  4:  End Position

	if ( CIRCLE_RUNNING )
	{
		if ( PARAM1 )
		{
			applyeffect ent_laststruckbyme effects/freeze_solid 10.0 $get(ent_me)
			local THROW_DIR $rand(1,2)
			if ( THROW_DIR == 1 ) addvelocity PARAM2 $relvel(-100,50,30)
			if ( THROW_DIR == 2 ) addvelocity PARAM2 $relvel(100,50,30)
		}
	}

	if ( PARAM1 )
	{
		if ( USE_SWIPE_SOUND )
		{
			applyeffectstack PARAM2 effects/effect_frost 4 $get(ent_me,id) FROST_DAMAGE
			playsound 0 10 SOUND_SWIPEHIT
		}
	}
	setvard USE_SWIPE_SOUND 0
}

{ npcatk_hunt

	if !SUSPEND_AI

	if ( !CIRCLE_DELAY ) setvard ATTACK_RANGE CIRCLE_RANGE
	if ( CIRCLE_DELAY ) setvard ATTACK_RANGE SWIPE_RANGE

	if ( !SNOWBALL_DELAY )
	{
		if ( $get(NPCATK_TARGET,range) > 256 ) 
		{
			if !CIRCLE_RUNNING
			if !PREP_CIRCLE
			playanim critical fireball
			setvard	AS_ATTACKING game.time
			setvard SNOWBALL_DELAY 1
			callevent SNOWBALL_FREQ reset_snowball
		}
	}
}

{ npc_selectattack

	////dbg temp AtkRng ATTACK_RANGE

	if !CIRCLE_RUNNING
	if !CIRCLE_DELAY
	if $cansee(NPCATK_TARGET)

	if $get(NPCATK_TARGET,range) < CIRCLE_RANGE
	setvard PREP_CIRCLE 1
	setvard NO_STUCK_CHECKS 1
	setvard	AS_ATTACKING game.time
	callevent npcatk_suspend_ai
	callevent npcatk_clear_movedest
	callevent 0.1 circle_prep
	setvard CIRCLE_DELAY 1
	callevent CIRCLE_FREQ reset_circle_delay
}

{ circle_prep

	//setbbox npcsize
	movespeed 0
	setanim.movespeed 0
	setvard NPC_HACKED_MOVE_SPEED 0
	//setmovedest TEMP_MOVE_TARGET 0
	effect glow ent_me (0,75,255) 50 5 5
	playsound 0 10 SOUND_CIRCLE_READY
	playanim critical tocharge
}

{ tocharge_done

	if ( $cansee(enemy) ) 
	{
		//setvard TEMP_MOVE_TARGET $get(ent_lastseen,origin) //blarg

		//setvard TEMP_MOVE_TARGET $relpos(0,9999,0) //works 
		local TRACE_START game.monster.origin
		local TRACE_END  $relpos(0,9999,0)
		setvard TEMP_MOVE_TARGET $get_traceline(TRACE_START,TRACE_END,worldonly) //w00t!
		//dbg temp tracesend TRACE_END result TEMP_MOVE_TARGET length $dist(TRACE_START,TEMP_MOVE_TARGET)
		setmovedest TEMP_MOVE_TARGET 10

	}

	//setmovedest TEMP_MOVE_TARGET 0
	setidleanim ANIM_CHARGEIDLE
	setmoveanim ANIM_CHARGEIDLE
	callevent 2.0 circle_go
}

{ circle_go //called from model anim tocharge

	if !CIRCLE_RUNNING

	//setvard DEST_ORIGIN $relpos(0,128,0)

	setmoveanim ANIM_CHARGE
	setidleanim ANIM_CHARGE
	movespeed 2.0

	//charge with swipe
	addvelocity ent_me $relvel(0,100,0)
	setanim.movespeed MOVE_FAST
	setvard NPC_HACKED_MOVE_SPEED MOVE_FAST
	playanim critical ANIM_CHARGE
	setvard CIRCLE_RUNNING 1

	playsound 0 10 SOUND_WAVE_GO

	createnpc CIRCLE_SCRIPT $relpos(0,0,0) 3.0 $get(ent_me,id)

	callevent circle_cycle
	callevent 3.0 circle_done
}

{ circle_cycle

	if CIRCLE_RUNNING
	setmovedest TEMP_MOVE_TARGET 10
	if ( $dist(game.monster.origin,TEMP_MOVE_TARGET) < 32 ) callevent circle_done
	callevent npcatk_dodamage $relpos(0,32,0) 72 0 100 0

	callevent 0.1 circle_cycle
}

{ circle_done
	if CIRCLE_RUNNING
	callevent npcatk_resume_ai
	setvard PREP_CIRCLE 0
	movespeed 1.0
	setmoveanim ANIM_WALK
	setidleanim ANIM_IDLE
	setvard ANIM_ATTACK ANIM_SWIPE
	setanim.movespeed MOVE_NORMAL
	setvard NPC_HACKED_MOVE_SPEED MOVE_NORMAL
	setvard CIRCLE_RUNNING 0
	setvard NO_STUCK_CHECKS 0
}

{ reset_circle_delay

	setvard CIRCLE_DELAY 0
}

{ slow_down

	//setvard CAN_ATTACK 1
	setvard NPC_HACKED_MOVE_SPEED MOVE_NORMAL
}

{ ammo_up

	setvard FIRE_BALL_AMMO FULL_FIRE_BALL_AMMO
}

{ npcatk_search_init_advanced

	if !$cansee(enemy)

	if !DID_SHRUG
	setvard DID_SHRUG 1

	setvard NPC_DELAYING_UNSTUCK 5.0

	playanim critical ANIM_SEARCH
	playsound 0 10 SOUND_IDLE3
}

{ my_target_died //called from base_npc_attack

	if ( !GLOAT_DELAY )
	{
		playanim critical ANIM_GLOAT
		playsound 0 10 SOUND_GLOAT
		setvard GLOAT_DELAY 1
		callevent 10.0 reset_gloat
	}

	if ( !$cansee(enemy) ) 
	{
		setvard DID_WARCRY 0
		setvard DID_SHRUG 0
	}
}

{ reset_gloat

	setvard GLOAT_DELAY 0 //this prevents sploiting with icewall/pets
}

{ npcatk_targetvalidate

	if !SUSPEND_AI

	if $get(PARAM1,isplayer)
	//callevent npcatk_setmovedest $get(ent_lastseen,id) ATTACK_RANGE
	if !DID_WARCRY

	//callevent npcatk_faceattacker
	setvard DID_WARCRY 1
	playanim critical ANIM_ALERT
	playsound 0 10 SOUND_ALERT
}

{ attack1_strike //called from anim attack1 @ frame12

	setvard USE_SWIPE_SOUND 1
	callevent npcatk_dodamage NPCATK_TARGET ATTACK_HITRANGE STRIKE_DAMAGE ATTACK_ACCURACY
}

{  [server] game_movingto_dest		//Hack in movement because the model anims are missing it

	if !RUNNING_CIRCLE
   setanim.movespeed NPC_HACKED_MOVE_SPEED	//Force move, since the animation doesn't have the required movement

	if !HOVER_LOOP_DELAY
	playsound CHAN_BODY 8 SOUND_HOVER
	setvard HOVER_LOOP_DELAY 1
	callevent PLAYTIME_HOVER hover_loop_reset
}

{ hover_loop_reset

	setvard HOVER_LOOP_DELAY 0
}

{  [server] 	game_stopmoving

   setanim.movespeed 0				//Force Stop
}

{ throw_fireball

	playsound 0 10 SOUND_SNOWBALL

	local AIM_ANGLE $get(ent_lastseen,dist)		//Aim up a bit
	divide AIM_ANGLE AIM_RATIO				//
	setangle add_view.pitch AIM_ANGLE			//

	//<projectile scriptname> <"view"|(src_origin)> <target|(targ_origin)|none> <speed> <damage> <cof> <skill|none> //Converted to use new tossprojectile //greatguys1@FEB2022
	tossprojectile "proj_snow_ball" $relpos(0,52,24) none 200 SNOWBALL_DAMAGE 2 none
}

{ reset_snowball

	//dbg Temp Snowball Reset
	setvard SNOWBALL_DELAY 0
}

//only two scripts use this, so we took it out of the AI to save load time
{ npcatk_clear_movedest
	setmovedest none
	setvard NPC_MOVEDEST_TARGET unset
}

