{ [shared]
	const ICE_GUARD_NAME "a|Fire Guardian"
	const ICE_GUARD_HP 6000
	//const ICE_GUARD_ICE_VULN 0.5
	const ICE_GUARD_FIRE_VULN 0.0
	const ICE_GUARD_LEVEL 2
	const ICE_GUARD_MODEL monsters/fire_guardian.mdl
	const ICE_GUARD_WIDTH 32
	const ICE_GUARD_HEIGHT 96

	const NPC_BASE_EXP 2000

	const DMG_BURST 200
	const DMG_LUNGE 250
	const DMG_STAFF 150
	const DOT_FROST 150

	const DMG_FIRE_BURST 400

	setvard FLAME_JET_DMG 200
	setvard FLAME_JET_DOT 100

	const FREQ_ICE_BALL $randf(10.0,20.0) //no sustain circle - but does this BS move more often

	const GUARD_ELEMENT fire
	const ICE_GUARD_DOT_EFFECT effects/dot_fire

	const ATTACK_MOVERANGE_DEF 200

	const FREQ_PROJECTILE 3.0

	const CL_FX_SCRIPT monsters/elemental_fire_guardian_cl

	const SOUND_STRUCK1 weapons/cbar_hitbod1.wav
	const SOUND_STRUCK2 weapons/cbar_hitbod2.wav
	const SOUND_STRUCK3 weapons/cbar_hitbod3.wav

	precache explode1.spr
	precache xfireball3.spr
}

{ game_precache
	precachefile effects/sfx_seal
	precache firemagic_8bit.spr
}

#include monsters/elemental_ice_guardian