//light and fire in hand

#scope client

{ [client]
	const SPRITE_FIRE fire1_fixed.spr
	const GLOW_RAD 128
	const GLOW_COLOR (255,255,128)
}

{ [client] client_activate //<target> <bone>

	setvard SKEL_ID PARAM1
	setvard BONE_IDX PARAM2
	if SKEL_LIGHT_ID equals 'SKEL_LIGHT_ID'
	cleffect light new $getcl(SKEL_ID,origin) GLOW_RAD GLOW_COLOR 5.0

	cleffect frameent sprite SPRITE_FIRE $getcl(SKEL_ID,bonepos,BONE_IDX) setup_flame
	//cleffect tempent sprite SPRITE_FIRE $vec(200,200,0) setup_fire_sprite fire_sprite_update
	setvard CUR_FRAME 0

	setvard SKEL_LIGHT_ID game.script.last_light_id
	setcallback render enable
}

{ [client] game_prerender

	local L_POS $getcl(SKEL_ID,origin)
	cleffect light SKEL_LIGHT_ID L_POS GLOW_RAD GLOW_COLOR 1.0
	cleffect frameent sprite SPRITE_FIRE $getcl(SKEL_ID,bonepos,BONE_IDX) setup_flame

	//callevent fire_sprite_update
}

{  [client] setup_flame

   local L_ATTACH_MDL_ID SKEL_ID
   local L_ATTACH_BODY 1

   cleffect frameent set_current_prop owner 		L_ATTACH_MDL_ID
   cleffect frameent set_current_prop skin 		L_ATTACH_MDL_ID
   cleffect frameent set_current_prop aiment 		L_ATTACH_MDL_ID
   cleffect frameent set_current_prop movetype 		12
   cleffect frameent set_current_prop body 		L_ATTACH_BODY
   cleffect frameent set_current_prop scale		0.5

	add CUR_FRAME 1
	if ( CUR_FRAME == 23 ) setvard CUR_FRAME 0
   cleffect frameent set_current_prop frame		CUR_FRAME
}

//{  [client] setup_fire_sprite
//
//	cleffect tempent set_current_prop origin $getcl(SKEL_ID,bonepos,BONE_IDX)
//	cleffect tempent set_current_prop framerate	30
//	cleffect tempent set_current_prop frames 23
//	cleffect tempent set_current_prop scale 1.0
//	cleffect tempent set_current_prop gravity 	0
//	cleffect tempent set_current_prop collide none
//	cleffect tempent set_current_prop rendermode add
//	cleffect tempent set_current_prop renderamt 200
//	cleffect tempent set_current_prop rendercolor (254,254,254)
//	cleffect tempent set_current_prop update 1
//}
//
//{ [client] fire_sprite_update
//
//	cleffect tempent set_current_prop origin $getcl(SKEL_ID,bonepos,BONE_IDX)
//}