//Standard Giant Rat

{
	const NO_EXP_MULTI 1

   setvar ANIM_IDLE idle1
   setvar ANIM_IDLE2 idle1
   //setvar ANIM_IDLE2 idle2
   setvar ANIM_RUN run
   setvar ANIM_WALK walk
   setvard ANIM_ATTACK attack
   setvard ANIM_DEATH die
	setvard MOVE_RANGE 10
   const ATTACK_DAMAGE 0.4
   setvard ATTACK_RANGE 48
   setvard ATTACK_HITRANGE 100
   const ATTACK_HITCHANCE 30%
   const SOUND_STRUCK1 weapons/cbar_hitbod1.wav
   const SOUND_STRUCK2 weapons/cbar_hitbod2.wav
   const SOUND_STRUCK3 weapons/cbar_hitbod3.wav
   const SOUND_PAIN monsters/rat/squeak1.wav
   const SOUND_ATTACK1 monsters/rat/squeak2.wav
   const SOUND_ATTACK2 monsters/orc/attack2.wav
   const SOUND_ATTACK3 monsters/orc/attack3.wav
   const SOUND_IDLE1 monsters/rat/squeak2.wav
   const SOUND_DEATH monsters/rat/squeak3.wav
   setvard CAN_FLEE 1			//Used by base_npc_attack
   const FLEE_HEALTH 2			//Used by base_npc_attack
   const FLEE_CHANCE 30%		//Used by base_npc_attack
   setvard DROP_ITEM1 skin_ratpelt 	//Used by base_monster
   setvard DROP_ITEM1_CHANCE 50%	  	//Used by base_monster

	setvard HUNT_AGRO 0


	//Possible precache issues
	precache SOUND_IDLE1
	precache SOUND_DEATH

}

#include monsters/base_monster

{
   eventname npc_spawn

   hp 4
   //ov 150
   width 32
   height 32
   name a|Giant Rat
   roam 1
   hearingsensitivity 0
   setvard NPC_GIVE_EXP 3
   race vermin

   setmodel monsters/giant_rat.mdl
   setmodelbody 1 0
   setidleanim ANIM_IDLE
   setmoveanim ANIM_WALK
}

{
   // Deal damage
   eventname bite1

   dodamage ent_lastseen ATTACK_RANGE ATTACK_DAMAGE ATTACK_HITCHANCE
}

   //Hit by someone
{
   eventname npc_struck
   
   volume 5
   playrandomsound 2 SOUND_PAIN SOUND_STRUCK2 SOUND_STRUCK1 SOUND_STRUCK3 SOUND_PAIN
}

{
   repeatdelay 10

   if !IS_HUNTING

   local STAND_UP $rand(0,5)
   if( STAND_UP == 0 ) playanim once ANIM_IDLE2
}