//Goblin

{
   setvar ANIM_RUN run
   setvar ANIM_WALK walk
   setvard ANIM_ATTACK battleaxe_swing1_L
   setvard ANIM_DEATH die_fallback
   setvard ATTACK_RANGE 130
   setvard ATTACK_HITRANGE 130
   setvard MOVE_RANGE 90
   const ATTACK_HITCHANCE 60%
	const SOUND_STRUCK1 body/flesh1.wav
	const SOUND_STRUCK2 body/flesh2.wav
	const SOUND_STRUCK3 body/flesh3.wav
	const SOUND_HIT monsters/goblin/c_gargoyle_hit1.wav
	const SOUND_HIT1 monsters/goblin/c_gargoyle_hit1.wav
	const SOUND_HIT2 monsters/goblin/c_gargoyle_hit2.wav
	const SOUND_PAINYELL monsters/orc/pain.wav
	const SOUND_WARCRY1 monsters/goblin/c_goblin_bat1.wav
	const SOUND_ATTACK1 monsters/goblin/c_goblin_atk1.wav
	const SOUND_ATTACK2 monsters/goblin/c_goblin_atk2.wav
	const SOUND_ATTACK3 monsters/goblin/c_goblin_atk3.wav
	const SOUND_DEATH monsters/goblin/c_goblin_dead.wav
	const SOUND_DEATH2 monsters/goblin/c_goblin_dead.wav
	const SOUND_HELP monsters/goblin/c_goblin_bat2.wav
   setvard CAN_HUNT 1
   setvard HUNT_AGRO 1
   setvard RETALIATE_CHANCE 75%  //base_npc_attack - Automatically switch targets to the last damaging player
   setvard CAN_FLEE 0		//base_npc_attack - Whether I run away at low health
   setvard DROP_GOLD 		$rand(0,1)
   setvard DROP_GOLD_MIN		1
   setvard DROP_GOLD_MAX		2
	setvard NPC_MUST_SEE_TARGET 0
 
   //Precache
   precache SOUND_DEATH //This sound must be explicitly precached since
			//the play command for it isn't in this file (it's
			//in base_monster.script)
}

#include monsters/base_monster_new

{
   eventname npc_spawn

	if ( G_NO_GOBLINS ) deleteent ent_me

   hp 50
   //ov 180
   width 32
   height 60
   name a|Goblin
   roam 1
   hearingsensitivity 6
   setvard NPC_GIVE_EXP 25
   race goblin
	setmodel monsters/goblin_new.mdl
	setmodelbody 0 0 //body: 0-bare 1-quiver 2-invis
	setmodelbody 1 0 //head: 0-bare 1-horns 2-Animal 3-chieftan 4-Slick
	setmodelbody 2 1 //weapon: 0-Unarmed 1-Axe 2-wbow 3-sbow 4-sword 5-rAxe 6-sword&shield 7-club 8-knife
	setmodelbody 3 0 //arrow: On/off
   setidleanim idle1
   setmoveanim ANIM_WALK
}

{
   // Deal damage
   eventname swing_axe
   setvar ATTACK_DAMAGE $randf(6,9)
   if ( $get(NPCATK_TARGET,range) < ATTACK_HITRANGE ) callevent npcatk_dodamage NPCATK_TARGET direct ATTACK_DAMAGE ATTACK_HITCHANCE

   callevent attack_sound
}

   //Hit by someone
{
   eventname npc_struck
   
   volume 5
   playrandomsound 2 SOUND_HIT SOUND_HIT2 SOUND_STRUCK1 SOUND_STRUCK2 SOUND_STRUCK3
}

   //Attack grunts
{
   eventname attack_sound
   
   if( $rand(0,1) == 0 )
   {
   	volume 5
   	playrandomsound 2 SOUND_ATTACK1 SOUND_ATTACK2 SOUND_ATTACK3
   }
   else
   {
      if( $rand(0,5) == 2 ) playsound 4 SOUND_WARCRY1
   }
}

{
   eventname npc_targetsighted		//Warcry

   local LASTSEEN_ENEMY $get(ent_lastseen,id)
   if LASTSEEN_ENEMY isnot LAST_ENEMY

   playsound game.sound.voice 5 SOUND_WARCRY1
   setvard LAST_ENEMY LASTSEEN_ENEMY
}

{ goblin_remove
	deleteent ent_me fade
}

{ game_death
	setmodelbody 2 0
}