//Hunger from Walking Ashes

{

   const SKEL_HP		70
   const ATTACK_HITCHANCE 	70%
   const ATTACK_DAMAGE_LOW 	0.9 
   const ATTACK_DAMAGE_HIGH 	10
   setvard NPC_GIVE_EXP 		50

   setvard DROP_GOLD 		1
   setvard DROP_GOLD_MIN		3
   setvard DROP_GOLD_MAX		7

   const SKEL_RESPAWN_CHANCE	0
   const SKEL_RESPAWN_LIVES	0
}

#include monsters/skeleton_base

{ skeleton_spawn

   name a|Hungry Skeleton
   movespeed 2
   roam 1
   hearingsensitivity 3
   blood none
}