{
	const PROJECTILE_SCRIPT proj_spore
	setvard SPORE_POISON_DMG 60

	const DMG_SWIPE $rand(80,200)

	const NPC_BASE_EXP 800
}

#include monsters/k_childre

{ game_precache
	precachefile monsters/summon/poison_burst
}

{ [override] childre_spawn

	name a|Black Kharaztorant Childre
	setmodel monsters/k_childre_black.mdl
	hp 3000
	race demon
	width 32
	height 68
	roam 1
	setbbox npcsize
	hearingsensitivity 4
	local L_MAP_NAME $lcase(game.map.name)
	if ( L_MAP_NAME contains helena )
	{
		setvard STEP_SIZE_NORM 18
		local EXIT_SUB 1
	}
	if ( L_MAP_NAME contains demontemple )
	{
		setvard STEP_SIZE_NORM 24
		local EXIT_SUB 1
	}
	if ( L_MAP_NAME contains islesofdread )
	{
		setvard STEP_SIZE_NORM 24
		local EXIT_SUB 1
	}
	if !EXIT_SUB
	stepsize STEP_SIZE_NORM
}

{ npc_post_spawn

	//resistances
	takedmg all 0.5
	takedmg fire 1.0
	takedmg cold 0.5
	takedmg holy 1.0
	takedmg poison 0.0
	takedmg lightning 2.0

	setvard IMMUNE_STUN 50

	//post-load stats used by base
	setvard ANIM_FLINCH new_flinch
	setvard CAN_FLINCH 1
	setvard FLINCH_HEALTH 500
	setvard FLINCH_DELAY 5.0
	setvard FLINCH_CHANCE 50

	setmoveanim ANIM_WALK
	setidleanim ANIM_IDLE
	setstat parry 100
}

{ [override] normal_immunes
	setvard AM_INVISIBLE 0
	takedmg all 0.5
	takedmg fire 1.0
	takedmg cold 0.5
	takedmg holy 1.0
	takedmg poison 0.0
	takedmg lightning 2.0
}

{ [override] do_fireball
	playsound 0 10 SOUND_FIREBALL
	setvard FIREBALL_TOSS 1
	playanim critical ANIM_ATTACK
	tossprojectile NPCATK_TARGET 400 200 0 PROJECTILE_SCRIPT (0,48,96)
	subtract FIREBALL_AMMO 1
	if ( FIREBALL_AMMO == 0 ) setprop ent_me skin 0
	callevent npcatk_resume_ai
	roam 1
}


{ [override] do_fade
	createnpc monsters/summon/poison_burst $get(ent_me,origin) $get(ent_me,id) 128 1 100 30
	callevent npcatk_flee NPCATK_TARGET 2048 3.0
	setvard FADE_TARGET NPCATK_TARGET
	setvard DOING_FADE 1
	callevent npcatk_suspend_ai 2.0
	setmoveanim ANIM_RUN
	setvard WAS_STRUCK 0
	callevent 0.1 do_fade2
	callevent 1.0 resume_attack
}