//Moved to player/cl_player_effects_special
#scope client
{ [client]
	const SPRITE_DRAINER fire1_fixed.spr
	const DRAINER_SPEED 30
	const GLOW_SPRITE glow01.spr
}

{ [client] client_activate

	setvard MY_OWNER PARAM1
	setvard SPRITE_POPS "0;0;0;0;0;0;0;0"
	dbg **** client_activate
}

{ [client] end_effect
	removescript
}

{ [client] spawn_drain_sprite_cl //<pos> <idx> <angs>
	local SPAWN_LOC PARAM1
	local DRAINER_INDEX PARAM2
	setvard DRAINER_ANGS PARAM3
	dbg **** spawn_drain_sprite_cl pos: PARAM1 idx: PARAM2 angs: PARAM3
	if ( DRAINER_INDEX == 1 ) cleffect tempent sprite SPRITE_DRAINER SPAWN_LOC setup_drainer update_drainer1
	if ( DRAINER_INDEX == 2 ) cleffect tempent sprite SPRITE_DRAINER SPAWN_LOC setup_drainer update_drainer2
	if ( DRAINER_INDEX == 3 ) cleffect tempent sprite SPRITE_DRAINER SPAWN_LOC setup_drainer update_drainer3
	if ( DRAINER_INDEX == 4 ) cleffect tempent sprite SPRITE_DRAINER SPAWN_LOC setup_drainer update_drainer4
	if ( DRAINER_INDEX == 5 ) cleffect tempent sprite SPRITE_DRAINER SPAWN_LOC setup_drainer update_drainer5
	if ( DRAINER_INDEX == 6 ) cleffect tempent sprite SPRITE_DRAINER SPAWN_LOC setup_drainer update_drainer6
	if ( DRAINER_INDEX == 7 ) cleffect tempent sprite SPRITE_DRAINER SPAWN_LOC setup_drainer update_drainer7
	if ( DRAINER_INDEX == 8 ) cleffect tempent sprite SPRITE_DRAINER SPAWN_LOC setup_drainer update_drainer8
}

{ [client] update_drainer //<idx> <angs>

	local DRAINER_INDEX PARAM1

	if ( DRAINER_INDEX == 1 ) 
	{
		setvard DRAINER_ANGS1 PARAM2
		dbg **** update_drainer 1 DRAINER_ANGS1
	}
	if ( DRAINER_INDEX == 2 ) setvard DRAINER_ANGS2 PARAM2
	if ( DRAINER_INDEX == 3 ) setvard DRAINER_ANGS3 PARAM2
	if ( DRAINER_INDEX == 4 ) setvard DRAINER_ANGS4 PARAM2
	if ( DRAINER_INDEX == 5 ) setvard DRAINER_ANGS5 PARAM2
	if ( DRAINER_INDEX == 6 ) setvard DRAINER_ANGS6 PARAM2
	if ( DRAINER_INDEX == 7 ) setvard DRAINER_ANGS7 PARAM2
	if ( DRAINER_INDEX == 8 ) setvard DRAINER_ANGS8 PARAM2
}

{ [client] update_drainer1
	//dbg **** update_drainer1 DRAINER_ANGS1 DRAINER_SPEED
	cleffect tempent set_current_prop velocity $relvel(DRAINER_ANGS1,$vec(0,DRAINER_SPEED,0))
	local MY_IDX 1
	subtract MY_IDX 1 //tokens start at 0
	if ( $get_token(SPRITE_POPS,MY_IDX) == 1 )
	{
		token.set SPRITE_POPS MY_IDX "0"
		cleffect tempent set_current_prop death_delay 0.1
		local SPRITE_ORG game.tempent.origin
		callevent sprite_splode SPRITE_ORG
	}
}
{ update_drainer2
	cleffect tempent set_current_prop velocity $relvel(DRAINER_ANGS2,$vec(0,DRAINER_SPEED,0))
	local MY_IDX 2
	subtract MY_IDX 1 //tokens start at 0
	if ( $get_token(SPRITE_POPS,MY_IDX) == 1 )
	{
		token.set SPRITE_POPS MY_IDX "0"
		cleffect tempent set_current_prop death_delay 0.1
		local SPRITE_ORG game.tempent.origin
		callevent sprite_splode SPRITE_ORG
	}
}
{ update_drainer3
	cleffect tempent set_current_prop velocity $relvel(DRAINER_ANGS3,$vec(0,DRAINER_SPEED,0))
	local MY_IDX 3
	subtract MY_IDX 1 //tokens start at 0
	if ( $get_token(SPRITE_POPS,MY_IDX) == 1 )
	{
		token.set SPRITE_POPS MY_IDX "0"
		cleffect tempent set_current_prop death_delay 0.1
		local SPRITE_ORG game.tempent.origin
		callevent sprite_splode SPRITE_ORG
	}
}
{ update_drainer4
	cleffect tempent set_current_prop velocity $relvel(DRAINER_ANGS4,$vec(0,DRAINER_SPEED,0))
	local MY_IDX 4
	subtract MY_IDX 1 //tokens start at 0
	if ( $get_token(SPRITE_POPS,MY_IDX) == 1 )
	{
		token.set SPRITE_POPS MY_IDX "0"
		cleffect tempent set_current_prop death_delay 0.1
		local SPRITE_ORG game.tempent.origin
		callevent sprite_splode SPRITE_ORG
	}

}
{ update_drainer5
	cleffect tempent set_current_prop velocity $relvel(DRAINER_ANGS5,$vec(0,DRAINER_SPEED,0))

	local MY_IDX 5
	subtract MY_IDX 1 //tokens start at 0
	if ( $get_token(SPRITE_POPS,MY_IDX) == 1 )
	{
		token.set SPRITE_POPS MY_IDX "0"
		cleffect tempent set_current_prop death_delay 0.1
		local SPRITE_ORG game.tempent.origin
		callevent sprite_splode SPRITE_ORG
	}
}
{ update_drainer6
	cleffect tempent set_current_prop velocity $relvel(DRAINER_ANGS6,$vec(0,DRAINER_SPEED,0))

	local MY_IDX 6
	subtract MY_IDX 1 //tokens start at 0
	if ( $get_token(SPRITE_POPS,MY_IDX) == 1 )
	{
		token.set SPRITE_POPS MY_IDX "0"
		cleffect tempent set_current_prop death_delay 0.1
		local SPRITE_ORG game.tempent.origin
		callevent sprite_splode SPRITE_ORG
	}
}
{ update_drainer7
	cleffect tempent set_current_prop velocity $relvel(DRAINER_ANGS7,$vec(0,DRAINER_SPEED,0))

	local MY_IDX 7
	subtract MY_IDX 1 //tokens start at 0
	if ( $get_token(SPRITE_POPS,MY_IDX) == 1 )
	{
		token.set SPRITE_POPS MY_IDX "0"
		cleffect tempent set_current_prop death_delay 0.1
		local SPRITE_ORG game.tempent.origin
		callevent sprite_splode SPRITE_ORG
	}
}
{ update_drainer8
	cleffect tempent set_current_prop velocity $relvel(DRAINER_ANGS8,$vec(0,DRAINER_SPEED,0))

	local MY_IDX 8
	subtract MY_IDX 1 //tokens start at 0
	if ( $get_token(SPRITE_POPS,MY_IDX) == 1 )
	{
		token.set SPRITE_POPS MY_IDX "0"
		cleffect tempent set_current_prop death_delay 0.1
		local SPRITE_ORG game.tempent.origin
		callevent sprite_splode SPRITE_ORG
	}
}

{ sprite_popped //idx
	token.set SPRITE_POPS PARAM1 "1"
}

{ sprite_splode //origin
	local SPARK_ORG PARAM1
	cleffect tempent sprite GLOW_SPRITE SPARK_ORG setup_spark
	cleffect tempent sprite GLOW_SPRITE SPARK_ORG setup_spark
	cleffect tempent sprite GLOW_SPRITE SPARK_ORG setup_spark
	cleffect tempent sprite GLOW_SPRITE SPARK_ORG setup_spark
	sound.play3d turret/tu_die2.wav 10 SPARK_ORG
}

//============= SETUPS
{ setup_drainer

	cleffect tempent set_current_prop death_delay 60.0
	cleffect tempent set_current_prop rendercolor (0,0,255)
	cleffect tempent set_current_prop renderamt 255
	cleffect tempent set_current_prop rendermode add
	cleffect tempent set_current_prop framerate 30
	cleffect tempent set_current_prop frames 23
	cleffect tempent set_current_prop scale 1.0
	cleffect tempent set_current_prop gravity 0
	cleffect tempent set_current_prop angles DRAINER_ANGS
	cleffect tempent set_current_prop velocity $relvel(DRAINER_ANGS,$vec(0,DRAINER_SPEED,0))
	cleffect tempent set_current_prop collide none
	cleffect tempent set_current_prop update 1
}
{ [client] setup_spark
	cleffect tempent set_current_prop death_delay 	2.0
	cleffect tempent set_current_prop fadeout 	lifetime
	cleffect tempent set_current_prop velocity $relvel($vec(0,$randf(0,359),0),$vec(0,20,40))
	cleffect tempent set_current_prop bouncefactor 	5
	cleffect tempent set_current_prop scale 	0.1
	cleffect tempent set_current_prop renderamt	255
	cleffect tempent set_current_prop rendermode add
	cleffect tempent set_current_prop rendercolor (0,0,255)
	cleffect tempent set_current_prop gravity 	1.0
	cleffect tempent set_current_prop collide 	none
	cleffect tempent set_current_prop framerate	30
	cleffect tempent set_current_prop frames	1
}//============= END SETUPS