//puke fx (self removing)
#scope client

{
	const PUKE_SPRITE bloodspray.spr
	const PUKE_SPRITE_FRAMES 10
	precache PUKE_SPRITE
}

{ client_activate //<idx> <bone#>
	setvard MY_OWNER PARAM1
	setvard BONE_IDX PARAM2
	setvard DO_PUKE 1
	callevent puke_loop
	callevent 4.0 end_puke
}

{ end_puke
	setvard DO_PUKE 0
	callevent 1.0 remove_me
}

{ remove_me
	removescript
}

{ puke_loop
	if DO_PUKE
	callevent 0.1 puke_loop
	cleffect tempent sprite PUKE_SPRITE $getcl(MY_OWNER,bonepos,BONE_IDX) setup_puke
}

{ setup_puke

   cleffect tempent set_current_prop death_delay 	0.5
   cleffect tempent set_current_prop framerate		10
   cleffect tempent set_current_prop frames			PUKE_SPRITE_FRAMES
   cleffect tempent set_current_prop bouncefactor 	0
   cleffect tempent set_current_prop scale 			$randf(1.5,2.0)
   cleffect tempent set_current_prop rendermode		texture
   cleffect tempent set_current_prop renderamt		255
   cleffect tempent set_current_prop rendercolor	(0,255,0)
   cleffect tempent set_current_prop gravity 		$randf(4,5)
   cleffect tempent set_current_prop collide 		none

	local CLOUD_ANG $getcl(MY_OWNER,angles.yaw)
	local RND_RL $randf(-10,10)
	local RND_UD $randf(-220,-180)
	local CLOUD_VEL $relvel($vec(-75,CLOUD_ANG,0),$vec(RND_RL,400,RND_UD))
	cleffect tempent set_current_prop velocity CLOUD_VEL
}