//This mummy summons wraiths
#scope server
{
	//base anims
	setvar ANIM_WALK walk
	setvar ANIM_RUN walk2
	setvar ANIM_IDLE idle1

	//base stats
	setvard NPC_GIVE_EXP 1000
	setvard ATTACK_RANGE 80 //slightly longer attack range in case someone tries to sploit him while he's healing
	setvard ATTACK_HITRANGE 96
	setvard ATTACK_MOVERANGE 80 //will depend on aura, if he can
	setvard ANIM_ATTACK steelpipe
	setvard FLINCH_DAMAGE_THRESHOLD 50 //flinches easy
	setvard FLINCH_HEALTH_RATIO 0.75 // " "

	//base mummy stats
	const AURA_TYPE 3
	const ATTACK_TYPE melee
	const ATTACK_HITCHANCE 80
	const DMG_STEELPIPE 400
	const MUMMY_STARTING_LIVES 1
	const MUMMY_MELEE_DMG_TYPE blunt
	const MUMMY_IS_NECRO 1
	setvard MUMMY_STUN_CHANCE 20%
	const DMG_AURA 100
	const FREQ_MUMMY_SUMMON 15.0
	const MUMMY_SUMMON_SCRIPT monsters/wraith_summoned
}

#include monsters/mummy_base

{ game_precache
	precachefile monsters/wraith_summoned
}

{ mummy_spawn

	name a|Mummified Necromonger
	hp 7000
	takedmg holy 1.5

	setmodelbody 0 0 //0=Dark_Bandages 1=Tan_Bandages
	setmodelbody 1 1 //0=None 1=Priest 2=Royal 3=Warrior 4=High_Peasant
	setmodelbody 2 4 //0=None 1=Mace 2=Axe 3=Sword 4=Mace_Bigger 5=Magic_Sword 6=Pike 7=Pike_glowfx
	setmodelbody 3 2 //0=None 1=Red_Repulse 2=Weird_Confusion(hi-poly)
}

{ game_death
	callexternal all ext_master_died $get(ent_me,id)
}