//This mummy heals other mummies
#scope server
{
	//base anims
	setvar ANIM_WALK walk
	setvar ANIM_RUN walk2
	setvar ANIM_IDLE idle1

	//base stats
	setvard NPC_GIVE_EXP 1000
	setvard ATTACK_RANGE 80 //slightly longer attack range in case someone tries to sploit him while he's healing
	setvard ATTACK_HITRANGE 96
	setvard ATTACK_MOVERANGE 48
	setvard ANIM_ATTACK steelpipe
	setvard FLINCH_DAMAGE_THRESHOLD 50 //flinches easy
	setvard FLINCH_HEALTH_RATIO 0.75 // " "

	//base mummy stats
	const ATTACK_TYPE melee
	const ATTACK_HITCHANCE 80
	const DMG_STEELPIPE 400
	const MUMMY_STARTING_LIVES 1
	const MUMMY_IS_CLERIC 1
	const MUMMY_MELEE_DMG_TYPE blunt
	setvard MUMMY_STUN_CHANCE 20%
}

#include monsters/mummy_base


{ mummy_spawn

	name a|Mummy High Priest
	hp 5000

	setmodelbody 0 1 //0=Dark_Bandages 1=Tan_Bandages
	setmodelbody 1 4 //0=None 1=Priest 2=Royal 3=Warrior 4=High_Peasant
	setmodelbody 2 4 //0=None 1=Mace 2=Axe 3=Sword 4=Mace_Bigger 5=Magic_Sword 6=Pike 7=Pike_glowfx
	setmodelbody 3 0 //0=None 1=Red_Repulse 2=Weird_Confusion(hi-poly)
}
