//Orc Scout Archer - weak
{
   setvard DROP_GOLD $rand(0,1)		//Chance of dropping gold
   setvard DROP_GOLD_AMT $rand(1,4)	//
   setvard NPC_GIVE_EXP 10
   setvard DROP_ITEM1 bows_orcbow //Used by base_monster
   setvard DROP_ITEM1_CHANCE 20%	  //Used by base_monster
   setvard DROP_ITEM2 proj_arrow_wooden 30 //Used by base_monster
   setvard DROP_ITEM2_CHANCE 80%	  //Used by base_monster

   setvard ANIM_ATTACK shootorcbow	//Attack animation
   setvard FLINCH_CHANCE 70%

   const AIM_RATIO 30			//Ratio of target distance to aim-up angle up
   const ARROW_DAMAGE_LOW 1
   const ARROW_DAMAGE_HIGH 2
   setvard MOVE_RANGE 300
   setvard ATTACK_RANGE 800
   const ATTACK_SPEED 800
   const ATTACK_CONE_OF_FIRE 2 //Cone of fire

   setvard DROPS_CONTAINER 1
   setvard CONTAINER_DROP_CHANCE 10% 
   setvard CONTAINER_SCRIPT chests/quiver_of_bluntwood
}

#include monsters/orc_base_ranged
#include monsters/orc_base

{
   eventname orc_spawn

   hp 15
   //ov 180
   width 40
   height 90
   name a|Blackhand scout
	if ( game.map.name equals ms_wicardoven )
	{
		name an|Voldar Peon
		setprop ent_me skin 3
	}
   hearingsensitivity 1
   setstat parry 20

   setmodelbody	0 0		//Body
   setmodelbody	1 1		//Head
   setmodelbody	2 2		//Weapon
}
