//Thothie - More appropriate naming for a MS 1.35 compatibility beast
//- note I *copied* instead of *renaming*
//- Please do this as a policy, so people don't have to update all their maps with every new SC.DLL
//- Hopefully include works - seems not to for some monsters

//Thothie - backwards compatibility for MS 1.35
//- apparently supposed to be unarmed orc citizen... Er, orc girl, maybe? ;)
//- armed fists only, runs, no gold
//- Buggar - thing wont run :/


{
   setvard DROP_GOLD 0			//Gold Drops
   setvard NPC_GIVE_EXP 1
   setvard CAN_FLEE		1	//base_npc_attack - Whether I run away at low health (changes for boar)
   const FLEE_HEALTH		19	//base_npc_attack - Health at which I run away
   const FLEE_CHANCE		99%	//base_npc_attack - Chance I run away

   setvard ANIM_ATTACK swordswing1_L	//Attack animation (wanted to use "kick" but couldnt hit)

   const ATTACK_ACCURACY 50%
   const ATTACK_DMG_LOW 1
   const ATTACK_DMG_HIGH 2
}

#include monsters/orc_base_melee
#include monsters/orc_base

{  orc_spawn

   	hp 20
   	//ov 180
   	name an|Unarmed Orc
   	hearingsensitivity 0
   	setstat parry 1
	takedmg all 1.0
	invincible 0

   setmodelbody	0 0		//Body 0=naked 2=leather 3=plate 4=green-hide
   setmodelbody	1 4		//Head 0=cap_shorthorn 1=cap_nohorn 2=buffo_skin 3=cheif_ramhorns 4=green_hood
   setmodelbody	2 0		//Weapon 0=fist 1=axe 2=bow_weak 3=bow_strng 4=sword 5=bloodyaxe 6=sword&sheild
}

{ eventname superorc

	//This is for testing invulnerability script
	invincible 1
   	name an|INVULNERABLE Unarmed Orc
	setvar LIGHT_COLOR (255,255,255)
	effect glow ent_me LIGHT_COLOR 255 255 5
	saytextrange 1024
	saytext W00t! I r invlnerable!
}

{ eventname godoff

	//This is for testing invulnerability script
	invincible 0
   	name an|Unarmed Orc
	setvar LIGHT_COLOR (1,1,1)
	effect glow ent_me LIGHT_COLOR 255 5 5
	saytextrange 1024
	saytext OMG WTF h4x!
}