//Orc Archer
{
   setvard DROP_GOLD 1			//Gold Drop
   setvard DROP_GOLD_AMT $rand(2,8)
   setvard NPC_GIVE_EXP 25

   setvard ANIM_ATTACK shootorcbow	//Attack animation

   const AIM_RATIO 30			//Ratio of target distance to aim-up angle up
   const ARROW_DAMAGE_LOW 3
   const ARROW_DAMAGE_HIGH 5
   setvard MOVE_RANGE 400
   setvard ATTACK_RANGE 800
   const ATTACK_SPEED 700
   const ATTACK_CONE_OF_FIRE 3//Cone of fire

   setvard DROP_ITEM1 bows_orcbow //Used by base_monster
   setvard DROP_ITEM1_CHANCE 20%	  //Used by base_monster
   setvard DROP_ITEM2 proj_arrow_wooden 30 //Used by base_monster
   setvard DROP_ITEM2_CHANCE 80%	  //Used by base_monster

   setvard DROPS_CONTAINER 1
   setvard CONTAINER_DROP_CHANCE 10% 
   setvard CONTAINER_SCRIPT chests/quiver_of_bluntwood
}

#include monsters/orc_base_ranged
#include monsters/orc_base

{ orc_spawn

	hp 40
	//ov 180
	name an|Orc Archer
	hearingsensitivity 1.5
	setstat parry 20

	setmodelbody 0 1 //Body
	setmodelbody 1 1 //Head
	setmodelbody 2 2 //Weapon
}
