//Orc warrior

{
	setvar DROP_GOLD 1 //Gold Drops
	setvar DROP_GOLD_AMT $rand(3,8)
	setvard NPC_GIVE_EXP 30
	
	setvard DROP_ITEM1 axes_battleaxe //Used by base_monster
	setvard DROP_ITEM1_CHANCE 10%	  //Used by base_monster

	setvard ANIM_ATTACK battleaxe_swing1_L //Attack animation

	const ATTACK_ACCURACY 60%
	const ATTACK_DMG_LOW 5
	const ATTACK_DMG_HIGH 10
}

#include monsters/orc_base
#include monsters/orc_base_melee

{  orc_spawn

   	hp 60
   	//ov 180
   	name an|Orc Warrior
   	hearingsensitivity 1.5
   	setstat parry 50
	takedmg all .9

   	setmodelbody	0 2		//Body
   	setmodelbody	1 0		//Head
   	setmodelbody	2 1		//Weapon
}
