//Orc base ranged

{
   if ( MOVE_RANGE equals 'MOVE_RANGE' ) setvard MOVE_RANGE 1000
   if ( ATTACK_RANGE equals 'ATTACK_RANGE' )setvard ATTACK_RANGE 1000
   if ( ATTACK_HITRANGE equals 'ATTACK_HITRANGE' ) setvard ATTACK_HITRANGE 1000
   const SOUND_BOW weapons/bow/bow.wav
}

{  orc_spawn

	width 32
  	height 60
}

{  orc_death			//On death, don't display arrow
   	setmodelbody 3 0	//Hide arrow
}

{  grab_arrow			//Called from the animation...
				//Just pulled an arrow out of quiver
   	setmodelbody 3 1	//Show arrow
}

   // Deal damage
   // Called from the animation on the attack frame
{  shoot_arrow

	setvard AS_ATTACKING game.time

   local AIM_ANGLE $get(ent_lastseen,dist)		//Aim up a bit
   divide AIM_ANGLE AIM_RATIO				//
   setangle add_view.x AIM_ANGLE			//

   local LCL_ATKDMG $randf(ARROW_DAMAGE_LOW,ARROW_DAMAGE_HIGH)
   tossprojectile view ATTACK_SPEED LCL_ATKDMG ATTACK_CONE_OF_FIRE proj_arrow_npc (0,0,48)
   setmodelbody 3 0		//Hide arrow
   playsound 2 SOUND_BOW
}

{ npc_targetsighted
	if !ALT_ATTACKS
	if ( $get(PARAM1,range) < ATTACK_RANGE ) playanim once ANIM_ATTACK
}