//This is an older script and may have some bad conventions as a result
//Rat

{

	const NO_EXP_MULTI 1

	setvard HUNT_AGRO 0

	setvard ANIM_DEATH die
	setvar ANIM_RUN run
	setvar ANIM_WALK walk
	setvard ANIM_ATTACK attack
	setvar ATTACK_DAMAGE 0.4
	setvard ATTACK_RANGE 68
	setvar ATTACK_HITCHANCE 30%
	setvar SOUND_STRUCK1 weapons/cbar_hitbod1.wav
	setvar SOUND_STRUCK2 weapons/cbar_hitbod2.wav
	setvar SOUND_STRUCK3 weapons/cbar_hitbod3.wav
	setvar SOUND_PAIN monsters/rat/squeak1.wav
	setvar SOUND_ATTACK1 monsters/rat/squeak2.wav
	setvar SOUND_ATTACK2 monsters/orc/attack2.wav
	setvar SOUND_ATTACK3 monsters/orc/attack3.wav
	setvar SOUND_IDLE1 monsters/rat/squeak2.wav
	const SOUND_DEATH monsters/rat/squeak3.wav
	setvard CAN_FLEE 1		//Used by base_npc_attack
	setvar FLEE_HEALTH 2		//Used by base_npc_attack
	setvar FLEE_CHANCE 30%	//Used by base_npc_attack
	setvard DROP_ITEM1 skin_ratpelt //Used by base_monster
	setvard DROP_ITEM1_CHANCE 50%	  //Used by base_monster
}

#include monsters/base_monster

{ npc_spawn

   hp 4
   //ov 150
   width 40
   height 64
   name a|Rat
   roam 1
   hearingsensitivity 0
   setvard NPC_GIVE_EXP 3
   race vermin

   setmodel monsters/rat.mdl
   setmodelbody 1 0
   setidleanim idle
   setmoveanim ANIM_WALK
}

{
  repeatdelay 10

  if !IS_HUNTING 
  if $rand(0,1) 

  playanim once idle2
}

{
   // Deal damage
   eventname bite1

   playrandomsound 2 SOUND_ATTACK1 none
   dodamage ent_lastseen ATTACK_RANGE ATTACK_DAMAGE ATTACK_HITCHANCE
}

   //Hit by someone
{
   eventname npc_struck
   
   volume 5
   playrandomsound 2 SOUND_PAIN SOUND_STRUCK2 SOUND_STRUCK1 SOUND_STRUCK3 SOUND_PAIN
}
