//Thothie - supplied for backwards compatability with MS1.35
//-TBH: I've no idea what this did in 1.35 - so, now it just spawns a rock
//-to prevent server crash on maps using it. (I think it's supposed to make spooky sounds, er somethin)
//-Currently I'm using it to verify my SC.DLL updated after map change (Hence the name)
{ spawn

   hp 150
   width 50
   height 50
   roam 0
   name a|PlaceHolder [Test Minions]
   setidleanim seq-name
   setmodel props/rock1.mdl
}