#scope client

{ [client] client_activate

}

{ [client] poof_fx
	setvard SPRITE_CENTER PARAM1
	cleffect tempent sprite 3dmflaora.spr SPRITE_CENTER poof_sprite
	cleffect tempent sprite 3dmflaora.spr SPRITE_CENTER poof_sprite
	cleffect tempent sprite 3dmflaora.spr SPRITE_CENTER poof_sprite
	cleffect tempent sprite 3dmflaora.spr SPRITE_CENTER poof_sprite
	cleffect tempent sprite 3dmflaora.spr SPRITE_CENTER poof_sprite
	cleffect tempent sprite 3dmflaora.spr SPRITE_CENTER poof_sprite
}

{ [client] unpoof_fx
	setvard SPRITE_CENTER PARAM1
	setvard ANG_COUNT 0
	calleventloop 6 unpoof_fx_loop
}

{ [client] unpoof_fx_loop
	local START_LOC SPRITE_CENTER
	vectoradd START_LOC $relpos($vec(0,ANG_COUNT,0),$vec(0,128,96))
	cleffect tempent sprite 3dmflaora.spr START_LOC unpoof_sprite
	add ANG_COUNT 60
}

{ [client] poof_sprite
	cleffect tempent set_current_prop death_delay 	5.0
	cleffect tempent set_current_prop velocity 	$vec(-90,$randf(-125,125),$randf(-125,125))
	cleffect tempent set_current_prop bouncefactor 	5
	cleffect tempent set_current_prop scale 	2
	cleffect tempent set_current_prop gravity 	$randf(-1.5,-1.1)
	cleffect tempent set_current_prop collide 	none
	cleffect tempent set_current_prop framerate	30
	cleffect tempent set_current_prop frames	1
	cleffect tempent set_current_prop rendermode add
	cleffect tempent set_current_prop rendercolor (255,0,0)
}

{ [client] unpoof_sprite
	cleffect tempent set_current_prop death_delay 	5.0
	cleffect tempent set_current_prop velocity 	$dir(START_LOC,SPRITE_CENTER) 
	cleffect tempent set_current_prop bouncefactor 	5
	cleffect tempent set_current_prop scale 	2
	cleffect tempent set_current_prop gravity 	1.0
	cleffect tempent set_current_prop collide 	none
	cleffect tempent set_current_prop framerate	30
	cleffect tempent set_current_prop frames	1
	cleffect tempent set_current_prop rendermode add
	cleffect tempent set_current_prop rendercolor (255,0,0)
}
