//server side beam effect
#scope server
{ game_spawn
	nopush 1
	invincible 1
	fly 1
	gravity 0
	setmodel monsters/shadowform_beams.mdl
	setidleanim rot
	setmoveanim rot
	setsolid none
	setbbox none
	playanim once rot
}

{
repeatdelay 10.0
	playanim once rot
	effect beam ents lgtning.spr 30 ent_me 1 ent_me 2 (200,0,200) 100 200 10.0
	effect beam ents lgtning.spr 30 ent_me 2 ent_me 3 (200,0,200) 100 200 10.0
	effect beam ents lgtning.spr 30 ent_me 3 ent_me 4 (200,0,200) 100 200 10.0
	effect beam ents lgtning.spr 30 ent_me 1 ent_me 1 (200,0,200) 100 200 10.0
}

//{
//repeatdelay 30.0
//	clientevent new all monsters/shadow_form_boss_fx_cl $get(ent_me,index)
//}

{ remove_beams //called by boss
	deleteent ent_me
}