//Nastier of the ice archers
#scope server
{
	//base stats
	setvard NPC_GIVE_EXP 800

	//skele stats
	const DMG_ARROW 400
	const DMG_SWIPE 80
	const C_SKELE_PUSH_STRENGTH 600
	const SKELE_GOLD 100

	const SKELE_ARROW_EFFECT effects/dot_cold
	const SKELE_ARROW_EFFECT_HANDLED 1 //direct hits have freeze_solid effects
	const SKELE_ARROW_AOE 128
	const SKELE_DOT_DMG 50
	const SKELE_DOT_DUR 5.0
	const SKELE_ARROW_GLOW 1
	const SKELE_ARROW_GLOW_COLOR (128,128,255)
	const SKELE_ARROW_SCRIPT proj_arrow_npc_dyn
	const C_SKELE_ARROW_KNOCKBACK 800

	const SKELE_DROPS_CONTAINER 1
	const SKELE_CONTAINER_SCRIPT chests/quiver_of_frost
	const SKELE_DROPS_CONTAINER_CHANCE 100%

	const SKELE_START_LIVES 1
	const SKELE_ARROW_ARC 1
	const SKELE_ARROW_SPEED 500

	//local stats
	const ARROW_CL_SCRIPT effects/sfx_ice_burst
	const DMG_AOE 200
	const FREEZE_DUR 8.0

	// createnpc monsters/skeleton_archer_fire2
}

#include monsters/skeleton_archer_base

{ skele_spawn
	name an|Ancient Frozen Archer
	hp 3000

	takedmg fire 1.25
	takedmg cold 0.0
	takedmg holy 1.25
	height 80

	setmodelbody 0 5 //0=Classic 1=Dark 2=Poison 3=Fire 4=Gore 5=Ice 6=Gold 7=Stone 8=Royal_ice 9=Bright_Fire 10=Greek_Armor
	setmodelbody 1 10 //0=Unarmed 1=Mace 2=Sword 3=Hammers 4=Sword+Shield 5=Ice_Clubs 6=Fire_Clubs 7=Big_Sword 8=Wand 9=Wand_Glow 10=Bow
	setmodelbody 2 0 //0=Hide_Arrow 1=Show_arrow
}

{ skele_arrow_fx
	local ARROW_ORG PARAM1
	//<center_point> <radius> <light:0|1> <light_color>
	clientevent new all ARROW_CL_SCRIPT ARROW_ORG 128 1 (0,0,255)
	xdodamage ARROW_ORG SKELE_ARROW_AOE DMG_AOE 0 ent_me ent_me none cold_effect
}

{ skele_handle_effect
	applyeffect PARAM1 effects/dot_cold_freeze FREEZE_DUR $get(ent_me,id) SKELE_DOT_DMG
}


//glow
{ npc_post_spawn
	clientevent new all effects/sfx_follow_glow_cl $get(ent_me,index) (128,128,255) 128 15.0
}

{
repeatdelay 15.1
	//renew light 10/secs (light is now self-removing)
	if $get(ent_me,isalive)
	clientevent new all effects/sfx_follow_glow_cl $get(ent_me,index) (128,128,255) 128 15.0
}