{
	const PROJ_TYPE proj_fire_xolt
	const PROJ_OFS (0,0,32)
	setvard DOT_FIRE 3
}

#include monsters/spider_turret

{ [override] spider_spawn

	hp 150
	//ov 359
	if ( !AM_CLIPPED )
	{
		width 64
		height 64
	}

	if ( AM_CLIPPED )
	{
		width 32
		height 20
		setbbox npcsize
	}

	name a|Fire Spider
	hearingsensitivity 7
	setmodel monsters/fer_spider_large.mdl
	setprop ent_me skin 1
	takedmg all .8
	takedmg fire 0.0
	setanim.movespeed 0.0
	movespeed 0
	setmoveanim ANIM_IDLE
	setvard NO_STUCK_CHECKS 1

	setvard NPC_GIVE_EXP	100
	callevent 0.1 make_turret

	//catchspeech debug_props debug
}

{ make_turret
	setvar ANIM_RUN idle
	setvar ANIM_WALK idle
}

{ game_dodamage

	if PARAM1
	if $rand(1,5) == 1
	applyeffect PARAM2 effects/dot_fire 5 $get(ent_me,id) DOT_FIRE 1 1
}