{
	const PROJ_TYPE proj_fire_xolt
	const PROJ_OFS (0,0,32)
	setvard DOT_FIRE 3
}

#include monsters/spider_spitting

{ [override] spider_spawn

	hp 100
	//ov 359
	if ( !AM_CLIPPED )
	{
		width 64
		height 64
	}

	if ( AM_CLIPPED )
	{
		width 32
		height 20
		setbbox npcsize
	}

	name a|Fire Spider
	hearingsensitivity 7
	setmodel monsters/fer_spider_large.mdl
	setprop ent_me skin 1
	takedmg all .8
	takedmg fire 0.0
	setvard NPC_GIVE_EXP	90

	//catchspeech debug_props debug
}

{ game_dodamage

	if PARAM1
	if $rand(1,5) == 1
	applyeffect PARAM2 effects/dot_fire 5 $get(ent_me,id) DOT_FIRE
}