//Spot enemy hack by Thothie
//- For non-agro monsters that have issues spotting enemies, such as guards
//- use callevent 1.0 see_enemy in spawn to start checks
//- bade obsolete by new AI 7/Sep/2006 18:55
{ see_enemy

	repeatdelay 1.0

	////dbg HUNT_LASTTARGET

	if ( HUNT_LASTTARGET isnot 'HUNT_LASTTARGET' )
	{
			if ( HUNT_LASTTARGET isnot ¯NONE¯ )	local EXIT_SUB 1
	}
	if !EXIT_SUB

	if ( $cansee(enemy) ) 
	{
		if ( !NO_ADVANCED_SEARCHES ) fov 359
		setvard CAN_ATTACK 1
		setvard CAN_HUNT 1
		setvard NPC_MOVE_TARGET $get(ent_lastseen,id)
		setvard NPC_ATTACK_TARGET NPC_MOVE_TARGET
		setvard HUNT_LASTTARGET ent_lastseen
		setvard CYCLE_TIME CYCLE_TIME_ACTIVE
		callevent cycle_up
		setmovedest ent_lastseen MOVE_RANGE
		if ( $get(range,ent_lastseen) < ATTACK_RANGE ) callevent npcatk_attackenemy
	}
}