#scope server
{
	setvard NPC_GIVE_EXP 1500
	setvard DROP_GOLD 1
	setvard DROP_GOLD_AMT 300

	const ELF_IS_ARCHER 1
	const ELF_EXPLOSIVE_BOLTS 1
	const ELF_MELEE_PUSH_VEL $relvel(10,400,110)

	const DMG_MELEE 25
	const ATTACK_HITRANGE_MELEE 64
}

#include monsters/elf_wizard_base

{ elf_spawn


	name a|Torkalath Apprentice
	hp 4000
	race torkie

	setmodelbody 1 3 //0=Unarmed 1=Dark_Staff 2=Dragon_Staff 3=H4xbow
	setprop ent_me skin 2 //0=Young_Black_Robe 1=Elder_Black_Robe 2=Young_Green_Robe 3=Elder_Green_Robe 4=Young_Puce_Robe 5=Elder_Puce_Robe 6=Good_Pale 7=Good_Pink
}
