{
	const AM_GENERIC 1
}

{ game_precache
	precachefile aleyesu/death_image
}

#include bloodrose/venevus

{ do_ale_intro
	callevent 1.0 do_ale_intro1
}

{ do_ale_intro1
	saytextrange 2048
	saytext "I don't believe it! I mean of course I believe it, I did just travel forward through time."
	callevent 4.0 do_ale_intro2
}

{ do_ale_intro2
	saytext "Who are you?! What are you doing in my chamber?!"
	callevent 4.0 do_ale_intro3
}

{ do_ale_intro3
	saytext "Don't tell me you touched that dial!?"
	callevent 4.0 do_ale_intro4
}

{ do_ale_intro4
	saytext "Oh never mind... I'll just kill you all!"
}

{ game_death
	if $lcase(game.map.name) contains 'aleyesu'
	createnpc aleyesu/death_image $relpos(0,0,0) NPC_SPAWN_LOC
	setprop ent_me rendermode 5
	setprop ent_me renderamt 0
}