//This is an older script and may have some bad conventions as a result.

{
	const DMG_PROJECTILE 20
	const NPC_BASE_EXP 80
	const ZOMBIE_NAME "a|Byle Zombie"

	const SOUND_SHOOT1 bullchicken/bc_attack2.wav
	const SOUND_SHOOT2 bullchicken/bc_attack3.wav
}

#include monsters/zombie

{ npc_targetsighted
	if game.time > NEXT_BILE
	setvard NEXT_BILE game.time
	add NEXT_BILE 3.0
	if $get(NPCATK_TARGET,range) > 256
	setvard AS_ATTACKING game.time
	add AS_ATTACKING 5.0
	playanim critical ANIM_DISEASE
	setvard DOING_PROJECTILE 1
}

{ [override] attack_2


	setvard I_ATTACKING 1
	callevent npcatk_dodamage NPCATK_TARGET ATTACK_HITRANGE ATTACK_DAMAGE ATTACK_HITCHANCE blunt

	if ( DOING_PROJECTILE )
	{

		playrandomsound 0 10 SOUND_SHOOT1 SOUND_SHOOT2
		if ( $rand(1,5) == 1 )
		{
			//<projectile scriptname> <"view"|(src_origin)> <target|(targ_origin)|none> <speed> <damage> <cof> <skill|none> //Converted to use new tossprojectile //greatguys1@FEB2022
			tossprojectile "proj_poison_spit2" $relpos(0,10,24) NPCATK_TARGET 300 DMG_PROJECTILE 2 none
			effect glow ent_lastprojectile (0,255,0) 64 -1 0
		}
		else
		{
			tossprojectile "proj_poison" $relpos(0,10,24) NPCATK_TARGET 300 DMG_PROJECTILE 2 none
		}
	}

	if ( !DOING_PROJECTILE )
	{
		setvard I_DISEASE 1
		setvard ANIM_ATTACK ANIM_SWIPE
	}

	setvard DOING_PROJECTILE 0
}