{
  const ARMOR_MODEL      	armor/p_helmets.mdl
	const ARMOR_BODY 28
	const ARMOR_BODY_HUMAN_FEMALE 29
  const ARMOR_TEXT		"You equip the Helm of Venom."
  const BARMOR_TYPE		platemail
  const BARMOR_PROTECTION	60%
	const STUN_PROTECTION 50

	const SP_ATTRIB 'skill.spellcasting.affliction.ratio'
	const ELM_NAME "velm1"
	const ELM_TYPE "poison"
}

#include [server] items/base_elemental_resist
#include [shared] items/armor_base_helmet

{  game_spawn

   name 	a|Helm of Venom
   desc 	This battered helm protects the wearer from poisons
   weight 	1
   size 	20
   wearable     1 head
   value	1000
   
   sethudsprite trade 49
}

{ [server] elm_get_resist

	setvard ELM_AMT $get(ent_owner,SP_ATTRIB)
	multiply ELM_AMT 2
	multiply ELM_AMT 100
	if ( ELM_AMT > 25 ) setvard ELM_AMT 25
}

{ [server] elm_activate_effect
	callexternal ent_owner ext_register_element "velm2" "acid" ELM_AMT
}

{ [server] elm_remove_effect
	callexternal ent_owner ext_register_element "velm2" remove
}