//Thothie DA fix attempt #4 - File Pipes are not String Seperators (fixed the packs at least)
{
	const ARMOR_TEXT		"No one tosses a dwarf."
	const BARMOR_TYPE		dwarf_normal
	const BARMOR_PROTECTION	10%
}

#include [shared] items/armor_base

{  game_spawn

   name 	Dwarf Test
   desc 	Testing the submodel system
   weight 	120
   size 	60
   wearable     1 "chest;arms;legs"
   value	590
   
   sethudsprite trade armor3
}
