{
  const ARMOR_MODEL      	armor/p_helmets.mdl
  const ARMOR_BODY		2
  const ARMOR_TEXT		"You put on a knight's platemail helmet."
  const BARMOR_TYPE		platemail
  const BARMOR_PROTECTION	60%
	const STUN_PROTECTION 25
}

#include items/armor_base_helmet

{  game_spawn

   name 	a|Knight's Platemail Helmet
   desc 	A knight's platemail helmet
   weight 	40
   size 	30
   wearable     1 head
   value	530
   
   sethudsprite trade helm3
}
