{
	const ARMOR_MODEL      	armor/p_helmets.mdl
	const ARMOR_BODY		7
	//onst ARMOR_BODY_HUMAN_FEMALE 14
	const ARMOR_TEXT		"You equip the Helm of Fire Reistance."
	const BARMOR_TYPE		platemail
	const BARMOR_PROTECTION	60%
	const STUN_PROTECTION 40

	const REG_SPECIAL_EFFECT 1

	const SP_ATTRIB 'skill.spellcasting.fire.ratio'
	const ELM_NAME "fireh"
	const ELM_TYPE "fire"
}

#include [server] items/base_elemental_resist
#include [shared] items/armor_base_helmet

{ game_spawn

   name 	"the|Helm of Fire Resistance"
   desc 	"This helm causes a shiver to go down your spine."
   weight 	5
   size 	20
   wearable 1 head
   value 1150
   
   sethudsprite trade 83
}

{ [server] elm_get_resist

	setvard ELM_AMT $get(ent_owner,SP_ATTRIB)
	multiply ELM_AMT 2
	multiply ELM_AMT 100
	if ( ELM_AMT > 50 ) setvard ELM_AMT 50
}