{
  const ARMOR_MODEL      	armor/p_helmets.mdl
  const ARMOR_BODY		5
  const ARMOR_TEXT		"You put on the Helm of Stability."
  const BARMOR_TYPE		platemail
  const BARMOR_PROTECTION	60%
	const STUN_PROTECTION 70
}

#include items/armor_base_helmet

{  game_spawn

   name 	a|Helmet of Stability
   desc 	This thoroughly padded helmet offers extraordinary stun resistance
   weight 	5
   size 	20
   wearable     1 head
   value	1150
   
   sethudsprite trade 81
}

//{ [server] barmor_effect_activate
//	if game.serverside
//	setvard BOGUS_SCRIPT_TEST $randf(-10000,10000)
//}
//
//
//{ [server]
//repeatdelay 1.0
//	if game.serverside
//	dbg pulse BOGUS_SCRIPT_TEST
//	//`if ( NOT_BOGUS_SCRIPT equals 'NOT_BOGUS_SCRIPT' ) deleteent ent_me
//}