#include items/axes_battleaxe

{  weapon_spawn

   name  an|Envenomed Battleaxe
   desc  This battleaxe has been laced with a fast acting poison
   weight  80
   size  15
   value 500
   sethudsprite hand battleaxe
   sethudsprite trade battleaxe
}

{ game_dodamage

	if PARAM1
	local L_RAND $rand(0,1)
	if L_RAND
	applyeffect ent_laststruckbyme effects/dot_poison $rand(6,12) $get(ent_owner,id) $randf(3.5,5.5) axehandling
}
