//Thothie - lots of the spell scripts damage an area ever few seconds
//many are buggy in how they go about it
//hopeing to move them all over to a central system
//Required vars:
//setvard BSCAN_RADIUS 256 //radius to scan
//setvard BSCAN_OWNER	//defaults to PARAM1 of game_dynamically_Created but can be overriden
//const BSCAN_EVENT some_event //event to fire when target found <param1> will be target
//const BSCAN_ALLIES 1 //optional: set to 1 to affect allies to
{
	const BSCAN_CENTER $relpos(0,0,0)
}


{ game_dynamically_Created
	setvard BSCAN_OWNER PARAM1
	callevent 0.25 bscan_start_scan
}

{ bscan_start_scan
	//wip - do I even have a 100% dependable area scan that doesn't involve dodamage? :\
	//getents 
}