{ [server] ext_activate_items
	if PARAM1 equals $get(ent_owner,id)
	if $get(ent_me,is_worn)
	callevent barmor_effect_activate
}
{ [server] game_wear
	callevent 0.1 barmor_effect_activate
}

{ [server] game_putinpack //this isn't working (SEP2009 - comment only)
	callevent 0.1 barmor_effect_remove
}
{ [server] game_remove
	callevent 0.1 barmor_effect_remove
}
{ [server] game_fall
	callevent 0.1 barmor_effect_remove
}
{ [server] game_sheath
	callevent 0.1 barmor_effect_remove
}
{ [server] game_drop
	callevent 0.1 barmor_effect_remove
}
{ [server] game_deploy
	callevent 0.1 barmor_effect_remove
}