//Base Arrow
//1:41 PM 2/11/2005
//
//Req. Variables
//ARROW_BODY_OFS
//ANIM_DEPLOY
//ARROW_SOLIDIFY_ON_WALL
//ARROW_BREAK_CHANCE

{
  const MODEL_HANDS      	weapons/bows/p_arrows.mdl
  const MODEL_WORLD      	weapons/bows/p_arrows.mdl
  const SOUND_HITWALL1		weapons/bow/arrowhit1.wav
  const SOUND_HITWALL2		weapons/bow/arrowhit1.wav
  const SPRITE_ARROW_TRADE	woodenarrow
  const SPRITE_ARROW_HAND	arrows
  const ARROW_BODY_OFS		0
  const ANIM_DEPLOY		idle2
  const ANIM_DROPPED		idle1
  const ARROW_EXPIRE_DELAY 	20
  setvard PROJ_DAMAGETYPE	pierce
  setvard PROJ_COLLIDEHITBOX	1	//Only hit monster hitboxes, not bounding boxes
}

#include items/base_projectile

{
   eventname 	projectile_spawn

   groupable    	25
   playanim     	ANIM_DEPLOY
 
   setworldmodel	MODEL_WORLD
   sethudsprite 	hand SPRITE_ARROW_HAND
   sethudsprite 	trade SPRITE_ARROW_TRADE
   sethand 		left

   callevent 		arrow_spawn
}


{
  eventname game_deploy

  setviewmodel  none
  setmodel 	MODEL_HANDS
  playanim 	ANIM_DEPLOY

  local 	MB_TEMP game.item.hand_index
  inc		MB_TEMP 1
  inc	 	MB_TEMP ARROW_BODY_OFS
  setmodelbody 	0 MB_TEMP

  callevent 	arrow_deploy
}
{
  eventname game_fall

  setmodelbody 	0 ARROW_BODY_OFS

  playanim	ANIM_DROPPED
}


{
  eventname game_projectile_hitwall

  volume 5
  playrandomsound 0 SOUND_HITWALL1 SOUND_HITWALL2
  //if( ARROW_SOLIDIFY_ON_WALL == 1 ) solidifyprojectile

  //callevent arrow_hitwall
}

{
  eventname projectile_landed

  expiretime ARROW_EXPIRE_DELAY	//Let the fired arrows stay around for a bit
  if( ARROW_BREAK_CHANCE > 0 ) callevent arrow_breakchance
}
{
  eventname arrow_breakchance

  if $rand(0,99) < ARROW_BREAK_CHANCE

  callevent projectile_broke
  deleteme
}