//Thothie - 'all your concentration' - as wiki says, 'disambiguation'.
//- Scrolls changed to Tomes for new spell system
//Requires:
//SPELL_SCRIPT

{
  const MODEL_WORLD      	misc/p_misc.mdl
  const MODEL_HOLD      	misc/p_misc.mdl
}

#include items/base_item_extras

{ game_spawn

	weight 	1
	size 	2
	setworldmodel MODEL_WORLD
	sethudsprite hand item
	sethudsprite trade book
	callevent script_spawn
}

{ game_deploy

	callexternal $get(ent_owner,id) tome_warn

	callevent 1.0 tome_two
	setviewmodel  none
	setmodel MODEL_HOLD
	local L_SUBMODEL 15
	add	L_SUBMODEL game.item.hand_index
	setmodelbody 0 L_SUBMODEL
	setvar READING 0
}

{ tome_two

	callexternal $get(ent_owner,id) tome_warn
}

{ game_fall

	setmodel	MODEL_WORLD
 	setmodelbody 	0 17
  	playanim 	package_floor_idle

	callevent scroll_fall
}

{ game_attack1

	if READING == 0

	setvard READING 1
	playermessage You study the tome carefully...
	callevent 3 learn_spell
}

{ learn_spell

	if READING == 1

	learnspell SPELL_SCRIPT
	setvard READING 0
}

{ game_removefromowner

	setvard READING 0
}

{ game_learnspell_failed

	playermessage Your spell casting skills are not yet sufficient to memorize this tome.
}