{ try_vampire_target //<owner> <target> <healAmt>

	setvard CAN_VAMPIRE_TARGET 0
	callevent check_can_vampire $pass(PARAM1) $pass(PARAM2)
	
	if CAN_VAMPIRE_TARGET
	givehp PARAM1 PARAM3
	playsound 0 5 player/heartbeat_noloop.wav //Dunno if i want this
}

{ check_can_vampire //<owner> <target>

	local L_VAMPIRE PARAM1
	local L_DAMSEL PARAM2
	
	local L_RELATIONSHIP $get(L_VAMPIRE,relationship,L_DAMSEL)
	
	if $get(L_DAMSEL,race) isnot undead
	if !$get(L_DAMSEL,scriptvar,'IMMUNE_VAMPIRE') //Cant vampire undead, or otherwise immune to vampire enemies.

	if L_RELATIONSHIP isnot ally
	if L_RELATIONSHIP isnot neutral
	if L_RELATIONSHIP isnot none

	setvard CAN_VAMPIRE_TARGET 1
} 
