{
	const MODEL_WORLD misc/p_misc.mdl
	const MODEL_HOLD misc/p_misc.mdl
	const MODEL_VIEW none
	const MODEL_WEAR armor/p_gowns.mdl
	//const NEW_MODEL_WEAR      	armor/p_body.mdl
	//const	MODEL_CREST_OFS		0
	const MODEL_BODY_OFS 16
	const ANIM_PREFIX package
}

#include items/base_item_extras

{ game_spawn

	setworldmodel MODEL_WORLD
	sethudsprite trade crestedana
	setanimext	holditem1

	setvard FINAL_OFS MODEL_CREST_OFS
	subtract FINAL_OFS 1 // Get the real submodel since setmodelbody starts at 0

	if ( MODEL_OFS_FEMALE > 0 )
	{
		if ( game.clientside )
		{
			local OWNER_RACE $get_local_prop(race)
			local OWNER_GENDER $get_local_prop(gender)
		}
		else
		{
			if game.serverside
			local OWNER_RACE $get(ent_owner,race)
			local OWNER_GENDER $get(ent_owner,gender)
		}

		local OWNER_RACE $lcase(OWNER_RACE)
		local OWNER_GENDER $lcase(OWNER_GENDER)
		if ( OWNER_RACE equals 0 ) local OWNER_RACE PARAM1 //char_menu, most likely
		if ( OWNER_GENDER equals 0 ) local OWNER_GENDER PARAM2 //char_menu, most likely

		if ( OWNER_GENDER equals female )
		{
			if ( OWNER_RACE equals human )
			{
				//setvard FINAL_OFS MODEL_OFS_FEMALE
			}
		}
	}


	weight 	0
	size 	0
	wearable     1 neck
	value	1200
	setmodelbody 0 MODEL_BODY_OFS

	callevent crest_spawn
	callevent register_armor
}

{ game_show
	setmodel MODEL_WEAR
	local REALLY_FINAL_OFS FINAL_OFS
	setmodelbody 0 REALLY_FINAL_OFS
}

{ register_armor

	setvar ARMOR_MODEL_BODY	-1

	registerarmor
}

{ game_deploy

	setmodel MODEL_HOLD
	local L_SUBMODEL MODEL_BODY_OFS
	subtract L_SUBMODEL game.item.hand_index
	setmodelbody 0 L_SUBMODEL

	callevent crest_deploy
}

{ game_fall

	setmodel MODEL_HOLD
	local L_SUBMODEL MODEL_BODY_OFS
	add L_SUBMODEL 1
	setmodelbody 0 L_SUBMODEL

	local L_ANIM ANIM_PREFIX
	stradd L_ANIM _floor_idle
	playanim L_ANIM

	callevent crest_fall
}

{ game_removefromowner

	setmodelbody 0 0

	callevent crest_remove
}

{ game_drop

   callevent game_fall
}

{ game_wear

	if ( MODEL_OFS_FEMALE > 0 )
	{
		if ( game.clientside )
		{
			local OWNER_RACE $get_local_prop(race)
			local OWNER_GENDER $get_local_prop(gender)
		}
		else
		{
			if game.serverside
			local OWNER_RACE $get(ent_owner,race)
			local OWNER_GENDER $get(ent_owner,gender)
		}

		local OWNER_RACE $lcase(OWNER_RACE)
		local OWNER_GENDER $lcase(OWNER_GENDER)
		if ( OWNER_RACE equals 0 ) local OWNER_RACE PARAM1 //char_menu, most likely
		if ( OWNER_GENDER equals 0 ) local OWNER_GENDER PARAM2 //char_menu, most likely

		if ( OWNER_GENDER equals female )
		{
			if ( OWNER_RACE equals human )
			{
				setvard FINAL_OFS MODEL_OFS_FEMALE
			}
		}
	}

	setmodel MODEL_WEAR
	local FINAL_CREST_OFS MODEL_CREST_OFS
	subtract FINAL_CREST_OFS 1 // Get the real submodel since setmodelbody starts at 0
	setmodelbody 0 FINAL_CREST_OFS

	//weararmor
	playermessagecl You place the crest over your head.

	callevent crest_remove
}
