//Base Projectile
//1:32 PM 2/11/2005
//
//Req. Variables:
//PROJ_STICK_DURATION
//PROJ_DAMAGE


#include items/base_hide_stuff
{
  eventname game_spawn

  movetype	projectile	//Causes the orientation to change based on velocity

  callevent 	projectile_spawn
  registerprojectile
}

{
  eventname game_projectile_landed

  movetype	none	//Back to normal movement
  expiretime 	0
  callevent 	projectile_landed
}