{
	const BASE_LEVEL_REQ     15

	const ANIM_HANDS_DOWN 3
	const ANIM_LIFT1 2
	const ANIM_LOWER 3
	const ANIM_IDLE1 1
	const ANIM_IDLE_TOTAL 1
	const ANIM_ATTACK1 4
	const ANIM_SHEATH 3
	const MODEL_VIEW viewmodels/v_martialarts.mdl
	const MODEL_VIEW_IDX 4

	const MODEL_HANDS weapons/p_weapons2.mdl
	const MODEL_WORLD weapons/p_weapons2.mdl
	const MODEL_BODY_OFS 112 //56

	const MELEE_DMG  125
	const MELEE_DMG_RANGE      0
	const MELEE_DMG_TYPE  poison
	const MELEE_ACCURACY  85%

	const SOUND_SWIPE weapons/swingsmall.wav
	const SOUND_HITWALL1 weapons/cbar_hitbod1.wav
	const SOUND_HITWALL2 bullchicken/bc_bite2.wav
	const SOUND_SWING weapons/swingsmall.wav

	const MELEE_CALLBACK gaunt

	const SOUND_BITE bullchicken/bc_bite2.wav

	const DOT_EFFECT effects/dot_poison
}

#include items/blunt_gauntlets_fire

{  weapon_spawn

   name  Serpent Gauntlets
   desc  These magical gauntlets have a bite
   weight  3
   size  1
   value 2000
   sethand  both
   sethudsprite hand 117
   sethudsprite trade 117
}

//{ gaunt_damaged_other
//
//	if $rand(1,2) == 1
//
//	if ( $get(PARAM1,isplayer) )
//	{
//		if !GAME_PVP
//		local EXIT_SUB 1
//	}
//	if !EXIT_SUB
//
//	playsound 0 8 SOUND_BITE
//
//	local BURN_DAMAGE $get(ent_owner,skill.spellcasting.affliction)
//	//divide BURN_DAMAGE 1.5
//	add BURN_DAMAGE $randf(1,3)
//	if ( BURN_DAMAGE < 5 ) local BURN_DAMAGE 5
//
//	applyeffect PARAM1 effects/dot_poison 5 $get(ent_owner,id) BURN_DAMAGE 0 martialarts
//}