//Blunt weapon (two-handed)
//

{
	const ANIM_LIFT1      	0
	const ANIM_IDLE1       	1
	const ANIM_IDLE_TOTAL	1
	const ANIM_ATTACK1     	2
	const ANIM_ATTACK2     	3
	const PLAYERANIM_AIM		bluntdouble
  	const PLAYERANIM_SWING		swing_bluntdouble

	const SOUND_HITWALL1 weapons/xbow_hitbod1.wav
	const SOUND_HITWALL2 weapons/cbar_hitbod2.wav
}

#include items/blunt_base_onehanded

{ weapon_spawn

    	sethand both
}
