//Snakestaff by Thothie from Hammer
//- Todos:
//- Secondary attack summons snake but poisons owner
//- Convert Model
{
  //const MODEL_VIEW        weapons/staff/snake_staff_rview.mdl
	const MODEL_VIEW        viewmodels/v_1hblunts.mdl
	const MODEL_VIEW_IDX 4

const MODEL_WORLD weapons/p_weapons2.mdl
  const MODEL_PLAYER  weapons/staff/snake_staff_player.mdl
const MODEL_BODY_OFS 58
 const ANIM_PREFIX khopesh
 const MELEE_STAT spellcasting.affliction
 const SECONDARY_DMG 0
 const MELEE_DMG_TYPE poison

 const SOUND_SUMMON magic/spawn.wav
 const SOUND_BITE bullchicken/bc_bite2.wav
 const SOUND_POISON monsters/snakeman/sm_alert1.wav

	const ANIM_LIFT1        	0
	const ANIM_IDLE1        	1
	const ANIM_IDLE_TOTAL        	1
	const ANIM_ATTACK1      	2
	const ANIM_ATTACK2      	3
	const ANIM_ATTACK3      	4
	const ANIM_SHEATH      		5

  //Used in base_melee
  //------------------
  const MELEE_RANGE  100
  const MELEE_DMG_DELAY  0.3
  const MELEE_ATK_DURATION 0.6
  const MELEE_ENERGY  0.3
  const MELEE_DMG  30
  const MELEE_DMG_RANGE      60
  const MELEE_ACCURACY  65%

	const BLUNT_NO_STUN 1

 precachefile monsters/summon/snake_cursed
}

#include items/blunt_base_onehanded

{  weapon_spawn

   name  a|Snake Staff
   desc  A magic staff used by snake charmers
   weight  10
   size  1
   value 500
   sethudsprite hand 79
   sethudsprite trade 79
}


{ melee_strike

 if $get(ent_laststruckbyme,range) < 100

 local random $rand(1,100)
 if random < 15
 dodamage ent_lastseen direct 10 1 MELEE_ACCURACY ent_owner 
 applyeffect ent_laststruckbyme effects/dot_poison $rand(3,6) $get(ent_owner,id) $randf(3,10) 0 spellcasting.affliction
 playsound 0 10 SOUND_BITE
 callevent 0.1 second_sound
}

{ second_sound
 playsound 0 10 SOUND_POISON
}

{  [override] melee_start

   local VATTACK $rand(1,3)
 if ( VATTACK == 1 ) local VATTACK_ANIM ANIM_ATTACK1
 if ( VATTACK == 2 ) local VATTACK_ANIM ANIM_ATTACK2
 if ( VATTACK == 3 ) local VATTACK_ANIM ANIM_ATTACK3
 playviewanim  VATTACK_ANIM
 if( PLAYERANIM_SWING isnot 'PLAYERANIM_SWING' ) playowneranim once PLAYERANIM_SWING global.anim.combatwalk 3
 callevent  MELEE_SOUND_DELAY melee_playsound
}

{ [override] special_02_start

	playviewanim 5

 if ( SNAKES_CREATED >= 20 ) playermessage The staffs magic is depleted, it may recharge in time.
 if SNAKES_CREATED < 20

 add SNAKES_CREATED 1
 applyeffect ent_owner effects/dot_poison 5 $get(ent_me,id) $randf(1,5)
 playermessage You have been poisoned by your snake staff!
 local NCHARGES 20
 subtract NCHARGES SNAKES_CREATED
 local NCHARGES $int(NCHARGES)
 playermessage Staff has NCHARGES charges remaining
 playsound 0 10 SOUND_SUMMON
	local SPAWN_POS $relpos(0,60,0) //surprised this works
	vectorset SPAWN_POS z $get_ground_height(SPAWN_POS)
 createnpc monsters/summon/snake_cursed $relpos(0,60,0) $get(ent_owner,id)
 effect glow ent_lastcreated (0,255,0) 100 1 1
}

