//Snakestaff by Thothie from Hammer
//- Todos:
//- Secondary attack summons snake but poisons owner
//- Convert Model
{
  const MODEL_VIEW viewmodels/gearshield_rview.mdl
const MODEL_WORLD weapons/p_weapons2.mdl
  const MODEL_PLAYER  weapons/staff/snake_staff_player.mdl
const MODEL_BODY_OFS 58
 const ANIM_PREFIX khopesh
 const MELEE_STAT spellcasting.affliction
 const SECONDARY_DMG 0
 const MELEE_DMG_TYPE poison

 const SOUND_SUMMON magic/spawn.wav
 const SOUND_BITE bullchicken/bc_bite2.wav
 const SOUND_POISON monsters/snakeman/sm_alert1.wav

 const ANIM_LIFT1         0
 const ANIM_IDLE1         0
 const ANIM_IDLE_TOTAL       1
 const ANIM_ATTACK1       1
 const ANIM_ATTACK2       3
 const ANIM_ATTACK3       5
 const ANIM_SHEATH        4

  //Used in base_melee
  //------------------
  const MELEE_RANGE  100
  const MELEE_DMG_DELAY  0.3
  const MELEE_ATK_DURATION 0.6
  const MELEE_ENERGY  0.3
  const MELEE_DMG  30
  const MELEE_DMG_RANGE      60
  const MELEE_ACCURACY  65%

}

#include items/blunt_base_onehanded

{  weapon_spawn

	name  a|Test Item
	desc  Test stuff
	weight  10
	size  1
	value 500
	sethudsprite hand item
	sethudsprite trade package
}
