// Phoenix Bow. CrazyMonkeyDude Oct 2009
// Shoots projectiles that explode when they hit the ground.
// Damage increases as range increases (Max distance 1024)

{
	const BASE_LEVEL_REQ	30
	const MODEL_VIEW_IDX	7
	const MODEL_VIEW       	viewmodels/v_bows.mdl
	const MODEL_HANDS      	weapons/p_weapons3.mdl
	const MODEL_WORLD      	weapons/p_weapons3.mdl
	const MODEL_WEAR	weapons/p_weapons3.mdl
	const SOUND_SHOOT      	weapons/bow/bow.wav
	const ITEM_NAME		longbow
	const ANIM_PREFIX	standard
	const MODEL_BODY_OFS	40

	const RANGED_AIMANGLE	(0,0,0)

	const CUSTOM_ATTACK	1
}

#include items/bows_base

{ bow_spawn

	name 			a|Phoenix Bow
	desc 			A magical bow that shoots explosive projectiles.
	weight 			100
	value			1500
	sethudsprite trade	129

	callevent custom_register
}

{ custom_register

	local reg.attack.type		charge-throw-projectile
	local reg.attack.keys		+attack1
	local reg.attack.hold_min&max	1.1;1.3
	local reg.attack.dmg.type	magic
	local reg.attack.range		1324
	local reg.attack.energydrain	1
	local reg.attack.stat		archery
	local reg.attack.COF		1;1
	local reg.attack.projectile	proj_arrow_phx
	local reg.attack.priority	0
	local reg.attack.delay.strike	0.8
	local reg.attack.delay.end	0.8
	local reg.attack.ofs.startpos	(0,0,10)
	local reg.attack.ofs.aimang	RANGED_AIMANGLE
	local reg.attack.ammodrain	0
	local reg.attack.callback	ranged
	local reg.attack.noise		1000

	registerattack
}