//Telf bows by Thothie, from Phoenix Bow by CMD

{
	const BASE_LEVEL_REQ	30
	const MODEL_VIEW_IDX	9
	const MODEL_VIEW       	viewmodels/v_bows.mdl
	const MODEL_HANDS      	weapons/p_weapons3.mdl
	const MODEL_WORLD      	weapons/p_weapons3.mdl
	const MODEL_WEAR	weapons/p_weapons3.mdl
	const SOUND_SHOOT      	weapons/bow/bow.wav
	const ITEM_NAME		longbow
	const ANIM_PREFIX	standard
	const MODEL_BODY_OFS	54
	const RANGED_POSTFIRE_DELAY	1.0
	const RANGED_ATK_DURATION 1.0
	const RANGED_AIMANGLE	(0,0,0)

	const CUSTOM_ATTACK	1

	const RANGED_HOLD_MINMAX 1.1;1.3 //Min;Max
	const RANGED_STAT archery
	const RANGED_PULLTIME 1.0

	const DAMAGE_TYPE lightning_effect
	setvar TORKIE_BOW_TYPE lightning

	const DMG_ADJ 0.65
}

#include items/bows_telf1

{ bow_spawn

	name 			a|Torkalath Lightning Bow
	desc 			This enchanted bow tingles to the touch.
	weight 			100
	value			1500
	sethudsprite trade	166

	callevent custom_register
}

{ [override] set_bow_type
	local DMG_AMT $get(ent_owner,skill.spellcasting.lightning)
	multiply DMG_AMT DMG_ADJ
	if ( UNDER_SKILLED ) multiply DMG_AMT 0.1
	setvard TORKIE_BOW_TYPE lightning
	callexternal ent_owner ext_set_spiral TORKIE_BOW_TYPE DMG_AMT
}

{ ranged_start
	if game.serverside
	local OWNER_SKILL $get(ent_owner,skill.spellcasting.lightning)
	if OWNER_SKILL < 15
	dplayermessage ent_owner You lack the lightning affinity to activate this bow's magic.
	cancelattack
}