#scope server

{ [shared]
	const ITEM_NEVER_DELETE 1

	const BASE_LEVEL_REQ 35
	const RANGED_STAT archery
	const RANGED_DMG_MULTI 1.5

	setvard WEAPON_PRIMARY_SKILL RANGED_STAT
	const MODEL_VIEW viewmodels/v_steambow.mdl
	const MODEL_HANDS weapons/p_weapons3.mdl
	const MODEL_WORLD weapons/p_weapons3.mdl
	const MODEL_BODY_OFS 80

	const VMODEL_FILE viewmodels/v_steambow.mdl

	const PMODEL_FILE weapons/p_weapons3.mdl
	const PMODEL_IDX_HANDS 80
	const PMODEL_IDX_FLOOR 82

	const VANIM_IDLE0 1 //0-6
	const VANIM_FIRE 7 //1-6
	const VANIM_RELOAD1 14
	const VANIM_RELOAD2 15
	const VANIM_RL_LOWER 16
	const VANIM_RL_LOADBOLT 17 //17 and 18, 19 not used
	const VANIM_RL_PRIME 20 //20-25 is 1-6 bolts
	const VANIM_DRAW 0

	const WANIM_HAND standard_idle
	const WANIM_FLOOR standard_floor_idle

	setvard BOW_CHAMBER 0
	setvard BOW_RELOADING 0
	setvard NEXT_BOLT 0
	setvard BOLT_ANIM 0

	const BOLT_LOAD_TIME 0.56
	const RELOAD_LOWER_TIME 0.8
	const RELOAD_RAISE_TIME 1.83
	const RELOAD_CANCEL_RAISE_TIME 1.83

	precache weapons/reload1.wav
	precache weapons/reload2.wav
	precache weapons/reload3.wav
	precache weapons/357_cock1.wav
}

#include items/base_item_extras

{ [shared] game_spawn
	name Steam Crossbow
	desc A strange dwarven contraption
	weight 50
	value 4000
	//wearable 0

	setanimext bow
	setworldmodel MODEL_WORLD
	setviewmodel MODEL_VIEW
	setpmodel	MODEL_HANDS
	sethand	both
	sethudsprite trade 147

	callevent register_attack
}

{ register_attack
	local reg.attack.type charge-throw-projectile
	local reg.attack.keys +attack1
	local reg.attack.hold_min&max 0;0
	local reg.attack.noautoaim 1
	local reg.attack.dmg.type pierce
	local reg.attack.range 1000
	local reg.attack.energydrain 0
	local reg.attack.stat archery
	local reg.attack.COF 0
	local reg.attack.projectile bolt
	local reg.attack.priority 10
	local reg.attack.delay.strike 0.0
	local reg.attack.delay.end 0.2 //reload time, I think
	local reg.attack.ofs.startpos (10,10,-15)
	local reg.attack.ofs.aimang (8,-4,0)
	local reg.attack.callback ranged
	local reg.attack.dmg.multi RANGED_DMG_MULTI //this has no affect on hitscan arrows, thus we pass to setvard HITSCAN_DMG_MULTI which they read from
	local reg.attack.noise 10

	setvard HITSCAN_DMG_MULTI RANGED_DMG_MULTI

	registerattack
}

{ ranged_start
	cancelattack
}

{ game_attack1_down

	if $get(ent_owner,scriptvar,'PLR_ACTIVE_WEAPON') equals $get(ent_me,id)

	//delay a sec if we just selected an arrow so ammo type can change
	local L_ARROW_MENU_TIME $get(ent_owner,scriptvar,'PLR_ARROW_MENU')
	if ( L_ARROW_MENU_TIME > 0 ) add L_ARROW_MENU_TIME 1.0
	if ( game.time < L_ARROW_MENU_TIME )
	{
		setvard NEXT_ATTACK L_ARROW_MENU_TIME
	}

	//got bolts in it, stop reloading and shoot
	if ( BOW_RELOADING )
	{
		if ( BOW_CHAMBER < 6 ) callevent reload_cancel
	}

	if game.time > NEXT_ATTACK

	if $get(ent_owner,canattack)

	if !BOW_RELOADING

	if ( BOW_CHAMBER < 6 )
	{
		local L_COF 0
		local L_SPEED 1000

		if ( UNDER_SKILLED )
		{
			local L_COF 20
			local L_SPEED 300

			local RND_LOCK $rand(1,3)
		}

		if ( RND_LOCK == 1 )
		{
			if BOW_CHAMBER < 6
			playsound 0 10 weapons/357_reload1.wav
			dplayermessage ent_owner Your lack of proficiency causes you to jam the weapon.
			setvard NEXT_ATTACK game.time
			add NEXT_ATTACK 4.0
			local EXIT_SUB 1
		}
		if !EXIT_SUB

		add BOW_CHAMBER 1
		local FIRE_ANIM BOW_CHAMBER
		add FIRE_ANIM VANIM_FIRE
		splayviewanim ent_me FIRE_ANIM

//		local PLR_ARROW $get(ent_owner,chosenarrow)
//		if ( PLR_ARROW equals unset )
//		{
//			clientcmd ent_owner "quickslot arrow"
//			local PLR_ARROW $get(ent_owner,chosenarrow)
//			if PLR_ARROW equals unset
//			local GENERIC_ARRROW 1
//			local PLR_ARROW proj_bolt_generic
//		}

		local PLR_ARROW proj_bolt_generic
		local L_AMMO_ID $get(ent_owner,scriptvar,'PLR_ARROW_ID')
		local L_AMMO_NAME $get(L_AMMO_ID,itemname)
		local L_AMMO_LEFT $get(L_AMMO_ID,quantity)
		if ( $get(L_AMMO_ID,owner) isnot $get(ent_owner,id) ) local L_AMMO_NAME none

		//selection is lost on map change, use the last bolt type picked and saved in player_main game_arrowmenu - Dravus
		if ( L_AMMO_NAME !startswith proj_bolt )
		{
			local L_LAST_BOLT $get_quest_data(ent_owner,sxbow_bolt)
			if ( L_LAST_BOLT startswith proj_bolt )
			{
				local L_FOUND_ID $item_exists(ent_owner,L_LAST_BOLT,id)
				if ( L_FOUND_ID isnot 0 )
				{
					local L_AMMO_ID L_FOUND_ID
					local L_AMMO_NAME L_LAST_BOLT
					local L_AMMO_LEFT $get(L_AMMO_ID,quantity)
				}
			}
		}

		if ( L_AMMO_NAME startswith proj_bolt )
		{
			if ( L_AMMO_NAME equals proj_bolt_generic )
			{
				local PLR_ARROW proj_bolt_generic
			}
			else if ( L_AMMO_LEFT > 0 )
			{
				local PLR_ARROW L_AMMO_NAME
				subtract L_AMMO_LEFT 1
				if ( L_AMMO_LEFT > 0 ) setquantity L_AMMO_ID L_AMMO_LEFT
				else local L_GONE $item_exists(ent_owner,L_AMMO_NAME,remove)
			}
		}

		dbg arrowtype: PLR_ARROW

		//<projectile scriptname> <"view"|(src_origin)> <target|(targ_origin)|none> <speed> <damage> <cof> <skill|none> //Converted to use new tossprojectile //greatguys1@FEB2022
		callexternal ent_owner ext_tossprojectile PLR_ARROW view none L_SPEED 0 L_COF archery

		playowneranim hold xbow_idle global.anim.combatwalk

		playsound 0 10 weapons/xbow_reload1.wav
		playsound 0 10 weapons/bow/crossbow.wav
	}

	dbg chamber BOW_CHAMBER

	if ( BOW_CHAMBER >= 6 )
	{
		callevent do_reload
	}
	else
	{
		callevent 0.5 do_idle
		setvard NEXT_ATTACK game.time
		add NEXT_ATTACK 0.6
	}
}

{ game_+attack2

	if $get(ent_owner,canattack)
	if $get(ent_owner,scriptvar,'PLR_ACTIVE_WEAPON') equals $get(ent_me,id)
	if game.time > NEXT_ATTACK
	if ( BOW_CHAMBER == 0 ) callevent show_chamber
	if BOW_CHAMBER > 0
	callevent do_reload
}

{ do_reload

	if $get(ent_owner,scriptvar,'PLR_ACTIVE_WEAPON') equals $get(ent_me,id)
	if !BOW_RELOADING
	if BOW_CHAMBER > 0

	setvard BOW_RELOADING 1

	playowneranim once xbow_reload global.anim.combatwalk
	playsound 0 10 weapons/357_reload1.wav

	setviewmodelprop ent_me animspeed $math(divide,0.68,RELOAD_LOWER_TIME)
	splayviewanim ent_me VANIM_RL_LOWER

	setvard NEXT_BOLT game.time
	add NEXT_BOLT RELOAD_LOWER_TIME
	subtract NEXT_BOLT 0.05
	callevent RELOAD_LOWER_TIME reload_bolt
}

{ reload_bolt

	if BOW_RELOADING
	if game.time >= NEXT_BOLT
	if $get(ent_owner,scriptvar,'PLR_ACTIVE_WEAPON') equals $get(ent_me,id)

	if ( BOW_CHAMBER <= 1 )
	{
		callevent do_reload2
		exitevent
	}

	local BOLT_IDX VANIM_RL_LOADBOLT
	add BOLT_IDX BOLT_ANIM
	add BOLT_ANIM 1
	if ( BOLT_ANIM > 1 ) setvard BOLT_ANIM 0
	setviewmodelprop ent_me animspeed $math(divide,0.62,BOLT_LOAD_TIME)
	splayviewanim ent_me BOLT_IDX

	setvard NEXT_BOLT game.time
	add NEXT_BOLT BOLT_LOAD_TIME
	subtract NEXT_BOLT 0.05
	callevent BOLT_LOAD_TIME reload_bolt2
}

{ reload_bolt2

	if BOW_RELOADING
	if game.time >= NEXT_BOLT
	if $get(ent_owner,scriptvar,'PLR_ACTIVE_WEAPON') equals $get(ent_me,id)

	subtract BOW_CHAMBER 1
	dbg bolt loaded BOW_CHAMBER

	if ( BOW_CHAMBER > 0 )
	{
		callevent reload_bolt
	}
	else
	{
		callevent do_reload2
	}
}

{ do_reload2

	setvard BOW_CHAMBER 0
	setvard BOW_RELOADING 0
	callevent do_raise RELOAD_RAISE_TIME
	callevent RELOAD_RAISE_TIME pilot_light
}

{ reload_cancel

	if ( BOW_CHAMBER > 0 ) subtract BOW_CHAMBER 1
	setvard BOW_RELOADING 0
	setvard NEXT_BOLT 0
	callevent do_raise RELOAD_CANCEL_RAISE_TIME
	callevent RELOAD_CANCEL_RAISE_TIME pilot_light
}

{ do_raise //PARAM1 = time

	setviewmodelprop ent_me animspeed $math(divide,1.83,PARAM1)
	//prime anim for however many bolts are in
	local PRIME_IDX VANIM_RL_PRIME
	add PRIME_IDX 5
	subtract PRIME_IDX BOW_CHAMBER
	splayviewanim ent_me PRIME_IDX

	setvard NEXT_ATTACK game.time
	add NEXT_ATTACK PARAM1

	setvard RAISE_END NEXT_ATTACK
	subtract RAISE_END 0.05
	callevent PARAM1 raise_done
}

{ raise_done

	if !BOW_RELOADING
	if game.time >= RAISE_END

	setviewmodelprop ent_me animspeed 1
	callevent show_chamber
}

{ show_chamber

	local IDLE_ANIM BOW_CHAMBER
	add IDLE_ANIM VANIM_IDLE0
	splayviewanim ent_me IDLE_ANIM
}

{ pilot_light
	if $get(ent_owner,scriptvar,'PLR_ACTIVE_WEAPON') equals $get(ent_me,id)

	svplaysound 0 10 weapons/bow/steam.wav
}

{ do_idle

	if $get(ent_owner,scriptvar,'PLR_ACTIVE_WEAPON') equals $get(ent_me,id)
	if !BOW_RELOADING
	callevent show_chamber
}

//============== from polearms
{ [shared] game_deploy

	callevent item_deploy //compatibility

	setviewmodel VMODEL_FILE
	setmodel PMODEL_FILE
	setworldmodel PMODEL_FILE
	setmodelbody 0 PMODEL_IDX_HANDS

	setanimext xbow
	playviewanim VANIM_DRAW
	playanim WANIM_HAND

	if game.serverside
	callevent check_skill

	setvard BOW_RELOADING 0
	setvard NEXT_BOLT 0
	setviewmodelprop ent_me animspeed 1

	if ( BOW_CHAMBER > 0 )
	{
		callevent 0.1 redeploy_idle
	}
	//so I don't prematurely fire
	setvard NEXT_ATTACK game.time
	add NEXT_ATTACK 0.6

	//callevent 0.1 arrow_check
}

{ redeploy_idle //case we slotted this during reload
	callevent show_chamber
}

//{ arrow_check
//	local PLR_ARROW $get(ent_owner,chosenarrow)
//	if ( PLR_ARROW equals unset ) clientcmd ent_owner "quickslot arrow"
//}

{ game_show
	setmodel PMODEL_FILE
	setworldmodel PMODEL_FILE
	setmodelbody 0 PMODEL_IDX_HANDS
}

{ game_drop

	callevent item_drop //compatibility
}

{ game_fall

 	setmodelbody 0 PMODEL_IDX_FLOOR
	playanim WANIM_FLOOR

	callevent weapon_fall //compatibility
}

{ game_switchhands

	playviewanim  IDLE_ANIM

	callevent item_switchhands //compatibility
}

{ check_skill
	if game.serverside

	if $get(ent_owner,scriptvar,'GAVE_MAP_INTRO')

	local FIND_MELEE_STAT "skill."
	stradd FIND_MELEE_STAT RANGED_STAT
	//dbg game_deploy $get(ent_owner,FIND_MELEE_STAT) FIND_MELEE_STAT BASE_LEVEL_REQ
	if ( $get(ent_owner,FIND_MELEE_STAT) < BASE_LEVEL_REQ )
	{
		dplayermessage ent_owner You lack the skill to properly wield this weapon!
		local OUT_STR "You lack the proficiency to wield this weapon. ( requires: "
		stradd OUT_STR RANGED_STAT
		stradd OUT_STR " proficiency "
		stradd OUT_STR BASE_LEVEL_REQ
		stradd OUT_STR " )"
		infomsg ent_owner "Insufficient Skill" OUT_STR
		setvard UNDER_SKILLED 1
	}
	else
	{
		if ( UNDER_SKILLED )
		{
			setvard HITSCAN_DMG_MULTI RANGED_DMG_MULTI
		}
		setvard UNDER_SKILLED 0
	}

	if ( !UNDER_SKILLED )
	{
		setvard HITSCAN_DMG_MULTI RANGED_DMG_MULTI
	}
	else
	{
		setvard HITSCAN_DMG_MULTI 0.1
	}
}
