//Was using wrong world model
//Drink Ale

{
  const ANIM_IDLE		0
  const ANIM_DRINK		3
  const MODEL_HANDS      	misc/p_misc.mdl
  const MODEL_WORLD      	misc/p_misc.mdl
  const MODEL_VIEW		viewmodels/v_misc.mdl
	const ITEM_MODEL_VIEW_IDX 4
  const SOUND_DRINK		items/drink.wav

  const MODEL_BODY_OFS		18
  setvar DRINK_TYPE		getdrunk
  setvar DRINK_EFFECTAMT	50
  setvar DRINK_AMOUNT     	1	
  setvar DRINK_GULP_DELAY	3
  setvar DRINK_TIME		3
}

#include items/base_drink

{ drink_spawn

   name 	a mug of|Forsuth's Bitter Ale
   desc 	Forsuth's bitter ale, brewed for the bitter cold.
   weight 	2
   size 	2
   value	1000
   sethudsprite hand item
   sethudsprite trade mhealth
}

{ game_fall

	local		L_SUBMODEL MODEL_BODY_OFS
	add		L_SUBMODEL 2
	setmodelbody	0 L_SUBMODEL

	local		L_ANIM ANIM_PREFIX
	stradd		L_ANIM _floor_idle
	playanim	L_ANIM
}

{  drink_now

   add ALE_DRUNK 1

   if ALE_DRUNK >= 1

	playermessage You feel warm and tingly all over.	

   	clientevent new ent_owner effects/sfx_drunk 5

 	callexternal $get(ent_owner,id) ext_register_element forsu cold 75
}