//Gauntlet's by Thothie, from fists_bare
//Model/Concept by Jester
//- Jester also discoverd that game_hitwall does not work - just use hitwall
//- Thothie wonders how many other script functions are busted due to that break in convention
{
	const NO_IDLE 1
	const MELEE_OVERRIDE 1

	const ANIM_HANDS_DOWN 3
	const ANIM_LIFT1 2
	const ANIM_LOWER 3
	const ANIM_IDLE1 1
	const ANIM_IDLE_TOTAL 1
	const ANIM_ATTACK1 4
	const ANIM_SHEATH 3
	const MODEL_VIEW viewmodels/v_martialarts.mdl
	const MODEL_VIEW_IDX 2
	const MODEL_BODY_OFS 54
	const MODEL_HANDS weapons/p_weapons2.mdl
	const MODEL_WORLD weapons/p_weapons2.mdl
  const SOUND_SWIPE      	weapons/swingsmall.wav
  const SOUND_HITWALL1      weapons/axemetal1.wav
  const SOUND_HITWALL2      weapons/axemetal2.wav
  const SOUND_SWING			weapons/swingsmall.wav

  const ANIM_PREFIX		gauntlets

	const NO_WORLD_MODEL 1

  //Used in base_melee
  //------------------
  const MELEE_RANGE		50
  const MELEE_DMG_DELAY		0.3
  const MELEE_ATK_DURATION	0.9
  const MELEE_ENERGY		1
  const MELEE_DMG		80
  const MELEE_DMG_RANGE     	0
  const MELEE_DMG_TYPE		blunt
  const MELEE_ACCURACY		75%
  const MELEE_STAT		martialarts
  const MELEE_VIEWANIM_ATK     	ANIM_ATTACK1

  const MELEE_SOUND     	SOUND_SWIPE
  const MELEE_SOUND_DELAY     	MELEE_DMG_DELAY
  const MELEE_PARRY_CHANCE     	5%

  const PLAYERANIM_AIM		fists
  //const PLAYERANIM_SWING	axe_onehand_swing
}

#include items/base_melee
#include items/base_kick

{  weapon_spawn

   name 	a set of|Gauntlets
   desc 	Strong metal gauntlets for otherwise unarmed combat
   weight 	3
   size 	1
   value	200
   sethand 	both
   sethudsprite hand gauntlets
   sethudsprite trade gauntlets
}

{ weapon_deploy

	playviewanim  ANIM_HANDS_DOWN

}

{ [override] melee_start

  playviewanim  ANIM_ATTACK1

  if( PUNCH_ATTACK == 0 )
  {
  	local l.punch_anim stance_normal_lowjab_r1
  	setvard PUNCH_ATTACK 1
  }
  else if( PUNCH_ATTACK == 1 )
  {
  	local l.punch_anim stance_normal_lowjab_r2
  	setvard PUNCH_ATTACK 0
  }

  playowneranim once l.punch_anim global.anim.combatwalk 3

  playsound const.sound.item 5 SOUND_SWING
  setvard FISTS_LAST_ATTACK game.time
  callevent punch1_done		//Lower fists in 5 seconds
}

{ punch1_done
  repeatdelay 1

  if FISTS_LAST_ATTACK
  local l_elapsedtime game.time
  subtract l_elapsedtime FISTS_LAST_ATTACK

  if l_elapsedtime > 5

  playviewanim ANIM_LOWER
  setvard FISTS_LAST_ATTACK 0
}

{ hitwall

  ////dbg hitwall fired

  playrandomsound 2 10 SOUND_HITWALL1 SOUND_HITWALL2
}
