{
  const MODEL_WORLD misc/p_misc.mdl
  const MODEL_HANDS misc/p_misc.mdl
  const	MODEL_BODY_OFS 28
  const ANIM_PREFIX ring
}

#include items/base_miscitem

{ miscitem_spawn

	name "Ryza's Ensorcelled Device"
	desc "You feel a faint thrum of power from the artifact that once bound Ryza"

	setviewmodel none
	setworldmodel MODEL_WORLD
	value 420
	sethudsprite trade 226
}

{ game_wear

	setmodel none
}

{ game_removefromowner

	setmodel MODEL_HANDS
}