{
	const MODEL_WORLD	misc/p_misc.mdl
	const MODEL_HOLD	misc/p_misc.mdl
	const MODEL_BODY_OFS		28
	const ANIM_PREFIX		ring
}

#include items/base_miscitem

{ miscitem_spawn

   name 	a|Bracelet of Friendship
   desc 	Inscription says: "Thanks for your help, Hugs and kisses from Salandria"
   setpmodel	MODEL_HANDS
   setviewmodel	none
   setworldmodel MODEL_WORLD
   weight 	3
   size 	3
   value	10
}