{
  const MODEL_WORLD misc/p_misc.mdl
  const MODEL_HANDS misc/p_misc.mdl
  const	MODEL_BODY_OFS 28
  const ANIM_PREFIX ring
}

#include items/base_miscitem

{ miscitem_spawn

	name "Focusing Stone"
	desc "Its radiance channels and focuses raw leyline energies."

	setviewmodel none
	setworldmodel MODEL_WORLD
	value 420
	sethudsprite trade 228
}

{ game_wear

	setmodel none
}

{ game_removefromowner

	setmodel MODEL_HANDS
}