{
  const MODEL_WORLD      	misc/p_misc.mdl
  const MODEL_HANDS      	misc/p_misc.mdl
  const MODEL_VIEW		none

  const MODEL_BODY_OFS		66
  const ANIM_PREFIX		boar
}

#include items/base_miscitem

{
   eventname miscitem_spawn

	name 	a|Cannon Ball
	desc 	This is a large iron ball for a dwarven flint cannon
	value    0
	weight 110

   setworldmodel MODEL_WORLD
   setpmodel	MODEL_HANDS
   setviewmodel MODEL_VIEW
}