{
  const MODEL_WORLD      	misc/p_misc.mdl
  const MODEL_HANDS	     	misc/p_misc.mdl
  const	MODEL_BODY_OFS		28
  const ANIM_PREFIX		ring
}

#include items/base_miscitem

{
   eventname miscitem_spawn

   name 	a|Golden Ring
   desc 	A golden ring

   setviewmodel	none
   setworldmodel MODEL_WORLD
   value	0
   wearable     1 rightfinger
   sethudsprite trade ring
}

{ game_wear

	setmodel none
}

{ game_removefromowner

	setmodel MODEL_HANDS
}