{
	const SKILL_LEVEL_REQ 0
	const SKILL_TYPE skill.spellcasting
}

#include items/base_crystal

{ crystal_spawn

	name a|Crystal of Relocation
	desc "Once this crystal's magic is deployed it will define a new respawn point."
	weight 5 //some weight prevent over-stock
	size 5
	value 1000
	sethand both
}

{ activate_crystal

	setvard OWNER_POS $get(ent_owner,origin)
	setvard BEAM_ROT 0
	callexternal $get(ent_owner,id) set_spawn_point OWNER_POS

	calleventloop 18 beams

	playsound 0 10 magic/spawn.wav
}

{ beams

	local BEAM_START OWNER_POS
	local BEAM_END OWNER_POS

	vectoradd BEAM_START $relpos($vec(0,BEAM_ROT,0),$vec(0,32,-32))
	vectoradd BEAM_END $relpos($vec(0,BEAM_ROT,0),$vec(0,32,128))
	effect beam point lgtning.spr 100 BEAM_START BEAM_END (255,0,255) 200 16 3

	add BEAM_ROT 20
}
