{
  const ARMOR_MODEL      	armor/p_helmets.mdl
  const ARMOR_BODY		11
  const ARMOR_TEXT		"You put on the funny hat."
  const BARMOR_TYPE		platemail
  const BARMOR_PROTECTION	0%
	const STUN_PROTECTION 0
}

#include items/armor_base_helmet

{  game_spawn

   name 	a|Funny Looking Hat
   desc 	A funny looking hat. Who'd wear this thing anyways?
   weight 	1
   size 	1
   wearable     1 head
   value	1
   
	sethudsprite	trade 90
}
