{
	const SKILL_LEVEL_REQ 0
	const SKILL_TYPE skill.spellcasting
}

#include items/base_crystal

{ crystal_spawn

	name a|Crystal of Return
	desc This crystal will return you to the last spawn point.
	weight 5 //some weight prevent over-stock
	size 5
	value 50
	sethand both
}

{ activate_crystal

	effect screenfade ent_owner 2 0.5 (0,0,0) 255 fadein
	local L_RESPAWN_POINT $get(ent_owner,scriptvar,'NEW_SPAWN_POS')
	
	if ( L_RESPAWN_POINT isnot 'NEW_SPAWN_POS' ) //If spawn was relocated, then use the relocated point
	{
		setorigin ent_owner L_RESPAWN_POINT
	}
	else
	{
		respawn ent_owner
	}
	
	playsound 0 10 magic/spawn.wav
}