{
	const MODEL_WORLD misc/p_misc.mdl
	const MODEL_HANDS misc/p_misc.mdl
	const MODEL_BODY_OFS	28
	const ANIM_PREFIX	ring
}

#include items/base_miscitem

{
   eventname miscitem_spawn

   name 	a|Bloodstone Ring
   desc 	A sinister red stone is mounted in this ring

   setviewmodel	none
   setworldmodel MODEL_WORLD
   value	100
   wearable     1 rightfinger
   sethudsprite trade ring
}

{ game_wear
	callevent bonus_on
	setmodel none
}

{ [server} game_removefromowner

	callevent bonus_off
	setmodel MODEL_HANDS
}

{ [server} game_deploy
	callevent bonus_off
}

{ [server}
repeatdelay 12.0
	if game.serverside
	if $get(ent_me,is_worn)
	if $get(ent_owner,scriptvar,DISPLAY_TARG_HP) equals 0
	callevent bonus_on
}

{ bonus_on
	callexternal ent_owner monster_health_on
}

{ bonus_off
	callexternal ent_owner monster_health_off
}