{
	const SKILL_LEVEL_REQ 0
	const SKILL_TYPE skill.spellcasting
}

#include items/base_crystal

{ crystal_spawn

	name a|Crystal of Return
	desc This crystal will return you to the last spawn point.
	weight 5 //some weight prevent over-stock
	size 5
	value 50
	sethand both
}

{ activate_crystal

	callexternal $get(ent_owner,id) set_spawn_point NEW_SPAWN_POS
	effect screenfade ent_owner 2 3 (0,0,0) 255 fadein
	infomessage ent_owner TELEPORTATION You have been returned to the last spawn point without XP loss.
	playsound 0 10 magic/spawn.wav
	respawn ent_owner
}