{
  const MODEL_WORLD      	misc/p_misc.mdl
  const MODEL_HANDS	     	misc/p_misc.mdl
  const	MODEL_BODY_OFS		27
  const ANIM_PREFIX		ring

	const SP_ATTRIB 'skill.spellcasting.lightning.ratio'
	const ELM_NAME "ringl"
	const ELM_TYPE "lightning"
}

#include [server] items/base_elemental_resist
#include [shared] items/base_miscitem

{ miscitem_spawn

   name 	a|Ring of Grounding
   desc 	This ring provides the owner some protection against lightning magics

   setviewmodel	none
   setworldmodel MODEL_WORLD
   value	1000
   wearable     1 rightfinger
   sethudsprite trade ring

	//if game.serverside
	//callevent 10.0 resistance_check_loop
}

{ game_wear

	setmodel none
	if game.serverside
}

{ game_removefromowner

	setmodel MODEL_HANDS
}

{ [server] elm_get_resist

	setvard ELM_AMT $get(ent_owner,SP_ATTRIB)
	multiply ELM_AMT 2
	multiply ELM_AMT 100
	if ( ELM_AMT > 75 ) setvard ELM_AMT 75
}