//Thothie - this thing does WAY too much damage, and is impossible to get at level 15
//- reducing damage and level
//- Seems more appropriate as fire than summon?
//- XP for this goes to null proficiency still :\
{
  const SOUND_SHOOT      	magic/cast.wav

  const MELEE_RANGE		600
  const MELEE_HITCHANCE 	100%
  const MELEE_ATK_DURATION 	1

  setvar SPELL_SKILL_REQUIRED	1
  const SPELL_FIZZLE_TIME	12
  const SPELL_CAST_SUCCESS	75%	//was 50% - just hellafrustrting
  const SPELL_PREPARE_TIME	2
  const SPELL_DAMAGE_TYPE	fire
  const SPELL_ENERGYDRAIN	200
  const SPELL_MPDRAIN		1
  const SPELL_STAT		spellcasting.fire

  const EFFECT_MAXDURATION 	30
  const EFFECT_MINDURATION 	8
  const EFFECT_DURATION_STAT	1
  const EFFECT_DURATION 	20
  const EFFECT_MAX_DMG 		10
  const EFFECT_MIN_DMG 		3
  //const EFFECT_DMG		$get(ent_owner,skill.spellcasting.fire.ratio)

  const EFFECT_SCRIPT		monsters/summon/volcano_troll
  precachefile 			EFFECT_SCRIPT
}

#include items/magic_hand_base

{  spell_spawn

   name 		Trollcano
   desc 		Trollllololol
}

{  spell_casted	//PARAM1: "none"/"npc"/"world"   2: Attack end Position   3: Entity hit (if any)

	local pos PARAM2
	local temp $get_ground_height(pos)
	local x $vec.x(pos)
	local y $vec.y(pos)
	local pos $vec(x,y,temp)
	createnpc EFFECT_SCRIPT pos $get(ent_owner,id)
	deleteent ent_me //prevents volcano spam
}