//Thothie - this thing does WAY too much damage, and is impossible to get at level 15
//- reducing damage and level
//- Seems more appropriate as fire than summon?
//- XP for this goes to null proficiency still :\
{
  const SOUND_SHOOT      	magic/frost_pulse.wav

  const MELEE_RANGE			600
  const MELEE_HITCHANCE 	100%
  const MELEE_ATK_DURATION 	1

  setvar SPELL_SKILL_REQUIRED	18	//will be 18
  const SPELL_FIZZLE_TIME	20
  const SPELL_CAST_SUCCESS	99%
  const SPELL_PREPARE_TIME	1
  const SPELL_DAMAGE_TYPE	cold
  const SPELL_ENERGYDRAIN	1
	const MELEE_ATK_DURATION	2
  const SPELL_MPDRAIN		50 //will be 50
  const SPELL_STAT		none //this spell does no damage, prevents XP expoit
  const EFFECT_SCRIPT		monsters/summon/ice_blast
  precachefile 			EFFECT_SCRIPT
}

#include items/magic_hand_base

{  spell_spawn

   name 		Freezing Sphere
   desc 		Freezing Sphere - a sphere of ice that freezes opponents
}

{  spell_casted	//PARAM1: "none"/"npc"/"world"   2: Attack end Position   3: Entity hit (if any)

	if ( FX_SPAMMERS >= MAX_FX_SPAMMERS ) 
	{
		playermessage $get(ent_owner,id) "Too many active FX: cannot create spell."
		deleteent ent_me
	}
	if FX_SPAMMERS < MAX_FX_SPAMMERS

	local FREEZE_DURATION $get(ent_owner,skill.spellcasting.ice)
	if ( FREEZE_DURATION < 10 ) local FREEZE_DURATION 10
	if ( FREEZE_DURATION > 20 ) local FREEZE_DURATION 20
	//local FINAL_DEST PARAM2

	local OWNER_ORG $get(ent_owner,origin)
	local OWNER_ANG $get(ent_owner,angles)
	local OWNER_PITCH $vec.pitch(OWNER_ANG)
	//if ( OWNER_PITCH < 0 ) add OWNER_PITCH 359
	local OWNER_PITCH $neg(OWNER_PITCH)
	local OWNER_YAW $vec.yaw(OWNER_ANG)
	local OWNER_ROLL $vec.roll(OWNER_ANG)
	local OWNER_DEST PARAM2
	vectoradd OWNER_DEST $relpos($vec(OWNER_PITCH,OWNER_YAW,OWNER_ROLL),$vec(0,20000,0))
	//local LSTORM_MOVETO $get_traceline(OWNER_ORG,OWNER_DEST,worldonly)

	createnpc EFFECT_SCRIPT $relpos(0,32,32) $get(ent_owner,id) FREEZE_DURATION OWNER_DEST spellcasting.ice
	//deleteent ent_me //prevents spam
}