//Thothie changing RANGED_COF so holding button down actually does something
{
	const ANIM_CAST 11
	const SOUND_CHARGE      	magic/fireball_powerup.wav
	const SOUND_SHOOT      	magic/fireball_strike.wav

	const RANGED_FORCE		1000
	const RANGED_COF 		10;1	//uncharged spread; charged spread  (all in degrees)
	const RANGED_ATK_DURATION 	1
	const RANGED_PROJECTILE 	proj_fire_dart
	const RANGED_DMG_DELAY	0.5

	setvar SPELL_SKILL_REQUIRED	0
	const SPELL_FIZZLE_TIME	35
	const SPELL_CAST_SUCCESS	97%
	const SPELL_PREPARE_TIME	4
	const SPELL_DAMAGE_TYPE	fire
	const SPELL_ENERGYDRAIN	5
	const SPELL_MPDRAIN		1
	const SPELL_STAT		spellcasting.fire
}

#include items/magic_hand_base

{ spell_spawn

   name "Fire Dart"
   desc "A weak bolt of fire"
}

{ spell_casted	//PARAM1: "none"/"npc"/"world"   2: Attack end Position   3: Entity hit (if any)

	//playviewanim  ANIM_FIRE
	svplaysound game.sound.item game.sound.maxvol SOUND_SHOOT
}

{ cast_start

	setvard baseitem.canidle 0
	callevent 1.65 start_spell_anim
}

{ [override] cast_toss	//If ranged
	
	callevent	spell_casted
	playowneranim	critical PLAYERANIM_CAST squatwalk1
}

{ start_spell_anim

	callevent 2.5 bitem_set_can_idle
	playviewanim 12
}

{ fake_precache
	svplaysound 0 0 SOUND_CHARGE
	svplaysound 0 0 SOUND_SHOOT
}