//Thothie - Increasing the mana drain on this to stop it being spammed on players
//- Better solution would be to make it so it can't be spawned within x units of a player
//- Or was killed by players by touch
//- Neither of which I can figure how to do :/
{
  const SOUND_SHOOT      	magic/ice_strike.wav

  const MELEE_RANGE		600
  const MELEE_HITCHANCE 	100%
  const MELEE_ATK_DURATION 	1

  setvar SPELL_SKILL_REQUIRED	4
  const SPELL_FIZZLE_TIME	25
  const SPELL_CAST_SUCCESS	80%
  const SPELL_PREPARE_TIME	2
  const SPELL_DAMAGE_TYPE	cold
  const SPELL_ENERGYDRAIN	75
  const SPELL_MPDRAIN		25
  const SPELL_STAT		spellcasting.ice

  //const EFFECT_MAXDURATION 	30
  //const EFFECT_MINDURATION 	2
  //const EFFECT_DURATION_STAT	$get(ent_owner,stat.concentration.ratio)
  //const EFFECT_DURATION 	$get_skill_ratio(EFFECT_DURATION_STAT,EFFECT_MINDURATION,EFFECT_MAXDURATION)
  //const EFFECT_MAX_DMG 	10
  //const EFFECT_MIN_DMG 	0.1
  //const EFFECT_DMG		$get(ent_owner,skill.spellcasting.ice.ratio)

  const EFFECT_SCRIPT		monsters/summon/summon_ice_wall
  precachefile 			EFFECT_SCRIPT
}

#include items/magic_hand_base

{  spell_spawn

   name 		Ice Wall
   desc 		Ice Wall - Impede your opponents progress
}

{  spell_casted	//PARAM1: "none"/"npc"/"world"   2: Attack end Position   3: Entity hit (if any)

	local pos PARAM2
	local temp $get_ground_height(pos)
	local x $vec.x(pos)
	local y $vec.y(pos)
	local pos $vec(x,y,temp)

	add ICE_WALLS 1
	if ( ICE_WALLS >= MAX_ICE_WALLS ) playermessage Too many ice walls present, cannot create more
	if ICE_WALLS < MAX_ICE_WALLS
	local OWNER_SKILL $get(ent_owner,skill.spellcasting.ice)
	createnpc EFFECT_SCRIPT pos $get(ent_owner,angles.yaw) firstcast OWNER_SKILL
}