{
	const SPELL_SKILL_REQUIRED 5
	const BASE_LEVEL_REQ 5
	const MELEE_STAT spellcasting.divination
	
	const MODEL_VIEW viewmodels/v_1hblunts.mdl
	const MODEL_VIEW_IDX 2

	const MODEL_BODY_OFS 71
	const ANIM_PREFIX  maul

	//Used in base_melee
	//------------------
	const MELEE_RANGE  80
	const MELEE_DMG_DELAY  0.8
	const MELEE_ATK_DURATION 1.3
	const MELEE_ENERGY  2
	const MELEE_DMG 102
	const MELEE_DMG_RANGE      5
	const MELEE_ACCURACY  65%
	const MELEE_PARRY_AUGMENT     10%
	const MELEE_DMG_TYPE holy
}

#include items/blunt_base_onehanded

{ game_spawn //Registers the spell faster so it fizzles as soon as its thrown

	local	reg.spell.reqskill	BASE_LEVEL_REQ
	local	reg.spell.fizzletime	9999999
	local	reg.spell.castsuccess	100%
	local	reg.spell.preparetime	3
	registerspell
}

{ weapon_spawn

   name "a|Holy Hammer"
   desc "Can't touch this."
   
   weight  10
   size  10
   value 270
   
   sethudsprite hand hammer
   sethudsprite trade maul
}
