{
	const DRINK_TYPE effect
	const ANIM_IDLE 0
	const ANIM_DRINK 1
	const MODEL_HANDS misc/p_misc.mdl
	const MODEL_WORLD misc/p_misc.mdl
	const MODEL_VIEW viewmodels/v_misc.mdl
	const ITEM_MODEL_VIEW_IDX 2
	const SOUND_DRINK items/drink.wav
	const MODEL_BODY_OFS 39
	const ANIM_PREFIX mana
	setvar DRINK_AMOUNT 1	
	setvar DRINK_GULP_DELAY 3
	setvar DRINK_TIME 3

	const SPEED_RATIO 0.5
}

#include items/base_drink

{ drink_spawn

   name 	a|Swift Blade Potion
   desc 	This potion doubles your base attack speed
   weight 	1
   size 	2
   value	1000
   sethudsprite hand item
   sethudsprite trade gpot
	sethand both //two handed, as off hand weapon not immediately affected
}

{ drink_effect
	effect screenfade ent_owner 2.0 0.5 (255,0,0) 255 fadeout
	effect glow ent_me (255,0,0) 256 1.0 1.0
	callexternal ent_owner ext_set_swift_blade SPEED_RATIO
}