//Thothie Potion of Protection (from Potion of Speed)
{
	const ANIM_IDLE		0
	const ANIM_DRINK		1
	const MODEL_HANDS	     	misc/p_misc.mdl
	const MODEL_WORLD      	misc/p_misc.mdl
	const MODEL_VIEW		viewmodels/v_misc.mdl
	const ITEM_MODEL_VIEW_IDX 2
	const SOUND_DRINK		items/drink.wav

	const MODEL_BODY_OFS		39
	const ANIM_PREFIX		mana

	setvar DRINK_TYPE		givemana
	setvar RESTORE_PERCENT	0.9
	setvar DRINK_EFFECTAMT	300
	setvar DRINK_AMOUNT     	1	
	setvar DRINK_GULP_DELAY	3
	setvar DRINK_TIME		3
}

#include items/base_item

{ drink_spawn

	name 	a|Vial of Demon Blood
	desc 	"Infuses you with the soul of a demon for a time, but at a price."
	weight 	1
	size 	1
	value	1000
	sethudsprite hand item
	sethudsprite trade gpot
}

{ game_spawn

	sethand any
	setanimext	holditem

	callevent drink_spawn
	registerdrink
}


{ game_start_drink

	playviewanim ANIM_DRINK

	callevent drink_start
}

{ game_drink

	applyeffect $get(ent_owner,id) "effects/demon_blood" 60.0 -5
	hud.addstatusicon ent_owner hud/status/status_demon demon_blood 60.0

	//Change sound to protection
	//playsound CHAN_VOICE 10 player/breathe_fast2.wav

	callevent drink_now
}

{ game_drink_done

	playviewanim ANIM_IDLE
}

{ [override] game_deploy

	setviewmodel	MODEL_VIEW
	setmodel	MODEL_HANDS
	local		L_SUBMODEL MODEL_BODY_OFS
	add		L_SUBMODEL game.item.hand_index
	setmodelbody	0 L_SUBMODEL

	callevent drink_deploy
}

{ game_fall

	local		L_SUBMODEL MODEL_BODY_OFS
	add		L_SUBMODEL 2
	setmodelbody	0 L_SUBMODEL

	local		L_ANIM ANIM_PREFIX
	stradd		L_ANIM _floor_idle
	playanim	L_ANIM
}