//Large Sack
//8:13 PM 2/16/2005

{
  //Used by base_pack
  const MODEL_VIEW      	none
  const MODEL_HANDS      	misc/p_misc.mdl
  const MODEL_WORLD      	armor/packs/p_packs.mdl
  const MODEL_WEAR      	armor/packs/p_packs.mdl

  const CONTAINER_TYPE		generic
  const CONTAINER_SPACE	200
  const CONTAINER_MAXITEMS	32
  const CONTAINER_CANCLOSE     0	
  const CONTAINER_LOCK_STRENGTH 0
  const CONTAINER_ITEM_REJECT	"polearms;arrow;scroll2;axes;swords;blunt;bows;shields;smallarms;bolt"

  //const CONTAINER_ITEM_REJECT	"arrow;axes;swords;bows;shields"

  const MODEL_BODY_OFS		6
  const	ANIM_PREFIX		bigsack
}


#include items/pack_base

{
   eventname pack_spawn

   name 	a|Big Sack
   desc 	A big sack, worn over the shoulder
   weight 	1
   size 	25
   value	4
   wearable     1 shoulder
   sethudsprite trade backsheath
}

{
  eventname pack_deploy

  setviewmodel  none
}
{
  eventname pack_wear

  playermessage You sling a big sack over your shoulder. 
}