//Quiver for crossbow bolts
//9:47 PM 2/16/2005

{
  //Used by pack_base
  const ANIM_IDLE		0
  const MODEL_VIEW       	weapons/bows/quiver_rview.mdl
  const MODEL_HANDS      	weapons/bows/quiver_hands.mdl
  const MODEL_WORLD      	weapons/bows/quiver_floor.mdl
  const MODEL_WEAR      	weapons/bows/quiver_spine3.mdl

  const CONTAINER_SPACE	600
  const CONTAINER_MAXITEMS	16
  const CONTAINER_ITEM_ACCEPT	"arrow;bolt;bows;crossbow"
	//I dunno why, but this thing keeps taking things it shouldn't - with or without this line - but not ALWAYS (*shrug*) - Thothie
  	//const CONTAINER_ITEM_REJECT	"scroll;scroll2;axes;swords;bows;shields;smallarms;health;mana;item;armor;gauntlets;key;skin"
	const CONTAINER_ITEM_REJECT "item_tk_"
}


#include items/pack_quiver

{
   eventname pack_spawn

   name 	Quiver of the Archer
   desc 	A large quiver for all sorts of projectiles
   weight 	4
   size 	70
   value	25
   wearable     1 back
   sethudsprite trade quiver
}
