//Greater Ice Bolt by Thothie from Ice Bolt
//- Some variance for the npc ice mages
{
	const MODEL_HANDS      	none
	const MODEL_WORLD      	weapons/projectiles.mdl
	const MODEL_BODY_OFS 2
	const ARROW_BODY_OFS 2
	const SOUND_HITWALL1		magic/frost_pulse.wav
	const SOUND_HITWALL2		magic/frost_pulse.wav
	const SOUND_BURN		magic/ice_powerup.wav
	const ARROW_SOLIDIFY_ON_WALL	0  	//base_arrow: Turns solid when a wall is hit
	const ARROW_BREAK_CHANCE	100%	//base_arrow: Chance of breaking upon hit
	const ITEM_NAME		watermana
	const PROJ_DAMAGE_TYPE	cold
	const PROJ_DAMAGESTAT		spellcasting.ice //this does not determin xp stat
	const PROJ_ANIM_IDLE		idle_iceball
	const PROJ_MOTIONBLUR 0

	const PROJ_DAMAGE		50
	const PROJ_AOE_RANGE		64
	const PROJ_AOE_FALLOFF	0
	const PROJ_STICK_DURATION	0  //Don't stick in enemies
	const PROJ_COLLIDEHITBOX	32 
}

#include items/proj_arrow_base

{ arrow_spawn

	name 		a|Greater Ice Bolt
	desc 		A jagged ball of ice
	weight 		0.1
	size 		1
	value		0
	gravity		0.0
	groupable    	25
}

{ game_dodamage //1: Attack Hit (1/0)  2: Entity Attack hit  3:  Start Position  4:  End Position

	if game.serverside

	if PARAM1

	setvard MY_OWNER $get(ent_expowner,id)
	setvard OWNER_ISPLAYER $get(MY_OWNER,isplayer)
	local ENT_HIT $get(PARAM2,id)

	if ( OWNER_ISPLAYER == 1 )
	{
		setvard EFFECT_DURATION $get(MY_OWNER,skill.spellcasting.ice)
		multiply EFFECT_DURATION 0.5
		setvard DOT_FREEZE $get(MY_OWNER,skill.spellcasting.ice)
		multiply DOT_FREEZE 0.5
		if ( EFFECT_DURATION < 3 ) setvard EFFECT_DURATION 3
		if !game.pvp
		if $get(ENT_HIT,isplayer)
		local EXIT_SUB 1
	}
	if !EXIT_SUB

	if $get(MY_OWNER,relationship,ENT_HIT) equals enemy

	if ( !OWNER_ISPLAYER )
	{
		//set these vars on monster
		setvard EFFECT_DURATION $get(MY_OWNER,scriptvar,PROJSET_DURATION)
		setvard DOT_FREEZE $get(MY_OWNER,scriptvar,PROJSET_DAMAGE)
	}

	applyeffect ENT_HIT effects/dot_cold EFFECT_DURATION MY_OWNER DOT_FREEZE spellcasting.ice
}