//Greater Holy Arrow by Thothie (from Holy Arrow)
//Adds Turn Undead effect +divine light damage

{
	const CLFX_ARROW 1

	const SPRITE_ARROW_TRADE	firearrow	//This does not have its own trade sprite yet
	const MODEL_BODY_OFS		0
	const PROJ_DAMAGE_TYPE	holy
	const PROJ_DAMAGE		400
	const ARROW_STICK_DURATION	5 	//How long to stick in enemies
	const ARROW_SOLIDIFY_ON_WALL	0  	//base_arrow: Turns solid when a wall is hit
	const ARROW_BREAK_CHANCE	50%	//base_arrow: Chance of breaking upon hit
  	const ARROW_EXPIRE_DELAY 	5//300
}

#include items/proj_arrow_base

{  arrow_spawn

	name 		Greater Holy Arrow
	desc 		An arrow imbued with fantastic divine energies
	weight 		0.2
	size 		1
	value		500
	gravity		0.8
	groupable	15
}


{ game_projectile_hitnpc //<target> - game_hitnpc doesn't do what ya think it does //Changed from strike_target, as that only goes off with hitscan arrows/bolts greatguys1@August2018

	dbg strike_target $get(PARAM1,name)

	if !DID_HIT
	setvard DID_HIT 1
	local L_TARG PARAM1

	local MY_OWNER $get(ent_expowner,id)

	local HOLY_DMG $get(ent_expowner,skill.spellcasting.divination)

	add HOLY_DMG 5

	if ( HOLY_DMG <= 5 ) local HOLY_DMG 5

	//multiply HOLY_DMG 2.0

	callexternal L_TARG turn_undead HOLY_DMG MY_OWNER
}