//Frost Arrow by Thothie (From Poison Arrow)

{
	const CLFX_ARROW 1

	const SPRITE_ARROW_TRADE	silverarrow	//This does not have its own trade sprite yet
	const MODEL_BODY_OFS		6
	const PROJ_DAMAGE_TYPE	cold

	const PROJ_DAMAGE		'$rand(60,100)'
	const ARROW_STICK_DURATION	25 	//How long to stick in enemies
	const ARROW_SOLIDIFY_ON_WALL	0  	//base_arrow: Turns solid when a wall is hit
	const ARROW_BREAK_CHANCE	50%	//base_arrow: Chance of breaking upon hit
  	const ARROW_EXPIRE_DELAY 	10//300
}

#include items/proj_arrow_base

{  arrow_spawn

	name 		Frost Arrow
	desc 		These arrows have been enchanted with ice magics.
	weight 		0.1
	size 		1
	value		150
	gravity		0.8
	groupable	15
	useable		1
}

{ game_dodamage

	if PARAM1

	local MY_OWNER $get(ent_expowner,id)

	if ( $get(MY_OWNER,isplayer) )
	{
		local L_DOT $get(MY_OWNER,skill.spellcasting.ice)
		multiply L_DOT 0.5
		if ( L_DOT < 5 ) local L_DOT $rand(5,10)
	}
	else
	{
		local L_DOT $rand(5,10)
	}


	applyeffect PARAM2 effects/effect_frostbite_dmg L_DOT MY_OWNER 5 archery
}