
{
	const HITSCAN_BOLT 1
  	const MODEL_BODY_OFS		0

  	const PROJ_DAMAGE		110
  	const PROJ_STICK_DURATION	25 	//How long to stick in enemies
  	const ARROW_SOLIDIFY_ON_WALL	1  	//base_arrow: Turns solid when a wall is hit
  	const ARROW_BREAK_CHANCE	1%	//base_arrow: Chance of breaking upon hit
}

#include items/proj_arrow_base

{ arrow_spawn

	name 		a|Wooden Bolt
	desc 		A crossbow bolt made for climbing
	weight 		0.2
	size 		1
	value		10
	gravity		0
	groupable	25

	//scan damage
}




