//Wooden Arrow


{
	const CLFX_ARROW 1

	const MODEL_BODY_OFS		0

	const PROJ_DAMAGE		$rand(60,90)
	const ARROW_STICK_DURATION	10 	//How long to stick in enemies
	const ARROW_SOLIDIFY_ON_WALL	1  	//base_arrow: Turns solid when a wall is hit
	const ARROW_BREAK_CHANCE	20%	//base_arrow: Chance of breaking upon hit
}

#include items/proj_arrow_base

{ arrow_spawn

	name 		Wooden Arrow
	desc 		A wooden arrow
	weight 		0.1
	size 		1
	value		1
	gravity		0.7
	groupable    	25
}
