{

	const MODEL_HANDS      		none
	const MODEL_WORLD      		none
	//setvard SOUND_HITWALL1		null.wav
	//setvard SOUND_HITWALL2		null.wav
	const PROJ_DAMAGE_TYPE	none
	const PROJ_ANIM_IDLE		idle

	const PROJ_DAMAGE			0
	const PROJ_AOE_RANGE		0
	const PROJ_AOE_FALLOFF	0
	const PROJ_STICK_DURATION	0
	const PROJ_COLLIDEHITBOX	32

}

#include items/proj_base

{  projectile_spawn

	name 		a|Stupid Hack
	weight 		0
	size 		32
	value		0
	gravity		0.0

	setvard HIT_NPC 0
   
	sethudsprite hand arrows
	sethudsprite trade ITEM_NAME
	sethand any

} //end projectile_spawn

{  game_tossprojectile

	
	setvard START_POS $get(ent_me,origin)
}

{ hit_npc
	setalive 0
	setvard HIT_NPC 1
	deleteent ent_me
}

{  projectile_landed

	if !HIT_NPC
	
	setvard END_POS $get(ent_me,origin)
	setvard DISTANCE $dist(START_POS,END_POS)
	callexternal $get(ent_expowner,id) hitwall_test DISTANCE HIT_NPC
}

{ game_dodamage

	if $get(PARAM2,isalive)
	setvard HIT_NPC 1
}