//Poison spell added by Thothie
//- No one ever makes it to spell casting 8
//- So I figure we need more spells to help get people there
{
  setvar SPELL_SCRIPT      	magic_hand_poison
}

#include items/base_scroll

{
   eventname script_spawn

   name 	a|Tome of Poison
   desc 	The method for instilling insidius poison by magic is described here
   value	125
}

{ game_learnspell_success

  playermessage You learn how to afflict your enemies with debilitating poison
}