{
  const MODEL_VIEW_BOOK		misc/p_misc.mdl
  const MODEL_HANDS      	misc/p_misc.mdl
  const MODEL_WORLD     	misc/p_misc.mdl
  const MODEL_BODY_OFS		6
  const ANIM_PREFIX		evilbook


  setvar SPELL_LEVEL_REQ		0

  setvar SPELL_TO_CREATE		magic_hand_div_glow
  const THIS_ITEM		scroll2_glow
  const SPELL_MAKER_SCRIPT	monsters/companion/spell_maker_divination
  const SPELL_MAKER_HEIGHT	64

  const REPEAT_DELAY		4		//delay before you can use scroll again

  precachefile SPELL_MAKER_SCRIPT
}

#include items/base_item
#include items/base_scroll2

{ game_spawn

   name 	Glow Scroll
   desc 	A magical compedium of glowing light
   value	50

   size 	1
   sethudsprite hand item
   sethudsprite trade letter

   setvar ACTIVE_DELAY REPEAT_DELAY
}