{
	const BASE_SPELL_SCRIPT "magic_hand_poison"
	
	const BASE_REQUIRED_SKILL skill.spellcasting.affliction
	const BASE_REQUIRED_LEVEL 0
	
	const SPELL_MAKER_SCRIPT "monsters/companion/spell_maker_affliction"
	const SPELL_MAKER_HEIGHT 48
}

#include items/base_scroll

{ game_spawn

   name 	"a|Poison Scroll"
   desc 	"A vile compendium of lesser affliction curses"
   
   sethudsprite trade 217
   
   value	225
}