//Poison spell added by Thothie
//- No one ever makes it to spell casting 8
//- So I figure we need more spells to help get people there
{
	const SPELL_SCRIPT "magic_hand_poison"
	const BASE_LEARN_SUCCESS "You learn how to afflict your enemies with debilitating poison."
}

#include items/base_tome

{ game_spawn

	name 	"a|Tome of Poison"
	desc 	"The method for instilling insidius poison by magic is described here."

	value	125
}
