//hijacking this script to make it into a spawner for ice bolt. //greatguys1@OCT2022
{
	const BASE_SPELL_SCRIPT "magic_hand_ice_bolt"
	
	const BASE_REQUIRED_SKILL skill.spellcasting.ice
	const BASE_REQUIRED_LEVEL 18
	
	const SPELL_MAKER_SCRIPT "monsters/companion/spell_maker_ice"
	const SPELL_MAKER_HEIGHT 18
}

#include items/base_scroll

{ game_spawn

   name "an|Icebolt Scroll"
   desc "A magical compedium of strong frost enchantments."
   
   value 1200
}
