{
	const BASE_SPELL_SCRIPT "magic_hand_poison_cloud"
	
	const BASE_REQUIRED_SKILL skill.spellcasting.affliction
	const BASE_REQUIRED_LEVEL 15
	
	const SPELL_MAKER_SCRIPT "monsters/companion/spell_maker_affliction"
	const SPELL_MAKER_HEIGHT 48
}

#include items/base_scroll

{ game_spawn

   name 	"a|Poison Cloud Scroll"
   desc 	"A magical compendium of strong affliction enchantments."
   
   sethudsprite trade 216
   
   value	900
}
