{
	const SKILL_REQ skill.spellcasting.lightning
	const SPELL_LEVEL_REQ 10

	setvar SPELL_TO_CREATE "magic_hand_lightning_storm"
	const THIS_ITEM "scroll2_lightning_storm"
	const SPELL_MAKER_SCRIPT "monsters/companion/spell_maker_lightning"
	const SPELL_MAKER_HEIGHT 48

	precachefile SPELL_MAKER_SCRIPT
}

#include items/base_scroll2

{ game_spawn

	name Lightning Storm Scroll
	desc A magical compedium of extrordinary electrical enchantments
	value 2500
	size 1
}
