{
	const BASE_SPELL_SCRIPT "magic_hand_summon_undead"
	
	const BASE_REQUIRED_SKILL skill.spellcasting
	const BASE_REQUIRED_LEVEL 8
	
	const SPELL_MAKER_SCRIPT "monsters/companion/spell_maker_summoning"
	const SPELL_MAKER_HEIGHT 48
}

#include items/base_scroll

{ game_spawn

   name 	"an|Undead Creation Scroll"
   desc 	"A compendium of necromantic magics."
   
   sethudsprite trade 224
   
   value	750
}
