{
  const MODEL_VIEW_BOOK		misc/p_misc.mdl
  const MODEL_HANDS      	misc/p_misc.mdl
  const MODEL_WORLD     	misc/p_misc.mdl
  const MODEL_BODY_OFS		6
  const ANIM_PREFIX		evilbook


  const SPELL_LEVEL_REQ		4

  setvar SPELL_TO_CREATE		magic_hand_ice_wall
  const THIS_ITEM		scroll2_ice_wall
  const SPELL_MAKER_SCRIPT	monsters/companion/spell_maker_ice
  const SPELL_MAKER_HEIGHT	18

  const REPEAT_DELAY		10		//delay before you can use scroll again

  precachefile SPELL_MAKER_SCRIPT
}

#include items/base_scroll2

{ game_spawn

   name 	Ice Wall Scroll
   desc 	A magical compedium of strong ice enchantments
   value	800

   size 	1
   sethudsprite hand item
   sethudsprite trade letter

   setvar ACTIVE_DELAY REPEAT_DELAY
}