{
	const BASE_SPELL_SCRIPT "magic_hand_lightning_storm"
	
	const BASE_REQUIRED_SKILL skill.spellcasting.lightning
	const BASE_REQUIRED_LEVEL 10
	
	const SPELL_MAKER_SCRIPT "monsters/companion/spell_maker_lightning"
	const SPELL_MAKER_HEIGHT 48
}

#include items/base_scroll

{ game_spawn

	name "Lightning Storm Scroll"
	desc "A magical compendium of extrordinary electrical enchantments."
	
	sethudsprite trade 215
	
	value 1220
}
