{
  const MODEL_VIEW_BOOK		misc/p_misc.mdl
  const MODEL_HANDS      	misc/p_misc.mdl
  const MODEL_WORLD     	misc/p_misc.mdl
  const MODEL_BODY_OFS		6
  const ANIM_PREFIX		evilbook


  const SPELL_LEVEL_REQ		0

  setvar SPELL_TO_CREATE		magic_hand_trollcano
  const THIS_ITEM		scroll2_trollcano
  const SPELL_MAKER_SCRIPT	monsters/companion/spell_maker_fire
  const SPELL_MAKER_HEIGHT	48

  const REPEAT_DELAY		10		//delay before you can use scroll again

  precachefile SPELL_MAKER_SCRIPT
}

#include items/base_scroll2

{ game_spawn

   name 	Trollcano Scroll
   desc 	Be careful what you wish for
   value	0

   size 	1
   sethudsprite hand item
   sethudsprite trade 21

   setvar ACTIVE_DELAY REPEAT_DELAY
}

{ game_deploy
	if !IS_RESERVED
	setvard IS_RESERVED 1
	array.create PICKUP_ALLOW_LIST
	array.add PICKUP_ALLOW_LIST $get(ent_owner,id)
}

{ game_fall
	if !IS_RESERVED
	setvard IS_RESERVED 1
	array.create PICKUP_ALLOW_LIST
	array.add PICKUP_ALLOW_LIST $get(ent_owner,id)
}

{ game_restricted
	local OUT_MSG "This troll scroll is reserved for "
	local ITEM_RESERVER $get_array(PICKUP_ALLOW_LIST,0)
	stradd OUT_MSG $get(ITEM_RESERVER,name)
	infomsg PARAM1 "Item Restricted" OUT_MSG
}