{
	const BASE_SPELL_SCRIPT "magic_hand_ice_wall"
	
	const BASE_REQUIRED_SKILL skill.spellcasting.ice
	const BASE_REQUIRED_LEVEL 4
	
	const SPELL_MAKER_SCRIPT "monsters/companion/spell_maker_ice"
	const SPELL_MAKER_HEIGHT 18
}

#include items/base_scroll

{ game_spawn

   name 	"an|Ice Wall Scroll"
   desc 	"A magical compendium of weak ice enchantments."
   
   sethudsprite trade 213
   
   value	95
}