//Thothie - long awaited "make sheilds useful" patch up

{
	const NOPUSH_CHANCE 50%

	const PARRY_MULTI 1.75
	const SHIELD_BASE_PARRY 20

	const MODEL_VIEW       	viewmodels/v_shields.mdl
	const MODEL_VIEW_IDX	0
	//const MODEL_VIEW armor/shields/ishield_rview.mdl

  const MODEL_BODY_OFS		65 //4
  const MELEE_ENERGY		4
  const MELEE_ACCURACY   	50%
  const BLOCK_CHANCE_UP		100	//%Chance of blocking damage while up
  const DMG_BLOCK_UP		0.35	//%Damage player takes when blocks (0.0=none 1.0=all)
  const BLOCK_CHANCE_DOWN	20	//%Chance of blocking all damage while down
  const SHIELD_MAXHEALTH	1000
  const SHIELD_IMMORTAL		0
  setvard SHIELD_HEALTH		1000
  const SOUND_BLOCK      	body/armour2.wav
  precache SOUND_BLOCK

}

#include items/shields_base

{  shield_spawn

   name 	an|Iron Shield
   desc 	An Iron shield
   weight 	40
   size 	45
   value	600
   quality      150
   sethudsprite hand ironshield
   sethudsprite trade ironshield
}


{ game_wear

  playermessage You sling an iron shield over your shoulder.
}
