//Clunky shield of the beat bag
{
	const NOPUSH_CHANCE 75%

	const PARRY_MULTI 3.0
	const SHIELD_BASE_PARRY 40

	const MODEL_VIEW       	viewmodels/v_shields.mdl
	const MODEL_VIEW_IDX	3
	//const MODEL_VIEW armor/shields/darkshield_rview.mdl

	const MODEL_BODY_OFS		73 //12
	const MELEE_ENERGY		1
	const MELEE_ACCURACY   	150%
	const BLOCK_CHANCE_UP		100	//%Chance of blocking damage while up
	const DMG_BLOCK_UP		0.05 //%Damage player takes when blocks (0.0=none 1.0=all)
	const BLOCK_CHANCE_DOWN	50	//%Chance of blocking all damage while down
	const SHIELD_MAXHEALTH	infinite
	const SHIELD_IMMORTAL		1
	setvard SHIELD_HEALTH		infinite
	const SOUND_BLOCK      	doors/doorstop5.wav
	const EFFECT_RANGE		150
}

{ game_precache
	precache SOUND_BLOCK
}

#include items/shields_base

{  shield_spawn

   name 	an|Urdulian Shield
   desc 	A massive shield forged from the seal of a fallen temple of Urdual
   weight 	120
   size 	45
   value	5000
   quality      2000
   sethudsprite hand 165
   sethudsprite trade 165
}

{ game_wear
	playermessage You heft an Urdulian shield onto your back.
}

{ bweapon_effect_activate //Slow activate

	if game.item.wielded
	if $get(ent_owner,scriptvar,'PLR_IN_WORLD')
	local L_SCRIPTFLAG $get(ent_me,itemname)
	callexternal ent_owner plr_change_speed -1 0.75 L_SCRIPTFLAG
}

{ bweapon_effect_remove //Remove slow effect
	local L_SCRIPTFLAG $get(ent_me,itemname)
	callexternal ent_owner plr_update_speed_effects remove L_SCRIPTFLAG
}
