{
  const MODEL_WORLD      	misc/p_misc.mdl
  const MODEL_HANDS      	misc/p_misc.mdl
  const MODEL_VIEW		none

  const MODEL_BODY_OFS		31
  const ANIM_PREFIX		boar
}

#include items/base_miscitem

{
   eventname miscitem_spawn

   name 	a|Heavy Boar Skin
   desc 	A heavy boar skin
   weight 	4
   size 	3
   value	30
   setworldmodel MODEL_WORLD
   setpmodel	MODEL_HANDS
   setviewmodel MODEL_VIEW
   sethudsprite trade boarskin
}