//Thothie - seems basically same as dagger, not sure why removed
//- Naming convention indicates there should be some difference, so... you can parry with a dirk! ;)
//Dirk

#include items/item_precache
{
  const MODEL_VIEW        viewmodels/v_smallarms.mdl
	const MODEL_VIEW_IDX 0

  	const ANIM_LIFT1 18
  	const ANIM_IDLE1 19
  	const ANIM_IDLE_TOTAL 1
  	const ANIM_WIELD 20
  	const ANIM_UNWIELD 21
  	const ANIM_WIELDEDIDLE1 22
  	const ANIM_ATTACK1 23
  	const ANIM_ATTACK2 24

const MODEL_HANDS weapons/p_weapons2.mdl
const MODEL_WORLD weapons/p_weapons2.mdl

  //Used in base_melee
  //------------------
  const BASE_LEVEL_REQ     9
  const MELEE_RANGE  40
  const MELEE_DMG_DELAY  0.2
  const MELEE_ATK_DURATION 0.9
  const MELEE_ENERGY  1
  const MELEE_DMG  120
  const MELEE_DMG_RANGE      80
  const MELEE_ACCURACY  80%
  const MELEE_ALIGN_BASE 3.6,-6
  const MELEE_ALIGN_TIP  0,0 

  const MELEE_SOUND_DELAY      MELEE_DMG_DELAY
  const MELEE_PARRY_CHANCE      75%

  const PLAYERANIM_AIM  knife
  const PLAYERANIM_SWING swing_knife

const MODEL_BODY_OFS 4
  const ANIM_PREFIX  dagger

  const ANIM_PARRY  6
}

#include items/smallarms_base

{  weapon_spawn

   name  a|Dirk
   desc  A small dirk
   weight  3
   size  3
   value 30
   sethudsprite hand 169
   sethudsprite trade 169
}

{ [override] game_parry

 playsound 1 SOUND_HITMETAL1

 playowneranim break
 playviewanim ANIM_PARRY

 callevent weapon_parry
}
