//Stiletto


#include items/item_precache
{
  //const MODEL_VIEW        weapons/smallarms/dagger_rview.mdl
  const MODEL_VIEW        viewmodels/v_smallarms.mdl
	const MODEL_VIEW_IDX 0

	const ANIM_LIFT1 0
	const ANIM_IDLE1 1
	const ANIM_IDLE_TOTAL 1
	const ANIM_WIELD  2
	const ANIM_UNWIELD      3
	const ANIM_WIELDEDIDLE1  4
	const ANIM_ATTACK1 5
	const ANIM_ATTACK2 6

const MODEL_HANDS weapons/p_weapons2.mdl
const MODEL_WORLD weapons/p_weapons2.mdl

  //Used in base_melee
  //------------------
  const BASE_LEVEL_REQ     3
  const MELEE_RANGE  40
  const MELEE_DMG_DELAY  0.2
  const MELEE_ATK_DURATION 0.9
  const MELEE_ENERGY  1
  const MELEE_DMG  140
  const MELEE_DMG_RANGE      100
  const MELEE_ACCURACY  80%
  const MELEE_ALIGN_BASE 3.6,-6
  const MELEE_ALIGN_TIP  0,0 

  const MELEE_SOUND_DELAY      MELEE_DMG_DELAY
  const MELEE_PARRY_CHANCE      75%

  const PLAYERANIM_AIM  knife
  const PLAYERANIM_SWING swing_knife

  const MODEL_BODY_OFS 4
  const ANIM_PREFIX  dagger

  const ANIM_PARRY  6
}

#include items/smallarms_base

{  weapon_spawn

   name  a|Stiletto
   desc  A pointed stiletto, taking advantage of exposed gaps on armored enemies
   weight  3
   size  3
   value 30
   sethudsprite trade 169
}

{ [override] game_parry

 playsound 1 SOUND_HITMETAL1

 playowneranim break
 playviewanim ANIM_PARRY

 callevent weapon_parry
}
