{ [shared]
	const BWEAPON_NAME "an|Envenomed Crescent Blade"
	const ATK1_DMG_TYPE poison
	const CRE_TYPE poison
	const CRE_EFFECT_SCRIPT effects/effect_poison
	const CRE_EFFECT_DURATION 10.0
	const CRE_EFFECT_NAME DOT_poison
	const CRE_EFFECT_SKILL skill.spellcasting.affliction
	const CRE_EFFECT_RATIO 0.3
	
	const VMODEL_IDX 20
	const PMODEL_IDX_FLOOR 73 //p_model floor offset (-1 from JHLMV index)
	const PMODEL_IDX_HANDS 75 //automagically gets the index for oither hand
}

#include items/smallarms_cre

{ atk1_damaged_other
	if !$get(PARAM1,haseffect,CRE_EFFECT_NAME)

	if ( $get(PARAM1,isplayer) )
	{
		if !GAME_PVP
		local EXIT_SUB 1
	}
	if !EXIT_SUB

	local DOT_AMT $get(ent_owner,CRE_EFFECT_SKILL)
	multiply DOT_AMT CRE_EFFECT_RATIO

	dbg atk1_damaged_other burn $get(PARAM1,name) at DOT_AMT for CRE_EFFECT_DURATION
	
	applyeffect PARAM1 CRE_EFFECT_SCRIPT CRE_EFFECT_DURATION $get(ent_owner,id) DOT_AMT
}
