//Lesser Ice Blade, From Short Sword by Thothie (model pending)

{
	const BASE_LEVEL_REQ 6

  const ANIM_LIFT1         0
  const ANIM_IDLE1         1
  const ANIM_ATTACK1       2
  const ANIM_ATTACK2       3
  const ANIM_ATTACK3       4
  const ANIM_SHEATH       5
 //model pending
  const MODEL_VIEW        viewmodels/v_1hswordssb.mdl
	const MODEL_VIEW_IDX 1 
const MODEL_HANDS weapons/p_weapons1.mdl
const MODEL_WORLD weapons/p_weapons1.mdl
  const SOUND_SWIPE       weapons/swingsmall.wav
  const SOUND_SHOUT  $get(ent_owner,scriptvar,'PLR_SOUND_SHOUT1')

const MODEL_BODY_OFS 48

  //Used in base_melee
  //------------------
  const MELEE_RANGE  60
  const MELEE_DMG_DELAY  0.6
  const MELEE_ATK_DURATION 1.1
  const MELEE_ENERGY  0.3
  const MELEE_DMG  150
  const MELEE_DMG_RANGE      120
  const MELEE_DMG_TYPE  cold
  const MELEE_ACCURACY  75%
  const MELEE_STAT  swordsmanship
  const MELEE_ALIGN_BASE 4,-6 
  const MELEE_ALIGN_TIP  0,6
  const MELEE_VIEWANIM_ATK      ANIM_ATTACK1
  const ANIM_PREFIX shortsword

  const MELEE_SOUND      SOUND_SWIPE
  const MELEE_SOUND_DELAY      MELEE_DMG_DELAY
  const MELEE_PARRY_CHANCE      15%
 const FREEZE_HITS_NEEDED 10 //Freezes opponent every xth hit
  const SOUND_HITWALL1 debris/glass1.wav
  const SOUND_HITWALL2 debris/glass2.wav
}

#include items/swords_base_onehanded
#include [server] items/base_varied_attacks

{ weapon_spawn

   name  a|Lesser Ice Blade
   desc  A shortsword variant of the Ice Blade used by elite Marogar
   weight  30
   size  7
   value 400
   sethudsprite trade 95
 setvard FREEZE_HITS 1 
}

{ game_dodamage //1: Attack Hit (1/0)  2: Entity Attack hit  3:  Start Position  4:  End Position

 if PARAM1

 add FREEZE_HITS 1

 if FREEZE_HITS == 10

 local ENEMY_HIT $get(PARAM2,id)

 local NME_MAXHP $get(PARAM2,hp)
 if ( NME_MAXHP > 500 ) playermessage This enemy is too strong to be affected by your swords magic!
 if NME_MAXHP < 500
 applyeffect ENEMY_HIT effects/dot_cold 5 $get(ent_owner,id) 10 swordsmanship
 playermessage "The Ice Blade's magic has frozen your enemy!"
 playsound 0 10 debris/beamstart14.wav
 setvard FREEZE_HITS 1
}

{ [override] melee_start

//  local SWING $rand(1,ATTACK_ANIMS)
//  local SWING_ANIM ANIM_ATTACK1
//  if( SWING == 2 ) setvard SWING_ANIM ANIM_ATTACK2
//  else if( SWING == 3 ) setvard SWING_ANIM ANIM_ATTACK3
//  else if( SWING == 4 ) setvard SWING_ANIM ANIM_ATTACK4
//  else if( SWING == 5 ) setvard SWING_ANIM ANIM_ATTACK5

	playsound 1 10 SOUND_SWIPE


	if game.serverside
	playowneranim once sword_swing //global.anim.combatwalk 3
	callevent check_attack_anim
	setvard SWING_ANIM CUR_ATTACK_ANIM
	splayviewanim ent_me SWING_ANIM
}