//Shortsword

{
  const ANIM_LIFT1        	0
  const ANIM_IDLE1        	1
  const ANIM_ATTACK1      	2
  const ANIM_ATTACK2      	3
  const ANIM_ATTACK3      	4
  const ANIM_SHEATH      	5
  const MODEL_VIEW       	weapons/swords/smallswords_skins_rview.mdl
  const MODEL_HANDS      	weapons/swords/p_swords.mdl
  const MODEL_WORLD      	weapons/swords/p_swords.mdl
  const MODEL_BLOCK      	armor/shields/p_shields.mdl
  const SOUND_SWIPE      	weapons/swingsmall.wav
	const SOUND_SHOUT $get(ent_owner,scriptvar,'PLR_SOUND_SHOUT1')

  const MODEL_BODY_OFS		28
  const ANIM_PREFIX		shortsword

  //Used in base_melee
  //------------------
  const MELEE_RANGE		60
  const MELEE_DMG_DELAY		0.6
  const MELEE_ATK_DURATION	1.1
  const MELEE_ENERGY		0.3
  const MELEE_DMG		140
  const MELEE_DMG_RANGE     	110
  const MELEE_DMG_TYPE		slash
  const MELEE_ACCURACY		70%
  const MELEE_STAT		swordsmanship
  const MELEE_ALIGN_BASE	4,-6 
  const MELEE_ALIGN_TIP		0,6
  const MELEE_VIEWANIM_ATK     	ANIM_ATTACK1

  const MELEE_SOUND     	SOUND_SWIPE
  const MELEE_SOUND_DELAY     	MELEE_DMG_DELAY
  const MELEE_PARRY_CHANCE     	5%
}

#include items/swords_base_onehanded

{
   eventname weapon_spawn

   name 	a|Shortsword Skintest
   desc 	A short one-handed Sword
   weight 	30
   size 	7
   value	15
   sethudsprite trade shortsword
	setmodelskin 2
}