//Skullblade

{
  const BASE_LEVEL_REQ     6
  const ANIM_LIFT1         0
  const ANIM_IDLE1         1
  const ANIM_IDLE_TOTAL         1
  const ANIM_IDLE_DELAY_LOW 1
  const ANIM_IDLE_DELAY_HIGH    3
  const ANIM_ATTACK1       2
  const ANIM_ATTACK2       3
  const ANIM_ATTACK3       4
  const ANIM_ATTACK4       5
  const ANIM_ATTACK5       6
  const ANIM_SHEATH       7
  const MODEL_VIEW        viewmodels/v_1hswordssb.mdl
	const MODEL_VIEW_IDX 0
const MODEL_HANDS weapons/p_weapons1.mdl
const MODEL_WORLD weapons/p_weapons1.mdl
  const SOUND_SWIPE       weapons/swingsmall.wav
	const SOUND_SHOUT $get(ent_owner,scriptvar,'PLR_SOUND_SHOUT1')

const MODEL_BODY_OFS 32
  const ANIM_PREFIX  skullblade

  //Used in base_melee
  //------------------
  const MELEE_RANGE  64
  const MELEE_DMG_DELAY  0.6
  const MELEE_ATK_DURATION 1.5
  const MELEE_ENERGY  2
  const MELEE_DMG  200
  const MELEE_DMG_RANGE      10
  const MELEE_DMG_TYPE  slash
  const MELEE_ACCURACY  60%
  const MELEE_STAT  swordsmanship
  const MELEE_ALIGN_BASE 4,-6 
  const MELEE_ALIGN_TIP  0,6
  const MELEE_VIEWANIM_ATK      ANIM_ATTACK1

  const MELEE_SOUND      SOUND_SWIPE
  const MELEE_SOUND_DELAY      MELEE_DMG_DELAY
  const MELEE_PARRY_CHANCE      5%
}

#include items/swords_base_onehanded
#include [server] items/base_varied_attacks

{ weapon_spawn

   name  a|Skullblade
   desc  This sword relies more on it's weight than it's sharp edge
   weight  80
   size  7
   value 200
   sethudsprite trade skullblade
}

{ [override] melee_start

//  local SWING $rand(1,ATTACK_ANIMS)
//  local SWING_ANIM ANIM_ATTACK1
//  if( SWING == 2 ) setvard SWING_ANIM ANIM_ATTACK2
//  else if( SWING == 3 ) setvard SWING_ANIM ANIM_ATTACK3
//  else if( SWING == 4 ) setvard SWING_ANIM ANIM_ATTACK4
//  else if( SWING == 5 ) setvard SWING_ANIM ANIM_ATTACK5

	playsound 1 10 SOUND_SWIPE


	if game.serverside
	playowneranim once sword_swing //global.anim.combatwalk 3
	callevent check_attack_anim
	setvard SWING_ANIM CUR_ATTACK_ANIM
	splayviewanim ent_me SWING_ANIM
}