#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(10,23)
	addstoreitem	STORENAME	health_mpotion	 	3	0
	addstoreitem	STORENAME	proj_arrow_broadhead	60	0	0	30

	local THIS_MAP $lcase(game.map.name)
	if ( THIS_MAP equals edanasewers )
	{
		addstoreitem STORENAME item_riddleanswers2	1 0
	}
	if ( THIS_MAP equals heras )
	{
		addstoreitem STORENAME item_riddleanswers 1 0
	}	

	if ( $rand(1,2) == 1 ) addstoreitem STORENAME proj_bolt_iron 25 0 0 25

	callevent addrandomitems
}

{ addrandomitems

   if ( $rand(1,6) == 1 ) addstoreitem  STORENAME	bows_longbow		1	0
   if ( $rand(1,8) == 1 ) addstoreitem  STORENAME	armor_helm_knight	1	0
   if ( $rand(1,5) == 1 ) addstoreitem  STORENAME	proj_arrow_jagged	60	0	0	30
   if ( $rand(1,19) == 1 ) addstoreitem  STORENAME	bows_longbow		1	0
}