//Thothie mscave almost entirely underground - no rail plzktnx
//Setup the map's weather
//
{ [shared]

	const MAP_NAME 		'lowlands'
	const MAP_WEATHER 	"clear;clear;clear;clear;clear;clear"
	const MAP_ALLOWNIGHT 	0

	setvarg G_MAP_NAME "Curse of the Bear Gods: Lowlands by Crow & Dridje"
	setvarg G_MAP_DESC "Foglund has been cursed by the Bear Gods. Can you save him?"
	setvarg G_MAP_DIFF "Levels 15-20 / 200-300hp"
	setvarg G_WARN_HP 200
}

#include worlditems/map_startup
