//Thothie mscave almost entirely underground - no rail plzktnx
//Setup the map's weather
//
{ [shared]

	const MAP_NAME 		'gertenheld_cave'
	const MAP_WEATHER 	clear;clear;clear;clear;clear;clear
	const MAP_ALLOWNIGHT 0

	setvarg G_MAP_NAME "The Vile Blood Goblin Caves"
	setvarg G_MAP_DESC "These caves are infested with the most tenacious goblins in all of daragoth"
	setvarg G_MAP_DIFF "Levels 35-40 / 500-800hp"
	setvarg G_WARN_HP 500
}

#include worlditems/map_startup
