#scope client

{
	const SPR_SPRITE "char_breath.spr"
	const SPR_DEATH_DELAY 0.5
	const SPR_RENDER_PROPS FX_RENDER_PROPS
	const SPR_SCALE 3
}

{ client_activate //<position> <"green"|"red">

	local L_POS PARAM1
	local L_BLOOD_COL PARAM2
	
	if ( L_BLOOD_COL equals 'green' )
	{
		setvard FX_RENDER_PROPS "0;1;255;add;(225,225,0);58;30"
	}
	else
	{
		setvard FX_RENDER_PROPS "0;1;255;add;(200,0,0);58;30"
	}
	
	cleffect tempent sprite SPR_SPRITE L_POS setup_sprite
	removescript
}

//explode sprite
{ setup_sprite

	//render props format: fadeout:0|1;scale;renderamt;rendermode;rendercolor;framerate;frames
	//setvard SPR_RENDER_PROPS "0;1;255;add;(225,225,0);60;30"

	cleffect tempent set_current_prop death_delay SPR_DEATH_DELAY
	if ( $get_token(SPR_RENDER_PROPS,0) == 1 ) cleffect tempent set_current_prop fadeout lifetime
	cleffect tempent set_current_prop scale SPR_SCALE
	cleffect tempent set_current_prop renderamt $get_token(SPR_RENDER_PROPS,2)
	cleffect tempent set_current_prop rendermode $get_token(SPR_RENDER_PROPS,3)
	cleffect tempent set_current_prop rendercolor $get_token(SPR_RENDER_PROPS,4)
	cleffect tempent set_current_prop framerate $get_token(SPR_RENDER_PROPS,5)
	cleffect tempent set_current_prop frames $get_token(SPR_RENDER_PROPS,6)
	cleffect tempent set_current_prop gravity 0
	cleffect tempent set_current_prop collide none
}