//Cheater freeze - designed to suspend cheaters from game (blinds and paralyzes), by Thothie
//- PARAM1 = duration (-1 = forevah)

{ [server]
	const EFFECT_ID			effect_stun
	const EFFECT_NAME		"Cheater"
	const EFFECT_ACTIONTYPE		nostack
	const EFFECT_SCRIPT		$currentscript

	setvard game.effect.id		EFFECT_ID
	setvard game.effect.displayname	EFFECT_NAME
	setvard game.effect.type	EFFECT_ACTIONTYPE

}

#include effects/effect_base	allowduplicate

{ [server] game_activate

	setvard game.effect.movespeed 1%
	setvard game.effect.canjump 0
	setvard game.effect.anim.framerate 0.01
	setvard game.effect.canattack 0
	setvard local.effect.duration PARAM1

	callevent local.effect.duration effect_die
}

{ repeatdelay 5.0

	effect screenfade ent_me 0.1 local.effect.duration (10,10,10) 255 noblend
}