{ [server]
	const EFFECT_ID			"effect_nomove"
	const EFFECT_FLAGS		nostack
}

#include effects/base_effect	allowduplicate

{ [server] game_activate

	setvard TARGET_VICT PARAM1
	callexternal TARGET_VICT ext_reset_nomove 0
	setvard game.effect.movespeed 0.0001%
	setvard game.effect.canmove 0
	setvard game.effect.canjump 0
	//setvard game.effect.canattack 0
	setvard IS_ACTIVE 1
	callevent scan_for_remove
}

{ scan_for_remove
	if IS_ACTIVE
	callevent 0.1 scan_for_remove
	if $get(TARGET_VICT,scriptvar,'PLR_EFFECT_REMOVE_NOMOVE')
	setvard IS_ACTIVE 0
	callevent effect_die
}