//Freeze thar blood
//Any npc
//PARAM1 == Duration in seconds
//PARAM2 == Percent to be healed over duration (0-100%)

//
// TODO: Get NPC's height/width and use this to define the area in which the freeze spurt forth
//


{  [shared]

	const OFS_POS			16
	const OFS_NEG			-16
	
	const OFSZ_NEG			0

	const SPRITE_1			xsmoke3.spr
	precache bluejet1.spr
}

{ [server]

	const EFFECT_ID			effect_freeze
	const EFFECT_NAME		"Freeze"
	const EFFECT_ACTIONTYPE		normal
	const EFFECT_SCRIPT		$currentscript

	setvard game.effect.id		EFFECT_ID
	setvard game.effect.displayname	EFFECT_NAME
	setvard game.effect.type	EFFECT_ACTIONTYPE
}

#include effects/effect_base

{ [server] game_activate

	//=== Check Immunities
	callevent resist_check cold $get(PARAM2,id)
	if RESISTED_EFFECT < 2
	//=== End Check Immunities
	
	setvard local.effect.duration 		PARAM1
	clientevent new all $currentscript local.effect.duration $get(ent_me,index) $get(ent_me,height)
	setvard effect.clientscript game.script.last_sent_id
	callevent local.effect.duration effect_die
}

{ 	[server] effect_die

}

// ===========
// Client Side
// ===========

{ [client] client_activate

	setvard sfx.npcid PARAM2
	setvard OFSZ_POS PARAM3
	callevent PARAM1 effect_die
}

{ [client]
	repeatdelay $randf(0.2,0.8)

	callevent createsprite
}

{ [client]
	repeatdelay $randf(0.2,0.8)

	callevent createsprite
}

{ [client] createsprite

	local l.pos $getcl(sfx.npcid,origin)
	vectoradd l.pos $vec($randf(OFS_NEG,OFS_POS),$randf(OFS_NEG,OFS_POS),$randf(OFSZ_POS,OFSZ_NEG))
	cleffect tempent sprite SPRITE_1 l.pos setup_sprite1_flame
}

{  [client] setup_sprite1_flame

	cleffect tempent set_current_prop death_delay 	$randf(0.4,0.6)
	cleffect tempent set_current_prop framerate	25
	cleffect tempent set_current_prop rendermode add
	cleffect tempent set_current_prop renderamt 255
	cleffect tempent set_current_prop rendercolor (64,64,255)
	cleffect tempent set_current_prop velocity	$vec($randf(-4,4),$randf(-4,4),0)
	cleffect tempent set_current_prop frames	20
	cleffect tempent set_current_prop scale 	0.5
	cleffect tempent set_current_prop gravity 	-0.5
	cleffect tempent set_current_prop collide 	none
}