//Push
//Any npc
//Param1 - Duration //means nothing
//Param2 - Push velocity
//Param3 - 1 == Do screenshake

#scope server

{
	const EFFECT_ID "effect_push"
	const EFFECT_FLAGS nostack
	const EFFECT_SCRIPT $currentscript //Must be copied, as is, at the top script!
}

#include effects/base_effect	allowduplicate

{ game_activate

	if !$get(ent_me,nopush)
	if !$get(ent_me,scriptvar,'IMMUNE_PUSH')

	setvard local.effect.duration 	PARAM1
	setvard local.effect.force 	PARAM2
	setvard local.effect.scrnshake 	PARAM3

	addvelocity ent_me local.effect.force
   	if ( local.effect.scrnshake ) effect screenshake $relpos(0,0,0) 64 15 1 1

	removescript
}
