//Potion of Stability effect - immune stun/throw
//PARAM1 == Duration
//script name error made permanent due to leak :)

{ 	[server]
	const EFFECT_ID			effect_leadfoot
	const EFFECT_NAME		"stability"
	const EFFECT_ACTIONTYPE		nostack
	const EFFECT_SCRIPT		$currentscript

	setvard game.effect.id		EFFECT_ID
	setvard game.effect.displayname	EFFECT_NAME
	setvard game.effect.type	EFFECT_ACTIONTYPE
}

#include effects/effect_base

{ 	[server] game_activate

	local EFFECT_DURATION PARAM1
	callexternal $get(ent_me,id) ext_potion_stability
	gplayermessage ent_me You can no longer be moved against your will.
	callevent EFFECT_DURATION effect_die
}

{ [server] effect_die
	dplayermessage ent_me The stability effect fades.
	callexternal $get(ent_me,id) ext_potion_stability end
}

{ [server]
repeatdelay 3.0

	//loop this in case helm screws it up
	if ( $get(ent_me,scriptvar,IMMUNE_STUN) isnot 100 ) callexternal $get(ent_me,id) ext_potion_stability
}
