//Thothie - Can't believe we don't have this already

//Param1 - Duration
//Param2 - New movespeed%
//Param3 - Attacker Who Afflicted (optional)

{ [server]
	const EFFECT_ID			slow
	const EFFECT_NAME		"slow"
	const EFFECT_ACTIONTYPE		normal
	const EFFECT_SCRIPT		$currentscript

	setvard game.effect.id		EFFECT_ID
	setvard game.effect.displayname	EFFECT_NAME
	setvard game.effect.type	EFFECT_ACTIONTYPE
}

#include effects/effect_base	allowduplicate

{ [server] game_activate

	setvard local.effect.duration 	PARAM1

	setvard game.effect.movespeed PARAM2
	setvard game.effect.canjump 0
	setvard game.effect.anim.framerate 0.4

	playermessage $get(ent_me,id) You are being slowed.

	callexternal $get(ent_me,id) ext_set_slowed 1
	callevent local.effect.duration effect_die
}

{ effect_die
	callexternal $get(ent_me,id) ext_set_slowed 0
}

{ game_death
	//deleteent script.stunring	//Delete the ring from here, because skellys stay 'alive' after death
	setvard game.effect.movespeed 100%
	setvard game.effect.canjump 1
	setvard game.effect.anim.framerate 1.0
	callevent effect_die
}