//Acid - By Thothie
allowduplicate
#scope server

{
	const DOT_NAME $rand(0,999)
	
	const DOT_TYPE acid
	
	const DOT_RESISTED $get(ent_me,name) " resists the acid burn!"
	const DOT_AFFLICTED "You have been acid burned!"
	const DOT_END "The acid burns out."
}

#include effects/base_dot	allowduplicate

{ [override] dot_start //Overridden since this increases the dot duration.

	local DUR_RATIO $get(DOT_AFFLICTER,scriptvar,'PLR_CORRODE_DURATION')
	if ( DUR_RATIO != 0 )
	{
		multiply DOT_DURATION DUR_RATIO
	}
	
	if ( !$get(ent_me,scriptvar,IS_LURE) ) effect glow ent_me (75,215,0) 72 DOT_DURATION DOT_DURATION
	
	if ( $get(ent_me,isplayer) )
	{
		clientevent new ent_me $currentscript DOT_DURATION
		svplaysound game.sound.body game.sound.maxvol $get(ent_me,scriptvar,'PLR_SOUND_STOMACHHIT1')
	}
	
	callevent DOT_FREQ dot_effect
	callevent DOT_DURATION effect_die
}

{ game_damaged //PARAM1=attacker PARAM2=dmg PARAM3=dmg_type PARAM4=accuracy_roll PARAM5=skill PARAM6=Inflicter

	//take 150% damage while under this effect, if not resisted
	if PARAM2
	return 1.5
}

// ===========
// Client Side
// ===========

{ [client]
	const POISON_SCREEN_DELAY		0.2
	const POISON_SCREEN_ALPHA		30
}

{ [client] client_activate

	local L_DURATION PARAM1
	callevent L_DURATION effect_die
}

{ [client]
	repeatdelay POISON_SCREEN_DELAY

	setvard game.cleffect.screenfade.newfade 1
	setvard game.cleffect.screenfade.alphalimit POISON_SCREEN_ALPHA	//Only use this fade if current fade is under this limit
	setvard game.cleffect.screenfade.color (75,215,0)
	setvard game.cleffect.screenfade.alpha POISON_SCREEN_ALPHA
	setvard game.cleffect.screenfade.duration POISON_SCREEN_DELAY
	setvard game.cleffect.screenfade.blendduration POISON_SCREEN_DELAY
	setvard game.cleffect.screenfade.type fadein
}
