//Thothie - generic damage
//- used to increase the damage of player weapons via spells, potions, etc.
//- Param1 - damage
//- Param2 - damage source
//- Param3 - make noise if set to 1
//- Param4 - type (generic if unset)
//- PARAM5 - xpskill

{ 	[server]
	const EFFECT_ID			damage_effect
	const EFFECT_NAME		"damage"
	const EFFECT_ACTIONTYPE		nostack
	const EFFECT_SCRIPT		$currentscript

	setvard game.effect.id		EFFECT_ID
	setvard game.effect.displayname	EFFECT_NAME
	setvard game.effect.type	EFFECT_ACTIONTYPE
}

#include effects/effect_base	allowduplicate

{ 	[server] game_activate

	setvard local.effect.damage 	PARAM1
	setvard local.effect.dmgsource 	PARAM2
	setvard LIGHTNING_NOISE PARAM3
	setvard DAMAGE_TYPE PARAM4
	if ( DAMAGE_TYPE equals 'PARAM4' ) setvard DAMAGE_TYPE generic

	if ( !$get(ent_me,isalive) ) 
	{
		local EXIT_SUB 1
	}
	if !EXIT_SUB
	callevent add_damage
	if ( PARAM5 isnot 'PARAM5' ) setvard ACTIVE_SKILL PARAM5
}

{ add_damage

	if !DID_DAMAGE

	setvard ACTIVE_SKILL $get(local.effect.dmgsource,scriptvar,PL_ACTIVE_SKILL)
	if ( ACTIVE_SKILL equals 'PL_ACTIVE_SKILL' ) setvard ACTIVE_SKILL none

	local LAST_DMG $get(ent_me,scriptvar,EXT_LAST_EFFECT_DMG)
	add 0.1
	local TIME_DIFF game.time

	if ( TIME_DIFF > LAST_DMG )
	{
		dbg temp sending DAMAGE_TYPE
		//Dmg PARAM1 Src PARAM2 Durat PARAM3 Type PARAM4
		xdodamage $get(ent_me,id) direct local.effect.damage 100% local.effect.dmgsource local.effect.dmgsource ACTIVE_SKILL DAMAGE_TYPE
		setvard DID_DAMAGE 1
		callevent 0.1 effect_die
		if LIGHTNING_NOISE == 1
		playsound 0 10 weather/Storm_exclamation.wav
	}
	else
	{
		if ( !DID_DAMAGE ) callevent 0.1 add_damage
	}

	if DID_DAMAGE
	callevent effect_die
}