//. applyeffect effects/hold_person 5 

{
	setvard ROCK_CLIMB_STEP 1.0
}

#scope client
{ client_activate //<target> <duration> <width> <height>

	setvard COIL_POS $getcl(PARAM1,origin)
	if ( $getcl(PARAM1,isplayer) )
	{
		setvard IS_PLAYER 1
		vectoradd COIL_POS z -32
	}
	setvard COIL_DURATION PARAM2
	setvard ROT_COUNT 0

	setvard COIL_WIDTH $math(multiply,PARAM3,0.75)
	setvard COIL_WIDTH_MIN $math(multiply,PARAM3,0.4) //prob 0.65
	setvard COIL_WIDTH_MAX COIL_WIDTH
	setvard COIL_HEIGHT PARAM4
	setvard COIL_Z_START $vec.z(COIL_POS)
	setvard COIL_Z_MAX COIL_Z_START
	add COIL_Z_MAX COIL_HEIGHT
	dbg *** $currentscript client_activate COIL_POS w COIL_WIDTH h COIL_HEIGHT zm COIL_Z_MAX

	if ( COIL_HEIGHT > 96 )
	{
		if !IS_PLAYER
		if ( COIL_HEIGHT > 200 ) setvard COIL_HEIGHT 200 //don't go bigger than this (too many rocks)
		local L_MAX_HEIGHT_RATIO $math(divide,COIL_HEIGHT,200)
		add ROCK_CLIMB_STEP $ratio(L_MAX_HEIGHT_RATIO,0.2,2.0)
	}

	setvard COIL_START_TIME game.time

	setvard FX_ACTIVE 1			
	setvard ROCK_COUNT 0
	calleventloop 100 draw_coil_loop
	callevent COIL_DURATION end_fx
}

{ draw_coil_loop
	//dbg **** Draw Coil ROT_COUNT COIL_HEIGHT

	//cleffect beam_points <startpos> <endpos> <spritename> <life> <width> <amplitude> <brightness> <speed> <framerate> <color>
	//if FX_ACTIVE
	local L_COIL_CUR_Z $vec.z(COIL_POS)
	if L_COIL_CUR_Z < COIL_Z_MAX
	add ROCK_COUNT 1
	//callevent 0.01 draw_coil_loop

	local L_COMP_RATIO_MAX $math(subtract,COIL_Z_MAX,COIL_Z_START)
	local L_COMP_RATIO_CUR $math(subtract,COIL_Z_MAX,L_COIL_CUR_Z)
	local L_COMP_RATIO $math(divide,L_COMP_RATIO_CUR,L_COMP_RATIO_MAX)
	setvard COIL_WIDTH $ratio(L_COMP_RATIO,COIL_WIDTH_MIN,COIL_WIDTH_MAX)

	local BEAM_START COIL_POS
	vectoradd BEAM_START $relpos($vec(0,ROT_COUNT,0),$vec(0,COIL_WIDTH,0))
	//add COIL_HEIGHT 1
	vectoradd COIL_POS z ROCK_CLIMB_STEP
	add ROT_COUNT 20
	if ( ROT_COUNT > 359 ) subtract ROT_COUNT 359
	local BEAM_END COIL_POS
	vectoradd BEAM_END $relpos($vec(0,ROT_COUNT,0),$vec(0,COIL_WIDTH,0))
	cleffect beam_points BEAM_START BEAM_END lgtning.spr COIL_DURATION 2 0.1 0.9 0.1 30 (255,255,255) //(1,0.5,2)
	//add ROCK_IDX 1
	//cleffect tempent model rockgibs.mdl BEAM_START setup_rock update_rock
}

{ end_fx
	setvard FX_ACTIVE 0
	callevent 5.0 remove_fx
}

{ remove_fx
	removescript
}

{ update_rock
	if game.time > game.tempent.fuser1
	
	if ( game.time > NEXT_SOUND )
	{
		if game.tempent.iuser1 == 0
		cleffect tempent set_current_prop iuser1 1
		setvard NEXT_SOUND game.time
		add NEXT_SOUND 0.25
		sound.play3d debris/concrete3.wav 10 game.tempent.origin 0.8 0 $rand(30,80)
		//dbg update_rock fall_start
	}

	cleffect tempent set_current_prop collide world;die

	local CUR_VEL game.tempent.velocity
	vectoradd CUR_VEL z -50
	cleffect tempent set_current_prop velocity CUR_VEL
}

//. applyeffect effects/hold_person_stone 10.0 GM 1 none 99999
////. applyeffect effects/hold_person 5 
//
//#scope client
//{ [client] client_activate //<target> <duration>
//	dbg **** client_activate PARAM1 PARAM2
//	setvard COIL_POS $getcl(PARAM1,origin)
//	if ( $get(PARAM1,isplayer) ) vectoradd COIL_POS z -32
//	setvard COIL_DURATION PARAM2
//	setvard ROT_COUNT 0
//	//vectoradd COIL_POS z -16
//	//setvard COIL_HEIGHT $vec.z(COIL_POS)
//	cleffect light new COIL_POS 64 (255,255,255) COIL_DURATION
//	calleventloop 64 draw_coil
//	callevent COIL_DURATION remove_me
//}
//
//{ [client] draw_coil
//	//dbg **** Draw Coil ROT_COUNT COIL_HEIGHT
//
//	//cleffect beam_points <startpos> <endpos> <spritename> <life> <width> <amplitude> <brightness> <speed> <framerate> <color>
//	local BEAM_START COIL_POS
//	vectoradd BEAM_START $relpos($vec(0,ROT_COUNT,0),$vec(0,32,0))
//	//add COIL_HEIGHT 1
//	vectoradd COIL_POS z 1
//	add ROT_COUNT 20
//	if ( ROT_COUNT > 359 ) subtract ROT_COUNT 359
//	local BEAM_END COIL_POS
//	vectoradd BEAM_END $relpos($vec(0,ROT_COUNT,0),$vec(0,32,0))
//	cleffect beam_points BEAM_START BEAM_END lgtning.spr COIL_DURATION 2 0.1 0.9 0.1 30 (255,255,255) //(1,0.5,2)
//}
//
//{ [client] remove_me
//	removescript
//}