//chew chew for scarabs (dmg increases with more scarabs)
{
	const EFFECT_ID			DOT_scarab
	const EFFECT_NAME		"Scarabchew"
	const EFFECT_ACTIONTYPE		nostack
	const EFFECT_SCRIPT		$currentscript
}

{ game_precache

	local reg.effect.name	EFFECT_ID
	local reg.effect.flags	EFFECT_ACTIONTYPE
	local reg.effect.script	EFFECT_SCRIPT

	setvard game.effect.removeondeath 1

	setvard game.effect.id		EFFECT_ID
	setvard game.effect.displayname	EFFECT_NAME
	setvard game.effect.flags	EFFECT_ACTIONTYPE

	registereffect
}

{ [server] game_activate //<duration> <attacker> <DOT*latchers>

	//dbg effect:game_activate EFFECT_ID dot_settings : DOT_EFFECT DOT_TYPE DOT_DMG DOT_FREQ DOT_ATTACKER ACTIVE_SKILL

	if ( !$get(ent_me,isalive) ) removescript //trying to affect a map brush, most likely
	if $get(ent_me,isalive)

	setvard EFFECT_ACTIVE 1
	setvard EFFECT_DURATION PARAM1
	setvard EFFECT_ATTACKER PARAM2
	setvard EFFECT_BASE_DOT PARAM3

	dbg game_activate EFFECT_DURATION $get(EFFECT_ATTACKER,name) EFFECT_BASE_DOT

	callevent effect_loop
	callevent EFFECT_DURATION effect_die
}

{ effect_die
	setvard EFFECT_ACTIVE 0
	removescript
}

{ effect_loop
	if EFFECT_ACTIVE
	callevent 0.5 effect_loop
	dbg scarab_dmg_loop
	local DMG_MULTI $get(ent_me,scriptvar,'SCARABS_ATTACHED')
	local L_DMG EFFECT_BASE_DOT
	multiply L_DMG DMG_MULTI
	//dodamage ent_me direct 100% EFFECT_ATTACKER magic
	xdodamage $get(ent_me,id) direct L_DMG 100% EFFECT_ATTACKER EFFECT_ATTACKER none magic
}