//crecent radial burst outwards
//<origin> <yaw> <cone_width[degrees]>
#scope client
{
	//so we can adjust sprite by include
	const SPRITE_NAME fire1_fixed.spr
	const SPRITE_COLOR (255,128,64)
	const SPRITE_RENDERAMT 200
	const SPRITE_RENDERMODE add
	const SPRITE_FRAMERATE 30
	const SPRITE_NFRAMES 23	
	const SPRITE_SCALE 1.75
	const SPRITE_SPEED 400

	const SOUND_BURST ambience/steamburst1.wav
	precache SOUND_BURST
}

#include effects/sfx_ice_wave2