{ client_activate //<v_ofs|remove> [drift]

	dbg *** sfx_viewheight client_activate PARAM1 PARAM2 PARAM3

	if ( PARAM1 isnot remove )
	{
		setvard FX_SPEED PARAM2
		if ( FX_SPEED != 0 )
		{
			setvard FX_DEST_V PARAM1
			setvard FX_DRIFTING 1
			callevent drift_to_new_view 
		}
		else
		{
			local L_PARAM1 PARAM1
			callevent set_view L_PARAM1
			setvard FX_CUR_V PARAM1
		}
	}
	else
	{
		removescript
	}
}

{ set_view
	setvard game.cleffect.view_ofs.z PARAM1
}

{ update_view //<dest_v> <speed>
	dbg *** $currentscript update_view PARAM1 PARAM2 PARAM3
	setvard FX_SPEED PARAM2
	if ( FX_SPEED != 0 )
	{
		setvard FX_DEST_V PARAM1
		if !FX_DRIFTING
		setvard FX_DRIFTING 1
		callevent drift_to_new_view 
	}
	else
	{
		setvard FX_CUR_V PARAM1
		callevent set_view FX_CUR_V
	}
}

{ drift_to_new_view
	if FX_DRIFTING

	add FX_CUR_V FX_SPEED

	if ( FX_SPEED < 0 )
	{
		if FX_CUR_V < FX_DEST_V
		callevent set_view FX_CUR_V
		setvard FX_DRIFTING 0
	}
	else
	{
		if FX_CUR_V > FX_DEST_V
		callevent set_view FX_CUR_V
		setvard FX_DRIFTING 0
	}

	callevent set_view FX_CUR_V

	if FX_DRIFTING
	callevent 0.01 drift_to_new_view
}
