//big flaming burst in rapidly expanding circle
{ client_activate //<origin>
	setvard FX_CENTER PARAM1
	cleffect light new FX_CENTER 512 (255,128,64) 1.0
	cleffect tempent sprite weapons/projectiles.mdl FX_CENTER setup_repulse_burst update_repulse_burst
	sound.play3d magic/boom.wav 10 FX_CENTER
	callevent 2.0 remove_fx
}

{ remove_fx
	removescript
}

{ update_repulse_burst
	local CUR_SCALE game.tempent.fuser1
	if CUR_SCALE < 15
	add CUR_SCALE 0.5
	cleffect tempent set_current_prop fuser1 CUR_SCALE
	cleffect tempent set_current_prop scale CUR_SCALE 
}

{ setup_repulse_burst
	cleffect tempent set_current_prop death_delay 1.5
	cleffect tempent set_current_prop body 51
	cleffect tempent set_current_prop framerate 1.0
	cleffect tempent set_current_prop sequence 8
	cleffect tempent set_current_prop rendermode add
	cleffect tempent set_current_prop renderamt 255
	cleffect tempent set_current_prop scale 0.5
	cleffect tempent set_current_prop gravity 0
	cleffect tempent set_current_prop collide none

	cleffect tempent set_current_prop frames 11
	cleffect tempent set_current_prop fadeout lifetime
	cleffect tempent set_current_prop angles $vec(0,90,0)
	cleffect tempent set_current_prop velocity $vec(0,0,0)
	cleffect tempent set_current_prop movetype 0
	cleffect tempent set_current_prop fuser1 0.1
}