{ client_activate

	setcallback render enable
	//local OWNER_IDX game.localplayer.eyepos
	local EYE_POS game.localplayer.eyepos
	local EYE_ANGS game.localplayer.viewangles
	vectoradd EYE_POS $relpos(EYE_ANGS,$vec(0,20,28))
	dbg *** client_activate EYE_POS EYE_ANGS
	cleffect tempent sprite bunny.spr EYE_POS setup_bunny update_bunny
	callevent 20.0 remove_script
	//playsound 0 10 ambience/the_horror1.wav
	sound.play3d ambience/the_horror1.wav 10 EYE_POS
}

{ game_prerender

	
}

{ remove_script
	removescript
}

{ update_bunny
	//local OWNER_IDX game.localplayer.viewmodel.active.id
	local EYE_POS game.localplayer.eyepos
	local EYE_ANGS game.localplayer.viewangles
	vectoradd EYE_POS $relpos(EYE_ANGS,$vec(0,20,28))
	cleffect tempent set_current_prop origin EYE_POS

	local CUR_ALPHA game.tempent.fuser1
	add CUR_ALPHA 1
	if ( CUR_ALPHA > 255 ) local CUR_ALPHA 200
	cleffect tempent set_current_prop fuser1 CUR_ALPHA
	cleffect tempent set_current_prop renderamt CUR_ALPHA

	//sprites rendered "glow" cannot scale
//	local CUR_SCALE game.tempent.fuser1
//	add CUR_SCALE 0.5
//	cleffect tempent set_current_prop fuser1 CUR_SCALE
//	cleffect tempent set_current_prop scale CUR_SCALE 
}

{ setup_bunny
	cleffect tempent set_current_prop death_delay 19.0
	cleffect tempent set_current_prop fadeout lifetime
	cleffect tempent set_current_prop framerate 30
	cleffect tempent set_current_prop frames 1
	cleffect tempent set_current_prop scale 0.1
	cleffect tempent set_current_prop rendermode texture
	cleffect tempent set_current_prop renderamt 255
	cleffect tempent set_current_prop gravity 0
	cleffect tempent set_current_prop collide none
	cleffect tempent set_current_prop fuser1 200
}