//dark staff shield (currently fixed size)
{ client_activate //<origin> <max_duration>

	setvard FX_ORIGIN PARAM1
	setvard FX_DURATION PARAM2
	setvard FX_ACTIVE 1

	sound.play3d magic/temple.wav 10 FX_ORIGIN
	sound.play3d magic/boom.wav 10 FX_ORIGIN
	setcallback render enable
	setvard FX_RAD 128
	cleffect light new FX_ORIGIN FX_RAD (255,0,255) 0.1
	setvard LIGHT_ID game.script.last_light_id
	callevent FX_DURATION end_fx

	cleffect tempent sprite weapons/projectiles.mdl FX_ORIGIN setup_dark_burst update_dark_burst
}

{ game_prerender
	if ( FX_ACTIVE )
	{
		cleffect light LIGHT_ID FX_ORIGIN 128 (255,0,255) 0.1
	}
	else
	{
		if FX_RAD > 2
		subtract FX_RAD 1
		cleffect light LIGHT_ID FX_ORIGIN FX_RAD (255,0,255) 0.1
	}
}

{ update_dark_burst
	if ( FX_ACTIVE )
	{
		local CUR_SCALE game.tempent.fuser1
		if CUR_SCALE < 1.0
		add CUR_SCALE 0.04
		cleffect tempent set_current_prop scale CUR_SCALE 
		cleffect tempent set_current_prop fuser1 CUR_SCALE
	}
	
	if ( !FX_ACTIVE )
	{
		cleffect tempent set_current_prop origin $vec(20000,20000,20000)
	}
}

{ end_fx
	setvard FX_ACTIVE 0
	callevent 1.0 remove_fx
}

{ remove_fx
	removescript
}

{ setup_dark_burst
	cleffect tempent set_current_prop death_delay FX_DURATION
	cleffect tempent set_current_prop body 54
	cleffect tempent set_current_prop framerate 1.0
	cleffect tempent set_current_prop sequence 8
	cleffect tempent set_current_prop rendermode add
	cleffect tempent set_current_prop rendercolor (255,0,255)
	cleffect tempent set_current_prop renderamt 255
	cleffect tempent set_current_prop scale 0.1
	cleffect tempent set_current_prop fuser1 0.1
	cleffect tempent set_current_prop gravity 0
	cleffect tempent set_current_prop collide none

	cleffect tempent set_current_prop frames 11
	cleffect tempent set_current_prop fadeout lifetime
	cleffect tempent set_current_prop angles $vec(0,90,0)
	cleffect tempent set_current_prop velocity $vec(0,0,0)
	cleffect tempent set_current_prop movetype 0
}