//sphere spins, grows, and bursts ~256 units (fades in, spins up 3 secs)
{ client_activate //<origin>
	setvard FX_ORIGIN PARAM1

	setvard FX_GROW_START game.time
	add FX_GROW_START 2.5
	setvard FX_END_TIME FX_GROW_START
	setvard FX_SCALE 2.0
	setvard FX_ACTIVE 1
	callevent 6.0 end_fx

	cleffect tempent model weapons/projectiles FX_ORIGIN setup_bubble update_bubble
	
}

{ update_bubble
	if ( FX_ACTIVE )
	{
		if ( !GROW_MODE )
		{
			if game.time > FX_GROW_START
			setvard GROW_MODE 1
		}

		if GROW_MODE

		add FX_SCALE 0.01
		cleffect tempent set_current_prop scale FX_SCALE
	}
	else
	{
		cleffect tempent set_current_prop origin $vec(20000,20000,20000)
	}
}

{ end_fx
	setvard FX_ACTIVE 0
	callevent 1.0 remove_fx
}

{ remove_fx
	removescript
}


{ setup_bubble
	cleffect tempent set_current_prop death_delay 10.0
	cleffect tempent set_current_prop scale FX_SCALE
	cleffect tempent set_current_prop body 1
	cleffect tempent set_current_prop sequence 6 //7-8 for faster
	cleffect tempent set_current_prop frames 255
	cleffect tempent set_current_prop gravity 0
	cleffect tempent set_current_prop framerate 1.0
	//cleffect tempent set_current_prop rendermode add
	//cleffect tempent set_current_prop renderamt 100
	cleffect tempent set_current_prop collide none
	cleffect tempent set_current_prop movetype 0
}