//Ice Cage by Thothie from sfx_stunring
//PARAM1 - Stunned npc ID
//PARAM2 - Duration

{  game_dynamically_created

	setvard		script.owner	PARAM1
	setvard		script.tilt	1

	local MY_DURATION PARAM2
	local MY_OWNER PARAM1
	dbg ice cage spawn
   	callexternal MY_OWNER freeze_solid_start MY_DURATION

   	setmodel	weapons/magic/icecage.mdl
	setprop		ent_me movetype const.movetype.noclip
	setprop		ent_me solid 0
	setangle	angles.z -20
	fly		1
	invincible	1
	playanim	idle
	setanim.framerate 	0

	callevent	snap_to_owner
	callevent	set_tilt
	callevent 	PARAM2	die
}

{
	repeatdelay 0.1

	callevent	snap_to_owner	
}

{  snap_to_owner
	local l.pos $get(script.owner,origin)
	setvard rheight 0

	if ( $get(script.owner,isplayer) == 1 )
	{
		setvard rheight 0
		vectoradd l.pos $vec(0,0,rheight)
	}


	setorigin ent_me l.pos

	if !$get(script.owner,isalive)

}

{  die

	setprop	ent_me avelocity (0,0,0)
	deleteent ent_me
}