//Smallarms charge up attack (200%) - Haste - speed boost

#scope server

{
	const EFFECT_ID			"player_haste"
	const EFFECT_FLAGS		nostack
	const EFFECT_SCRIPT $currentscript //Must be copied, as is, at the top script!
}

#include effects/base_effect	allowduplicate

{ game_activate //<duration> <calling weapon>

	setvard CALLING_WEAPON PARAM2

	setvard game.effect.movespeed 500
    setvard game.effect.anim.framerate 3.0
    setvard game.effect.canjump 0

	clientevent new ent_me $currentscript EFFECT_DURATION
	setvard local.effect.clientscript game.script.last_sent_id
}

{ effect_die
	
	callexternal CALLING_WEAPON turbo_off
}

// ===========
// Client Side
// ===========

{ [client] client_activate

	setvard game.cleffect.move_scale.forward 	3
	setvard game.cleffect.move_scale.right 		3
	
	callevent PARAM1 effect_die
}

{ [client] effect_die
	removescript
}