//seeing if speed penalties stack with scripts, or are static
//(result: Yes, it does indeed stack)
#scope server
{
	const EFFECT_ID			chill_stack
	const EFFECT_NAME		"chillstack"
	const EFFECT_ACTIONTYPE		normal
	const EFFECT_SCRIPT		$currentscript
	const ATTACK_DAMAGE_TYPE	cold

	setvard game.effect.id		EFFECT_ID
	setvard game.effect.displayname	EFFECT_NAME
	setvard game.effect.type	EFFECT_ACTIONTYPE
}

{ game_precache

	local reg.effect.name	EFFECT_ID
	local reg.effect.flags	EFFECT_ACTIONTYPE
	local reg.effect.script	EFFECT_SCRIPT

	setvard game.effect.removeondeath 1

	registereffect

	setvard game.effect.id		EFFECT_ID
	setvard game.effect.displayname	EFFECT_NAME
	setvard game.effect.flags	EFFECT_ACTIONTYPE
}

{ game_activate //<attacker_id> <dot_add> <slow%_add>

	if ( !$get(ent_me,isalive) )
	{
		removescript //not a valid target
		local EXIT_SUB 1
	}
	if !EXIT_SUB

	setvard game.effect.anim.framerate 0.5
	setvard game.effect.movespeed 50%

	callevent 20.0 effect_die
}

{ effect_die
	removescript
}