#include items/base_treasurechest

{ treasure_spawn

   gold $rand(6,12)
   setvar      STORENAME treasure_storechalls2
}

{ chest_additems

   //           |Store name|  |Item name|  	|Quantity| |cost|
    if( $rand(0,1) == 1 ) addstoreitem  STORENAME     blunt_greatmaul 	1         0
    if( $rand(0,5) == 1 ) addstoreitem  STORENAME     swords_katana2 	1         0
    if( $rand(1,50) == 1 ) addstoreitem  STORENAME     swords_katana3 	1         0
	addstoreitem STORENAME proj_bolt_iron 25 0 0 25

	if ( $rand(1,100 ) == 1 )
	{
		local SCROLL_TOME $rand(1,2)
		if ( SCROLL_TIME == 1 )  addstoreitem  STORENAME     scroll2_volcano	1   	   0
		if ( SCROLL_TIME == 2 )  addstoreitem  STORENAME     scroll_volcano	1   	   0
	}

}