//Setup the map's weather
//
{ [shared]

	const MAP_NAME 		'challs'
	const MAP_WEATHER 	clear;clear;clear;clear;clear;clear
	const MAP_ALLOWNIGHT 	0

	setvarg G_MAP_NAME "The Halls of Charthane" //Carthain
	setvarg G_MAP_DESC "Once a hall of heroes, now a den of evi.l"
	setvarg G_MAP_DIFF "Levels 15-25 / 200-450hp"
	setvarg G_WARN_HP 200
}

#include worlditems/map_startup

{ [client] game_newlevel	//PARAM1 = Mapname

 	setvarg global.map.allownight	0
}