//Items cannot have menus, so use additional npc to handle these menus

{
	setvar MENU_TYPE 0 //0 = main; 1 = beams; 2 = afflictions type menu; 3 = afflictions duration menu
	//... 4 = afflictions dmg menu; 5 = player attributes menu; 6 = Player levels menu
	//... 7 = addgold menu; 8 = treasure menu; 9 = treasure weapons menu;
	//... 10 = trigger menu; 11 = successful trigger menu; 12 = save waypoint;
	//... 13 = load waypoint
}

#include developer/items/dev_staff/menus/beams
#include developer/items/dev_staff/menus/player
#include developer/items/dev_staff/menus/treasure
#include developer/items/dev_staff/menus/trigger
#include developer/items/dev_staff/menus/waypoints

{ game_spawn

	name "Jester's Staff"

	setmodel null.mdl
	race beloved
	invincible 1
}

{ game_dynamically_created

	setvard MY_OWNER PARAM1
	setvard MY_ITEM PARAM2
}

{ game_menu_getoptions

	if ( MENU_TYPE == 0 ) callevent menu_main
	if ( MENU_TYPE == 1 ) callevent menu_listbeams
	if ( MENU_TYPE == 2 ) callevent menu_listafflicttype
	if ( MENU_TYPE == 3 ) callevent menu_listafflictduration
	if ( MENU_TYPE == 4 ) callevent menu_listafflictdmg
	if ( MENU_TYPE == 5 ) callevent menu_playerlist
	if ( MENU_TYPE == 6 ) callevent menu_playerlevels
	if ( MENU_TYPE == 7 ) callevent menu_addgold
	if ( MENU_TYPE == 8 ) callevent menu_treasure
	if ( MENU_TYPE == 9 ) callevent menu_treasure_weapons
	if ( MENU_TYPE == 10 ) callevent menu_trigger
	if ( MENU_TYPE == 11 ) callevent menu_trigger_successful
	if ( MENU_TYPE == 12 ) callevent menu_waypoint_save
	if ( MENU_TYPE == 13 ) callevent menu_waypoint_load
}

{ menu_main

	name "Jester's Staff"

	local reg.mitem.title "Spawn Galat Chest"
	local reg.mitem.type callback
	local reg.mitem.callback spawn_galats
	menuitem.register

	local reg.mitem.title "Change Beam Type"
	local reg.mitem.type callback
	local reg.mitem.callback set_menu_type
	local reg.mitem.data 1
	menuitem.register
	
	local reg.mitem.title "Set Player Attribute"
	local reg.mitem.type callback
	local reg.mitem.callback set_menu_type
	local reg.mitem.data 5
	menuitem.register
	
	local reg.mitem.title "Spawn Items"
	local reg.mitem.type callback
	local reg.mitem.callback set_menu_type
	local reg.mitem.data 8
	menuitem.register
	
	local reg.mitem.title "Use Trigger"
	local reg.mitem.type callback
	local reg.mitem.callback set_menu_type
	local reg.mitem.data 10
	menuitem.register
	
	local reg.mitem.title "Save Waypoint"
	local reg.mitem.type callback
	local reg.mitem.callback set_menu_type
	local reg.mitem.data 12
	menuitem.register
	
	local reg.mitem.title "Load Waypoint"
	local reg.mitem.type callback
	local reg.mitem.callback set_menu_type
	local reg.mitem.data 13
	menuitem.register
}

{ set_menu_type
	setvard MENU_TYPE PARAM2
	callevent 0.1 ext_menu_open
}

{ ext_menu_open
	menu.open MY_OWNER
}

{ ext_menu_main //sets menu to main page and opens menu on player
	setvard MENU_TYPE 0
	callevent 0.1 ext_menu_open
}

{ spawn_galats

	local OWNER_POS $get(MY_OWNER,origin)
	local OWNER_YAW $get(MY_OWNER,angles.yaw)
	local SPAWN_POS OWNER_POS
	vectoradd SPAWN_POS $relpos($vec(0,OWNER_YAW,0),$vec(0,64,0))
	createnpc chests/bank1 SPAWN_POS MY_OWNER
}