{ menu_playerlist

	local reg.mitem.title "Loreldian Soup (God)"
	local reg.mitem.type callback
	local reg.mitem.callback toggle_soup
	menuitem.register
	
	local reg.mitem.title "Set Levels"
	local reg.mitem.type callback
	local reg.mitem.callback set_menu_type
	local reg.mitem.data 6
	menuitem.register
	
	local reg.mitem.title "Add Gold"
	local reg.mitem.type callback
	local reg.mitem.callback set_menu_type
	local reg.mitem.data 7
	menuitem.register
	
	local reg.mitem.title "Set Respawn Here"
	local reg.mitem.type callback
	local reg.mitem.callback set_respawn
	menuitem.register
}

{ toggle_soup

	if ( $get(MY_OWNER,haseffect,'lsoup') )
	{
		bplayermessage MY_OWNER "Removed Loreldian Soup effect."
		callexternal MY_OWNER ext_remove_lsoup
	}
	else 
	{
		bplayermessage MY_OWNER "Applied Loreldian Soup effect."
		applyeffect MY_OWNER developer/effects/loreldian_soup
	}
}

{ menu_playerlevels

	local reg.mitem.title "1"
	local reg.mitem.type callback
	local reg.mitem.callback setlevels
	local reg.mitem.data 1
	menuitem.register
	
	local reg.mitem.title "5"
	local reg.mitem.type callback
	local reg.mitem.callback setlevels
	local reg.mitem.data 5
	menuitem.register
	
	local reg.mitem.title "10"
	local reg.mitem.type callback
	local reg.mitem.callback setlevels
	local reg.mitem.data 10
	menuitem.register
	
	local reg.mitem.title "15"
	local reg.mitem.type callback
	local reg.mitem.callback setlevels
	local reg.mitem.data 15
	menuitem.register
	
	local reg.mitem.title "20"
	local reg.mitem.type callback
	local reg.mitem.callback setlevels
	local reg.mitem.data 20
	menuitem.register
	
	local reg.mitem.title "25"
	local reg.mitem.type callback
	local reg.mitem.callback setlevels
	local reg.mitem.data 25
	menuitem.register
	
	local reg.mitem.title "30"
	local reg.mitem.type callback
	local reg.mitem.callback setlevels
	local reg.mitem.data 30
	menuitem.register
	
	local reg.mitem.title "35"
	local reg.mitem.type callback
	local reg.mitem.callback setlevels
	local reg.mitem.data 35
	menuitem.register
	
	local reg.mitem.title "40"
	local reg.mitem.type callback
	local reg.mitem.callback setlevels
	local reg.mitem.data 40
	menuitem.register
}

{ setlevels
	callexternal MY_OWNER ext_setstats $pass(PARAM2)
	bplayermessage MY_OWNER "Set all levels to:" PARAM2
	
	givehp MY_OWNER 10000
	givemp MY_OWNER 10000
}

{ menu_addgold

	local reg.mitem.title "100"
	local reg.mitem.type callback
	local reg.mitem.callback addgold
	local reg.mitem.data 100
	menuitem.register
	
	local reg.mitem.title "10000"
	local reg.mitem.type callback
	local reg.mitem.callback addgold
	local reg.mitem.data 10000
	menuitem.register
	
	local reg.mitem.title "1000000"
	local reg.mitem.type callback
	local reg.mitem.callback addgold
	local reg.mitem.data 1000000
	menuitem.register
	
	local reg.mitem.title "999999999"
	local reg.mitem.type callback
	local reg.mitem.callback addgold
	local reg.mitem.data 999999999
	menuitem.register
}

{ addgold

	callexternal MY_OWNER ext_addgold PARAM2
}

{ set_respawn

	callexternal MY_OWNER set_spawn_point $get(MY_OWNER,origin)
	bplayermessage MY_OWNER "Respawn point set."
}