{ menu_treasure

	local reg.mitem.title "Weapons"
	local reg.mitem.type callback
	local reg.mitem.callback set_menu_type
	local reg.mitem.data 9
	menuitem.register
	
	local reg.mitem.title "Armor"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/armor"
	menuitem.register
	
	local reg.mitem.title "Ammunition"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/ammo"
	menuitem.register
	
	local reg.mitem.title "Rings"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/rings"
	menuitem.register

	local reg.mitem.title "Packs"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/packs"
	menuitem.register
	
	local reg.mitem.title "Potions"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/potions"
	menuitem.register
	
}

{ menu_treasure_weapons

	local reg.mitem.title "Swords"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/swords"
	menuitem.register
	
	local reg.mitem.title "Martial Arts"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/martialarts"
	menuitem.register
	
	local reg.mitem.title "Small Arms"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/smallarms"
	menuitem.register
	
	local reg.mitem.title "Axes"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/axes"
	menuitem.register
	
	local reg.mitem.title "Blunt Arms"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/bluntarms"
	menuitem.register
	
	local reg.mitem.title "Archery"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/archery"
	menuitem.register
	
	local reg.mitem.title "Magic"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/magic"
	menuitem.register
	
	local reg.mitem.title "Polearms"
	local reg.mitem.type callback
	local reg.mitem.callback create_treasure
	local reg.mitem.data "developer/chests/polearms"
	menuitem.register
}

{ create_treasure //PARAM2 = scriptname

	local OWNER_POS $get(MY_OWNER,origin)
	local OWNER_YAW $get(MY_OWNER,angles.yaw)
	local SPAWN_POS OWNER_POS
	vectoradd SPAWN_POS $relpos($vec(0,OWNER_YAW,0),$vec(0,64,0))
	createnpc PARAM2 SPAWN_POS MY_OWNER
}