{
	setvard WAYPOINT_QUEST "wpoint_" $lcase(game.map.name)
}

{ menu_waypoint_save

	bplayermessage MY_OWNER "Waypoints save along with the map."

	local reg.mitem.title "#1 Waypoint"
	local reg.mitem.type callback
	local reg.mitem.callback save_waypoint
	local reg.mitem.data 0
	menuitem.register
	
	local reg.mitem.title "#2 Waypoint"
	local reg.mitem.type callback
	local reg.mitem.callback save_waypoint
	local reg.mitem.data 1
	menuitem.register
	
	local reg.mitem.title "#3 Waypoint"
	local reg.mitem.type callback
	local reg.mitem.callback save_waypoint
	local reg.mitem.data 2
	menuitem.register
	
	local reg.mitem.title "#4 Waypoint"
	local reg.mitem.type callback
	local reg.mitem.callback save_waypoint
	local reg.mitem.data 3
	menuitem.register
	
	local reg.mitem.title "#5 Waypoint"
	local reg.mitem.type callback
	local reg.mitem.callback save_waypoint
	local reg.mitem.data 4
	menuitem.register
}

{ save_waypoint

	local L_WAYPOINTS $get_quest_data(MY_OWNER,WAYPOINT_QUEST)
	if ( L_WAYPOINTS equals '0' ) local L_WAYPOINTS "0;0;0;0;0"
	
	token.set L_WAYPOINTS PARAM2 $get(MY_OWNER,origin)
	quest set MY_OWNER WAYPOINT_QUEST L_WAYPOINTS
	
	bplayermessage MY_OWNER "Waypoint saved."
}

{ menu_waypoint_load

	local L_WAYPOINTS $get_quest_data(MY_OWNER,WAYPOINT_QUEST)
	if ( L_WAYPOINTS equals '0' ) local L_WAYPOINTS "0;0;0;0;0"

	local reg.mitem.title "#1 Waypoint"
	if ( $get_token(L_WAYPOINTS,0) isnot '0' )
	{
		local reg.mitem.type callback
		local reg.mitem.callback load_waypoint
		local reg.mitem.data 0
	}
	else local reg.mitem.type disabled
	menuitem.register
	
	local reg.mitem.title "#2 Waypoint"
	if ( $get_token(L_WAYPOINTS,1) isnot '0' )
	{
		local reg.mitem.type callback
		local reg.mitem.callback load_waypoint
		local reg.mitem.data 1
	}
	else local reg.mitem.type disabled
	menuitem.register
	
	local reg.mitem.title "#3 Waypoint"
	if ( $get_token(L_WAYPOINTS,2) isnot '0' )
	{
		local reg.mitem.type callback
		local reg.mitem.callback load_waypoint
		local reg.mitem.data 2
	}
	else local reg.mitem.type disabled
	menuitem.register
	
	local reg.mitem.title "#4 Waypoint"
	if ( $get_token(L_WAYPOINTS,3) isnot '0' )
	{
		local reg.mitem.type callback
		local reg.mitem.callback load_waypoint
		local reg.mitem.data 3
	}
	else local reg.mitem.type disabled
	menuitem.register
	
	local reg.mitem.title "#5 Waypoint"
	if ( $get_token(L_WAYPOINTS,4) isnot '0' )
	{
		local reg.mitem.type callback
		local reg.mitem.callback load_waypoint
		local reg.mitem.data 4
	}
	else local reg.mitem.type disabled
	menuitem.register
}

{ load_waypoint

	local L_WAYPOINTS $get_quest_data(MY_OWNER,WAYPOINT_QUEST)
	local L_POINT $get_token(L_WAYPOINTS,PARAM2)
	
	setorigin MY_OWNER L_POINT
	
	bplayermessage MY_OWNER "Waypoint loaded."
}