//Setup the map's weather
//
{ [shared]

	const MAP_NAME 		'keledrosprelude'
	const MAP_WEATHER 	clear;clear;clear;clear;rain;rain
	const MAP_ALLOWNIGHT 	1

	setvarg MAP_CON 1
}

#include worlditems/map_startup

{ [client] game_newlevel	//PARAM1 = Mapname

 	//Setup map-specific reflections
	//

	local reg.texture.name		'glass_bright'
	local reg.texture.reflect	1
	local reg.texture.reflect.blend	1
	local reg.texture.reflect.color	1;1;1;0.8
	local reg.texture.water		0
	//registertexture
}