//Bandit boss only spawns in helena if there are a VERY large number of powerful players present (about 5000hp)

{ treasure_spawn

	setvar	STORENAME banid_boss_chest

	playsound 0 10 amb/quest1.wav //alert folks to my presense as I spawn a bit late to avoid edict crashes
}

#include items/base_treasurechest

{ chest_additems

	callevent add_gold 100 2000 100

	callevent add_great_item
	callevent add_great_item
	callevent add_epic_item
	callevent add_epic_item
}
