//Bandit boss only spawns in helena if there are a VERY large number of powerful players present (about 5000hp)

{ game_spawn
	playsound 0 10 amb/quest1.wav //alert folks to my presense as I spawn a bit late to avoid edict crashes
}

#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(100,1000)

	callevent add_great_item
	callevent add_great_item
	callevent add_epic_item
	callevent add_epic_item
}
