{
	const MALE_MODEL "npc/human1.mdl"
	const FEMALE_MODEL "npc/human2.mdl"
	precache npc/human1.mdl
	precache npc/human2.mdl
	const MY_RAID_POS '$relpos(0,0,0)'

	const DEFAULT_HUMAN 1

	setvar ANIM_IDLE idle1
	setvar ANIM_RUN run
	setvar ANIM_WALK walk
	setvard ANIM_DEATH diesimple
}

#include monsters/base_civilian
#include helena/helena_npc
#include monsters/base_npc
#include monsters/base_xmass

{ npc_spawn

   hp		25
   //ov		120
   width	32
   height	72
   race		human
   name		Commoner
   roam		1
	blood red
   skilllevel -10

	setmoveanim ANIM_WALK
	setidleanim ANIM_IDLE

	//dbg spawning

	local GENDER_BENDER $rand(1,2)
	if ( GENDER_BENDER == 1 ) 
	{
		//dbg spawned a male
		setvard MY_SEX male
		setmodel MALE_MODEL
	}
	if( GENDER_BENDER == 2 ) 
	{ 
		//dbg ZOMG - THERE'S A CHICK IN TOWN!
		setmodel FEMALE_MODEL
		setvard MY_SEX female
	}

   setmodelbody 0 $rand(0,2)
   setmodelbody 1 $rand(0,5)
   setmoveanim	walk
}

{
  repeatdelay $rand(25,35)

	if !RAID_ON
	
	if $cansee(ally,180)
	
	setmovedest ent_lastseen 128
	volume 2
	if ( MY_SEX equals male ) say chitchat[.5] [.2] [.55] [.55] [.23] [.22]
	if ( MY_SEX equals female )
	{
		//this is kidna annoying - so only once
		if !DID_FEM_VOICE
		if ( $get(ent_lastseen,isplayer) ) 
		{
			playsound 0 8 voices/human/female_vendor2.wav
			setvard DID_FEM_VOICE 1
			say [.5] [.2] [.55] [.55] [.23] [.22] [.5] [.2] [.55] [.55] [.23] [.22]
		}
	}

	if ( HELENA_SAVED )
	{
		if $rand(1,2) == 1
		local RND_SAY $rand(1,2)
		if ( RND_SAY == 1 ) saytext Thank you for saving our little village.
		if ( RND_SAY == 2 ) saytext Thanks to heros like you, we may yet turn this into a safe place to live.
	}
}

