{ treasure_spawn

	setvar	STORENAME laravachest
}


#include items/base_treasurechest

{ chest_additems

	callevent add_gold 25 600 25
	callevent get_players 100

	callevent add_noob_item
	callevent add_noob_item
	callevent add_noob_item
	callevent add_noob_item

	if TC_NPLAYERS > 1

	callevent add_good_item

	if TC_NPLAYERS > 3
	callevent add_good_item
	callevent add_great_item
	
	if TC_NPLAYERS > 4
	callevent add_great_item

	if TC_NPLAYERS > 6
	addstoreitem STORENAME smallarms_k_fire 1 0
}
