//Thothie - Provided for backwards compatability with MS 1.35
//Otherwise all the maps go bad with each revision
//- Similar to Orc Flayer, no roam, more cash / hp

{
   setvard DROP_GOLD 1			//Gold Drops
   setvard DROP_GOLD_AMT $rand(15,35)	//
   setvard NPC_GIVE_EXP 100
   setvard DROP_ITEM1 axes_battleaxe //Used by base_monster
   setvard DROP_ITEM1_CHANCE 40%	  //Used by base_monster

   setvard ANIM_ATTACK battleaxe_swing1_L//Attack animation
   setvard FLINCH_CHANCE 45%

   const ATTACK_ACCURACY 80%
   const ATTACK_DMG_LOW 18
   const ATTACK_DMG_HIGH 45
}

#include monsters/orc_base_melee
#include monsters/orc_base

{  orc_spawn

   	hp 600
	//ov 180
	width 32
	height 60
	name an|Orc Guard
   	hearingsensitivity 3
   	setstat parry 15
	setstat swordsmanship 10 25 20
	takedmg all .8
	roam 0

   	setmodelbody	0 2		//Body
   	setmodelbody	1 2		//Head
   	setmodelbody	2 1		//Weapon
}