//placeholder
{ treasure_spawn

	setvar	STORENAME spid_chest
}

#include items/base_treasurechest

{ chest_additems

	callevent add_gold 25 200 25
	callevent get_players 50

	callevent add_noob_item
	callevent add_noob_item

	if TC_NPLAYERS > 1

	callevent add_good_item

	if TC_NPLAYERS > 3
	callevent add_good_item
	callevent add_good_item
	addstoreitem STORENAME mana_prot_spiders 1 0
	
	if TC_NPLAYERS > 4
	callevent add_great_item

	if TC_NPLAYERS > 7
	addstoreitem STORENAME swords_spiderblade 1 0
}
