#scope server
#include chests/base_treasurechest_array

{ chest_additems

	callevent add_gold 100

	local POT_AMT 1
	if ( game.playersnb > 2 ) local POT_AMT 2
	
	addstoreitem STORENAME health_spotion POT_AMT 0
	addstoreitem STORENAME mana_mpotion POT_AMT 0
	addstoreitem STORENAME item_log POT_AMT 0
	addstoreitem STORENAME item_crystal_return POT_AMT 0
}

{ chest_add_quality_items //PARAM1=user

	callevent add_great_item 100 20
	callevent add_epic_arrows 30
}