#scope server

#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(50,500)
   
	addstoreitem STORENAME health_spotion 1 0
	addstoreitem STORENAME mana_mpotion 1 0
	addstoreitem STORENAME item_log 1 0
	addstoreitem STORENAME item_crystal_return 1 0

	if ( FOAMY_CHEST_TYPE == 1 )
	{
		if ( $rand(0,1) ) addstoreitem STORENAME mana_gprotection 1 0
		else addstoreitem STORENAME mana_protection 1 0

		setvard SCROLL_TOME $get_random_token(scroll_poison_cloud;scroll2_poison_cloud;scroll_acid_xolt;scroll2_acid_xolt;scroll_poison;scroll2_poison)
		addstoreitem STORENAME SCROLL_TOME 1 0
	}

	if ( FOAMY_CHEST_TYPE == 2 )
	{
		callevent add_great_item
		addstoreitem STORENAME smallarms_fangstooth 1 0
	}

	if ( FOAMY_CHEST_TYPE == 3 )
	{
		addstoreitem STORENAME swords_nkatana 1 0
		addstoreitem STORENAME mana_speed 1 0

	}

	if ( FOAMY_CHEST_TYPE == 4 )
	{
		addstoreitem STORENAME armor_helm_bronze 1 0
		if ( $rand(1,8) == 1 ) addstoreitem STORENAME armor_salamander 1 0
		if ( $rand(1,4) == 1 ) addstoreitem STORENAME mana_immune_poison 1 0
	}
}
