#scope server
#include [server] items/base_treasurechest

{ chest_additems //PARAM1 = stock type , called externally from chest_a_filler

	if !ALREADY_FULL
	setvard ALREADY_FULL 1

	callevent add_gold 50 1000 100

	callevent get_players 500

	local NUM_PLAYERS TC_NPLAYERS

	local POT_AMT 1
	if ( TC_NPLAYERS > 6 ) local POT_AMT 2
	
	addstoreitem STORENAME health_spotion POT_AMT 0
	addstoreitem STORENAME mana_mpotion POT_AMT 0
	addstoreitem STORENAME item_log POT_AMT 0
	addstoreitem STORENAME item_crystal_return POT_AMT 0

	//This should no longer be here. -greatguys1 SEP2021
	//setvard FOAMY_CHEST_TYPE $rand(1,4)

	if ( FOAMY_CHEST_TYPE == 1 )
	{
		addstoreitem STORENAME item_crystal_reloc 1 0
		if ( TC_NPLAYERS > 4 ) addstoreitem STORENAME mana_speed 1 0
	}

	if ( FOAMY_CHEST_TYPE == 2 )
	{
		addstoreitem STORENAME item_log_magic 1 0
	}

	if ( FOAMY_CHEST_TYPE == 3 )
	{
		addstoreitem STORENAME mana_gprotection 1 0
		if NUM_PLAYERS > 2
		callevent get_chance 20 30 75 500
		if ( GIVE_PRIZE ) addstoreitem STORENAME mana_regen 1 0
	}

	if ( FOAMY_CHEST_TYPE == 4 )
	{
		addstoreitem STORENAME mana_demon_blood 1 0
		if ( TC_NPLAYERS > 4 ) addstoreitem STORENAME mana_demon_blood 1 0
	}

}

{ add_quality_items //PARAM1=user

	if ( $get(PARAM1,maxhp) < 500 ) callevent 0.1 reset_quality
	if $get(PARAM1,maxhp) >= 500

	callevent get_players 500

	if ( FOAMY_CHEST_TYPE == 1 )
	{
		if TC_NPLAYERS > 1
		callevent get_chance 1 20 75 500
		if ( GIVE_PRIZE ) addstoreitem smallarms_bone_blade 1 0
		callevent get_chance 1 20 75 500
		if ( GIVE_PRIZE ) addstoreitem STORENAME scroll2_acid_xolt 1 0
	}

	if ( FOAMY_CHEST_TYPE == 2 )
	{
		callevent get_chance 1 10 75 500
		if ( GIVE_PRIZE ) addstoreitem STORENAME armor_helm_gray 1 0
		callevent get_chance 1 10 75 500
		if ( GIVE_PRIZE ) addstoreitem STORENAME scroll2_poison_cloud 1 0
		callevent get_chance 1 5 75 500
		if ( GIVE_PRIZE ) addstoreitem STORENAME axes_runeaxe 1 0
	}

	if ( FOAMY_CHEST_TYPE == 3 )
	{
		callevent get_chance 20 30 75 500
		if ( GIVE_PRIZE ) addstoreitem STORENAME mana_regen 1 0
		callevent get_chance 1 20 75 500
		if ( GIVE_PRIZE ) addstoreitem STORENAME swords_rune_green 1 0
		callevent get_chance 1 10 75 500
		if ( GIVE_PRIZE ) addstoreitem STORENAME scroll_poison_cloud 1 0
	}

	if ( FOAMY_CHEST_TYPE == 4 )
	{
		callevent offer_felewyn_symbol 100
		if ( TC_NPLAYERS > 5 ) callevent add_great_item 75
	}

}

{ reset_quality
	setvard ADDED_QUALITY 0
}