// Cupboard in barracks
{
	const ANIM_OPEN seq-name
	const ANIM_CLOSE seq-name
	const ANIM_IDLE seq-name
}

#include chests/base_treasurechest

{ game_spawn

	name		an|Old Dresser
	setmodel	props/Xen_furniture2.mdl
	setidleanim	ANIM_IDLE
}

{ trade_success
   playrandomsound 2 10 items/creak.wav
}

{ chest_additems

	callevent add_gold $rand(13,26)
	//           |Store name|  |Item name|  	|Quantity| |cost|
	addstoreitem STORENAME health_mpotion 1 0
	addstoreitem STORENAME key_red 1 0
}