{
	setvarg POISON_TRIG 0
	const ELEMENT_TYPE poison
}

#include bloodrose/trigger_base

{ trigger_spawn

	name an|Elemental Shard of Affliction

	setvard IMMUNE_LIGHTNING 1
	setvard IMMUNE_FIRE 1
	setvard IMMUNE_COLD 1
	setvard IMMUNE_POISON 0


	takedmg lightning 0.0
	takedmg fire 0.0
	takedmg cold 0.0
	takedmg poison 1.0
	takedmg acid 1.0

	takedmg slash 0.0
	takedmg blunt 0.0
	takedmg pierce 0.0
	takedmg holy 0.0
}
