{
	setvarg COLD_TRIG 0
	setvarg FIRE_TRIG 0
	setvarg LIGHTNING_TRIG 0
	setvarg POISON_TRIG 0 
}

{ game_spawn
	
	name_unique ele_monitor
	
	setmodel null.mdl

	invincible 1
	fly 1
	roam 0
	movespeed 0.0
	race beloved
	callevent 1.0 monitor_triggers
}

{ monitor_triggers

	//local FOUR_TRIGS 0
	//add FOUR_TRIGS COLD_TRIG
	//add FOUR_TRIGS FIRE_TRIG
	//add FOUR_TRIGS LIGHTNING_TRIG
	//add FOUR_TRIGS POISON_TRIG

	//if ( FOUR_TRIGS == 4 )
	//{
	//	setvard ATHOLO_ID $get_by_name(boss_atholo)
	//	callexternal ATHOLO_ID vulnerable
	//	usetrigger monitor_triggered
	//}

	local FOUR_TRIGS 0

	add FOUR_TRIGS COLD_ON
	add FOUR_TRIGS FIRE_ON
	add FOUR_TRIGS POISON_ON
	add FOUR_TRIGS LIGHTNING_ON

	if ( FOUR_TRIGS == 4 )
	{
		setvard ATHOLO_ID $get_by_name(boss_atholo)
		callexternal ATHOLO_ID vulnerable
		usetrigger monitor_triggered
		callexternal all element_trigs_remove
		setvard MON_DONE 1
	}

	if !MON_DONE
	callevent 0.5 monitor_triggers
}

{ trigger_on //PARAM1 = type

	if ( PARAM1 equals cold ) setvard COLD_ON 1
	if ( PARAM1 equals fire ) setvard FIRE_ON 1
	if ( PARAM1 equals poison ) setvard POISON_ON 1
	if ( PARAM1 equals lightning ) setvard LIGHTNING_ON 1

}

{ trigger_off //PARAM1 = type

	if ( PARAM1 equals cold ) setvard COLD_ON 0
	if ( PARAM1 equals fire ) setvard FIRE_ON 0
	if ( PARAM1 equals poison ) setvard POISON_ON 0
	if ( PARAM1 equals lightning ) setvard LIGHTNING_ON 0
}