{
   setvar SND_STRUCK1 body/flesh1.wav
   setvar SND_STRUCK2 body/flesh2.wav
   setvar SND_STRUCK3 body/flesh3.wav
   setvar SOUND_PAINYELL voices/human/male_hit1.wav
   setvar SOUND_WARCRY1 voices/human/male_guard_shout.wav
   setvar SOUND_WARCRY2 voices/human/male_guard_shout2.wav
   setvar SND_ATTACK1 voices/human/male_hit1.wav
   setvar SND_ATTACK2 voices/human/male_hit2.wav
   setvar SND_ATTACK3 voices/human/male_hit3.wav
   setvar SND_BOW weapons/bow/bow.wav
   const SOUND_DEATH voices/human/male_die.wav
   setvard CAN_FLINCH 1
   setvar ANIM_RUN run
   setvar ANIM_WALK walk
   setvard ANIM_ATTACK shootorcbow
   const ARROW_DAMAGE_LOW 8
   const ARROW_DAMAGE_HIGH 12
   setvard MOVE_RANGE 600
   setvard ATTACK_RANGE 650
   const ATTACK_SPEED 700
   const ATTACK_CONE_OF_FIRE 4//Cone of fire
   setvard FLINCH_DELAY 4
   setvar FLEE_HEALTH 10
   setvar FLEE_CHANCE 15%
   setvard CAN_FLEE 1
   setvard CAN_HUNT 1
   setvard HUNT_AGRO 1
}

#include monsters/base_npc_attack

{
   eventname npc_spawn

   hp 120
   //ov 180
   width 32
   height 85
   race human
   name a|Human Archer
   roam 1
   skilllevel 30
   gold $rand(6,10)
   hearingsensitivity 3
   setmodel npc/archer.mdl
   takedmg all .8
   setmodelbody	2 2
   setidleanim idle1
   setmoveanim walk
   setactionanim shootorcbow
   giveitem proj_arrow_iron 30
   setstat parry 5
}

{
   eventname grab_arrow

   setmodelbody 3 1
}

{
   // Deal damage
   eventname shoot_arrow

   local AIM_ANGLE $get(ent_lastseen,dist)	//Aim up a bit
   divide AIM_ANGLE 30					//
   setangle add_view.x AIM_ANGLE			//

   local LCL_ATKDMG $rand(ARROW_DAMAGE_LOW,ARROW_DAMAGE_HIGH)
   tossprojectile view ATTACK_SPEED LCL_ATKDMG ATTACK_CONE_OF_FIRE proj_arrow_npc (0,0,48)
   setmodelbody 3 0		//Hide arrow
   playsound 2 SND_BOW
} 

   //Hit by someone
{
   eventname npc_struck
   
   volume 10
   playrandomsound 2 SOUND_PAINYELL SND_STRUCK2 SOUND_PAINYELL
}