#include chests/base_treasurechest

{ game_spawn

	//already common in one of the loot tables....
	//callevent tc_add_artifact armor_leather_gaz1 80
	
	callevent tc_add_artifact armor_helm_undead 12
}

{ chest_additems

	callevent add_gold $math(multiply,50,game.playersnb)
	callevent chest_add_hpot_mpot
	
	callevent add_good_item
	callevent add_great_item

	if ( $rand(1,6) == 1 )
	{
		callevent add_great_item
	}
}
