{
	const STORENAME ara_chest1
	const GM_VERIFY 1
}

#include items/base_treasurechest

{ chest_additems

	callevent add_gold 50 500 50
	callevent get_players 300

	local L_MAP_NAME $lcase(game.map.name)
	if L_MAP_NAME equals ara

	//addstoreitem <storename> <item> <amt> <cost%> <buy_ratio> <bundle_size>
	addstoreitem  STORENAME     health_spotion 	 	TC_NPLAYERS 	0
	addstoreitem  STORENAME     mana_mpotion 	TC_NPLAYERS	0

	if ( TC_NPLAYERS <= 4 )
	{
		callevent get_chance_rare 300
		if ( GIVE_PRIZE ) addstoreitem STORENAME armor_leather_gaz1 1 0
		callevent get_chance_rare 300
		if ( GIVE_PRIZE ) addstoreitem STORENAME armor_helm_undead 1 0
	}
	if TC_NPLAYERS > 4
	addstoreitem STORENAME armor_leather_gaz1 1 0
	if TC_NPLAYERS > 5
	callevent add_good_item 100
	if TC_NPLAYERS > 6
	addstoreitem STORENAME armor_helm_undead 1 0
	callevent add_great_item 100
	if TC_NPLAYERS > 7
	callevent add_great_item 100
}
