#include chests/base_treasurechest

{ game_spawn

	callevent tc_add_artifact swords_volcano 15
	callevent tc_add_artifact shields_urdual 15
}

{ chest_additems

	callevent add_gold $math(multiply,50,game.playersnb)
	callevent chest_add_hpot_mpot
	
	callevent add_good_item
	callevent add_good_item

	if ( $rand(1,2) == 1 ) callevent add_good_item
	if ( $rand(1,3) == 1 ) callevent add_great_item
	if ( $rand(1,4) == 1 ) callevent add_great_item
	if ( $rand(1,4) == 1 ) callevent add_epic_item
}