{ treasure_spawn

	setvar	STORENAME jump_chest
}

#include items/base_treasurechest

{ chest_additems
	callevent add_gold 50 500 50
	addstoreitem STORENAME mana_mpotion TC_NPLAYERS_QUART 0
	addstoreitem STORENAME health_spotion TC_NPLAYERS_HALF 0
	callevent add_good_item 100

	addstoreitem STORENAME mana_resist_fire 1 0
	if TC_NPLAYERS > 1
	callevent add_good_item 100
	addstoreitem STORENAME mana_resist_cold 1 0

	if TC_NPLAYERS > 2
	addstoreitem STORENAME mana_resist_cold 1 0

	if TC_NPLAYERS > 3
	callevent add_good_item 50

	if TC_NPLAYERS > 6
	addstoreitem STORENAME mana_immune_fire 1 0

	if TC_NPLAYERS > 7
	addstoreitem STORENAME mana_immune_poison 1 0
	callevent add_great_item 50
}