#include chests/base_treasurechest

{ chest_additems
	gold $math(multiply,50,game.playersnb)
	callevent chest_add_hpot_mpot
	
	callevent add_good_item
	callevent add_good_item
	
	addstoreitem STORENAME mana_resist_fire 1 0
	addstoreitem STORENAME mana_resist_cold 1 0

	if ( $rand(1,5) == 1 ) addstoreitem STORENAME mana_resist_cold 1 0
	if ( $rand(1,5) == 1 ) callevent add_good_item
	
	if ( $rand(1,6) == 1 ) addstoreitem STORENAME mana_immune_fire 1 0

	if ( $rand(1,6) == 1 )
	{
		addstoreitem STORENAME mana_immune_poison 1 0
		callevent add_great_item
	}
}