//Thothie - for the xbows, so we have some place to get them, should we ever get them working

{
   eventname treasure_spawn

   gold		0
   setvar	STORENAME xoltchest
}

#include items/base_treasurechest

{
   eventname chest_additems

	addstoreitem STORENAME proj_bolt_wooden 50 0 0 50
	addstoreitem STORENAME proj_bolt_iron 50 0 0 50
	addstoreitem STORENAME proj_bolt_silver 50 0 0 50
	addstoreitem STORENAME proj_bolt_fire 50 0 0 50

}
