{
	const SCROLL_1 scroll_summon_fangtooth
	const SCROLL_2 scroll_summon_guard
	const SCROLL_3 scroll_acid_xolt
	const SCROLL_4 scroll_poison_cloud
	const SCROLL_5 scroll_ice_blast
	const SCROLL_6 scroll_healing_circle
	const SCROLL_7 scroll_ice_xolt

	const CHEST_SELF_ADJ 1
}

#include chests/base_treasurechest_array

{ chest_additems

	local TOTAL_KILLS G_SADJ_DEATHS
	local TOTAL_LEVELS G_SADJ_LEVELS
	setvard AVG_LEVELS TOTAL_LEVELS
	divide AVG_LEVELS TOTAL_KILLS

	if ( G_DEVELOPER_MODE )
	{

		local OUT_TITLE "Stat Tracking"
		local OUT_MSG "Kills: "
		stradd OUT_MSG TOTAL_KILLS
		stradd OUT_MSG " Levels: "
		stradd OUT_MSG TOTAL_LEVELS
		stradd OUT_MSG " Average: "
		stradd OUT_MSG AVG_LEVELS
		infomsg all OUT_TITLE OUT_MSG
		consolemsg all "Stats - " OUT_MSG
	}

	callevent add_great_item 100
	callevent add_great_arrows
}

{ chest_add_quality_items
	dbg chest_add_quality_items AVG_LEVELS

	callevent add_epic_item 100

	if ( AVG_LEVELS >= 2.5 )
	{
		if ( !G_GAVE_TOME1 )
		{
			if $rand(1,16) <= game.playersnb
			setvarg G_GAVE_TOME1 1
			addstoreitem STORENAME SCROLL_1 1 0
		}
		callevent add_epic_arrows

		if ( !G_GAVE_TOME7 )
		{
			local BASE_CHANCE 100
			local BASE_CHANCE_ADJ BASE_CHANCE
			subtract BASE_CHANCE_ADJ game.playersnb
			if $rand(1,BASE_CHANCE) > BASE_CHANCE_ADJ
			addstoreitem STORENAME scroll_summon_bear1 1 0
			setvarg G_GAVE_TOME7 1
		}
	}

	if ( AVG_LEVELS >= 3.5 )
	{
		if ( !G_GAVE_TOME2 )
		{
			if $rand(1,16) <= game.playersnb
			setvarg G_GAVE_TOME2 1
			addstoreitem STORENAME SCROLL_2 1 0
		}
		if ( !G_GAVE_ARTI1 )
		{
			if $rand(1,16) <= game.playersnb
			setvarg G_GAVE_ARTI1 1
			local RND_TYPE $rand(1,100)
			if ( RND_TYPE < 20 )
			{
				addstoreitem STORENAME blunt_ms3 1 0
				local EXIT_SUB 1
			}
			if !EXIT_SUB
			if ( RND_TYPE < 40 )
			{
				addstoreitem STORENAME blunt_ms2 1 0
				local EXIT_SUB 1
			}
			if !EXIT_SUB
			addstoreitem STORENAME blunt_ms1 1 0
		}

		if ( !G_GAVE_TOME7 )
		{
			local BASE_CHANCE 50
			local BASE_CHANCE_ADJ BASE_CHANCE
			subtract BASE_CHANCE_ADJ game.playersnb
			if $rand(1,BASE_CHANCE) > BASE_CHANCE_ADJ
			addstoreitem STORENAME scroll_summon_bear1 1 0
			setvarg G_GAVE_TOME7 1
		}

		callevent add_epic_item 100
		callevent add_epic_arrows
	}

	if ( AVG_LEVELS >= 4 )
	{
		if ( !G_GAVE_TOME3 )
		{
			if $rand(1,16) <= game.playersnb
			setvarg G_GAVE_TOME3 1
			addstoreitem STORENAME SCROLL_3 1 0
		}

		if ( !G_GAVE_TOME7 )
		{
			if $rand(1,16) <= game.playersnb
			setvarg G_GAVE_TOME7 1
			addstoreitem STORENAME SCROLL_7 1 0
		}
		callevent add_epic_item 100
		callevent add_epic_arrows

		if ( !G_GAVE_TOME7 )
		{
			local BASE_CHANCE 30
			local BASE_CHANCE_ADJ BASE_CHANCE
			subtract BASE_CHANCE_ADJ game.playersnb
			if $rand(1,BASE_CHANCE) > BASE_CHANCE_ADJ
			addstoreitem STORENAME scroll_summon_bear1 1 0
			setvarg G_GAVE_TOME7 1
		}
	}


	if ( AVG_LEVELS >= 5 )
	{
		if ( !G_GAVE_TOME4 )
		{
			if $rand(1,16) <= game.playersnb
			setvarg G_GAVE_TOME4 1
			addstoreitem STORENAME SCROLL_4 1 0
		}
		if ( !G_GAVE_TOME5 )
		{
			if $rand(1,16) <= game.playersnb
			setvarg G_GAVE_TOME5 1
			addstoreitem STORENAME SCROLL_5 1 0
		}
		if ( !G_GAVE_TOME6 )
		{
			if $rand(1,16) <= game.playersnb
			setvarg G_GAVE_TOME6 1
			addstoreitem STORENAME SCROLL_6 1 0
		}

		if ( !G_GAVE_TOME7 )
		{
			local BASE_CHANCE 25
			local BASE_CHANCE_ADJ BASE_CHANCE
			subtract BASE_CHANCE_ADJ game.playersnb
			if $rand(1,BASE_CHANCE) > BASE_CHANCE_ADJ
			addstoreitem STORENAME scroll_summon_bear1 1 0
			setvarg G_GAVE_TOME7 1
		}

		callevent add_epic_item 100
		callevent add_epic_arrows
	}

	addstoreitem STORENAME gold_pouch_500 $int(AVG_LEVELS) 0
}

