//Chest near orc archers
#include chests/base_treasurechest_array

{ chest_additems

	callevent add_gold_by_hp 10
	callevent add_noob_item 100 10
	addstoreitem STORENAME bows_orcbow 1 0

	local ARROW_BUNDLES 30
	if ( $rand(1,4) <= game.playersnb ) addstoreitem STORENAME proj_arrow_fire ARROW_BUNDLES 0 0 30
	addstoreitem STORENAME proj_arrow_broadhead ARROW_BUNDLES 0 0 30
	if TC_NPLAYERS > 4
	addstoreitem STORENAME proj_arrow_holy ARROW_BUNDLES 0 0 30
	if TC_NPLAYERS > 7
	addstoreitem STORENAME bows_longbow 1 0
}
