//Gert_Caves final chest
#include chests/base_treasurechest_array

{ chest_additems

	//needs unique item!

	callevent add_gold_by_hp 500
	callevent add_epic_item 100 500
	if ( $rand(1,8) <= game.playersnb ) callevent add_epic_item 100 300
	callevent add_great_item 100 200
	callevent add_great_item 100 200
	callevent add_great_item 100 200

	if $get(GAME_MASTER,scriptvar,'BGOBLIN_CHIEF_SLAIN')
	if $get(GAME_MASTER,scriptvar,'VGOBLIN_CHIEF_SLAIN')

	if ( $rand(1,12) <= game.playersnb )
	{
		if !GAVE_DAXE
		setvard GAVE_DAXE 1
		addstoreitem STORENAME axes_dragon 1 0		
	}

}