//Table chest

#include chests/base_treasurechest

{ game_spawn

	callevent tc_add_artifact blunt_gauntlets_demon 4
	callevent tc_add_artifact blunt_gauntlets_serpant 10
}

{ chest_additems

	callevent add_gold 50
	
	addstoreitem STORENAME mana_mpotion 1 0
	addstoreitem STORENAME health_spotion 1 0
	
	callevent add_good_item
	
	addstoreitem STORENAME mana_demon_blood 1 0

	if game.playersnb > 2
	callevent add_good_item
	if game.playersnb > 3
	callevent add_great_item
	
}
