//table chest
{
   setvar STORENAME demon_table
}

#include items/base_treasurechest

{ chest_additems
	callevent add_gold 50 600 50
	addstoreitem STORENAME mana_mpotion TC_NPLAYERS_QUART 0
	addstoreitem STORENAME health_spotion TC_NPLAYERS_HALF 0
	callevent add_good_item 100

	if TC_NPLAYERS > 2
	callevent add_good_item 100
	if TC_NPLAYERS > 3
	callevent add_great_item 100
}

{ add_quality_items

	//callevent get_chance_rare 350
	addstoreitem STORENAME blunt_gauntlets_serpant 1 0
	addstoreitem STORENAME mana_demon_blood 1 0

	callevent get_chance_ultra_rare 1
	if GIVE_PRIZE
	addstoreitem STORENAME blunt_gauntlets_demon 1 0
}
