//djinn chest

#include chests/base_treasurechest

{ game_spawn

	callevent tc_add_artifact smallarms_k_fire 20
	callevent tc_add_artifact axes_vaxe 10
}

{ chest_additems

	callevent offer_felewyn_symbol 5

	callevent add_gold 120
	
	addstoreitem STORENAME mana_mpotion 1 0
	addstoreitem STORENAME health_spotion 1 0
	
	callevent add_good_item
	callevent add_good_item
	
	if game.playersnb > 2
	callevent add_great_item
	if game.playersnb > 3
	callevent add_great_item
}