//sekrat chest (requires most of map complete, but not boss)
{
	const EPIC_POTION_LIST "mana_faura;mana_paura;mana_speed;mana_gprotection;mana_immune_cold;mana_immune_fire;mana_immune_poison;mana_demon_blood;mana_regen;mana_leadfoot;mana_immune_lightning;mana_flesheater2"
	const GOOD_POTION_LIST "mana_resist_cold;mana_resist_cold;mana_resist_fire;mana_vampire;mana_prot_spiders;mana_flesheater1"
}

#include chests/base_treasurechest_array

{ chest_additems

	if ( !CHEST_QUALIFY_FOR_QUALITY )
	{
		addstoreitem STORENAME gold_pouch_50 1 0
		callevent add_noob_item

		local N_POTIONS $get_token_amt(GOOD_POTION_LIST)
		subtract N_POTIONS 1
		local RND_POTION $rand(0,N_POTIONS)
		addstoreitem STORENAME $get_token(GOOD_POTION_LIST,RND_POTION) 1 0
	}
}

{ chest_add_quality_items

	addstoreitem STORENAME gold_pouch_500 1 0

	local N_POTIONS $get_token_amt(GOOD_POTION_LIST)
	subtract N_POTIONS 1
	local RND_POTION $rand(0,N_POTIONS)
	addstoreitem STORENAME $get_token(GOOD_POTION_LIST,RND_POTION) 1 0

	local N_POTIONS $get_token_amt(EPIC_POTION_LIST)
	subtract N_POTIONS 1
	local RND_POTION $rand(0,N_POTIONS)
	addstoreitem STORENAME $get_token(EPIC_POTION_LIST,RND_POTION) 1 0

	if game.playersnb > 4

	local N_POTIONS $get_token_amt(GOOD_POTION_LIST)
	subtract N_POTIONS 1
	local RND_POTION $rand(0,N_POTIONS)
	addstoreitem STORENAME $get_token(GOOD_POTION_LIST,RND_POTION) 1 0

	local N_POTIONS $get_token_amt(GOOD_POTION_LIST)
	subtract N_POTIONS 1
	local RND_POTION $rand(0,N_POTIONS)
	addstoreitem STORENAME $get_token(GOOD_POTION_LIST,RND_POTION) 1 0
}