//tunnels
#include chests/base_treasurechest

{ chest_additems

	callevent add_gold 150
	
	callevent add_great_item
	callevent add_noob_item
	callevent add_good_item
	callevent add_great_item
	callevent add_great_item
	if ( $rand(1,20) == 1 ) callevent add_epic_item

	callevent add_great_arrows
	callevent add_epic_arrows
	if ( $rand(1,20) == 1 ) callevent add_epic_arrows
	if ( $rand(1,20) == 1 ) callevent add_epic_arrows
}