#include chests/base_treasurechest

{ game_spawn

	callevent tc_add_artifact polearms_dra 10
}

{ chest_additems

	callevent add_gold $math(multiply,500,game.playersnb)
	
	callevent add_great_item
	callevent add_great_item
	callevent add_great_item
	callevent add_great_item
	callevent add_epic_item
	callevent add_epic_item
	
	if ( $rand(1,20) == 1 ) callevent add_epic_item
	if ( $rand(1,20) == 1 ) callevent add_epic_arrows
	if ( $rand(1,20) == 1 ) callevent add_epic_arrows
	if ( $rand(1,20) == 1 ) callevent add_epic_arrows
	if ( $rand(1,20) == 1 ) callevent add_epic_arrows
	
	if ( $rand(1,15) == 1 ) addstoreitem STORENAME blunt_ms2 1 0
	if ( $rand(1,20) == 1 ) addstoreitem STORENAME blunt_ms3 1 0
	
	if ( $rand(1,10) == 1 ) addstoreitem STORENAME scroll_turn_undead 1 0
	
	if ( $rand(1,20) == 1 ) addstoreitem STORENAME scroll_ice_xolt 1 0
}