#scope server
{
	const CHEST_SELF_ADJ 1

	//small chance of random unique from other maps
	const SPEC_ARTI "shields_f;swords_vb;smallarms_cre;armor_belmont;armor_faura;armor_helm_elyg;armor_helm_gaz2;armor_helm_gray;armor_helm_undead;armor_paura;armor_pheonix55"
}

#include chests/base_treasurechest_array

{ chest_additems
	local L_GOLD_TO_ADD $get(CHEST_USER,scriptvar'PLR_TOTAL_DMG')
	multiply L_GOLD_TO_ADD game.playersnb
	multiply L_GOLD_TO_ADD 10
	dbg fmines_boss gold: L_GOLD_TO_ADD
	callevent add_gold L_GOLD_TO_ADD
}

{ chest_add_quality_items

	//also need chance for unique item based on # of chests found

	local INT_CHEST_LEVELS $int(CHEST_AVG_LEVELS)

	if ( INT_CHEST_LEVELS == 1 )
	{
		callevent add_epic_arrows
	}

	if ( INT_CHEST_LEVELS >= 2 )
	{
		callevent add_epic_arrows
	}

	if ( INT_CHEST_LEVELS >= 3 )
	{
		callevent add_epic_arrows
	}

	if game.time > 300

	//unlikely to be below this level, more likely orcfor_final_easy
	if ( INT_CHEST_LEVELS >= 4 )
	{
		callevent add_epic_item
		callevent add_epic_arrows
	} 

	if ( INT_CHEST_LEVELS >= 5 )
	{
		callevent add_epic_item
		callevent add_epic_item
		callevent add_epic_arrows
		callevent add_epic_arrows
	} 

	if ( INT_CHEST_LEVELS > 5 )
	{
		callevent add_epic_item
		callevent add_epic_arrows
	}

	local L_N_PLAYERS game.playersnb
	add L_N_PLAYERS INT_CHEST_LEVELS

	if ( $rand(1,30) < L_N_PLAYERS ) addstoreitem STORENAME mana_bravery 1 0
	if ( $rand(1,30) < L_N_PLAYERS ) addstoreitem STORENAME mana_paura 1 0
	if ( $rand(1,30) < L_N_PLAYERS ) addstoreitem STORENAME mana_faura 1 0
	if ( $rand(1,30) < L_N_PLAYERS ) addstoreitem STORENAME mana_fbrand 1 0
	if ( $rand(1,30) < L_N_PLAYERS ) addstoreitem STORENAME mana_font 1 0

	callevent find_strongest_player_reset
	if ( CHEST_USER isnot BC_STRONGEST_PLAYER ) exitevent

	if ( game.players > 2 )
	{
		local L_F_CHANCE game.players
		multiply L_F_CHANCE 10
		callevent offer_felewyn_symbol L_F_CHANCE
	}

	if !CHECKED_ARTI
	setvard CHECKED_ARTI 1

	if game.time > 1500

	local L_BONUS 100
	subtract L_BONUS $rand(1,100)
	if L_BONUS <= game.playersnb
	local L_N_ARTIS $get_token_amt(SPEC_ARTI)
	subtract L_N_ARTIS 1
	local L_RND_ARTI $rand(0,L_N_ARTIS)
	addstoreitem STORENAME $get_token(SPEC_ARTI,L_RND_ARTI) 1 0
}
