//ms_snow ice queen chest

//artifact handling
//setvard BC_ARTIFACTS "token;string" //list of artifacts to potentially dish out (one chosen when add_artifact % is called)
//const BC_ARTIFACTS_SINGLE 1 //set to 0 to allow multiple artifacts to distribute, otherwise only one will spawn per chest
//const BC_ARTIFACTS_STRONGEST 1 //reserve artifact for strongest player
//const BC_ARTIFACTS_ONE_OF_EACH 1 //give a maximum of one of each type of artifact

{
	setvard BC_ARTIFACTS "bows_frost;armor_helm_gaz2"
}

#include chests/base_treasurechest_array

{ chest_additems

	callevent add_gold_by_hp 546
   
	local N_ARROWS 120
	//addstoreitem STORENAME ITEMNAME QUANITY SELL_PRICE_ADJUSTMENT(integer%) BUYPRICE_ADJUSTMENT(multiplier%) #IN_BUNDLE
   	addstoreitem STORENAME proj_arrow_frost N_ARROWS 0 0 60
   	addstoreitem STORENAME mana_resist_cold	1 0
	
	if ( $rand(0,1) ) addstoreitem STORENAME mana_immune_cold 1 0
	
   	if ( $rand(0,1) ) addstoreitem STORENAME swords_liceblade 1 0

   	addstoreitem STORENAME mana_forget 1 0
}

{ chest_add_quality_items

	callevent add_artifact 10

	if ( $rand(1,100) <= 2 ) addstoreitem STORENAME scroll2_ice_blast 1 0
	
	local SCROLL_TOME $rand(1,2)
	if ( SCROLL_TOME == 1 )	addstoreitem STORENAME scroll_ice_shield 1 0
	if ( SCROLL_TOME == 2 )	addstoreitem STORENAME scroll2_ice_shield 1 0

	if ( $rand(1,100) <= 10 )
	{
		local SCROLL_TOME $rand(1,2)
		if ( SCROLL_TOME == 1 )	addstoreitem STORENAME scroll_blizzard 1 0
		if ( SCROLL_TOME == 2 )	addstoreitem STORENAME scroll2_blizzard 1 0
	}
}
