//ms_snow ice queen chest
{
	const GM_VERIFY 1
}

{
   eventname treasure_spawn

   //old		100
   setvar	STORENAME ice_main
	if ( $lcase(game.map.name) isnot ms_snow ) deleteent ent_me
}

#include items/base_treasurechest

{
   eventname chest_additems

	callevent add_gold 100 2000 100 //add gold pouches to chest
   
	callevent get_players 600
	local N_ARROWS 120
	multiply N_ARROWS TC_NPLAYERS
	//addstoreitem STORENAME ITEMNAME QUANITY SELL_PRICE_ADJUSTMENT(integer%) BUYPRICE_ADJUSTMENT(multiplier%) #IN_BUNDLE
   	addstoreitem STORENAME health_spotion TC_NPLAYERS 0
   	addstoreitem STORENAME mana_mpotion	TC_NPLAYERS 0
   	addstoreitem STORENAME proj_arrow_frost N_ARROWS 0 0 60
   	addstoreitem STORENAME mana_resist_cold	TC_NPLAYERS_HALF 0
   	addstoreitem STORENAME mana_immune_cold	TC_NPLAYERS_QUART 0
   	addstoreitem STORENAME swords_liceblade	TC_NPLAYERS_HALF 0

   	addstoreitem STORENAME mana_forget 1 0

	if ( $rand(1,100) <= 20 )
	{
		if game.playersnb > 2
		addstoreitem STORENAME shields_rune 1 0
	}

}

{ add_quality_items

	if ( $get(PARAM1,maxhp) < 600 ) callevent 0.1 reset_quality //dont rip peeps off just cuz some nub opened the chest

	if $get(PARAM1,maxhp) > 600
	callevent get_players 600

   	if ( TC_NPLAYERS > 3 )
	{
		setvard GAVE_GIB 1
		addstoreitem STORENAME swords_giceblade	1 0
	}

   	if ( !GAVE_GIB )
	{
		callevent get_chance_ultra_rare 500
		if GIVE_PRIZE
		addstoreitem STORENAME swords_giceblade	1 0
	}
	callevent get_chance_ultra_rare 500
	if ( GIVE_PRIZE ) addstoreitem STORENAME scroll2_ice_blast 1 0

	callevent get_chance_rare 500
	if ( GIVE_PRIZE )
	{
		local SCROLL_TOME $rand(1,2)
		if ( SCROLL_TOME == 1 )	addstoreitem STORENAME scroll_ice_shield 1 0
		if ( SCROLL_TOME == 2 )	addstoreitem STORENAME scroll2_ice_shield 1 0
	}

	callevent get_chance_rare 500
	if ( GIVE_PRIZE )
	{
		local SCROLL_TOME $rand(1,2)
		if ( SCROLL_TOME == 1 )	addstoreitem STORENAME scroll_ice_wall 1 0
		if ( SCROLL_TOME == 2 )	addstoreitem STORENAME scroll2_ice_wall 1 0
	}

	callevent get_chance_rare 500
	if ( GIVE_PRIZE )
	{
		local SCROLL_TOME $rand(1,2)
		if ( SCROLL_TOME == 1 )	addstoreitem STORENAME scroll_blizzard 1 0
		if ( SCROLL_TOME == 2 )	addstoreitem STORENAME scroll2_blizzard 1 0
	}

	callevent get_chance_ultra_rare 500
	if ( GIVE_PRIZE )
	{
		addstoreitem STORENAME armor_helm_gaz1 1 0 //move to badlands
	}

	callevent get_chance_ultra_rare 500
	if ( GIVE_PRIZE )
	{
		addstoreitem STORENAME armor_helm_gaz2 1 0
	}

	callevent get_chance_ultra_rare 500
	if ( GIVE_PRIZE )
	{
		if TC_NPLAYERS > 3
		addstoreitem STORENAME polearms_ti 1 0
	}

	//will move to badlands
   if ( TC_NPLAYERS > 4 )
   {
		addstoreitem  STORENAME     scroll_volcano	1   	   0
   }

   if ( TC_NPLAYERS > 6 )
   {
		addstoreitem  STORENAME     scroll2_volcano	1   	   0
   }
}

{ reset_quality
	setvard ADDED_QUALITY 0
}