#include chests/base_treasurechest_array

{ chest_additems
	callevent add_gold_by_hp 200
}

{ chest_add_quality_items
	callevent add_great_item
	if ( $rand(1,10) <= game.playersnb ) callevent add_epic_item
	if ( $rand(1,10) <= game.playersnb ) callevent add_epic_arrows
	addstoreitem STORENAME item_crystal_reloc 1 0

	if ( $rand(1,30) <= game.playersnb ) addstoreitem STORENAME blunt_fs 1 0
	if ( $rand(1,30) <= game.playersnb ) addstoreitem STORENAME mana_fbrand 1 0

	addstoreitem STORENAME polearms_hal 1 0
	if ( $rand(1,30) <= game.playersnb ) addstoreitem STORENAME mana_flesheater2 1 0
}