#include chests/base_treasurechest

{ chest_additems
	callevent add_gold 400

	callevent add_great_item
	
	if ( $rand(1,3) == 1 ) callevent add_epic_item
	if ( $rand(1,3) == 1 ) callevent add_good_item
	if ( $rand(1,3) == 1 ) callevent add_epic_arrows
	if ( $rand(1,3) == 1 ) callevent add_epic_arrows
	addstoreitem STORENAME item_crystal_reloc 1 0

	if ( $rand(1,20) == 1 ) addstoreitem STORENAME mana_fbrand 1 0

	addstoreitem STORENAME polearms_nag 1 0
}