{
	const GOLD_AMT $rand(250,1000)
	const BAG_NO_DELETE 1
	const BAG_MULTI_OPEN 1
}

#include chests/bag_o_gold_base

{ game_spawn
	callevent 0.1 secondary_reward
}

{ secondary_reward
	if ( $rand(1,15) <= game.playersnb )
	{
		addstoreitem STORENAME scroll_turn_undead 1 0
		addstoreitem STORENAME item_crystal_reloc 1 0		
	}
	else
	{
		addstoreitem STORENAME scroll2_turn_undead 1 0
	}

	addstoreitem STORENAME item_crystal_return 1 0
}