//Goblin chest
#include chests/base_treasurechest

{ chest_additems

	callevent add_gold 100
	
	if ( $rand(1,2) == 1 ) callevent add_noob_item
	if ( $rand(1,2) == 1 ) callevent add_noob_item
	if ( $rand(1,2) == 1 ) callevent add_good_item
	if ( $rand(1,2) == 1 ) callevent add_good_item
	if ( $rand(1,2) == 1 ) callevent add_good_item

	local RND_ARROW $rand(1,4)
	if ( RND_ARROW == 1 ) addstoreitem STORENAME proj_arrow_broadhead 60 0 0 60
	if ( RND_ARROW == 2 ) addstoreitem STORENAME proj_arrow_fire 60 0 0 60
	if ( RND_ARROW == 3 ) addstoreitem STORENAME proj_arrow_jagged 60 0 0 60
	if ( RND_ARROW == 4 ) addstoreitem STORENAME proj_arrow_poison 60 0 0 60
}
