//Creates one random epic item for each player with qualifying HP, plus some pots and gold
{
	const MAX_GOLD_AMT 1000
}

#include chests/base_treasurechest_array

{ chest_additems

	callevent add_gold_by_hp MAX_GOLD_AMT
	callevent add_epic_item 100 500
	callevent add_epic_item 100 500
	callevent add_great_item 100 200
	callevent add_great_item 100 200
	callevent add_good_item 100 100

	if ( $rand(1,20) == 20 ) addstoreitem STORENAME armor_paura 1 0
}
