//final boss chest

{ treasure_spawn

	name Lodagond Bonus Chest 1
	setvar	STORENAME lodagond_bonus1
}

#include items/base_treasurechest

{ chest_additems

	callevent add_gold 55 1000 50
	callevent get_players 500

	addstoreitem  STORENAME health_spotion TC_NPLAYERS 0
	addstoreitem  STORENAME mana_mpotion TC_NPLAYERS 0

	callevent add_epic_item
	callevent add_great_item

	if TC_NPLAYERS > 1

	callevent add_epic_item

	if TC_NPLAYERS > 3
	callevent add_epic_item
	
	if TC_NPLAYERS > 4
	callevent add_great_item
	callevent add_great_item
	callevent add_epic_item
	addstoreitem  STORENAME mana_speed TC_NPLAYERS 0
}