{
	const BLACK_CHEST_LOC $relpos(0,0,128) 
	const BC_ITEM_LIST "smallarms_frozentongueonflagpole;bows_thornbow;scroll2_lightning_chain;blunt_mithral;mana_leadfoot;armor_belmont;armor_helm_gaz2;swords_frostblade55;"
	const BC_ITEM_CHANCES "15;10;25;10;25;10;15;5" //(per player)
	const BC_REQ_PLAYERS "1;2;1;2;1;2;1;1;"
	const BC_ITEM_NAMES "Litch Tongue;Thornbow;Chain Lightning Scroll;Bludgeon Hammer;Stability Potion;Bravery Armor;Helm of Ice Reistance;Hoarfrost Shard;"
	const IBC_MIN_HP 500
}

{ treasure_spawn

	name Lodagond Chest 4
	setvar	STORENAME lodagond4
	callevent 0.1 ver_lodagond_chest
}

#include items/base_treasurechest

{ ver_lodagond_chest


	local L_VERI_RESULT $get(GAME_MASTER,scriptvar,GM_LODAGOND)

	if ( G_DEVELOPER_MODE ) local L_VERI_RESULT 4

	if ( L_VERI_RESULT != 4 )
	{
		deleteent ent_me
	}
	else
	{
		callevent 1.0 spawn_black_chest
	}
}

{ chest_additems

	callevent add_gold 55 1000 50
	callevent get_players 600
	addstoreitem  STORENAME health_spotion 20 0
	addstoreitem  STORENAME mana_mpotion 20 0
	addstoreitem  STORENAME item_crystal_reloc 8 0

	addstoreitem  STORENAME mana_resist_cold 1 0
	addstoreitem  STORENAME mana_resist_fire 1 0
	addstoreitem  STORENAME mana_gprotection 2 0
	addstoreitem  STORENAME mana_protection TC_NPLAYERS_QUART 0
	addstoreitem  STORENAME mana_speed TC_NPLAYERS_QUART 0
	addstoreitem  STORENAME mana_demon_blood TC_NPLAYERS_QUART 0
}