//Sorc Chest
{
	//const BLACK_CHEST_LOC $relpos(0,0,128) 
	//const BC_ITEM_LIST "bows_thornbow;armor_helm_gaz2;swords_frostblade55;"
	//const BC_ITEM_CHANCES "5;8;15;5;" //(per player)
	//const BC_REQ_PLAYERS "2;2;1;1;"
	//const BC_ITEM_NAMES "a Thornbow;a Helm of Ice Reistance;a Hoarfrost Shard"
}

{ treasure_spawn

	name Lodagond Chest 2
	setvar STORENAME lodagond2
	callevent 0.1 ver_lodagond_chest
}

#include items/base_treasurechest

{ ver_lodagond_chest
	if ( $get(GAME_MASTER,scriptvar,GM_LODAGOND) != 2 )
	{
		deleteent ent_me
	}
	else
	{
		//callevent 1.0 spawn_black_chest
	}
}

{ chest_additems

	callevent add_gold 55 1000 100
	callevent get_players 600

	if ( TC_NPLAYERS > 1 )
	{
		local SCROLL_TOME $rand(1,2)
		if ( SCROLL_TOME == 1 ) addstoreitem  STORENAME     scroll_ice_shield 		1       0
		if ( SCROLL_TOME == 2 ) addstoreitem  STORENAME     scroll2_ice_shield 		1       0
	}

	addstoreitem  STORENAME health_spotion TC_NPLAYERS 	0
	addstoreitem  STORENAME mana_mpotion TC_NPLAYERS 	0
	addstoreitem  STORENAME item_crystal_reloc TC_NPLAYERS_QUART 0

	addstoreitem  STORENAME mana_resist_cold 1 0
	if ( TC_NPLAYERS > 2 ) addstoreitem  STORENAME mana_resist_cold 1 0

	if ( TC_NPLAYERS > 3 ) callevent add_good_item
	if ( TC_NPLAYERS > 6 ) callevent add_good_item
}

{ add_quality_items

	if ( $get(PARAM1,maxhp) < 600 ) callevent 0.1 reset_quality
	if $get(PARAM1,maxhp) >= 600

	if ( TC_NPLAYERS > 1 )
	{
		local SCROLL_TOME $rand(1,2)
		if ( SCROLL_TOME == 1 ) addstoreitem  STORENAME     scroll_lightning_storm 		1       0
		if ( SCROLL_TOME == 2 ) addstoreitem  STORENAME     scroll2_lightning_storm 		1       0
	}

	if ( TC_NPLAYERS > 3 )
	{
		callevent add_epic_item
		addstoreitem  STORENAME mana_immune_cold 1 0
	}
	if ( TC_NPLAYERS > 6 ) callevent add_epic_item

	//artifacted:
	//callevent get_chance 1 3 50 600 //callevent get_chance <single_player%> <%chance_per_player> [max_chance] [hp_req] //returns GIVE_PRIZE (1|0) and TC_CHANCE (Total %Chance)
	//if ( GIVE_PRIZE ) addstoreitem STORENAME armor_belmont 1 0

	//callevent get_chance 1 5 50 600 //callevent get_chance <single_player%> <%chance_per_player> [max_chance] [hp_req] //returns GIVE_PRIZE (1|0) and TC_CHANCE (Total %Chance)
	//if ( GIVE_PRIZE ) addstoreitem STORENAME bows_thornbow 1 0

	//callevent get_chance_ultra_rare 600
	//if ( GIVE_PRIZE ) addstoreitem STORENAME armor_helm_gaz2 1 0

	//callevent get_chance 1 5 25 600 //callevent get_chance <single_player%> <%chance_per_player> [max_chance] [hp_req] //returns GIVE_PRIZE (1|0) and TC_CHANCE (Total %Chance)
	//if ( GIVE_PRIZE ) addstoreitem STORENAME swords_frostblade55 1 0

	if ( TC_NPLAYERS > 4 ) addstoreitem STORENAME mana_demon_blood 1 0
}