//final boss chest

{ treasure_spawn

	setvar	STORENAME lostcaverns3
}

#include items/base_treasurechest

{ chest_additems

	callevent offer_felewyn_symbol 50

	callevent add_gold 55 1000 50
	callevent get_players 300

	callevent add_good_item
	callevent add_good_item
	callevent add_great_item
	
	callevent get_chance_rare 300
	if ( GIVE_PRIZE ) callevent add_epic_item

	if TC_NPLAYERS > 1

	callevent add_great_item
	callevent add_epic_item

	if TC_NPLAYERS > 3
	callevent add_great_item
	
	if TC_NPLAYERS > 4
	callevent add_great_item
	callevent add_great_item
	callevent add_epic_item
}
