#include chests/base_treasurechest_array

{ chest_additems
	callevent add_noob_item
	callevent add_noob_item
	callevent add_good_item
	callevent add_good_item
	callevent add_good_item
	callevent add_good_item
	if ( game.playersnb > 2 )	callevent add_great_item
	if ( game.playersnb > 4 ) callevent add_great_item
	callevent add_gold 200
	addstoreitem STORENAME proj_arrow_blunt 15 0 0 15
	addstoreitem STORENAME proj_arrow_blunt 15 0 0 15
	addstoreitem STORENAME proj_arrow_blunt 15 0 0 15
}
