#include chests/base_treasurechest_array

{ game_spawn
	setvard GAVE_BONUS1 0
	setvard GAVE_BONUS2 0
	setvard BC_FARTIFACTS "shields_f;swords_vb;swords_gb"
}

{ treasure_spawn
	name "Jaminporlant's Generosity (multi)"
	setprop ent_me scale 2.0
}

{ chest_add_quality_items

	if ( !DID_FIRST_OPEN )
	{
		setvard DID_FIRST_OPEN 1
		callexternal $get_by_name(gdragon_img) ext_exit_sequence
	}

	callevent add_gold 5000
	callevent add_epic_item 100 500
	callevent add_epic_item 100 500
	addstoreitem STORENAME mana_resist_fire 1 0
	if ( $rand(1,8) <= game.playersnb ) addstoreitem STORENAME mana_immune_fire 1 0
	if ( $rand(1,8) <= game.playersnb ) callevent add_epic_item 100 300
	if ( $rand(1,24) <= game.playersnb )
	{
		if !GAVE_BONUS1
		if $get(CHEST_USER,scriptvar,'PLR_TOTAL_DMG') > 1
		setvard GAVE_BONUS1 1
		addstoreitem STORENAME armor_faura 1 0 //%%check name
	}
	if ( $rand(1,24) <= game.playersnb )
	{
		if !GAVE_BONUS2
		if $get(CHEST_USER,scriptvar,'PLR_TOTAL_DMG') > 1
		setvard GAVE_BONUS2 1
		addstoreitem STORENAME item_charm_w2 1 0
	}
	if ( $rand(1,24) <= game.playersnb )
	{
		if $get(CHEST_USER,scriptvar,'PLR_TOTAL_DMG') > 1
		addstoreitem STORENAME $get_random_token('smallarms_cre;smallarms_cre;smallarms_crel;smallarms_cref') 1 0
	}
	
	if ( game.players.totalhp > 4000 )
	{
		callevent add_epic_item 100 300
		callevent add_epic_item 100 300
	}
	callevent add_great_item 100 200
	callevent add_great_item 100 200
	callevent add_great_item 100 200

	if ( !FOUND_STRONGEST )
	{
		callevent find_strongest_player
		setvard FOUND_STRONGEST 1
		local SHOW_STRONGEST 0
		if ( G_DEVELOPER_MODE == 1 ) local SHOW_STRONGEST 1
		if ( game.playersnb > 1 ) local SHOW_STRONGEST 1
		if SHOW_STRONGEST
		local OUT_STR $get(ent_me,name)
		strconc OUT_STR " finds " $get(BC_STRONGEST_PLAYER,name) " to be the most worthy player."
		infomsg all "STRONGEST PLAYER" OUT_STR
	}

	if CHEST_USER equals BC_STRONGEST_PLAYER

	callevent add_epic_item 100
	callevent add_epic_item 100

	if !G_GAVE_ARTI1
	if $rand(1,12) <= game.playersnb
	callevent add_artifact 100
	setvarg G_GAVE_ARTI1 1
}
