{
	const CHEST_SELF_ADJ 1
}

#include chests/base_treasurechest_array
#include chests/orcfor_base

{ chest_additems

	if ( !CHEST_QUALIFY_FOR_QUALITY )
	{
		addstoreitem STORENAME gold_pouch_50 1 0
		callevent add_noob_item
	}
}

{ chest_add_quality_items

	addstoreitem STORENAME gold_pouch_100 $int(CHEST_AVG_LEVELS) 0
	if ( G_GAVE_ARTI1 > 1 ) callevent add_epic_item

	//main thing with this chest is just an extra shot at the uniques
}

{ game_playerused
	if !SET_TRAP
	setvard SET_TRAP 1
	local MSG_TITLE $get(PARAM1,name)
	stradd MSG_TITLE " has triggered a trap!"
	infomsg all MSG_TITLE "Oh noes!"
	usetrigger spawn_cave_trap
}