#include chests/orcfor_base

{ chest_additems

	callevent add_gold $math(multiply,500,G_GAVE_ARTI1)

	if ( G_GAVE_ARTI1 == 1 )
	{
		callevent add_great_item
		callevent add_great_item
		callevent add_great_arrows
		callevent add_great_arrows
	}

	if ( G_GAVE_ARTI1 == 2 )
	{
		callevent add_great_item
		callevent add_epic_item
		callevent add_great_arrows
		callevent add_great_arrows
	}

	if ( G_GAVE_ARTI1 == 3 )
	{
		callevent add_great_item
		callevent add_epic_item
		callevent add_great_arrows
		callevent add_epic_arrows
	} 

	//unlike to get here - more like to see orcfor_final_hard
	if ( G_GAVE_ARTI1 == 4 )
	{
		callevent add_epic_item
		callevent add_epic_item
		callevent add_great_arrows
		callevent add_epic_arrows
	} 

	if ( G_GAVE_ARTI1 >= 5 )
	{
		callevent add_epic_item
		callevent add_epic_item
		callevent add_epic_item
		callevent add_epic_arrows
		callevent add_epic_arrows
	} 
}
