{

}

#include chests/base_treasurechest_array

{ verify_chest
	if game.serverside
	setvard QUICK_CHEST_LEVEL game.players.totalhp
	divide QUICK_CHEST_LEVEL 1000
	setvard QUICK_CHEST_LEVEL $int(QUICK_CHEST_LEVEL)

	name a|Treasure Chest I
	if ( QUICK_CHEST_LEVEL >= 2 ) name a|Treasure Chest II
	if ( QUICK_CHEST_LEVEL >= 3 ) name a|Treasure Chest III
	if ( QUICK_CHEST_LEVEL >= 4 ) name a|Treasure Chest IV
	if ( QUICK_CHEST_LEVEL >= 5 ) name a|Treasure Chest V
	if ( QUICK_CHEST_LEVEL >= 6 ) name a|Treasure Chest VI
}

{ chest_additems

	callevent add_gold_by_hp 500
}

{ chest_add_quality_items

	local N_PLAYERS game.playersnb

	//tier 1
	if ( QUICK_CHEST_LEVEL < 2 )
	{
		callevent add_epic_arrows
	}

	//tier 2
	if ( QUICK_CHEST_LEVEL >= 2 )
	{
		callevent add_epic_arrows
		callevent add_epic_arrows
		if QUICK_CHEST_LEVEL < 3
	}

	//tier 3
	if ( QUICK_CHEST_LEVEL >= 3 )
	{
		callevent add_epic_arrows
		callevent add_epic_item
		addstoreitem STORENAME mana_resist_cold 1 0
		if QUICK_CHEST_LEVEL < 4
		if ( $rand(1,25) < N_PLAYERS ) addstoreitem STORENAME mana_flesheater1 1 0
		if ( $rand(1,25) < N_PLAYERS ) addstoreitem STORENAME mana_immune_cold 1 0
	}

	//tier 4
	if ( QUICK_CHEST_LEVEL >= 4 )
	{
		callevent add_epic_item
		if QUICK_CHEST_LEVEL < 5
		if ( $rand(1,15) < N_PLAYERS ) addstoreitem STORENAME mana_flesheater2 1 0
		if ( $rand(1,25) < N_PLAYERS ) addstoreitem STORENAME bows_telf1 1 0
		if ( $rand(1,15) < N_PLAYERS ) addstoreitem STORENAME blunt_fs 1 0
		if ( $rand(1,15) < N_PLAYERS ) addstoreitem STORENAME mana_fbrand 1 0
		if ( $rand(1,15) < N_PLAYERS ) addstoreitem STORENAME mana_immune_cold 1 0
		if ( $rand(1,15) < N_PLAYERS ) addstoreitem STORENAME smallarms_k_fire 1 0
		if ( $rand(1,15) < N_PLAYERS ) addstoreitem STORENAME item_charm_w3 1 0
	}

	//tier 5
	if ( QUICK_CHEST_LEVEL >= 5 )
	{
		callevent add_epic_item
		callevent add_epic_arrows
		addstoreitem STORENAME mana_flesheater2 1 0
		if ( $rand(1,8) < N_PLAYERS ) addstoreitem STORENAME bows_telf1 1 0
		if ( $rand(1,8) < N_PLAYERS ) addstoreitem STORENAME blunt_fs 1 0
		if ( $rand(1,4) < N_PLAYERS ) addstoreitem STORENAME mana_fbrand 1 0
		if ( $rand(1,4) < N_PLAYERS ) addstoreitem STORENAME mana_faura 1 0
		if ( $rand(1,4) < N_PLAYERS ) addstoreitem STORENAME mana_immune_cold 1 0
		if ( $rand(1,8) < N_PLAYERS ) addstoreitem STORENAME item_charm_w2 1 0
		if ( $rand(1,8) < N_PLAYERS ) addstoreitem STORENAME mana_immune_lightning 1 0
		if ( $rand(1,8) < N_PLAYERS ) addstoreitem STORENAME smallarms_k_fire 1 0
	}

}

