{
	const SOME_POTS "mana_bravery;mana_paura;mana_faura;mana_fbrand;mana_font;mana_immune_cold;mana_resist_cold"
}

#include chests/base_treasurechest_array

{ verify_chest
	if game.serverside
	setvard QUICK_CHEST_LEVEL game.players.totalhp
	divide QUICK_CHEST_LEVEL 1000
	setvard QUICK_CHEST_LEVEL $int(QUICK_CHEST_LEVEL)
	add QUICK_CHEST_LEVEL 1
	callevent find_strongest_player

	name a|Treasure Chest
	if ( QUICK_CHEST_LEVEL >= 2 ) name a|Treasure Chest I
	if ( QUICK_CHEST_LEVEL >= 3 ) name a|Treasure Chest II
	if ( QUICK_CHEST_LEVEL >= 4 ) name a|Treasure Chest III
	if ( QUICK_CHEST_LEVEL >= 5 ) name a|Treasure Chest IV
	if ( QUICK_CHEST_LEVEL >= 6 ) name a|Treasure Chest V
}

{ chest_additems

	callevent add_gold_by_hp 500
	addstoreitem STORENAME mana_immune_cold 1 0
}

{ chest_add_quality_items

	local N_PLAYERS game.playersnb

	addstoreitem STORENAME mana_flesheater2 1 0
	addstoreitem STORENAME item_gwond 1 0
	addstoreitem STORENAME item_charm_w3 1 0
	addstoreitem STORENAME item_eh 1 0

	callevent offer_felewyn_symbol 100%

	callevent add_epic_item

	local RND_CHANCE 150
	divide RND_CHANCE QUICK_CHEST_LEVEL
	divide RND_CHANCE QUICK_CHEST_LEVEL
	local RND_HACK RND_CHANCE
	subtract RND_HACK $randf(1,RND_CHANCE)
	if ( RND_HACK <= N_PLAYERS ) addstoreitem STORENAME blunt_gauntlets_demon 1 0

	local RND_CHANCE 150
	divide RND_CHANCE QUICK_CHEST_LEVEL
	divide RND_CHANCE QUICK_CHEST_LEVEL
	local RND_HACK RND_CHANCE
	subtract RND_HACK $randf(1,RND_CHANCE)
	if ( RND_HACK <= N_PLAYERS )
	{
		local N_POTS $get_token_amt(SOME_POTS)
		subtract N_POTS 1
		local RND_POT_IDX $rand(SOME_POTS,N_POTS)
		local RND_POT $get_token(SOME_POTS,RND_POT_IDX)
		addstoreitem STORENAME RND_POT 1 0
	}

	local RND_HACK RND_CHANCE
	subtract RND_HACK $randf(1,RND_CHANCE)
	if ( RND_HACK <= N_PLAYERS )
	{
		local N_POTS $get_token_amt(SOME_POTS)
		subtract N_POTS 1
		local RND_POT_IDX $rand(SOME_POTS,N_POTS)
		local RND_POT $get_token(SOME_POTS,RND_POT_IDX)
		addstoreitem STORENAME RND_POT 1 0
	}
	
	if CHEST_USER equals BC_STRONGEST_PLAYER
	local RND_HACK 30
	subtract RND_HACK $rand(1,30)
	if ( RND_HACK <= N_PLAYERS )
	{
		if !G_GAVE_TOME1
		setvarg G_GAVE_TOME1 1
		addstoreitem STORENAME blunt_staff_f 1 0
	}

	//tier 2
	if ( QUICK_CHEST_LEVEL >= 2 )
	{
		callevent add_epic_item
		callevent add_epic_item
	}

	//tier 3
	if ( QUICK_CHEST_LEVEL >= 3 )
	{
		callevent add_epic_item
		if ( $rand(1,15) < N_PLAYERS ) addstoreitem STORENAME polearms_nag 1 0
		if QUICK_CHEST_LEVEL < 4
		addstoreitem STORENAME armor_fireliz 1 0
		addstoreitem STORENAME mana_flesheater2 1 0
	}

	//tier 4
	if ( QUICK_CHEST_LEVEL >= 4 )
	{
		callevent add_epic_item
		if ( $rand(1,10) < N_PLAYERS ) addstoreitem STORENAME mana_bravery 1 0
		if ( $rand(1,15) < N_PLAYERS ) addstoreitem STORENAME armor_fireliz 1 0
		if ( $rand(1,30) < N_PLAYERS ) addstoreitem STORENAME swords_novablade12 1 0
		if QUICK_CHEST_LEVEL < 5
		if ( $rand(1,25) < N_PLAYERS ) addstoreitem STORENAME bows_firebird 1 0
		if ( $rand(1,15) < N_PLAYERS ) addstoreitem STORENAME blunt_fs 1 0
		if ( $rand(1,15) < N_PLAYERS ) addstoreitem STORENAME mana_fbrand 1 0
		if ( $rand(1,15) < N_PLAYERS ) addstoreitem STORENAME item_charm_w3 1 0
		if ( $rand(1,50) < N_PLAYERS ) addstoreitem STORENAME axes_dragon 1 0
	}

	//tier 5
	if ( QUICK_CHEST_LEVEL >= 5 )
	{
		callevent add_epic_item
		callevent add_epic_arrows 60
		addstoreitem STORENAME mana_flesheater2 1 0
		if ( $rand(1,8) < N_PLAYERS ) addstoreitem STORENAME bows_firebird 1 0
		if ( $rand(1,8) < N_PLAYERS ) addstoreitem STORENAME blunt_fs 1 0
		if ( $rand(1,4) < N_PLAYERS ) addstoreitem STORENAME mana_fbrand 1 0
		if ( $rand(1,4) < N_PLAYERS ) addstoreitem STORENAME mana_faura 1 0
		if ( $rand(1,16) < N_PLAYERS ) addstoreitem STORENAME axes_dragon 1 0
		if ( $rand(1,8) < N_PLAYERS ) addstoreitem STORENAME mana_bravery 1 0
		if ( $rand(1,8) < N_PLAYERS ) addstoreitem STORENAME mana_immune_lightning 1 0
	}
}
