#include chests/base_treasurechest

{ game_spawn
	name a|Treasure Chest
}

{ chest_additems

	local L_GOLD game.players.totalhp
	if ( L_GOLD < 2000 ) local L_GOLD 2000
	callevent add_gold L_GOLD

	callevent add_epic_item

	if ( $rand(1,20) == 1 ) addstoreitem STORENAME blunt_darkmaul 1 0

	if ( $rand(1,20) == 1 ) addstoreitem STORENAME blunt_gauntlets_fire 1 0

	if ( $rand(1,15) == 1 ) callevent add_epic_item

	if ( $rand(1,10) == 1 ) callevent add_epic_item

	if ( $rand(1,5) == 1 ) callevent add_epic_item
	
	addstoreitem STORENAME mana_resist_cold 1 0
	
	if ( $rand(1,25) == 1 ) addstoreitem STORENAME blunt_fs 1 0

	if ( $rand(1,20) == 1 ) callevent add_epic_item
	
	if ( $rand(1,15) == 1 ) addstoreitem STORENAME mana_fbrand 1 0
	
	if ( $rand(1,20) == 1 ) callevent add_epic_item
	
	if ( $rand(1,4) == 1 ) addstoreitem STORENAME mana_fbrand 1 0
	
	if ( $rand(1,4) == 1 ) addstoreitem STORENAME mana_faura 1 0
}

