#include chests/base_treasurechest_array

{ verify_chest
	callevent find_strongest_player
}

{ chest_add_quality_items

	local WEIGHT_PLAYERS game.playersnb
	add WEIGHT_PLAYERS 1
	multiply WEIGHT_PLAYERS WEIGHT_PLAYERS
	
	//WEIGHT_PLAYERS = playersnb^2
	//CHANCE = WEIGHT_PLAYERS/RND_HACK

	callevent add_epic_item
	callevent add_epic_item

	local RND_HACK 40
	subtract RND_HACK $rand(1,RND_HACK)
	if ( RND_HACK <= WEIGHT_PLAYERS )
	{
		addstoreitem STORENAME mana_sb 1 0
	}

	local RND_HACK 40
	subtract RND_HACK $rand(1,RND_HACK)
	if ( RND_HACK <= WEIGHT_PLAYERS )
	{
		addstoreitem STORENAME swords_novablade12 1 0
	}

	if CHEST_USER equals BC_STRONGEST_PLAYER

	if ( !G_GAVE_TOME1 )
	{
		local RND_HACK 65
		subtract RND_HACK $rand(1,RND_HACK)
		if RND_HACK <= WEIGHT_PLAYERS
		addstoreitem STORENAME scroll2_summon_bear1 1 0
		setvarg G_GAVE_TOME1 1
		callevent find_strongest_player
	}


	if ( !G_GAVE_TOME2 )
	{
		local RND_HACK 65
		subtract RND_HACK $rand(1,RND_HACK)
		if RND_HACK <= WEIGHT_PLAYERS
		addstoreitem STORENAME blunt_staff_a 1 0
		setvarg G_GAVE_TOME2 1
	}
}