#scope server

#include chests/base_treasurechest

{ chest_additems
	local L_GOLD_TO_ADD $get(CHEST_USER,scriptvar,'PLR_TOTAL_DMG')
	multiply L_GOLD_TO_ADD game.playersnb
	multiply L_GOLD_TO_ADD 10
	callevent add_gold $int(L_GOLD_TO_ADD)

	addstoreitem STORENAME proj_bolt_poison 25 0 0 25

	callevent add_great_item
	callevent add_epic_item
	callevent add_great_arrows

	if ( $rand(1,8) == 1 ) callevent add_epic_arrows
	if ( $rand(1,8) == 1 ) callevent add_epic_arrows
	if ( $rand(1,8) == 1 ) callevent add_epic_arrows
	if ( $rand(1,8) == 1 ) callevent add_epic_item

	if ( $rand(1,25) == 1 ) addstoreitem STORENAME mana_bravery 1 0
	if ( $rand(1,25) == 1 ) addstoreitem STORENAME mana_paura 1 0
	if ( $rand(1,25) == 1 ) addstoreitem STORENAME mana_faura 1 0
	if ( $rand(1,25) == 1 ) addstoreitem STORENAME mana_fbrand 1 0
	if ( $rand(1,25) == 1 ) addstoreitem STORENAME mana_font 1 0

	addstoreitem STORENAME proj_bolt_poison 25 0 0 25
}
