#scope server
{
	const ANIM_IDLE base
	const ANIM_CLOSE base
	const ANIM_OPEN base

	const SOUND_OPEN debris/flesh5.wav
}

#include chests/base_treasurechest

{ game_spawn
	name "an|Abyssal Nest"
	setmodel tiod/ornest.mdl
	setprop ent_me scale 3.0
	width 96
	height 48
	
	callevent tc_add_artifact polearms_sl 5
	callevent tc_add_artifact axes_c 5
}

{ chest_additems
	local L_GOLD_TO_ADD $get(CHEST_USER,scriptvar,'PLR_TOTAL_DMG')
	multiply L_GOLD_TO_ADD game.playersnb
	multiply L_GOLD_TO_ADD 10
	callevent add_gold $int(L_GOLD_TO_ADD)

	addstoreitem STORENAME proj_bolt_poison 25 0 0 25

	callevent add_great_item
	callevent add_epic_item
	callevent add_great_arrows
	callevent add_epic_arrows

	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_great_arrows
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows

	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows

	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows

	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows

	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_item
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows
	if ( $rand(1,10) == 1 ) callevent add_epic_arrows

	if ( $rand(1,30) == 1 ) addstoreitem STORENAME mana_paura 1 0
	if ( $rand(1,30) == 1 ) addstoreitem STORENAME mana_faura 1 0
	if ( $rand(1,30) == 1 ) addstoreitem STORENAME mana_fbrand 1 0
	if ( $rand(1,30) == 1 ) addstoreitem STORENAME mana_font 1 0

	if ( $rand(1,5) == 1 )  addstoreitem STORENAME proj_bolt_poison 75 0 0 25
	
	callevent offer_felewyn_symbol 20
}
