//This chest should be deleted before port
//Using to test items

{
   eventname treasure_spawn

   gold		0
   setvar	STORENAME testchest
}

#include items/base_treasurechest

{
   eventname chest_additems
   
   //           |Store name|  	|Item name| 	|Quant|	|cost|	|0?|	|Stack?|
   addstoreitem	STORENAME 	scroll_fire_ball	1      0
   addstoreitem	STORENAME 	scroll_poison	1      0
   addstoreitem	STORENAME 	scroll_summon_undead	1      0
   addstoreitem	STORENAME 	blunt_rudolfsmace	1      0
   addstoreitem	STORENAME 	smallarms_dirk	1      0
   addstoreitem	STORENAME 	axes_runeaxe	1      0
   addstoreitem	STORENAME 	proj_arrow_poison	60      0	0	30
   addstoreitem	STORENAME 	swords_lostblade	1      0
   addstoreitem	STORENAME 	smallarms_dagger	1      0
   addstoreitem	STORENAME 	swords_bastardsword 	1      0

}