//dropped in sfor after killing 4 shadow wolves (req. high end players present)
//- placeholder, hoping for wolf's bane sword and potion later
{
	setvar STORENAME sfor_wolfiechestie
}

#include items/base_treasurechest

{ chest_additems

	callevent get_chance_uncommon 10
	if ( GIVE_PRIZE ) addstoreitem STORENAME swords_wolvesbane 1 0

	callevent add_gold 10 500 10

	addstoreitem STORENAME health_mpotion TC_NPLAYERS 0
	addstoreitem STORENAME mana_mpotion TC_NPLAYERS 0
}