#scope server

{
	setvard BC_FARTIFACTS "mana_faura;mana_fbrand;scroll_ice_blast"
}

#include chests/base_treasurechest

{ game_spawn
	name "Icewing Chest"
	
	callevent tc_add_artifact mana_faura 50
	callevent tc_add_artifact mana_fbrand 50
	callevent tc_add_artifact scroll_ice_blast 15
}

{ chest_additems

	if ( game.players.totalhp >= 2000 ) calleventloop 2 add_epics
	callevent add_epic_item
	
	calleventloop game.playersnb add_greats
	callevent add_gold 500
}

{ add_greats
	callevent add_great_item
}

{ add_epics
	callevent add_epic_item
}