{
	const STORENAME skcastlechest

	const BLACK_CHEST_LOC $relpos(0,0,128) 
	const BC_ITEM_LIST "blunt_gauntlets_fire;armor_golden;blunt_gauntlets_demon"
	const BC_ITEM_CHANCES "25;10;15" //(per player)
	const BC_REQ_PLAYERS "1;1;1"
	const BC_ITEM_NAMES "Gauntlets of Fire;Lord Vecilus Mail;Demon Gauntlets"
	const BC_SPAWN_ON_USE 1
}

#include items/base_treasurechest

{ chest_additems

	callevent add_gold 55 1000 50

   //addstoreitem <storename> <item> <amt> <cost%> <buy_ratio> <bundle_size>
	addstoreitem  STORENAME     skin_bear 		50      0
	addstoreitem  STORENAME     health_spotion 	 	TC_NPLAYERS 	0
	addstoreitem  STORENAME     armor_plate 	 	TC_NPLAYERS	0
	addstoreitem  STORENAME     item_crystal_reloc 	 	TC_NPLAYERS	0
	
	callevent get_players 400
	if ( TC_NPLAYERS > 1 ) addstoreitem  STORENAME     scroll_ice_shield 		1       0
}

{ add_quality_items

	if ( $get(PARAM1,maxhp) < 550 ) callevent 0.1 reset_quality
	if $get(PARAM1,maxhp) >= 550

	callevent get_players 500

	if ( TC_NPLAYERS < 1 ) TC_NPLAYERS 1

	callevent get_chance_ultra_rare  400
	if ( GIVE_PRIZE ) addstoreitem STORENAME blunt_gauntlets_fire 1 0

	callevent get_chance_uncommon 400
	if ( GIVE_PRIZE ) addstoreitem STORENAME swords_skullblade4 1 0

	local H_ARROWS TC_NPLAYERS
	multiply H_ARROWS 15

	callevent add_epic_item 100
	callevent add_epic_item 100
	addstoreitem STORENAME proj_arrow_gholy H_ARROWS 0 0 30
}

{ reset_quality
	setvard ADDED_QUALITY 0
}