#include chests/base_treasurechest_array

{ game_spawn
	setvard GAVE_BONUS1 0
	setvard GAVE_BONUS2 0
	setvard GAVE_BONUS3 0
}

{ chest_additems

	callevent add_gold_by_hp 500
	callevent add_gold_by_hp 500
	callevent add_gold_by_hp 500
	callevent add_epic_item 100 500
	callevent add_epic_item 100 500

	callevent add_epic_arrows 15
	callevent add_great_arrows 15

	if ( $rand(1,16) <= game.playersnb ) callevent add_epic_item 100 300
	if ( $rand(1,20) <= game.playersnb )
	{
		if !GAVE_BONUS1
		if $get(CHEST_USER,scriptvar,'PLR_TOTAL_DMG') > 1
		setvard GAVE_BONUS1 1
		addstoreitem STORENAME bows_firebird 1 0
	}
	if ( $rand(1,20) <= game.playersnb )
	{
		if !GAVE_BONUS2
		if $get(CHEST_USER,maxhp) > 500
		setvard GAVE_BONUS2 1
		addstoreitem STORENAME item_charm_w2 1 0
	}
	if ( !GAVE_BONUS3 )
	{
		if ( BC_STRONGEST_PLAYER equals 'BC_STRONGEST_PLAYER' ) callevent find_strongest_player
		if BC_STRONGEST_PLAYER equals CHEST_USER
		setvard GAVE_BONUS3 1
		addstoreitem STORENAME mana_immune_lightning 1 0	
	}

	if ( game.players.totalhp > 4000 )
	{
		callevent add_epic_item 100 300
		callevent add_epic_item 100 300
	}

	callevent add_great_item 100 200
	callevent add_great_item 100 200
	callevent add_great_item 100 200
}