#include chests/base_treasurechest

{ game_spawn

	callevent tc_add_artifact scroll_lightning_disc 5
	callevent tc_add_artifact scroll2_lightning_disc 5
}

{ chest_additems

	callevent add_gold 1500
	callevent add_epic_item
	callevent add_epic_item

	callevent add_epic_arrows 15
	callevent add_great_arrows 15

	if ( $rand(1,16) == 1 ) callevent add_epic_item
	if ( $rand(1,8) == 1 ) addstoreitem STORENAME item_charm_w2 1 0

	if ( $rand(1,8) == 1 ) addstoreitem STORENAME mana_immune_lightning 1 0	

	if ( $rand(1,8) == 1 ) callevent add_epic_item
	if ( $rand(1,8) == 1 ) callevent add_epic_item

	callevent add_great_item
	callevent add_great_item
	callevent add_great_item
}