#include chests/tundra_base

{ chest_additems

	callevent add_gold 500

	addstoreitem STORENAME mana_immune_fire 1 0
	callevent offer_felewyn_symbol 100

	callevent add_epic_item
	callevent add_epic_item

	if ( $rand(1,30) ) addstoreitem STORENAME item_charm_w2 1 0
	if ( $rand(1,30) ) addstoreitem STORENAME scroll2_ice_blast 1 0
	if ( $rand(1,30) ) addstoreitem STORENAME mana_font 1 0
	if ( $rand(1,30) ) addstoreitem STORENAME scroll2_healing_circle_920 1 0

	if ( $rand(1,10) ) callevent add_epic_item
	if ( $rand(1,10) ) callevent add_epic_item
	if ( $rand(1,10) ) callevent add_epic_item
	if ( $rand(1,10) ) callevent add_epic_item

	callevent add_epic_pot
}