#include chests/base_treasurechest

{ game_spawn

	callevent tc_add_artifact armor_fireliz 10
	callevent tc_add_artifact scroll2_summon_guard 4
	callevent tc_add_artifact armor_pheonix55 4
}

{ chest_additems

	callevent add_gold $rand(100,1000)

	addstoreitem	STORENAME 	health_spotion	1	0
	addstoreitem	STORENAME 	mana_mpotion	1	0

	addstoreitem	STORENAME	mana_vampire 1 0
	addstoreitem	STORENAME	mana_protection 1 0

	if ( $rand(1,3) == 1 ) addstoreitem	STORENAME	mana_speed 1 0

	if ( $rand(1,3) == 1 ) callevent add_great_item
	if ( $rand(1,3) == 1 ) callevent add_great_item
}