//same script, just adjusted for narrow passages
{
	const BOAR_WIDTH2 32
	const BOAR_HEIGHT2 75

	const BOAR_SIZE 2
	const BOAR_SKIN 0
	const BOAR_MODEL monsters/boar2.mdl

	setvard NPC_GIVE_EXP 125

	const DMG_GORE1 60
	const DMG_GORE2 $randf(10.0,15.0)
	const DMG_GORE3 $randf(10.0,15.0)
	const DMG_CHARGE $rand(50,100)

	const ATTACK_HITCHANCE	70%

	setvard FLEE_CHANCE 10%
}

#include monsters/boar2

{ npc_post_spawn
	//this is set in the base too (on spawn), so must reset here 
	setvard DROP_ITEM1 skin_boar_heavy 	//base_monster - Item Drop #1
	setvard DROP_ITEM1_CHANCE 50%		//base_monster - Chance of item drop #1

	setvard ATTACK_RANGE 90
	setvard ATTACK_HITRANGE 100
}