{ game_spawn

   	hp 1
   	name a|Frightened Mercenary
   	width 32
   	height 64
   	roam 0
   	race human
	blood red
   	setmodel npc/guard1.mdl
   	setmodelbody	1 0
   	setidleanim sitidle
   	setmoveanim sitidle
	playanim once sitidle
	blind 1 //saves da CPU

	nopush 1

	menu.autoopen 1

	callevent 10.0 get_slayer_id
}

{ get_slayer_id
	setvard SLAYER_ID $get_by_name(agrath)
}

{
repeatdelay $randf(10,60)
	playanim once cowering_in_corner
}

{ say_hi
	playanim once cowering_in_corner
	saytext Have you seen those things!? I'm not going in there again!
}

{ game_menu_getoptions
	if $get(ent_me,isalive)

	local reg.mitem.title 	"Hail."
	local reg.mitem.type 	callback
	local reg.mitem.callback say_hi
	menuitem.register
}

{ game_damaged

	if $get(PARAM1,isplayer)

	setdmg dmg 0
	setdmg hit 0
	returndata 0
}

{
repeatdelay 2.0
	if $get(ent_me,isalive)

	setvard ENEMY_ID $get_insphere(256,enemy)
	if $get(ENEMY_ID,isalive)

	local RND_ANIM $rand(1,2)
	if ( RND_ANIM == 1 ) playanim once sstruggleidle
	if ( RND_ANIM == 2 ) playanim once sstruggle

	local NME_TARGET $get(ENEMY_ID,scriptvar,'NPCATK_TARGET')
	if $get(NME_TARGET,name) isnot 'Frightened Mercenary'
	callexternal ENEMY_ID npcatk_settarget $get(ent_me,id)
}

{ game_death
	playanim hold diebackward
	playrandomsound 0 10 voices/kcult_die1.wav voices/human/male_die.wav
}