#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(3,20)
	callevent add_noob_item

	//           |Store name|  |Item name|  		|Quantity| |cost|
	addstoreitem  STORENAME     blunt_maul	         $rand(0,1)         0
	addstoreitem  STORENAME     bows_shortbow	         $rand(0,1)         0

	if ( $rand(1,3) == 1 )
	{
		addstoreitem  STORENAME     proj_arrow_broadhead	 60        0		0	60
	}
}