#scope server
{
	setvard NPC_IS_BOSS 1

	const OVR_DROP_GOLD_AMT 5000

	const NPC_BASE_EXP 5000

	setvarg G_DID_ESCORT_ALERT 0
	setvarg G_ESCORT_ALERT_SAYTEXT "Treachery! Children of Torkalath slaved to the will of Felewyn!"
}

#include monsters/telf_warrior_fmace_dshield

{ [override] [shared] elf_spawn
	name Ivicta of the Hammer
	//Torkalath Warrior - Club (stun)
	//Torkalath Assasin - Dagger (poison - maybe throw?)
	//Torkalath Slasher - Axe (more hp)
	//Torkalath Blademistress - Dbl Sword (more dmg)
	//Torkalath Shadowarcher - different base? (spiral arrows)
	hp 8000
	takedmg all 0.5
	race torkie

	setmodelbody 1 2 //0=Unarmed 1=PDagger 2=FMace 3=LAxe 4=ESword 5=DBow 6=IDagger 7=Axe 8=OBow 9=Dagger 10=Mace
	setmodelbody 2 1 //0=None 1=Dark_Shield 2=Wood_Shield 3=White_Shield

	giveitem item_telfh3

	saytextrange 1024
	catchspeech say_no elf no elves

	add G_TELF_LEADER_COUNTER 1
}

{ npc_post_spawn
	setvard ANIM_ATTACK swordswing1_R
}

{ say_no
	if ( G_TELF_ESCORTS > 1 )
	{
		saytext Lies! Kill them! KILL THEM NOW!
	}
	else
	{
		saytext "Lies! You'll not take any of us alive!"
	}
	
}

{ npc_targetsighted
	if $get(NPCATK_TARGET,isplayer)
	if !DID_INTRO
	setvard DID_INTRO 1
	saytext Kray Eldorad shall fall! 
}

{ game_death
	setvarg G_ESCORT_ALERT_SAYTEXT 'G_ESCORT_ALERT_SAYTEXT'
}