/**
 * GameMaster.as
 * 
 * The main GameMaster module that manages server-wide game logic,
 * event handling, and coordination between different game systems.
 * 
 * Converted from game_master.script and merged with GameMasterInit.as
 * Now uses the new module syntax for automatic discovery and loading.
 */

// Include directives now supported with pak file integration
// Using simplified data for initial testing
#include "gamemaster/GameMasterData_simple.as"
// TODO: Re-enable these when advanced systems are ready
#include "gamemaster/GameMasterUtils.as" 
#include "gamemaster/GameMasterEvents.as"

module GameMaster
{
    // Core properties
    string m_szName;
    uint m_nSpawnTime;
    uint m_nMapUptime;
    
    // Entity tracking
    EntityHandle m_hSelf;

    // ========================================
    // Simplified Logging Functions
    // ========================================
    
    /**
     * Simple logging functions for minimal GameMaster
     * TODO: Remove these when GameMasterUtils.as is re-enabled
     */
    void LogInfo(const string &in message)
    {
        // Use engine logging function
        LogMessage("[INFO] " + message);
    }
    
    void LogError(const string &in message)
    {
        LogMessage("[ERROR] " + message);
    }
    
    void LogWarning(const string &in message)
    {
        LogMessage("[WARNING] " + message);
    }
    
    // ========================================
    // Module Global Variables
    // ========================================
    
    // Global GameMaster instance (will be auto-generated by module system)
    // GameMaster@ g_GameMaster = null; // This will be auto-generated
    
    // ========================================
    // Module Auto-Instantiation (New Constructor Approach)
    // ========================================
    
    /**
     * GameMaster constructor - automatically called when module loads
     * This replaces the old Init() function approach
     */
    
    // ========================================
    // GameMaster System Management
    // ========================================
    
    /**
     * Initialize the GameMaster system
     * Called by the constructor and legacy compatibility functions
     */
    void InitializeGameMaster()
    {
        LogInfo("Initializing GameMaster system...");
        
        // Check if already initialized
        if (g_GameMaster !is null)
        {
            LogWarning("GameMaster already initialized, destroying previous instance");
            @g_GameMaster = null;
        }
        
        // Initialize supporting systems first
        // TODO: Re-enable these systems once they are fully tested
        // InitializeAdvancedTriggerSystem();
        // InitializeHPSequenceTrigger();
        // InitializeEntitySpawner();
        
        // Initialize entity communication system
        // InitializeEntityCommunications();
        
        LogInfo("GameMaster: Skipping advanced systems initialization for now");
        
        // GameMaster instance will be created automatically by the module system
        // @g_GameMaster = GameMaster(); // REMOVED: This caused infinite recursion
        
        // Global instance (g_GameMaster) will be created automatically by module system
        // Initialize other systems that don't require the instance
        RegisterGameMasterEngineEvents();
        
        LogInfo("GameMaster system initialized successfully");
    }
    
    /**
     * Shutdown the GameMaster system
     * Called when the map unloads
     */
    void ShutdownGameMaster()
    {
        LogInfo("Shutting down GameMaster system...");
        
        if (g_GameMaster !is null)
        {
            // Clean shutdown
            @g_GameMaster = null;
            LogInfo("GameMaster system shut down successfully");
        }
        else
        {
            LogWarning("GameMaster was not initialized");
        }
        
        // Shutdown supporting systems
        // TODO: Re-enable these shutdowns when systems are active
        // ShutdownEntityCommunications();
        // ShutdownHPSequenceTrigger();
        // ShutdownAdvancedTriggerSystem();
        // ShutdownEntitySpawner();
    }
    
    /**
     * Get the global GameMaster instance
     */
    GameMaster@ GetGameMasterInstance()
    {
        return g_GameMaster;
    }
    
    /**
     * Check if GameMaster is initialized
     * Moved to avoid conflicts with engine registration
     */
    bool GameMasterUtils_IsInitialized()
    {
        return g_GameMaster !is null;
    }
    
    // ========================================
    // GameMaster Module Implementation
    // ========================================
    // The Game Master entity that exists once per server and manages
    // all global game state and events.
    
    // GameMaster properties and methods (now module-level)
        
    GameMaster()
    {
        m_szName = "The Game Master";
        m_nSpawnTime = 0;
        m_nMapUptime = 0;

        LogInfo("GameMaster constructor called - initializing module...");
        
        // Initialize the GameMaster system (previously done in Init())
        InitializeGameMaster();
        
        // Call Spawn to complete initialization
        Spawn();
        
        LogInfo("GameMaster module initialized successfully via constructor");
    }

    /**
     * Called when the game master entity spawns in the world
     */
    void Spawn()
    {
        LogInfo("***************** Game_Master - Spawned");
    }

    // ========================================
    // Event Handler Methods
    // ========================================

    /**
     * Called when a player connects to the server
     */
    void OnPlayerConnect(const string &in szPlayerName)
    {
        LogInfo("GameMaster: Player connected - " + szPlayerName);
        // TODO: Implement actual player connection handling
    }

    /**
     * Called when a player disconnects from the server
     */
    void OnPlayerDisconnect(const string &in szPlayerName)
    {
        LogInfo("GameMaster: Player disconnected - " + szPlayerName);
        // TODO: Implement actual player disconnection handling
    }

    /**
     * Called when a monster is killed
     */
    void OnMonsterKilled(const string &in szMonsterName, const string &in szKillerName)
    {
        LogInfo("GameMaster: Monster killed - " + szMonsterName + " by " + szKillerName);
        // TODO: Implement actual monster death handling
    }

    /**
     * Called when treasure is spawned
     */
    void OnTreasureSpawned(const string &in szTreasureType)
    {
        LogInfo("GameMaster: Treasure spawned - " + szTreasureType);
        // TODO: Implement actual treasure spawn handling
    }

    /**
     * Handles gold spew effects
     */
    void GoldSpew(float flGoldPerBag, uint nBagsPerPlayer, float flDistance, 
                 uint nMinBags, uint nMaxBags, const Vector3 &in vecPosition)
    {
        LogInfo("GameMaster: Gold spew triggered at position " + vecPosition.x + ", " + vecPosition.y + ", " + vecPosition.z);
        // TODO: Implement actual gold spew effect
    }

    /**
     * Creates an NPC with a delay
     */
    void DelayedCreateNPC(uint nNPCIndex, float flDelay, const string &in szScript, const Vector3 &in vecPosition, const Vector3 &in vecAngles)
    {
        LogInfo("GameMaster: Delayed NPC creation requested - " + szScript);
        // TODO: Implement actual delayed NPC creation
    }

    /**
     * Fades an entity
     */
    void FadeEntity(EntityHandle hTarget, int nRenderMode = 5, uint nStartAmount = 255)
    {
        LogInfo("GameMaster: Entity fade requested");
        // TODO: Implement actual entity fading
    }

    
    // ========================================
    // Engine Event Registration
    // ========================================
    
    /**
     * Register GameMaster event handlers with the engine event system
     */
    void RegisterGameMasterEngineEvents()
    {
        LogInfo("GameMaster: Registering engine event handlers...");
        
        // Register the GameMaster engine event handlers
        // TODO: Re-enable when RegisterEngineEvent is implemented
        // RegisterEngineEvent("OnEnginePlayerConnect", OnEnginePlayerConnect);
        // RegisterEngineEvent("OnEnginePlayerDisconnect", OnEnginePlayerDisconnect);
        // RegisterEngineEvent("OnEngineMonsterKilled", OnEngineMonsterKilled);
        // RegisterEngineEvent("OnEngineTreasureSpawned", OnEngineTreasureSpawned);
        
        LogInfo("GameMaster: Engine event handlers registered successfully!");
    }
    
    // ========================================
    // Engine Event Callbacks (moved to global scope below)
    // ========================================
    
    // ========================================
    // Utility Functions for External Scripts (moved to global scope below)
    // ========================================
    
    // ========================================
    // Advanced Trigger System Functions (moved to global scope below)
    // ========================================
}

// ========================================
// Global Functions for Engine Integration
// (Outside module scope for global accessibility)
// ========================================

/**
 * Called by the engine when the map starts
 * Maintained for backward compatibility with legacy code
 * Note: The new module system auto-instantiates, but this provides fallback
 */
void game_master_init()
{
    // The module system now auto-instantiates via constructor
    // This function maintained for backward compatibility only
    LogMessage("[INFO] game_master_init() called - module should already be auto-instantiated");
    
    if (g_GameMaster is null)
    {
        LogMessage("[INFO] GameMaster not yet instantiated, creating manually...");
        GameMaster_Initialize();
    }
}

/**
 * Called by the engine when the map ends
 * Maintained for backward compatibility with legacy code
 */
void game_master_shutdown()
{
    GameMaster_Shutdown();
}

/**
 * Legacy compatibility function
 * Maintained for backward compatibility with legacy code
 */
void game_spawn()
{
    // This mimics the original { game_spawn } event
    // The module system now auto-instantiates via constructor
    LogMessage("[INFO] game_spawn() called - module should already be auto-instantiated");
    
    if (g_GameMaster is null)
    {
        LogMessage("[INFO] GameMaster not yet instantiated, creating manually...");
        GameMaster_Initialize();
    }
}

// ========================================
// Engine Event Callbacks (Global Functions)
// ========================================

/**
 * Called when a player connects
 * This would be hooked up to the engine's player connect event
 */
void OnEnginePlayerConnect(const string &in szPlayerName, const string &in szSteamID)
{
    if (g_GameMaster !is null)
    {
        g_GameMaster.OnPlayerConnect(szPlayerName);
        LogMessage("[INFO] Player:" + szPlayerName + " has connected!");
    }
}

/**
 * Called when a player disconnects
 */
void OnEnginePlayerDisconnect(const string &in szPlayerName, const string &in szSteamID)
{
    if (g_GameMaster !is null)
    {
        g_GameMaster.OnPlayerDisconnect(szPlayerName);
    }
}

/**
 * Called when a monster is killed
 */
void OnEngineMonsterKilled(const string &in szMonsterName, const string &in szKillerName,
                          const Vector3 &in vecDeathPos)
{
    if (g_GameMaster !is null)
    {
        g_GameMaster.OnMonsterKilled(szMonsterName, szKillerName);
        
        // Trigger gold spew if monster had gold
        // This is just an example - real implementation would check monster data
        bool containsBoss = false;
        for (uint i = 0; i <= szMonsterName.length() - 4; i++)
        {
            if (szMonsterName.substr(i, 4) == "boss")
            {
                containsBoss = true;
                break;
            }
        }
        if (containsBoss)
        {
            g_GameMaster.GoldSpew(100.0f, 3, 150.0f, 8, 25, vecDeathPos);
        }
    }
}

/**
 * Called when treasure is spawned
 */
void OnEngineTreasureSpawned(const string &in szTreasureType, const Vector3 &in vecPos)
{
    if (g_GameMaster !is null)
    {
        g_GameMaster.OnTreasureSpawned(szTreasureType);
    }
}

// ========================================
// Utility Functions for External Scripts (Global Functions)
// ========================================

/**
 * Trigger gold spew from external scripts
 */
void TriggerGoldSpew(float flGoldPerBag, uint nBagsPerPlayer, float flDistance,
                    uint nMinBags, uint nMaxBags, const Vector3 &in vecPosition)
{
    if (g_GameMaster !is null)
    {
        g_GameMaster.GoldSpew(flGoldPerBag, nBagsPerPlayer, flDistance, nMinBags, nMaxBags, vecPosition);
    }
    else
    {
        LogMessage("[ERROR] Cannot trigger gold spew: GameMaster not initialized");
    }
}

/**
 * Request delayed NPC creation
 */
void RequestDelayedNPC(float flDelay, const string &in szScript, const Vector3 &in vecPos,
                      const Vector3 &in vecAngles = Vector3())
{
    if (g_GameMaster !is null)
    {
        g_GameMaster.DelayedCreateNPC(0, flDelay, szScript, vecPos, vecAngles);
    }
    else
    {
        LogMessage("[ERROR] Cannot create delayed NPC: GameMaster not initialized");
    }
}

/**
 * Request entity fade
 */
void RequestEntityFade(EntityHandle hTarget, int nRenderMode = 5, uint nStartAmount = 255)
{
    if (g_GameMaster !is null)
    {
        g_GameMaster.FadeEntity(hTarget, nRenderMode, nStartAmount);
    }
    else
    {
        LogMessage("[ERROR] Cannot fade entity: GameMaster not initialized");
    }
}