{
	const NO_JOB 1
	setvard QUEST_DONE 0
}
#include monsters/base_chat
{ spawn

   hp	30
   gold	50    
   name	Elven Child
   //ov	180
   width	32
   height	72
   race	elf
   roam	0
   setmodel	npc/elf_fc.mdl
   invincible	1
   setmodelbody	0

   catchspeech say_hi hi hello hail greet greetings 

   catchspeech say_what documents document happened melanion

   catchspeech say_huh melanoin melanie melarie melarion malenion malanion moolanie molonoin melonion melanuon

   catchspeech say_rumour rumour news happenings
}

{ say_job
	//try to avoid the whole bar responding to the same statement
	if ( PARAM1 equals 'PARAM1' )
	{
		if $get(ent_lastspoke,range) > 128
		local EXIT_SUB 1
	}
	if !EXIT_SUB


	callevent say_hi2
}

{ say_rumor
	//try to avoid the whole bar responding to the same statement
	if ( PARAM1 equals 'PARAM1' )
	{
		if $get(ent_lastspoke,range) > 128
		local EXIT_SUB 1
	}
	if !EXIT_SUB


	callevent say_rumour
}

{ say_hi

	//try to avoid the whole bar responding to the same statement
	if ( PARAM1 equals 'PARAM1' )
	{
		if $get(ent_lastspoke,range) > 128
		local EXIT_SUB 1
	}
	if !EXIT_SUB

	if ( !QUEST_DONE ) callevent say_hi_normal
	if ( QUEST_DONE ) callevent say_thanx
}

{ say_thanx

   saytext Thanks again for what you've done for Melanion, You are my new friend now.
}

{ say_hi_normal

   saytext Hello! My name is Salandria.
   name Salandria
   calleventtimed 3 say_hi2
}

{
   eventname say_hi2

	setvard MEL_ID $get_by_name(melanion)
   callexternal MEL_ID askdocuments

   saytext You look like a friendly person, maybe you can help me with something.
   calleventtimed 4 say_hi3
}
{
   eventname say_hi3

   saytext My mother's good friend Melanion took me here, but she is very distressed.
   calleventtimed 7 say_hi4
}
{
   eventname say_hi4

   saytext She lost some documents from our home. It means so much to her.
   saytext she's been very quiet, barely eats, and talks of nothing but the documents.
	setvard SAID_MEL 1
}
{
   eventname say_what

   if !QUEST_DONE

   saytext I found her with a tragic look, and no documents.
   calleventtimed 3 say_what2
}
{
   eventname say_what2

   saytext She is getting better but she is still so sad.
   calleventtimed 3 say_what3
}
{
   eventname say_what3

   saytext You'd best ask her, she's been distraught over the loss of her documents.
}
{
   eventname say_huh

   saytext Who are you talking about? You mean Melanion? She's up there.
}
{
   eventname bookfound
	//dbg temp Quest Complete
   setvar QUEST_DONE 1
}
//Rumours
{
  eventname say_rumour

	//try to avoid the whole bar responding to the same statement
	if ( PARAM1 equals 'PARAM1' )
	{
		if $get(ent_lastspoke,range) > 128
		local EXIT_SUB 1
	}
	if !EXIT_SUB

  playanim once pondering
  saytext I heard Melanion's meeting has something to do with Eswen Sylen and about allowing humans inside.
}

{ game_menu_getoptions

	if ( !SAID_URD )
	{
		local reg.mitem.title 	"Ask about Jobs"
		local reg.mitem.type 	callback
		local reg.mitem.callback say_job
		menuitem.register
	}

	if SAID_URD
	if ( !QUEST_DONE )
	{
		local reg.mitem.title 	"Ask About Melanion"
		local reg.mitem.type 	callback
		local reg.mitem.callback say_what
		menuitem.register
	}
	if ( QUEST_DONE )
	{
		local reg.mitem.title 	"Ask About Melanion"
		local reg.mitem.type 	callback
		local reg.mitem.callback say_thanx
		menuitem.register
	}
	
}