{ map_shender_east_dream_win
	//teleport all players with z < -3168 back to elf house
	//remove sleeping elf
	//spawn quest reward elf
	//unlock elf chest
	local SLEEP_ELF_ID $get_by_name(sleep_elf)
	callexternal SLEEP_ELF_ID ext_quest_win
	local QUEST_ELF_ID $get_by_name(telf_quest)
	callexternal QUEST_ELF_ID ext_quest_win
	usetrigger spawn_win_elf
	setvard GM_SE_PLAYER_LIST ''
	getplayersnb GM_SE_PLAYER_LIST
	setvard GM_SHENDER_EAST_TELECOUNT 0
	callevent 1.0 map_shender_east_win2
	calleventloop $get_token_amt(GM_SE_PLAYER_LIST) map_shender_east_prepret

}

{ map_shender_east_win2
	calleventloop $get_token_amt(GM_SE_PLAYER_LIST) map_shender_east_return
}

{ map_shender_east_prepret
	local CUR_TARG $get_token(GM_SE_PLAYER_LIST,game.script.iteration)
	if $get(CUR_TARG,origin.z) < -3168
	effect screenfade CUR_TARG 3.0 1.0 (255,255,255) 255 fadein
}

{ map_shender_east_return
	local CUR_TARG $get_token(GM_SE_PLAYER_LIST,game.script.iteration)
	if $get(CUR_TARG,origin.z) < -3168
	if ( GM_SHENDER_EAST_TELECOUNT > 5 ) setvard GM_SHENDER_EAST_TELECOUNT 0
	add GM_SHENDER_EAST_TELECOUNT 1
	if ( GM_SHENDER_EAST_TELECOUNT == 1 ) setorigin CUR_TARG $vec(1784,-3568,296)
	if ( GM_SHENDER_EAST_TELECOUNT == 2 ) setorigin CUR_TARG $vec(1744,-3568,296)
	if ( GM_SHENDER_EAST_TELECOUNT == 3 ) setorigin CUR_TARG $vec(1704,-3568,296)
	if ( GM_SHENDER_EAST_TELECOUNT == 4 ) setorigin CUR_TARG $vec(1656,-3568,296)
	if ( GM_SHENDER_EAST_TELECOUNT == 5 ) setorigin CUR_TARG $vec(1640,-3616,296)
}

{ gm_shender_east_bunny
	//dbg gm_shender_east_bunny PARAM1 PARAM2 $get(PARAM1,name)
	infomsg PARAM1 "HOW COULD YOU!" "Poor bunny!"
	setvard GM_BUNNY_KILLED 1
	clientevent new PARAM1 effects/sfx_bunny 
}