//#scope client
//
//{ [client]
//	const HBAR_SPRITE health_bar.spr
//}
//
//
//{ [client] client_activate
//	setvard HBAR_POS PARAM1
//	setvard HBAR_FRAME PARAM2
//	setvard HBAR_SCALE PARAM3
//	callevent 1.0 remove_me
//	if ( !game.localplayer.thirdperson )
//	{
//		//hopefully this bit stops player from seeing own sprite when looking up
//		if game.localplayer.index equals PARAM4
//		local EXIT_SUB 1
//	}
//	if !EXIT_SUB
//	cleffect tempent sprite HBAR_SPRITE HBAR_POS show_hbar
//}
//
//{ [client] remove_me
//	removescript
//}
//
//{ [client] show_hbar
//	cleffect tempent set_current_prop death_delay	0.9
//	cleffect tempent set_current_prop fadeout		lifetime
//	cleffect tempent set_current_prop frame			HBAR_FRAME		
//	cleffect tempent set_current_prop scale 		HBAR_SCALE
//	cleffect tempent set_current_prop rendermode	add
//	cleffect tempent set_current_prop renderamt		255
//	cleffect tempent set_current_prop gravity 		0.0
//	cleffect tempent set_current_prop collide 		none
//}