//Regeneration
//(This is constant regen - even while walking/running/fighting.  1 hp/12 sec)
//(Regen for sitting is in the sitting emote script and is added to this)

{
	const REGEN_HP_DELAY	12
	const REGEN_MP_DELAY	12
	const THOTH_REGEN_RATE 12.0 //attempting to optimize (DEC2008)
	setvard regen.hp.amt	1
	setvard regen.mp.amt	1
}

{ thoth_regen
repeatdelay THOTH_REGEN_RATE
	givehp ent_me regen.hp.amt
	givemp ent_me regen.mp.amt
}