//Severside Player
/

//Regeneration
//(This is constant regen - even while walking/running/fighting.  1 hp/12 sec)
//(Regen for sitting is in the sitting emote script and is added to this)

{
	const REGEN_HP_DELAY	12
	const REGEN_MP_DELAY	12
	const THOTH_REGEN_RATE 12.0 //attempting to optimize (DEC2008)
	setvard regen.hp.amt	1
	setvard regen.mp.amt	1
}

//Thoth isn't this an awful of lot event calling?
//{ game_think
//
//	callevent player_regen_hp
//	callevent player_regen_mp
//}

//{ game_spawn
//	callevent THOTH_REGEN_RATE thoth_regen
//}

{ thoth_regen
repeatdelay THOTH_REGEN_RATE
	givehp ent_me regen.hp.amt
	givemp ent_me regen.mp.amt
}

{ player_regen_hp

	local l.elapsedtime game.time
	subtract l.elapsedtime regen.hp.time
	if l.elapsedtime > REGEN_HP_DELAY

	setvard regen.hp.time game.time

	givehp ent_me regen.hp.amt
}


{ player_regen_mp

	local l.elapsedtime game.time
	subtract l.elapsedtime regen.mp.time
	if l.elapsedtime > REGEN_MP_DELAY

	setvard regen.mp.time game.time

	givemp ent_me regen.mp.amt
}

