//Thothie mscave almost entirely underground - no rail plzktnx
//Setup the map's weather
//
{ [shared]

	const MAP_NAME 		'ww1'
	const MAP_WEATHER 	"clear;clear;rain;clear;clear;rain"
	const MAP_ALLOWNIGHT 	1

	setvarg G_MAP_NAME "World Walker - Series One, Part I by Crow"
	setvarg G_MAP_DESC "The First of three gauntlet maps: Entrance to the tomb of Sir Geric"
	setvarg G_MAP_DIFF "Levels 15-25 / 200-500hp"
	setvarg G_WARN_HP 200
}

#include worlditems/map_startup
