#scope server
{
	setvard STORE_NAME sorc_merc_
	stradd STORE_NAME $randf(-10000.00,10000.00)
   	setvard STORE_TRIGGERTEXT "store trade buy sell purchase sale offer"
}

#include monsters/base_npc_vendor
#include monsters/base_chat_array

{ [shared] game_spawn
	name a|Shadahar Merchant
	setmodel monsters/sorc.mdl
	hp 1
	invincible 1
	width 32
	height 72
	race beloved
	nopush 1

	setidleanim idle1
	setmoveanim idle1
	playanim once idle1

	if ( $rand(1,2) == 1 )
	{
		setmodelbody 0 1 //body: 0=bare 1=bloody_shirt 2=gold_armor 3=archer
		setmodelbody 1 4 //head: 0=hat_horns 1=hat_spiked 2=lizardskin_horned 3=gold_Chieftain 4=lizard_cap
		setmodelbody 2 0 //weapon: 0=unarmed 1=axe 2=bow 3=steel_bow 4=sword 5=great_axe 6=sword_sheild 8=yellow_axe 9=blooddrinker
	}
	else
	{
		setmodelbody 0 0 //body: 0=bare 1=bloody_shirt 2=gold_armor 3=archer
		setmodelbody 1 4 //head: 0=hat_horns 1=hat_spiked 2=lizardskin_horned 3=gold_Chieftain 4=lizard_cap
		setmodelbody 2 0 //weapon: 0=unarmed 1=axe 2=bow 3=steel_bow 4=sword 5=great_axe 6=sword_sheild 8=yellow_axe 9=blooddrinker
	}

	saytextrange 1024

	setvard VENDOR_MENU_OFF 0
	setvard VENDOR_NOT_ON_USE 0

	menu.autoopen 1
	callevent 0.1 get_yaw
}

{ get_yaw
	setvard START_YAW $get(ent_me,angles.yaw)
}

{ game_menu_getoptions

	if ( LAST_PLAYER_USED isnot PARAM1 )
	{
		local RND_COMMENT $rand(1,4)
		if ( RND_COMMENT == 1 ) saytext "Runegahr says we sells to you, so we sells to you."
		if ( RND_COMMENT == 2 ) saytext "Me have many things skinny humans maybe interested in."
		if ( RND_COMMENT == 3 ) saytext "First time me getting gold from a human without killing him first."
		if ( RND_COMMENT == 4 ) saytext "Some of my stuff maybe too heavy for skinny human arms."
		callevent $randf(30.0,60.0) reset_comment_target
	}
	setvard LAST_PLAYER_USED PARAM1

	setvard NEXT_YAW_RESET game.time
	add NEXT_YAW_RESET 30.0
}

{ reset_comment_target
	setvard LAST_PLAYER_USED -1
}

{ vendor_addstoreitems
	//shared with the human vendor

	if !SORC_STORE_STOCKED
	setvard SORC_STORE_STOCKED 1
	addstoreitem STORE_NAME health_mpotion $rand(0,1) 150% 0
	addstoreitem STORE_NAME health_spotion $rand(0,1) 150% 0
	addstoreitem STORE_NAME mana_mpotion $rand(0,1) 150% 0
	addstoreitem STORE_NAME drink_mead $rand(0,1) 150% 0
	addstoreitem STORE_NAME drink_ale $rand(0,1) 150% 0
	addstoreitem STORE_NAME shields_lironshield $rand(0,1) 150% 0
	addstoreitem STORE_NAME pack_heavybackpack $rand(0,1) 150% 0
	addstoreitem STORE_NAME pack_archersquiver $rand(0,1) 150% 0
	addstoreitem STORE_NAME sheath_back_holster $rand(0,1) 150% 0
	addstoreitem STORE_NAME swords_iceblade $rand(0,1) 150% 0
	addstoreitem STORE_NAME axes_poison1 $rand(0,1) 150% 0
	addstoreitem STORE_NAME blunt_granitemace $rand(0,1) 150% 0
	addstoreitem STORE_NAME blunt_granitemaul $rand(0,1) 150% 0
	addstoreitem STORE_NAME bows_swiftbow $rand(0,1) 150% 0
	
	addstoreitem STORE_NAME axes_thunder11 1 1000% 0
	addstoreitem STORE_NAME axes_gthunder11 $rand(0,1) 5000% 0
	addstoreitem STORE_NAME axes_greataxe $rand(0,1) 300% 0
	addstoreitem STORE_NAME axes_scythe $rand(0,1) 300% 0
	addstoreitem STORE_NAME bows_orcbow $rand(0,1) 50% 0
	addstoreitem STORE_NAME armor_helm_dark $rand(0,1) 300% 0

	addstoreitem STORE_NAME mana_demon_blood $rand(0,1) 1000% 0
	addstoreitem STORE_NAME mana_vampire $rand(0,1) 1000% 0
	addstoreitem STORE_NAME mana_regen $rand(0,1) 1000% 0
	addstoreitem STORE_NAME armor_helm_bronze $rand(0,1) 300% 0
	addstoreitem STORE_NAME blunt_gauntlets_serpant $rand(0,1) 1000% 0
	if ( $rand(1,5) == 4 ) addstoreitem STORE_NAME axes_tl	$rand(0,1) 10000% 0

	if ( $rand(1,20) == 20 ) addstoreitem STORE_NAME shields_rune 1 5000% 0
	if ( $rand(1,20) == 20 ) addstoreitem STORE_NAME armor_helm_gaz1 1 3000% 0
	if ( $rand(1,20) == 20 ) addstoreitem STORE_NAME armor_helm_gaz2 1 3000% 0
	if ( $rand(1,20) == 20 ) addstoreitem STORE_NAME armor_fireliz 1 3000% 0
	if ( $rand(1,20) == 20 ) addstoreitem STORE_NAME axes_vaxe 1 3000% 0
	if ( $rand(1,4) == 2 ) addstoreitem STORE_NAME mana_leadfoot 1 5000% 0
	if ( $rand(1,20) == 20 ) addstoreitem STORE_NAME swords_wolvesbane 1 10000% 0
	if ( $rand(1,10) == 2 ) addstoreitem STORE_NAME axes_tl	1 10000% 0
}


#include [server] monsters/debug

{ game_confirm_buy //<owner_id> <item_name> <scriptname> <skill_type>
	dbg PARAM1 PARAM2 PARAM3 PARAM4
}

{
repeatdelay 60.0
	if game.time > NEXT_YAW_RESET
	setangle face $vec(0,START_YAW,0)
}