#scope server
{ [shared]
	const ANIM_RECLINE_IDLE on_chair2
	const ANIM_SIT_IDLE on_chair
	const ANIM_DRINK drink //on_chair
	const ANIM_EAT eat //on_chair
	const ANIM_ACHE sit_ground //on_chair2
	const ANIM_WAVE waving //standing
}

{ [shared] game_spawn

	name a|Shadahar Orc
	setmodel monsters/sorc.mdl
	hp 2000
	takedmg all 0.7
	setstat parry 110
	invincible 1
	race beloved
	nopush 1
	roam 0

	width 32
	height 96

	setidleanim idle1
	setmoveanim idle1
	playanim once idle1

	setmodelbody 0 0 //body: 0=bare 1=bloody_shirt 2=gold_armor 3=archer
	setmodelbody 1 4 //head: 0=hat_horns 1=hat_spiked 2=lizardskin_horned 3=gold_Chieftain 4=lizard_cap
	setmodelbody 2 0 //weapon: 0=unarmed 1=axe 2=bow 3=steel_bow 4=sword 5=great_axe 6=sword_sheild 8=yellow_axe 9=blooddrinker

	catchspeech say_hi hail j0 hi waddup hello gweets greet

	menu.autoopen 1

	saytextrange 1024
}

{ game_postspawn
	setvard NPC_DO_EVENTS PARAM4
	if PARAM4 isnot 'none'
	calleventloop $get_token_amt(NPC_DO_EVENTS) npcatk_do_events
}

{ npcatk_do_events //run param events
	local N_EVENT game.script.iteration
	local EVENT_NAME $get_token(NPC_DO_EVENTS,N_EVENT)
	add N_EVENT 1
	if ( N_EVENT <= $get_token_amt(NPC_DO_EVENTS) )	local NEXT_EVENT $get_token(NPC_DO_EVENTS,N_EVENT)
	dbg doing token event EVENT_NAME
	callevent EVENT_NAME NEXT_EVENT
}

{ set_recline1
	setvard SORC_TYPE recline1
	setmodelbody 0 0
	setmodelbody 1 4
	setmodelbody 2 0
	setidleanim on_chair2
	setmoveanim on_chair2
	playanim once on_chair2
}

{ game_menu_getoptions
	local reg.mitem.title 	"Hail"
	local reg.mitem.type 	callback
	local reg.mitem.callback say_hi
	menuitem.register	
}

{ say_hi
	if ( SORC_TYPE equals recline1 )
	{
		playanim critical on_chair2
		saytext "Oh, it's Runegahr's 'guests'. Don't mind meez, I is just sunnings."
	}
}

