//Drunkard Dridmar

{
const NO_RUMOR 1
const NO_JOB 1
}


#include monsters/base_npc
#include monsters/base_civilian
#include monsters/base_chat

{ npc_spawn

hp 25
width 32
height 32
race human
name Drunkard
roam 0

setmodel npc/human1.mdl

setidleanim sitidle

setvar DRINK 0
setvar CAUGHT 0
setvar QUEST 0
setvar QUESTDONE 0
}

{ game_menu_getoptions

if ( CAUGHT == 0 )
	{ 
		local reg.mitem.id Ppocket
		local reg.mitem.title "Pickpocket"
		local reg.mitem.type callback
		local reg.mitem.callback say_rob
		menuitem.register
		}
		
if ( DRINK == 1 )
	{
		local reg.mitem.id AskDrink
		local reg.mitem.title "Drink"
		local reg.mitem.type callback
		local reg.mitem.callback say_drink
		menuitem.register
		}		

if ( QUEST == 1 ) 	
if ( $item_exists(PARAM1,drink_mead) )
	{
		local reg.mitem.title 	"Give Mead"
		local reg.mitem.type 	payment
		local reg.mitem.data 	drink_mead
		local reg.mitem.callback give_mead
		menuitem.register
		}
		
}

{ say_rob

setvard ROB_ATTEMPT $rand(1,3)

if ( ROB_ATTEMPT == 1 ) callevent rob_pass
if ( ROB_ATTEMPT == 2 ) callevent rob_pass
if ( ROB_ATTEMPT == 3 ) callevent rob_fail
}

{ rob_pass 

setvard Thief $get(ent_lastused,id)
offer Thief gold 3
setvarg CAUGHT 1
}

{ rob_fail

saytext Get your hands out of my pockets!
setvarg CAUGHT 1
callevent bchat_mouth_move
}

{ say_hi
if ( QUESTDONE == 0 )
{
saytext *hic* Can you believe they cut me off.  I really need another [drink].
setvarg DRINK 1
callevent bchat_mouth_move
}

if ( QUESTDONE == 1 )
{
saytext Thanks for *hic* your help, Adventurer.
callevent bchat_mouth_move
setvarg QUEST 0
}
}

{ say_drink

setvard CHAT_STEPS 3
setvard CHAT_STEP 0
setvard BUSY_CHATTING 1
setvard CHAT_STEP1 "Can you go inside the Inn and get me *hic* another drink?
setvard CHAT_STEP2 "I will give you some *hic* gold for your troubles."
setvard CHAT_STEP3 "I would you to get me *hic* a mug of mead."
callevent chat_loop
setvarg QUEST 1
callevent bchat_mouth_move
}

{ give_mead

saytext Cheers! Thanks for your *hic* help adventurer.  
offer PARAM1 gold 10
setvarg QUESTDONE 1
setvarg DRINK 0
callevent bchat_mouth_move
usetrigger RenderMug
}