#include chests/base_treasurechest

{ chest_additems

	addstoreitem STORENAME polearms_a 1 0
	addstoreitem STORENAME polearms_ba 1 0
	addstoreitem STORENAME polearms_dra 1 0
	addstoreitem STORENAME polearms_h 1 0
	addstoreitem STORENAME polearms_hal 1 0
	addstoreitem STORENAME polearms_har 1 0
	addstoreitem STORENAME polearms_nag 1 0
	addstoreitem STORENAME polearms_ph 1 0
	addstoreitem STORENAME polearms_qs 1 0
	addstoreitem STORENAME polearms_sl 1 0
	addstoreitem STORENAME polearms_sp 1 0
	addstoreitem STORENAME polearms_ti 1 0
	addstoreitem STORENAME polearms_tri 1 0
}