#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(5,15)

	//           |Store name|  |Item name|      |Quantity| |cost|
	addstoreitem  STORENAME     item_torch 	1          0
	addstoreitem  STORENAME     health_apple 	1          0

	if ( $rand(1,6) == 1 ) addstoreitem  STORENAME     blunt_hammer1	1   	   0
	if ( $rand(1,15) == 1 ) addstoreitem  STORENAME     armor_leather	1   	   0
}