#include items/base_treasurechest

{ treasure_spawn

   setvar STORENAME	rudolfschest
}

{ chest_additems
   
   //           |Store name|  |Item name|  	|Quantity| |cost|
   addstoreitem  STORENAME     blunt_rudolfsmace 1 0
   if ( $rand(1,2) == 1 ) addstoreitem STORENAME proj_arrow_gholy 15 0 0 15
   addstoreitem STORENAME proj_bolt_wooden 50 0 0 25
   if ( $rand(1,5) == 1 ) addstoreitem STORENAME proj_bolt_iron 25 0 0 25
}