#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(3,6)
	//           |Store name|  |Item name|  	|Quantity| |cost|
	addstoreitem  STORENAME       health_lpotion 	 2          0
	addstoreitem  STORENAME       item_torch         2          0
	addstoreitem  STORENAME       axes_smallaxe      1          0
	addstoreitem  STORENAME       swords_shortsword  1          0
	if ( $rand(1,2) == 1 ) addstoreitem STORENAME blunt_gauntlets 1 0
}