{ gm_map_m2_quest_setmusic //<target>
	local SYLPH_ID $get_by_name(sylphiel)
	if ( $get(SYLPH_ID,scriptvar,'DID_FIRST_HELP') )
	{
		if ( !$get(SYLPH_ID,scriptvar,'ALL_QUESTS_DONE') )
		{
			//player on quest, play questie music
			callexternal PARAM1 ext_play_music_me music/FortFraeyOrch.mp3
		}
		else
		{
			//quests done, play some ambiance
			callexternal PARAM1 ext_play_music_me idemarks_tower_elegie-in-bb-minor.mp3
		}
	}
}