#scope server
{ game_spawn
	name_unique cooking_pot
	invincible 1
	setvard PLAYING_DEAD 1
	nopush 1
	width 16
	height 72
	setmodel props/pot1.mdl
	setvard GLOW_COLOR (255,200,128)
	setvard GLOW_RAD 64
	callevent 0.1 glow_loop
}

{ glow_loop
	callevent 10.0 glow_loop
	clientevent new all effects/sfx_follow_glow_cl $get(ent_me,index) GLOW_COLOR GLOW_RAD 10.1
}

{ ext_cooking
	setmodelbody 0 1
	setvard GLOW_COLOR (255,225,164)
	setvard GLOW_RAD 96
}