//Thothie - can't figure why these chests were removed
//- adding a map condition, as this map used to contain nothing but a smidgen of gold
//- and many maps usde it as a minor reward
{
	setvar	STORENAME treasure_storeSfor2
}

{ treasure_spawn


	name a|Treasure Chest
}

#include items/base_treasurechest

{ chest_additems

	local L_MAP_NAME $lcase(game.map.name)
	if ( L_MAP_NAME equals sfor ) callevent add_gold 5 25 5
	if ( L_MAP_NAME isnot sfor ) callevent add_gold 10 50 5

	if L_MAP_NAME equals sfor

	callevent get_players 200
	local RANDOM $rand(1,3)
	//		|Store name|	|Item name|		|Quantity|	|cost|
	addstoreitem	STORENAME	item_manuscript		1		0
	//callevent get_chance 10 5 100 200
	//if ( GIVE_PRIZE ) addstoreitem	STORENAME	armor_mongol		1		0
	callevent get_chance 10 5 100 200
	if ( GIVE_PRIZE ) addstoreitem	STORENAME	mana_mpotion		2		0
	addstoreitem	STORENAME	health_lpotion		TC_NPLAYERS_QUART		0
	callevent get_chance 10 5 100 200
	if GIVE_PRIZE
	addstoreitem	STORENAME	shields_buckler		1		0
}