#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(5,50)

	//           |Store name|  |Item name|  	|Quantity| |cost|
	addstoreitem  STORENAME     item_ring 	1        0
	//addstoreitem  STORENAME     armor_leather_studded 	1        0
	addstoreitem  STORENAME     health_lpotion   1        0

	if ( $rand(1,4) == 1 ) callevent add_good_item
	if ( $rand(1,4) == 1 ) callevent add_great_item

	if ( $rand(1,8) == 1 )
	{
		addstoreitem STORENAME proj_bolt_steel 25 0 0 25
	}
}