//Thothie - can't figure why these chests were removed
//- adding a map condition, as this map used to contain nothing but a smidgen of gold
//- and many (only ms_swamp but ok) maps use it as a minor reward

#include chests/base_treasurechest

{ chest_additems

	local L_MAP_NAME $lcase(game.map.name)
	
	callevent add_gold $rand(5,25)

	//		|Store name|	|Item name|		|Quantity|	|cost|
	if ( L_MAP_NAME equals 'sfor' ) addstoreitem	STORENAME	item_manuscript		1		0

	addstoreitem	STORENAME	mana_mpotion		1		0
	addstoreitem	STORENAME	health_lpotion		1		0

	if ( $rand(1,5) == 1 ) addstoreitem	STORENAME	shields_buckler		1		0
}