#include items/base_treasurechest

{ treasure_spawn

   gold $rand(4,10)
   setvar      STORENAME treasure_sewers1
}

{ chest_additems

   createstore STORENAME
   addstoreitem  STORENAME     health_mpotion	 	3   	    0
   if ( $rand(1,2) == 1 ) addstoreitem STORENAME proj_bolt_iron 25 0 0 25
   callevent addrandomitems
}

{ addrandomitems
	if ( $rand(1,2) == 1 ) addstoreitem  STORENAME armor_leather_torn 2 0
	if ( $rand(1,2) == 1 ) addstoreitem  STORENAME blunt_rustyhammer 2 0
	if ( $rand(1,2) == 1 ) addstoreitem  STORENAME smallarms_knife 2 0
	if ( $rand(1,2) == 1 ) addstoreitem  STORENAME proj_arrow_wooden 90 0 0 30
}
