//Tests the $func script function

{ client_activate

	setvard FUNC_USED 0
	
	local L_RESULT $func(func_test,10,1231)
	local L_RESULT2 $func(func_test,11,22)

	if ( FUNC_USED )
	{
		infomsg all "Client-side Result #1: " L_RESULT
		infomsg all "Client-side Result #2: " L_RESULT2
	}
	else
	{
		local L_STR "Results: "
		stradd L_STR L_RESULT
		stradd L_STR " "
		stradd L_STR L_RESULT2
		
		infomsg all "Func was not used" L_STR
	}
	
	callevent 1.0 remove_me
}
			
{ func_test //adds two numbers and returns it

	setvard FUNC_USED 1

	local L_RETURN $math(add,PARAM1,PARAM2)
	return **clear
	return L_RETURN
}

{ remove_me

	removescript
}