{ game_spawn
	invincible 1
	nopush 1
	setvard PLAYING_DEAD 1
	setsolid none
	setmodel null.mdl //need a model to find origin center
}

{ ext_check_targets

	setvard TARGET_CHECK $get_tsphere(player,256,game.monster.origin)
}

{ ext_do_shake
	setvard TARGET_CHECK none //reset for next check
	effect screenshake $get(ent_me,origin) 300 30 10.0 384
	playsound 0 10 magic/volcano_start.wav
}

{ ext_do_boom
	callevent 1.5 ext_do_boom2
}

{ ext_do_boom2
	playsound 0 10 magic/boom.wav 0.5 50
}