//Thothie mscave almost entirely underground - no rail plzktnx
//Setup the map's weather
//
{ [shared]

	const MAP_NAME 		'nashalrath'
	const MAP_WEATHER 	clear;clear;clear;clear;clear;clear
	const MAP_ALLOWNIGHT 	0

	setvarg G_MAP_NAME "The Temple of Nashalrath"
	setvarg G_MAP_DESC "An ancient labrynth once belonging to The Lost."
	setvarg G_MAP_DIFF "Levels 30-40 / 500-800hp"
	setvarg G_WARN_HP 500
	
	setvarg G_DARKEN_BLOOM 0
}

#include worlditems/map_startup
