{ client_activate //<origin> <scale> <duration>

	dbg ****** wind client_activate

	setvard FX_ORIGIN PARAM1
	setvard FX_SCALE PARAM2
	setvard FX_DURATION PARAM3

	setvard FX_ACTIVE 1
	sound.play3d magic/vent1.wav 10 FX_ORIGIN
	cleffect tempent model monsters/monster_extras.mdl FX_ORIGIN setup_wind update_wind
	callevent FX_DURATION end_fx
}

{
repeatdelay 9.0
	if FX_ACTIVE
	sound.play3d magic/vent1.wav 10 FX_ORIGIN
}


{ end_fx
	setvard FX_ACTIVE 0
	callevent 1.0 remove_fx
}

{ remove_fx
	removescript
}

{ update_wind
	if !FX_ACTIVE
	cleffect tempent set_current_prop origin $vec(9999,9999,9999)
}

{ setup_wind
	cleffect tempent set_current_prop death_delay FX_DURATION
	cleffect tempent set_current_prop scale FX_SCALE
	cleffect tempent set_current_prop body 0
	cleffect tempent set_current_prop sequence 2
	cleffect tempent set_current_prop frames 255
	cleffect tempent set_current_prop gravity 0
	cleffect tempent set_current_prop framerate 1.0
	cleffect tempent set_current_prop rendermode add
	cleffect tempent set_current_prop renderamt 100
	cleffect tempent set_current_prop collide none
	cleffect tempent set_current_prop movetype 0
}