//Thothie - DrKill says Arrows must be in multiples of 15, but this seems not to be the issue
//-Scewing with it...

#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(4,10)
	//           |Store name|  |Item name|  	|Quantity| |cost|
	addstoreitem  STORENAME     health_lpotion		$rand(1,5)	0
	addstoreitem  STORENAME     item_torch		$rand(1,2)	0
	addstoreitem  STORENAME     swords_scimitar		1		0
	addstoreitem  STORENAME     pack_archersquiver	1		0
	addstoreitem  STORENAME     bows_longbow		1		0
	addstoreitem  STORENAME     proj_arrow_jagged 30 0 0 15

	if ( $rand(1,25) == 1 ) addstoreitem  STORENAME     bows_swiftbow	 	 1          0

	if $rand(1,25) == 1
	addstoreitem STORENAME proj_arrow_gholy 15 0 0 15
}
