{
	const FAILED_MSG "So very disapointing..."
}

#include calruin/base_riddler

{ riddler_spawn
	
	setvar RIDDLE_ANSWER river
	setangle face $vec(0,90,0)
}

{ riddle_question

	saytext	"What can run, yet never walks, has a mouth, yet never talks..."
	calleventtimed 1 riddle_question2
}

{ riddle_question2

	saytext "...has a head, but never weeps, has a bed, but never sleeps?"
}

{ riddle_correct

	saytext Smarter than I had thought. Or are you...?
	usetrigger spikedoor2
}