//Thothie - Making arrows non-random in my attempts to fix 'arrows from chest' bug.
#include items/base_treasurechest

{
   eventname treasure_spawn

   gold $rand(3,9)
   setvar      STORENAME treasure_storeSfor1
}

{ chest_additems
   
   //           |Store name|  |Item name|  	|Quantity| |cost|
   addstoreitem  STORENAME     health_lpotion    $rand(1,5) 0
   addstoreitem  STORENAME     item_torch    	 $rand(1,2) 0
   addstoreitem  STORENAME     proj_arrow_fire   	 60          0		0	   30
   callevent addrandomitems
}
{
   eventname addrandomitems
   if $rand(1,5) == 1
   addstoreitem  STORENAME     axes_scythe   	 1          0
}
{
   eventname addrandomitems
   if $rand(1,5) == 1
   addstoreitem  STORENAME     blunt_greatmaul   	 1          0
}
