//Pwnage Undead Guard

{

   const SKEL_HP		350
   const ATTACK_HITCHANCE 	100%
   const ATTACK_DAMAGE_LOW 	10
   const ATTACK_DAMAGE_HIGH 	13
   setvard NPC_GIVE_EXP 		80

   setvard DROP_GOLD 		$rand(0,1)
   setvard DROP_GOLD_MIN		10
   setvard DROP_GOLD_MAX		19

}

#include monsters/skeleton_base

{ skeleton_spawn

   name the|Fallen Knight
   roam 1
   hearingsensitivity 6
   setmodelbody	1 0
}