// *** Bats ***
//

// Spawn properties
{
   eventname spawn

   hp 20/20    
   gold 0    
   width 0
   height 0
   race neutral
   name        Bats
   roam 1      
   fly 1
   setmodel    animals/bats.mdl
   setidleanim flappin
   setvar SOUND_IDLE1 monsters/bats/bats.wav
   invincible  1
}
   // Idle sounds
{
   repeatdelay 8

// Volume min-max: 0-10
   volume 10
   playsound 0 SOUND_IDLE1
}

