// Kendra, the prisoner's wife

#include monsters/base_chat
{ spawn

   hp 30/30    //Start with 30 out of 30 max hit points
   gold 50    
   name	       |Kendra
   fov 120
   width 32
   height 72
   race human
   roam 0      //Don't go roaming around
   setmodel    npc/human2.mdl
   invincible  1
   setmodelbody 0 2
   setmodelbody 1 0
   setvar      QUEST_GOBLINPRISONER 0

   catchspeech  say_hi hi hello hail greet hey
   catchspeech	say_upset wrong upset sad
   catchspeech	say_rumor rumour news happenings rumor
   catchspeech	say_steambow sucks steam
}

{ say_job
	callevent say_upset
}

{ say_hi

	if( QUEST_GOBLINPRISONER == 0 )
	{
		saytext I'm too [upset] to talk right now.
	}

	if( QUEST_GOBLINPRISONER == 1 )
	{
		saytext Thank you Adventurer, I couldn't be happier!
	}
}

{ say_rumor

	if( QUEST_GOBLINPRISONER == 0 )
	{
		saytext ...
	}

	if( QUEST_GOBLINPRISONER == 1 )
	{
		saytext I haven't been out much recently.
	}
}

{ say_upset

	if( QUEST_GOBLINPRISONER == 0 )
	{
		saytext My husband has been missing for some time now.
		calleventtimed 3 say_upset2
	}
}

{ say_upset2

	saytext He's a travelling merchant. I'm affraid something has happened to him.
	calleventtimed 3 say_upset3
}

{ say_upset3

	saytext I wish there was some way to know that he is safe.
}

{ game_menu_getoptions

  if ( QUEST_GOBLINPRISONER == 0 )
  {
  	if( $item_exists(PARAM1,item_letter_almund) )
	{
		setvar QUESTER_LETTER PARAM1
		local reg.mitem.title 	"Give Almund's Letter"
		local reg.mitem.type 	payment
		local reg.mitem.data 	item_letter_almund
		local reg.mitem.callback say_ending
		menuitem.register
	}
  }
}

{ say_ending

	setvar QUEST_GOBLINPRISONER 1
	saytext This letter is from my husband...
	calleventtimed 3 say_ending2
}

{ say_ending2

	saytext He's going to be coming home!
	calleventtimed 3 say_reward
}

{ say_reward

	saytext Thank you Adventurer! Please take this gold!
	offer QUESTER_LETTER gold $rand(20,30)
}

{ say_steambow
	saytext You really think that yer going to get the Steam Crossbow that way?
}