{
	const GALA_CHEST_POS $relpos(20,50,50) //Better chest placement. -greatguys1@SEP2021

	const ANIM_CHAT nod
	const ANIM_NO attack
	const ANIM_STORE nod
	setvar ANIM_IDLE idle
	const SAYTEXT_REFUND "No pressure! Here's yer fee back. Come back anytime."
	const SAYTEXT_SELECT_ITEM "Pick what yer gonna store."
	const SAYTEXT_NOITEM "Er, sorry, I didn't get the thing."
	const SAYTEXT_NOTICKET "Sorry, I didn't get yer ticket."
	const SAYTEXT_NOSTORABLES "Sorry, ya've got nuttin I can store for you."
	const SAYTEXT_GIVETICKET "Here's yer ticket! Remember, ya can redeem that at any Galat outlet."
	const SAYTEXT_SELECT_TICKET "What ticket would ya like to redeem?"
	const SAYTEXT_HAND_WARN "Put yer tickets in your hands where I can see them please."
	const SAYTEXT_REDEEMTICKET "There ya go! Thank you for using Galat Storage, please come again!"
	const SAYTEXT_ITEMS_HANDS "Gotta put yer stuff in yer hands before I can store it."
}

#include monsters/base_npc
#include NPCs/base_storage

{ npc_spawn

	name Vogdor of Galat's Storage
	hp 1
	invincible 1
	race beloved
	width 28
	height 96
	setmodel	dwarf/male1.mdl
	setidleanim idle
	setmoveanim idle
	roam 0
	playanim once idle
	setmodelbody 0 1	//0-Elder 1-Youngin 2-Zombie
	setmodelbody 1 3 //0-Unarmed 1-smallaxe 2-battleaxe 3-bastardsword

	setmodelbody 1 0 
	setmodelbody 2 0

	//dbg temp Gatecity Teller Spawned

	saytextrange 1024

	catchspeech heard_hi hail hello hi greets gweets j0 waddup
	catchspeech heard_rumor job rumor rumour quest
	catchspeech heard_store shop store bank
}

{ heard_hi

	setvard DID_HELLO 1
	playanim critical ANIM_CHAT
	playsound 0 10 npc/dwarfatservice.wav
	saytext 'ello thar, welcome to Galat's Weapon and Armor Storage...
	callevent 5.0 heard_hi2
}

{ heard_hi2
	saytext For a nominal fee, we can store yer things here for ya's.
	callevent 5.0 heard_hi3
}

{ heard_hi3
	saytext We'll gives you a ticket for anything we can store.
	callevent 5.0 heard_hi4
}

{ heard_hi4
	saytext Thanks to our contacts with the Felewyn wizards, ya can redeem this ticket at any Galat outlet!
	callevent 5.0 heard_hi5
}

{ heard_hi5

	saytext Galat has outlets all over - even in the forsaken town of Helena!
}

{ heard_rumor

	saytext Hmm... Not much goin on here to be honest. We dwarves don't like change.
}

{ heard_store

	menu.open $get(ent_lastheard,id)
}

{ game_menu_getoptions

	if ( !DID_HELLO )
	{
		setvard DID_HELLO 1
		saytext Welcome to Galat's Weapon and Armor Storage!
	}

	local reg.mitem.title 	"Hail"
	local reg.mitem.type 	callback
	local reg.mitem.callback heard_hi
	menuitem.register
}

{ say_storage_chest
	if ( BUSY_CHATTING ) callevent 1.0 say_storage_chest
	if !BUSY_CHATTING
	callevent convo_anim
	setvard CHAT_STEPS 6
	setvard CHAT_STEP1 "Ah, that bleedin thing be the new fangled Wondrous Chest of Storage."
	setvard CHAT_STEP2 "This bugger here can store items for you, no need for tickets. Makes me wonder what I'm doin' here."
	setvard CHAT_STEP3 "Just thrust your fists at it, whiling holdin' whatever it be you wantin' to get off yer hands."
	setvard CHAT_STEP4 "Then, when ye want yer stuff back, just open her up - or anyone like her, anywhere."
	setvard CHAT_STEP5 "The chest has some magic thingie on it that makes sure you, and only you, gets yer stuff."
	setvard CHAT_STEP6 "It's free to use. Seems the lads at Galat HQ are in a giving mood this turn. *cough*"
	callevent chat_loop 
}

{ say_wondrous
	if ( BUSY_CHATTING ) callevent 1.0 say_wondrous
	if !BUSY_CHATTING
	callevent convo_anim
	setvard CHAT_STEPS 4
	setvard CHAT_STEP1 "Ah, here be the interestin' part of the whole deal. With one of these, you can summon that there chest in front of me."
	setvard CHAT_STEP2 "Meaning you, and yer friends, can have access to the Galat Wondrous Chest of Storage, wherever ye may happen to be."
	setvard CHAT_STEP3 "Only works once though - and ye need a fair bit of room to place the chest, so be careful."
	setvard CHAT_STEP4 "So, this where where they get ya. After suckering in with free use of the chest here, they charge you "
	stradd CHAT_STEP4 GALA_SCROLL_PRICE
	stradd CHAT_STEP4 " gold a piece the scrolls!"
	callevent chat_loop 
}