{ const BETA_TIMESTAMP "Thu 07/06/2006 15:36:16.93" } 
//Player commands
//
//This script is run on the server

{ game_playercmd

  	if( PARAM1 equals 'test' ) playermessage ent_currentplayer You typed 'test' with game.event.params arguments
	if( PARAM1 equals 'setweather' ) callexternal all game_playercmd_setweather PARAM2 PARAM3 PARAM4
  	if( PARAM1 equals 'time' )
	{
		consolemsg ent_currentplayer == TIME: CURRENT_TIME == 
		playermessage ent_currentplayer == TIME: CURRENT_TIME == 
	}
  	if( PARAM1 equals 'beta' ) callevent give_timestamp
  	if( PARAM1 equals 'date' ) callevent give_timestamp
  	if( PARAM1 equals 'betadate' ) callevent give_timestamp

	if( PARAM1 equals 'startattack' ) callexternal $get_by_name(helena) manual_start PARAM2

	//settime <hour> <minute>
  	if( PARAM1 equals 'settime' ) callevent set_time PARAM2 PARAM3
}

{ give_timestamp
		consolemsg ent_currentplayer SC.DLL timestamp is BETA_TIMESTAMP
		playermessage ent_currentplayer SC.DLL timestamp is BETA_TIMESTAMP
}

{ set_time //<hour> <minute>

	if game.event.params >= 2

	mod PARAM1 24
	mod PARAM2 60

	callevent time_getseconds			//Get the number of seconds passed
	local local.mstime.secs global.mstime.secs	//since the beginning of game (MS Time)

	local l.secs $int(PARAM1)			//Get the desired time in seconds
	multiply l.secs 3600

	local l.mins_to_secs $int(PARAM2)
	multiply l.mins_to_secs 60
	
	add l.secs l.mins_to_secs

	//Get the time offset from the start of the current day
	//Compare it to the requested time of day, to check if I should
	//advance to the next day.
	//--------------------------------------------------

	local l.daystart.secs global.mstime.secs	//Get start of this day
	divide l.daystart.secs 86400				
	setvard l.daystart.secs $int(l.daystart.secs)
	multiply l.daystart.secs 86400

	local l.timefromdaystart global.mstime.secs	//Get time offset from start of day
	subtract l.timefromdaystart l.daystart.secs

	//If Requested time of day is earlier than Current time of day, fast forward a full day

	if( l.secs < l.timefromdaystart ) add l.secs 86400

	//Add requested time to start of day

	local l.newtime l.daystart.secs
	add l.newtime l.secs

	//Store in global

	setvarg global.mstime.secs l.newtime

	setvarg global.mstime.updateall 0	//Force update to all
}
