//Circle of death, cast by gold forged skeletons.

#scope server

{
	const SOUND_PULSE ambience/pulsemachine.wav
	const AOE_SCAN_TYPE rsphere
	const AOE_SCAN_FREQ 1
}

#include monsters/summon/base_aoe2

{ game_precache

	precache skull.spr
	precache weapons/magic/seals.mdl
}

{ game_dynamically_created //PARAM1=Owner PARAM2=radius PARAM3=Damage PARAM4=Duration [PARAM5=skill]

	setvard AOE_OWNER PARAM1
	setvard AOE_RADIUS PARAM2
	setvard DMG_BASE PARAM3
	setvard AOE_DURATION PARAM4
	setvard ACTIVE_SKILL PARAM5
	setvard AOE_AFFECTS_WARY 1
	
	if ( ACTIVE_SKILL startswith PARAM ) setvard ACTIVE_SKILL spellcasting.affliction
	
	playsound 1 10 SOUND_PULSE

	local L_GROUND $get(ent_me,origin)
	vectorset L_GROUND z $get_ground_height(L_GROUND)
	setorigin ent_me L_GROUND
	
	clientevent new all monsters/summon/circle_of_death_cl L_GROUND AOE_DURATION
}

{ aoe_affect_target //<target>

	local CUR_TARG PARAM1
	xdodamage CUR_TARG direct DMG_BASE 100% AOE_OWNER ent_me ACTIVE_SKILL magic_effect //<target|(src_origin)> <range|aoe|(dest_origin)|direct> <damage> <cth|fall_off> <attacker> <inflciter> <skill|none> <dmg_type> [flag_string]
}

{ aoe_end

	playsound 1 0 SOUND_PULSE
	deleteent ent_me
}