#scope client
{ [client]

	const FIREBALL_SPEED 120
	const FIREBALL_SPRITE blueflare1.spr
	const EMITTER_SPRITE blueflare1.spr
	const SOUND_KABOOM magic/freeze.wav
	const SOUND_LOOP magic/pulsemachine_noloop.wav
	const FREQ_LOOP_SOUND 1.88
	const IS_COLORED 1
	const NEW_COLOR (128,164,255)
	const SPRITE_FRAMES_SMALL 1
	const SPRITE_FRAMES_LARGE 1
	const SPRITE_SCALE_SMALL 0.5
	const SPRITE_SCALE_LARGE 2.0
	const SPRITE_SCALE_KABOOM 3.0
}

#include monsters/summon/client_side_fireball

