#scope client

{ [client] client_activate

	const FIRE_SPRITE fire1_fixed.spr
	const TOTAL_OFS 10
	setvard CYCLE_ANGLE 0
	setvard OWNER_POS $getcl(PARAM1,origin)
	calleventloop 17 create_flames
	callevent 2.9 remove_me_cl
	sound.play3d ambience/steamburst1.wav 10 OWNER_POS
}

{ [client] remove_me_cl

	removescript
}

{ [client] create_flames

	local FLAME_POS OWNER_POS
	vectoradd FLAME_POS $relpos($vec(0,CYCLE_ANGLE,0),$vec(0,TOTAL_OFS,0))
	cleffect tempent sprite FIRE_SPRITE FLAME_POS setup_flame

	add CYCLE_ANGLE 20
}

{ [client] setup_flame

	cleffect tempent set_current_prop death_delay 	2.0
	cleffect tempent set_current_prop framerate	30
	cleffect tempent set_current_prop frames	23
	cleffect tempent set_current_prop scale 	2.0
	cleffect tempent set_current_prop gravity 	0
	//local FLAME_ANGLE $vec(0,CYCLE_ANGLE,0)
	//cleffect tempent set_current_prop angles FLAME_ANGLE
	//cleffect tempent set_current_prop angle FLAME_ANGLE
	local FLAME_TURN $relvel($vec(0,CYCLE_ANGLE,0),$vec(0,100,0))
	cleffect tempent set_current_prop velocity FLAME_TURN
	cleffect tempent set_current_prop collide 	none
	cleffect tempent set_current_prop fadeout lifetime
}
