#scope client
{
	const SOUND_KABOOM weapons/explode3.wav
}

{ client_activate //<origin> <radius>


	setvard MY_ORG PARAM1
	setvard MY_RADIUS PARAM2
	divide MY_RADIUS 2

	//splodie beams
	setvard CYCLE_ANGLE 0
	calleventloop 18 splodie_beams

	callevent ball_end
	sound.play3d SOUND_KABOOM 10 MY_ORG

	callevent 2.0 remove_fx
}

{ remove_fx
	removescript
}

{ splodie_beams
	local BEAM_START MY_ORG
	local BEAM_END BEAM_START
	local RND_UD $randf(-64.0,64.0)
	vectoradd BEAM_END $relpos($vec(0,CYCLE_ANGLE,0),$vec(0,MY_RADIUS,RND_UD))
	cleffect beam_points BEAM_START BEAM_END lgtning.spr 1.5 2.5 1.5 255 50 30 (255,255,0)
	add CYCLE_ANGLE 20
}

//No longer in use - this script just makes a splodie
//{ svr_update_vec //<angs> <where_server_thinks_I_am>
//	setvard VEL_ANGLES PARAM1
//}
//
//{ ball_end
//	setvard IS_ACTIVE 0
//	callevent 1.0 remove_fx //give a sec for tempents to disipate
//}
