//for holding monsters/players in place
#scope server
{ game_dynamically_created //<duration>
	if PARAM1 > 0
	callevent PARAM1 remove_me
}

{ game_spawn
	//setmodel holder.mdl
	setmodel misc/treasure.mdl
	setprop ent_me scale 0.01
	setprop rendermode 5
	setprop renderamt 0
	width 5
	height 5
	nopush 1
	race beloved
	invincible 1
	setidleanim none
	setmoveanim none
	setvard PLAYING_DEAD 1
}

{ remove_me
	deleteent ent_me
	removescript
}

{
repeatdelay 1.0
	dbg holder_present
}

