{ client_activate //<origin> <duration> <variant>

	setvard FX_ORIGIN PARAM1
	vectoradd FX_ORIGIN z 32
	local FX_DURATION PARAM2

	local CLOUD_VARIANT PARAM3
	if ( CLOUD_VARIANT == 1 ) setvard FX_COLOR (0,0,0)
	if ( CLOUD_VARIANT == 2 ) setvard FX_COLOR (128,255,0)
	if ( CLOUD_VARIANT == 3 ) setvard FX_COLOR (255,0,0)

	dbg *** client_activate org FX_ORIGIN dur FX_DURATION type CLOUD_VARIANT

	setvard IS_ACTIVE 1
	callevent do_smokes
	callevent FX_DURATION end_fx
}

{ do_smokes
	if IS_ACTIVE
	callevent 0.5 do_smokes
	calleventloop 3 do_smokes_loop
}

{ do_smokes_loop
	local L_POS FX_ORIGIN
	vectoradd L_POS x $randf(-128,128)	
	vectoradd L_POS y $randf(-128,128)
	cleffect tempent sprite poison_cloud.spr L_POS setup_smokes
}

{ end_fx
	setvard IS_ACTIVE 0
	callevent 3.0 remove_fx
}

{ remove_fx
	removescript
}

{  [client] setup_smokes

   cleffect tempent set_current_prop death_delay 	2.5
   cleffect tempent set_current_prop framerate		10
   cleffect tempent set_current_prop frames		17
   cleffect tempent set_current_prop bouncefactor 	0
   cleffect tempent set_current_prop scale 		$randf(0.5,1.0)
   cleffect tempent set_current_prop rendermode		add
   cleffect tempent set_current_prop renderamt		200
   cleffect tempent set_current_prop rendercolor	FX_COLOR
   cleffect tempent set_current_prop gravity 		0
   cleffect tempent set_current_prop collide 		none
}