//Thothie - stupid thing to ensure ice lords death anim goes right
{
	const DO_NADDA 0
}

{  game_dynamically_created
   
	setvard DO_NADDA2 0
}

{ game_spawn
	race beloved
	invincible 1
	callevent 0.1 glass_splodie
}

{ glass_splodie

	effect tempent gibs glassgibs.mdl $relpos(0,0,0) 1 40 10 100 30
	callevent 0.1 glass_splodie2
}

{ glass_splodie2

	effect tempent gibs glassgibs.mdl $relpos(0,0,128) 1 40 10 100 30
	callevent 0.1 remove_sploder
}

{ remove_sploder
	deleteent ent_me
}