//Lightning Storm
//Does friendly damage, but only to players

#scope server

//Shared
//======

{ [shared]
	const STORM_HEIGHT 260
	const SMOKE_SPRITE bigsmoke.spr
	const LIGHTNING_SPRITE lgtning.spr
	const LIGHTNING_SPRITE_SPARKS	3dmflaora.spr
	const STORM_WIDTH 75
	precache LIGHTNING_SPRITE_SPARKS	//Precache for the effect
	precache SMOKE_SPRITE
	precache LIGHTNING_SPRITE		//Precache for the effect

	const AOE_FREQ 1.0
	const AOE_RADIUS 150
}

#include monsters/summon/base_aoe

{  game_spawn
	name a|Lightning Storm
	setmodel null.mdl
	width 1
	height 1
	setidleanim none
	invincible 1
	setsolid none
	blood none
	width 10
	height 10
	race hated
	hp 1
	nopush 1

	setvard PLAYING_DEAD 1 //not valid target

	setvard LOOP_SOUND 0
	setvard I_DO_LIGHTNING_DAMAGE 1
}

{ [server] game_dynamically_created

	setvard NEG_WIDTH $neg(STORM_WIDTH)

	setvard MY_OWNER PARAM1
	setvard MY_BASE_DAMAGE PARAM3
	setvard STORM_DURATION PARAM4
	setvard ACTIVE_SKILL PARAM5
	if ( ACTIVE_SKILL equals 'PARAM5' ) setvard ACTIVE_SKILL spellcasting.lightning
	race $get(MY_OWNER,race)

	//callexternal MY_OWNER using_lightning 1 0.2 spellcasting.lightning

	setvard CAST_BY_PLAYER $get(PARAM1,isplayer)

	//setexpstat ent_me spellcasting.lightning	//Thothie added this to try to get the below to work, no luck
	//storeentity ent_expowner PARAM1

	setangle face.y PARAM2

	//find ground to send to client (stops storm from appearing upside-down sometimes)
	local FIND_GROUND_START game.monster.origin
	local FIND_GROUND_END FIND_GROUND_START
	vectorset FIND_GROUND_END z -10000
	local FIND_GROUND_TRACE $get_traceline(FIND_GROUND_START,FIND_GROUND_END,worldonly)

	local F_GROUND_Z $vec.z(FIND_GROUND_TRACE)
	dbg GroundLevelSentToClient: F_GROUND_Z

	if ( CAST_BY_PLAYER )
	{
		setvard STORM_COUNT 0
		if ( FX_SPAMMERS < MAX_FX_SPAMMERS )
		{
			clientevent new all $currentscript $get(ent_me,origin) PARAM2  F_GROUND_Z
			setvard STORM_CLID game.script.last_sent_id
		}
		if ( FX_SPAMMERS >= MAX_FX_SPAMMERS ) consolemsg all Some effects hidden to prevent crash.
	}

	if ( !CAST_BY_PLAYER )
	{
		clientevent new all $currentscript $get(ent_me,origin) PARAM2 F_GROUND_Z
		setvard STORM_CLID game.script.last_sent_id
		callevent STORM_DURATION lstorm_end
	}

	callevent do_storm
}

{ do_storm //Deal damage

	callevent 0.25 do_storm	

	if ( CAST_BY_PLAYER )
	{
		add STORM_COUNT 1
		if STORM_COUNT > 20
		//dbg Storm count up, ending storm
		callevent lstorm_end
	}

	//pick a beam position within radius
//	local NEG_WIDTH $neg(STORM_WIDTH)
//	local X_START $rand(NEG_WIDTH,STORM_WIDTH)
//	local Y_START $rand(NEG_WIDTH,STORM_WIDTH)
//	local FIND_GROUND_START $relpos(X_START,Y_START,0)
//	local FIND_GROUND_END $relpos(X_START,Y_START,-1000)
//	local FIND_GROUND_TRACE $get_traceline(FIND_GROUND_START,FIND_GROUND_END,worldonly)
//	local Z_START FIND_GROUND_TRACE //get groundheight is screwy, find with tracelin
//	local Z_SKY Z_START
//	add Z_SKY STORM_HEIGHT
//
//	local BEAM_START $relpos(X_START,Y_START,Z_START)
//	local BEAM_END $relpos(X_START,Y_START,Z_SKY)
//	callevent beam x y gnd

	//don't draw beam if spammed
//	if ( FX_SPAMMERS >= MAX_FX_SPAMMERS )
//	{
//		if !GAVE_SPAM_MESSAGE
//		playermessage MY_OWNER Too many effects, some effects hidden.
//		setvard GAVE_SPAM_MESSAGE 1
//	}
//	if FX_SPAMMERS < MAX_FX_SPAMMERS
//
//	//make sure there is room to draw beam with traceline
//	local BEAM_TRACE $get_traceline(BEAM_START,BEAM_END,worldonly)
//	//if ( $dist(BEAM_TRACE,BEAM_START) == 0 ) //dbg lstorm beam not clear start BEAM_START end BEAM_END tracend BEAM_TRACE
//	if $dist(BEAM_TRACE,BEAM_START) > 0

	//only dodamage if there is room
	//do damage at beam start (draws from ground up)
	//local DMG_LOC BEAM_START
	//vectoradd DMG_LOC $relpos($vec(0,0,0),$vec(0,2,-10))

	//works:
	//doskilldamage spellcasting.lightning BEAM_START 72 MY_BASE_DAMAGE 100% 0 reflective lightning

	add LOOP_SOUND 1
	if ( LOOP_SOUND >= 3 )
	{
		playsound 0 7 weather/lightning.wav
		setvard LOOP_SOUND 0
	}

	//new system
//	local X_START $rand(NEG_WIDTH,STORM_WIDTH)
//	local Y_START $rand(NEG_WIDTH,STORM_WIDTH)
//	local STORM_CENTER game.monster.origin
//	local G_START $get_ground_height(STORM_CENTER)
//	local BEAM_START STORM_CENTER
//	vectoradd BEAM_START x X_START
//	vectoradd BEAM_START y Y_START
//	vectorset BEAM_START z G_START
//	local BEAM_END BEAM_START
//	vectoradd BEAM_END z STORM_HEIGHT
	

	//(<id|player|monster|any>,<radius>,[(origin)]) - returns number of ent types in sphere
//	local NEAR_TARG $get_insphere(any,96,BEAM_START)
//	if ( $get(NEAR_TARG,isalive) )
//	{
//		if $get(NEAR_TARG,relationship,MY_OWNER) equals enemy
//		if ( $get(NEAR_TARG,isplayer) )
//		{
//			if CAST_BY_PLAYER
//			if game.pvp < 1
//			local EXIT_SUB 1
//		}
//		if !EXIT_SUB
//		applyeffect NEAR_TARG effects/effect_shock_dmg 5 MY_OWNER MY_BASE_DAMAGE spellcasting.lightning
//	}
//
//	clientevent update all STORM_CLID cl_beam BEAM_START BEAM_END
	//if ( G_DEVELOPER_MODE ) gplayermessage MY_OWNER BEAM_START - BEAM_END
}

//{ game_dodamage //1:AttackHit(1/0)  2:EntityHit  3:StartOrigin  4:EndOrigin
//
//	//dbg hit game_dodamage
//
//	if PARAM1
//	local SHOCK_DAMAGE MY_BASE_DAMAGE
//	multiply SHOCK_DAMAGE 0.1
//	applyeffect $get(PARAM2,id) effects/effect_shock_dmg 5 MY_OWNER SHOCK_DAMAGE spellcasting.lightning
//}

//{ game_damaged_other //1:AttackHit(1/0)  2:EntityHit  3:StartOrigin  4:EndOrigin
//
//	//dbg hit game_damaged_other
//
//	local SHOCK_DAMAGE MY_BASE_DAMAGE
//	multiply SHOCK_DAMAGE 0.1
//	applyeffect PARAM1 effects/effect_shock_dmg 5 MY_OWNER SHOCK_DAMAGE  spellcasting.lightning
//}

{ apply_aoe_effect
	if !$get(PARAM1,haseffect,DOT_lightning)
	dbg apply_aoe_effect $get(PARAM1,name) $get(MY_OWNER,name) [ MY_BASE_DAMAGE ]
	local EFFECT_DUR 5.0
	if ( $get(MY_OWNER,isplayer) ) multiply EFFECT_DUR 2
	applyeffect PARAM1 effects/effect_shock_dmg EFFECT_DUR MY_OWNER MY_BASE_DAMAGE ACTIVE_SKILL
}

{ sustain_storm //called externally from magic hand

	clientevent update all STORM_CLID cl_pos_update $get(ent_me,origin)
	setvard STORM_COUNT 0
}

{ lstorm_end  // Pewf

	callexternal MY_OWNER using_lightning 0

	clientevent remove all STORM_CLID
	deleteent ent_me
}

//Client (smokes, from original)
//======

{ [client]
   const HEIGHT 250
   const WIDTH 64

}

{ [client] client_activate

   setvard smoke_POSITION PARAM1
   setvard smoke_ANGLE $vec(0,PARAM2,0)
	setvard GROUND_Z PARAM3
   callevent smokes_start
}

// Random lightning bolt
{ [client]
   repeatdelay 0.25
   callevent smokes_shoot
}

// Throw clouds
{ [client] smokes_shoot
   local NEGWIDTH WIDTH
   multiply NEGWIDTH -1

   local x $rand(NEGWIDTH,WIDTH)
   local y $rand(NEGWIDTH,WIDTH)
   local L_POS $relpos(smoke_ANGLE,$vec(x,y,HEIGHT))
   vectoradd L_POS smoke_POSITION

	local GROUND_LPOS $get_ground_height(L_GPOS)
	local L_GPOS L_POS
	vectorset L_GPOS z GROUND_LPOS
	callevent cl_beam L_POS L_GPOS

   cleffect tempent sprite bigsmoke.spr L_POS setup_smokes
}

{ [client] cl_pos_update

   setvard smoke_POSITION PARAM1
}

{ [client] cl_beam
	local CL_BEAM_START PARAM1
	//local CL_BEAM_END PARAM2
	local CL_BEAM_END CL_BEAM_START
	vectorset CL_BEAM_END z GROUND_Z
	playermessage MY_OWNER CL_BEAM_START - CL_BEAM_END
	
	cleffect beam_points CL_BEAM_START CL_BEAM_END lgtning.spr 1.0 60 .4 .5 1 2 (255,255,0)
}

{  [client] setup_smokes


   cleffect tempent set_current_prop death_delay 	2.5
   cleffect tempent set_current_prop framerate		10
   cleffect tempent set_current_prop frames		17
   cleffect tempent set_current_prop bouncefactor 	0
   cleffect tempent set_current_prop scale 		$randf(0.5,1.0)
   cleffect tempent set_current_prop rendermode		alpha
   cleffect tempent set_current_prop renderamt		255
   cleffect tempent set_current_prop rendercolor	(0,0,0)
   cleffect tempent set_current_prop gravity 		.005
   cleffect tempent set_current_prop collide 		none
}