#include chests/base_treasurechest

{ chest_additems

	//addstoreitem STORENAME blunt_af 1 0
	addstoreitem STORENAME bows_crossbow_heavy33 1 0
	addstoreitem STORENAME bows_crossbow_light 1 0
	addstoreitem STORENAME bows_firebird 1 0
	addstoreitem STORENAME bows_frost 1 0
	addstoreitem STORENAME bows_longbow 1 0
	addstoreitem STORENAME bows_orcbow 1 0
	addstoreitem STORENAME bows_orion1 1 0
	addstoreitem STORENAME bows_shortbow 1 0
	addstoreitem STORENAME bows_steam 1 0
	addstoreitem STORENAME bows_swiftbow 1 0
	addstoreitem STORENAME bows_sxbow 1 0
	addstoreitem STORENAME bows_telf1 1 0
	addstoreitem STORENAME bows_telf2 1 0
	addstoreitem STORENAME bows_telf3 1 0
	addstoreitem STORENAME bows_telf4 1 0
	addstoreitem STORENAME bows_thornbow 1 0
	addstoreitem STORENAME bows_treebow 1 0
	
	addstoreitem STORENAME bows_arrow_blunt 1500 0 0 250
	addstoreitem STORENAME bows_arrow_broadhead 1500 0 0 250
	addstoreitem STORENAME bows_arrow_fire 1500 0 0 250
	addstoreitem STORENAME bows_arrow_frost 1500 0 0 250
	addstoreitem STORENAME bows_arrow_gholy 1500 0 0 250
	addstoreitem STORENAME bows_arrow_gpoison 1500 0 0 250
	addstoreitem STORENAME bows_arrow_holy 1500 0 0 250
	addstoreitem STORENAME bows_arrow_jagged 1500 0 0 250
	addstoreitem STORENAME bows_arrow_lightning 1500 0 0 250
	addstoreitem STORENAME bows_arrow_poison 1500 0 0 250
	addstoreitem STORENAME bows_arrow_wooden 1500 0 0 250
	
	addstoreitem STORENAME bows_bolt_fire 1500 0 0 250
	addstoreitem STORENAME bows_bolt_iron 1500 0 0 250
	addstoreitem STORENAME bows_bolt_poison 1500 0 0 250
	addstoreitem STORENAME bows_bolt_silver 1500 0 0 250
	addstoreitem STORENAME bows_bolt_steel 1500 0 0 250
	
}