{ treasure_spawn

	setvar STORENAME devarmor
}

#include items/base_treasurechest

{ chest_additems

	//addstoreitem	//<store_name> <item_script> <#toadd> <price%> [sell_ratio] [bundle_size]
	addstoreitem STORENAME armor_belmont 1 0
	addstoreitem STORENAME armor_dark 1 0
	addstoreitem STORENAME armor_faura 1 0
	addstoreitem STORENAME armor_fireliz 1 0
	addstoreitem STORENAME armor_golden 1 0
	addstoreitem STORENAME armor_knight 1 0
	addstoreitem STORENAME armor_leather 1 0
	addstoreitem STORENAME armor_leather_gaz1 1 0
	addstoreitem STORENAME armor_leather_studded 1 0
	addstoreitem STORENAME armor_leather_torn 1 0
	addstoreitem STORENAME armor_mongol 1 0
	addstoreitem STORENAME armor_paura 1 0
	addstoreitem STORENAME armor_pheonix55 1 0
	addstoreitem STORENAME armor_plate 1 0
	addstoreitem STORENAME armor_rehab 1 0
	//addstoreitem STORENAME armor_rm 1 0
	addstoreitem STORENAME armor_salamander 1 0
	addstoreitem STORENAME armor_venom 1 0
	
	
	addstoreitem STORENAME armor_helm_alvo1 1 0
	//addstoreitem STORENAME armor_helm_barnum 1 0 //<-- not in-game yet
	addstoreitem STORENAME armor_helm_bronze 1 0
	addstoreitem STORENAME armor_helm_dark 1 0
	addstoreitem STORENAME armor_helm_elyg 1 0
	addstoreitem STORENAME armor_helm_gaz1 1 0
	addstoreitem STORENAME armor_helm_gaz2 1 0
	addstoreitem STORENAME armor_helm_golden 1 0
	addstoreitem STORENAME armor_helm_gray 1 0
	addstoreitem STORENAME armor_helm_knight 1 0
	addstoreitem STORENAME armor_helm_mongol 1 0
	addstoreitem STORENAME armor_helm_plate 1 0
	addstoreitem STORENAME armor_helm_undead 1 0
	
}
