#include chests/base_treasurechest

{ chest_additems

	addstoreitem STORENAME axes_2haxe 1 0
	addstoreitem STORENAME axes_axe 2 0
	addstoreitem STORENAME axes_b 1 0
	addstoreitem STORENAME axes_battleaxe 1 0
	addstoreitem STORENAME axes_c 1 0
	addstoreitem STORENAME axes_df 1 0
	addstoreitem STORENAME axes_doubleaxe 2 0
	addstoreitem STORENAME axes_dragon 1 0
	addstoreitem STORENAME axes_golden 1 0
	addstoreitem STORENAME axes_golden_ref 1 0
	addstoreitem STORENAME axes_greataxe 1 0
	addstoreitem STORENAME axes_gthunder11 1 0
	addstoreitem STORENAME axes_poison1 1 0
	addstoreitem STORENAME axes_rsmallaxe 2 0
	addstoreitem STORENAME axes_runeaxe 2 0
	addstoreitem STORENAME axes_scythe 1 0
	addstoreitem STORENAME axes_smallaxe 2 0
	addstoreitem STORENAME axes_sp 1 0
	addstoreitem STORENAME axes_ss 1 0
	addstoreitem STORENAME axes_td 5 0
	addstoreitem STORENAME axes_tf 5 0
	addstoreitem STORENAME axes_ti 5 0
	addstoreitem STORENAME axes_tl 5 0
	addstoreitem STORENAME axes_tp 5 0
	addstoreitem STORENAME axes_thunder11 1 0
	addstoreitem STORENAME axes_vaxe 1 0
}