#include chests/base_treasurechest

{ chest_additems

	addstoreitem STORENAME pack_archersquiver 1 0
	addstoreitem STORENAME pack_bigsack 1 0
	addstoreitem STORENAME pack_boh_lesser 1 0
	addstoreitem STORENAME pack_heavybackpack 1 0
	addstoreitem STORENAME pack_quiver 1 0
	addstoreitem STORENAME pack_sackite 1 0
	addstoreitem STORENAME pack_sack 1 0
	
	addstoreitem STORENAME sheath_spellbook 1 0
	addstoreitem STORENAME sheath_axe_snakeskin 1 0
	addstoreitem STORENAME sheath_back 1 0
	addstoreitem STORENAME sheath_back_holster 1 0
	addstoreitem STORENAME sheath_back_snakeskin 1 0
	addstoreitem STORENAME sheath_belt 1 0
	addstoreitem STORENAME sheath_belt_holster 1 0
	addstoreitem STORENAME sheath_belt_holster_snakeskin 1 0
	addstoreitem STORENAME sheath_belt_snakeskin 1 0
	addstoreitem STORENAME sheath_blunt_snakeskin 1 0
	addstoreitem STORENAME sheath_dagger 1 0
	addstoreitem STORENAME sheath_dagger_snakeskin 1 0
}