#include chests/base_treasurechest

{ chest_additems

	//addstoreitem	//<store_name> <item_script> <#toadd> <price%> [sell_ratio] [bundle_size]
	addstoreitem STORENAME mana_bravery 3 0
	addstoreitem STORENAME mana_demon_blood 3 0
	addstoreitem STORENAME mana_faura 3 0
	addstoreitem STORENAME mana_fbrand 3 0
	addstoreitem STORENAME mana_flesheater1 3 0
	addstoreitem STORENAME mana_flesheater2 3 0
	addstoreitem STORENAME mana_font 3 0
	addstoreitem STORENAME mana_forget 3 0
	addstoreitem STORENAME mana_gprotection 3 0
	addstoreitem STORENAME mana_immune_cold 3 0
	addstoreitem STORENAME mana_immune_fire 3 0
	addstoreitem STORENAME mana_immune_lightning 3 0
	addstoreitem STORENAME mana_immune_poison 3 0
	addstoreitem STORENAME mana_leadfoot 3 0
	addstoreitem STORENAME mana_lleadfoot 3 0
	addstoreitem STORENAME mana_lsb 3 0
	addstoreitem STORENAME mana_mpotion 3 0
	addstoreitem STORENAME mana_paura 3 0
	addstoreitem STORENAME mana_prot_spiders 3 0
	addstoreitem STORENAME mana_protection 3 0
	addstoreitem STORENAME mana_regen 3 0
	addstoreitem STORENAME mana_resist_cold 3 0
	addstoreitem STORENAME mana_resist_fire 3 0
	addstoreitem STORENAME mana_sb 3 0
	addstoreitem STORENAME mana_soup 3 0
	addstoreitem STORENAME mana_speed 3 0
	addstoreitem STORENAME mana_st 3 0
	addstoreitem STORENAME mana_vampire 3 0
	
}
