#include chests/base_treasurechest

{ chest_additems

	addstoreitem STORENAME item_bearclaw 1 0
	addstoreitem STORENAME item_deed 1 0
	addstoreitem STORENAME item_eh 1 0
	addstoreitem STORENAME item_fstatue 1 0
	addstoreitem STORENAME item_gaxe_handle 1 0
	addstoreitem STORENAME item_goblinhead 1 0
	addstoreitem STORENAME item_hat 1 0
	addstoreitem STORENAME item_ikeletter 1 0
	addstoreitem STORENAME item_ikelog 1 0
	addstoreitem STORENAME item_key_rusty 1 0
	addstoreitem STORENAME item_key_sewer 1 0
	addstoreitem STORENAME item_ledger 1 0
	addstoreitem STORENAME item_letter 1 0
	addstoreitem STORENAME item_letter_almund 1 0
	addstoreitem STORENAME item_letter_mayor 1 0
	addstoreitem STORENAME item_manuscript 1 0
	addstoreitem STORENAME item_ore_lorel 1 0
	addstoreitem STORENAME item_ratskull 1 0
	addstoreitem STORENAME item_ring 1 0
	addstoreitem STORENAME item_ring_ryza 1 0
	addstoreitem STORENAME item_ring_ryza_gem1 1 0
	addstoreitem STORENAME item_ring_ryza_gem2 1 0
	addstoreitem STORENAME item_ring_ryza_gem3 1 0
	addstoreitem STORENAME item_roland_letter 1 0
	addstoreitem STORENAME item_runicsymbol 1 0
	addstoreitem STORENAME item_runicsymbol2 1 0
	addstoreitem STORENAME item_s1 1 0
	addstoreitem STORENAME item_s2 1 0
	addstoreitem STORENAME item_s3 1 0
	addstoreitem STORENAME item_s4 1 0
	addstoreitem STORENAME item_s5 1 0
	addstoreitem STORENAME item_sewernote 1 0
	addstoreitem STORENAME item_storageroomkey 1 0
	addstoreitem STORENAME item_telfh1 1 0
	addstoreitem STORENAME item_telfh2 1 0
	addstoreitem STORENAME item_telfh3 1 0
	addstoreitem STORENAME item_telfh4 1 0
	addstoreitem STORENAME item_warbosshead 1 0
	addstoreitem STORENAME key_blue 1 0
	addstoreitem STORENAME key_brass 1 0
	addstoreitem STORENAME key_crystal 1 0
	addstoreitem STORENAME key_forged 1 0
	addstoreitem STORENAME key_gold 1 0
	addstoreitem STORENAME key_green 1 0
	addstoreitem STORENAME key_ice 1 0
	addstoreitem STORENAME key_red 1 0
	addstoreitem STORENAME key_skeleton 1 0
	addstoreitem STORENAME key_treasury 1 0
}