{ treasure_spawn

	setvar STORENAME devswordz
}

#include items/base_treasurechest

{ chest_additems

	addstoreitem STORENAME swords_bastardsword 2 0
	addstoreitem STORENAME swords_blood_drinker 1 0
	addstoreitem STORENAME swords_frostblade55 1 0
	addstoreitem STORENAME swords_fshard1 1 0
	addstoreitem STORENAME swords_fshard2 1 0
	addstoreitem STORENAME swords_fshard3 1 0
	addstoreitem STORENAME swords_fshard4 1 0
	addstoreitem STORENAME swords_fshard5 1 0
	addstoreitem STORENAME swords_gb 1 0
	addstoreitem STORENAME swords_giceblade 2 0
	addstoreitem STORENAME swords_iceblade 2 0
	addstoreitem STORENAME swords_katana 2 0
	addstoreitem STORENAME swords_katana2 2 0
	addstoreitem STORENAME swords_katana3 2 0
	addstoreitem STORENAME swords_katana4 2 0
	addstoreitem STORENAME swords_liceblade 2 0
	addstoreitem STORENAME swords_longsword 1 0
	addstoreitem STORENAME swords_m2sword 1 0
	addstoreitem STORENAME swords_nkatana 2 0
	addstoreitem STORENAME swords_novablade12 1 0
	addstoreitem STORENAME swords_poison1 2 0
	addstoreitem STORENAME swords_rsword 2 0
	addstoreitem STORENAME swords_rune_green 2 0
	addstoreitem STORENAME swords_scimitar 2 0
	addstoreitem STORENAME swords_sf 1 0
	addstoreitem STORENAME swords_shortsword 2 0
	addstoreitem STORENAME swords_skullblade 2 0
	addstoreitem STORENAME swords_skullblade2 2 0
	addstoreitem STORENAME swords_skullblade3 2 0
	addstoreitem STORENAME swords_skullblade4 2 0
	addstoreitem STORENAME swords_spiderblade 1 0
	addstoreitem STORENAME swords_ub 1 0
	addstoreitem STORENAME swords_vb 2 0
	addstoreitem STORENAME swords_volcano 2 0
	addstoreitem STORENAME swords_wolvesbane 2 0
}