//Setup the map's weather
//
{ [shared]

	const MAP_NAME 		'keledrosprelude'
	const MAP_WEATHER 	clear;clear;clear;clear;rain;rain
	const MAP_ALLOWNIGHT 	1

	setvarg G_MAP_NAME "A Dangerous Pass"
	setvarg G_MAP_DESC "Bandits raid travelers along this pass so frequently that only the bravest of tradesmen still use it."
	setvarg G_MAP_DIFF "Levels 15-25 / 150-400hp"
	setvarg G_WARN_HP 150
}

#include worlditems/map_startup