//Base Keyhole by Thothie
//- To make it easier to add individual keyholes

//KEY_NAME //scriptname for item to accept
//KEYHOLE_NAME
//KEYHOLE_TITLE
//RETURN_KEY

{ game_spawn

	name KEYHOLE_NAME
	width 5
	height 16
	roam 0
	setmodel misc/keyhole.mdl
	invincible 1
	fly 1	//suspend in air where placed
	float 1
	setsolid none //Will block doors sometimes.

	menu.autoopen 1

	setvard IMMUNE_PUSH 1
}

{ game_menu_getoptions

	if ( $item_exists(PARAM1,KEY_NAME) )
	{
		local reg.mitem.title 	KEYHOLE_TITLE
		local reg.mitem.type 	payment
		local reg.mitem.data 	KEY_NAME
		local reg.mitem.callback key_used
		menuitem.register
	}
}

{ key_used //PARAM1 = PlayerID , PARAM2 = keyname
	
	usetrigger KEY_NAME
	if ( RETURN_KEY ) offer PARAM1 KEY_NAME
}

{ return_keys

	//called from external ms_npcscript
	setvard RETURN_KEY 1
}