{ game_spawn
	//ame_unique scripted_ice_wall
	invincible 1
}

{ activate_wall //<target>
	dbg activate_wall $get(PARAM1,origin)
	setorigin ent_me $get(PARAM1,origin)
	setprop ent_me rendermode 5
	setprop ent_me renderamt 255
	if !IS_ACTIVE
	setvard ROT_COUNT 0
	setvard IS_ACTIVE 1
	callevent spin_loop
}

{ spin_loop
	if IS_ACTIVE
	add ROT_COUNT 1
	if ( ROT_COUNT > 359 ) setvard ROT_COUNT 0
	setangle face $vec(0,ROT_COUNT,0)
	callevent 0.1 spin_loop
}

{ deactivate_wall
	setvard IS_ACTIVE 0
	callevent 2.0 hide_wall
}

{ hide_wall
	setorigin ent_me $vec(20000,20000,20000)
}