//experiments
{
	setcallback touch enable
	setprop ent_me solid 1
}

{ game_touch
	//dbg touched by $get(PARAM1,name) ret targetname [ PARAM2 ] target [ PARAM3 ]
//	if $get(PARAM1,race) isnot spider
	// usetrigger web_touched PARAM2
//	playermessage PARAM1 You have been webbed!
//	playsound 0 10 barnacle/bcl_chew2.wav
//	applyeffect PARAM1 effects/speed 10.0 25% 0.25
//	setcallback touch disable
//	removescript
}

//This returns nothing useful
{ game_used
	dbg used by $get(PARAM1,name) $get(PARAM2,name) PARAM3 PARAM4
}

{ [server] bd_debug  //<print_var> <property_printvar> <extra> <extra> <caller_id>
	saytextrange 2048
	saytext var PARAM1 prop PARAM2 = $get(PARAM1,PARAM2)
	consolemsg PARAM5 $get(ent_me,name) reports: var PARAM1 pvar $get(PARAM1,PARAM2)
	dbg PARAM5 $get(ent_me,name) reports: var PARAM1 pvar $get(PARAM1,PARAM2)
}