//This no workie
{ game_damaged
	dbg game_damaged PARAM1 PARAM2 PARAM3 PARAM4
}

{ game_takedamage
	dbg game_takedamage PARAM1 PARAM2 PARAM3 PARAM4
}

{ game_struck
	dbg game_struck PARAM1 PARAM2 PARAM3 PARAM4
}

{ game_death
	dbg game_death PARAM1 PARAM2 PARAM3 PARAM4
}

{ ext_test
	dbg ext_test PARAM1 PARAM2 PARAM3 PARAM4
}

{ ext_report
	dbg game.monster.origin
}

{ ext_follow
	setfollow PARAM1 align_bottom
}