{
	setcallback touch enable
}

{ game_touch

	if PARAM1 isnot UNDAMAEL_ID
	dbg touching something not undamael!
	if game.time > LAST_TOUCH
	setvard LAST_TOUCH game.time
	add LAST_TOUCH 0.5
	if $get(PARAM1,isalive)
	//dodamage PARAM1 direct 10000 100% UNDAMAEL_ID target
	if ( $get(UNDAMAEL_ID,isalive) )
	{
		helptip PARAM1 generic "BEWARE" "The lava Undmael rests in acts as his digestive system. Undamael has gained" $get(PARAM1,hp) "health."
		givehp UNDAMAEL_ID $get(PARAM1,hp)
	}
	if ( 'UNDAMAEL_ID' isnot UNDAMAEL_ID )
	{
		xdodamage PARAM1 direct 10000 100% UNDAMAEL_ID UNDAMAEL_ID none target
	}
	else
	{
		if ( $get(PARAM1,isplayer) )
		{
			kill PARAM1
		}
		else
		{
			xdodamage PARAM1 direct 10000 100% GAME_MASTER GAME_MASTER none target
		}
		
	}
}

{ undamael_spawn
	setvard UNDAMAEL_ID $get_by_name(undamael)
}

{ [server] bd_debug  //<print_var> <property_printvar> <extra> <extra> <caller_id>

	if ( RAND_ID equals 'RAND_ID' )
	{
		name pitedge
		setvard RAND_ID $rand(1000,9999)
	}

	saytextrange 2048
	saytext var PARAM1 prop PARAM2 = $get(PARAM1,PARAM2)
	consolemsg PARAM5 [ [ RAND_ID ]  ] $get(ent_me,name) reports: var PARAM1 pvar $get(PARAM1,PARAM2)
	//dbg [ RAND_ID ] reports: var PARAM1 pvar $get(PARAM1,PARAM2)
}
