//Tests base_effect duration, and reports back info

//. effectme developer/effects/test_duration 10
//. effectmestack developer/effects/test_duration 10

//. eventme effect_increase_duration 10

#scope server

{
	const EFFECT_ID "test_duration"
	const EFFECT_SCRIPT $currentscript //Must be copied, as is, at the top script!
}

#include effects/base_effect	allowduplicate

{ game_activate

	infomsg all "Duration: " EFFECT_DURATION
	
	setvard game.effect.movespeed 0.01
}

{ duration_ended

	infomsg all game.time $math(add,EFFECT_STARTED,EFFECT_DURATION)
}

{ effect_die

	infomsg all "Effect has been killed." "DX"
}
