{
	array.create A_PLAYERS
	setvar TELEPORT_MODE 3
}

{ menu_tele_mode

	local reg.mitem.title "Go to player"
	local reg.mitem.type callback
	local reg.mitem.callback set_tele_mode
	local reg.mitem.data 0
	menuitem.register
	
	local reg.mitem.title "Bring player here"
	local reg.mitem.type callback
	local reg.mitem.callback set_tele_mode
	local reg.mitem.data 1
	menuitem.register
}

{ set_tele_mode

	setvard TELEPORT_MODE PARAM2
	callevent set_menu_type 0 16
}

{ menu_tele_player

	getplayersarray A_PLAYERS
	calleventloop $get_array_amt(A_PLAYERS) add_player_to_menu
}

{ add_player_to_menu

	local L_PLAYER $get_array(A_PLAYERS,game.script.iteration)
	if ( L_PLAYER isnot MY_OWNER )
	{
		local reg.mitem.title $get(L_PLAYER,name)
		local reg.mitem.type callback
		local reg.mitem.callback teleport_player
		local reg.mitem.data L_PLAYER
		menuitem.register
	}
}

{ teleport_player

	if ( TELEPORT_MODE == 0 )
	{
		setorigin MY_OWNER $get(PARAM2,origin)
	}
	else
	{
		setorigin PARAM2 $get(MY_OWNER,origin)
	}
} 