//Thothie mscave almost entirely underground - no rail plzktnx
//Setup the map's weather
//
{
	const MAP_NAME 		'kfortress'
	const MAP_WEATHER 	clear;clear;clear;clear;clear;clear
	const MAP_ALLOWNIGHT 	0

	setvarg G_MAP_NAME "The Kharaztorant Fortress"
	setvarg G_MAP_DESC "You've found what is rumored to be a fortress of the dragon worshipper's cult"
	setvarg G_MAP_DIFF "Levels 30-40 / 600-800hp"
	setvarg G_WARN_HP 600
}

#include worlditems/map_startup
