//final boss chest

#include chests/base_treasurechest

{ game_spawn

	callevent tc_add_artifact armor_pheonix55 8
}

{ chest_additems

	callevent add_gold $rand(100,600)

	addstoreitem  STORENAME health_spotion 1 0
	addstoreitem  STORENAME mana_mpotion 1 0

	addstoreitem  STORENAME item_charm_w2 1 0

	callevent add_epic_item
	callevent add_epic_item
	callevent add_great_item

	callevent add_epic_item
	callevent add_epic_item

	addstoreitem  STORENAME mana_speed 1 0
}
