// Treasure Chest #5 in A3 - In the cave.  You must kill 4 skeletons.

#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(10,50)
	//           |Store name|  |Item name|  		|Quantity| |cost|
	addstoreitem  STORENAME		blunt_maul			1		0
	addstoreitem  STORENAME		bows_shortbow		1		0

	if ( $rand(1,10) == 1 )
	{
		addstoreitem STORENAME proj_arrow_broadhead 60 0 0 30
	}

	if ( $rand(1,5) == 1 ) callevent add_noob_item
}