// Treasure Chest #1 in A3 - Near the player start, on a platform
#include chests/base_treasurechest

{ game_spawn

	callevent tc_add_artifact health_lpotion 25
	callevent tc_add_artifact armor_leather_torn 50
}

{ chest_additems

	callevent add_gold $rand(4,15)
	
	//           |Store name|  |Item name|      |Quantity| |cost|
	addstoreitem STORENAME item_torch 1  0
	addstoreitem STORENAME health_apple $rand(1,2) 0

	if ( $rand(1,6) == 1 ) addstoreitem STORENAME blunt_hammer1	1 0

	if ( $rand(1,6) == 1 ) addstoreitem STORENAME smallarms_dirk 1 0

	if ( $rand(1,20) == 1 ) callevent add_noob_item
	if ( $rand(1,20) == 1 ) callevent add_noob_item
}