{
   eventname treasure_spawn

   //old		$rand(24,44)
   const STORENAME nightmare_storeA36
}

#include items/base_treasurechest

{
   eventname chest_additems
   callevent get_players 300

	callevent add_gold 20 400 25

	addstoreitem STORENAME mana_mpotion TC_NPLAYERS_HALF 0
	addstoreitem STORENAME mana_resist_fire TC_NPLAYERS_QUART 0
	addstoreitem STORENAME swords_spiderblade 1 0

	callevent get_chance 30 20 100 300
	if ( GIVE_PRIZE ) addstoreitem STORENAME item_crystal_reloc TC_NPLAYERS_QUART 0
	callevent get_chance 30 20 100 300
	if ( GIVE_PRIZE ) addstoreitem STORENAME item_crystal_return 1 0
	callevent get_chance_rare 300
	if ( GIVE_PRIZE ) addstoreitem STORENAME mana_speed 1 0
}