// Treasure Chest #1 in A3 - Near the player start, on a platform
{
   setvar	STORENAME hard_storeA31
}

{
   eventname treasure_spawn

   ///old		$rand(20,40)
}

#include items/base_treasurechest

{
   eventname chest_additems

	callevent add_gold 20 200 25

	callevent get_players 200
	local HALF_PLAYERS TC_NPLAYERS
	divide HALF_PLAYERS 2
	local HALF_PLAYERS $int(TC_NPLAYERS)

   //           |Store name|  |Item name|      |Quantity| |cost|
   addstoreitem STORENAME item_torch TC_NPLAYERS 0
   addstoreitem STORENAME health_apple TC_NPLAYERS 0
   addstoreitem STORENAME blunt_warhammer HALF_PLAYERS 0
   addstoreitem STORENAME armor_plate HALF_PLAYERS 0
   addstoreitem STORENAME scroll2_glow TC_NPLAYERS 0
}