// Treasure Chest #4 in A3 - By the portal

{
   eventname treasure_spawn

   //gold			$rand(30,60)
   setvar STORENAME	nmare_storeA34
}

#include items/base_treasurechest

{ chest_additems

	callevent get_players 300
	callevent add_gold 25 200 25
	local NBOLTS 25
	multiply NBOLTS TC_NPLAYERS
	local NARROWS 30
	multiply NARROWS TC_NPLAYERS

	//           |Store name|  |Item name|  	|Quantity| |cost|
	addstoreitem STORENAME item_book_old 1 0
	addstoreitem STORENAME blunt_club 1 0
	addstoreitem STORENAME armor_leather_studded 1 0
	addstoreitem STORENAME drink_forsuth 1 0
	addstoreitem STORENAME proj_arrow_holy NARROWS 0 0 30
	callevent get_chance_uncommon 300
	if ( GIVE_CHANCE ) addstoreitem STORENAME proj_bolt_silver 25 0 0 25
	callevent get_chance_rare 300
	if ( GIVE_CHANCE ) addstoreitem STORENAME mana_immune_poison 1 0
}