// Treasure Chest #1 in A3 - Near the player start, on a platform

#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(20,100)

	//           |Store name|  |Item name|      |Quantity| |cost|
	addstoreitem STORENAME item_torch 1 0
	addstoreitem STORENAME health_apple 1 0
	addstoreitem STORENAME blunt_warhammer 1 0
	addstoreitem STORENAME armor_plate 1 0
	addstoreitem STORENAME scroll2_glow 1 0
}