// Treasure chest after you kill all the orcs in a3 [random quest]
//- nightmare variant

#include chests/base_treasurechest

{ chest_additems

   	addstoreitem STORENAME health_mpotion $rand(1,2) 0
	addstoreitem STORENAME bows_orcbow 1 0
	addstoreitem STORENAME proj_arrow_jagged 60 0 0 15
	addstoreitem STORENAME proj_arrow_fire 60 0 0 15
   	addstoreitem STORENAME armor_leather_studded 1 0

   	if ( $rand(1,15) == 1 ) addstoreitem STORENAME bows_swiftbow 1 0
	if ( $rand(1,30) == 1 ) addstoreitem STORENAME mana_speed 1 0
	if ( $rand(1,10) == 1 ) addstoreitem STORENAME mana_protection 1 0
	if ( $rand(1,30) == 1 ) addstoreitem STORENAME blunt_gauntlets_fire 1 0
}