#include chests/base_treasurechest

{ chest_additems

	callevent add_gold $rand(20,100)

	addstoreitem STORENAME mana_mpotion 1 0
	addstoreitem STORENAME mana_resist_fire 1 0
	addstoreitem STORENAME swords_spiderblade 1 0

	if ( $rand(1,10) == 1 ) addstoreitem STORENAME item_crystal_reloc 1 0
	if ( $rand(1,10) == 1 ) addstoreitem STORENAME item_crystal_return 1 0
	if ( $rand(1,10) == 1 ) addstoreitem STORENAME mana_speed 1 0
}