{ treasure_spawn

   gold		$rand(1,3)
   setvar	STORENAME treasure_storeA36
}

#include items/base_treasurechest

{ chest_additems
   
  //           |Store name|  |Item name|	|Quan|  |cost|
  addstoreitem  STORENAME     health_apple	2       0

  if ( $rand(1,6) == 1 )
  {
  addstoreitem  STORENAME     axes_axe		1	0
  }

  if ( $rand(1,6) == 1 )
  {
  addstoreitem  STORENAME     blunt_mace	1	0
  }
}