//Map settings
//
{ [shared]

	const MAP_NAME 		'nightmare_thornlands'
	const MAP_WEATHER 	"clear;clear;clear;snow;clear;snow"
	const MAP_ALLOWNIGHT 	1
	
	setvarg G_MAP_NAME "Nightmare Thornlands"
	setvarg G_MAP_DESC "This is the realm of Thornlands as it will be if Lor Malgorand is not stopped."
	setvarg G_MAP_DIFF "Levels 30-35 / 400-700hp"
	setvarg G_WARN_HP 400
	
	setvarg G_DARKEN_BLOOM 6
}

#include worlditems/map_startup