//Thothie - I percieve anything else in the Keledros script that would cause brain death
//- It seems very likely that the createNPC meathod does not clean out memory the same way a standard msmonster_spawn does
//- As such, I'm removing 3 spawners, and replacing with "greater animated warriors" and seeing if it helps various issues
//- Also adding new scrolls to Keledros when I get them (and him) working right

//- This spawn is no longer called by Keledros, but he does call an map event called spawn_archers
{
	name_unique spawner5
}

#include keledrosruins/spawner_base

{ spawn_undead
	////dbg Spawn5Alive $get(spawner2,alive)
	createnpc monsters/anim_warrior2 $get(ent_me,origin) $get(ent_me,id)
}