//Thothie - I percieve anything else in the Keledros script that would cause brain death
//- It seems very likely that the createNPC meathod does not clean out memory the same way a standard msmonster_spawn does
//- As such, I'm removing 3 spawners, and replacing with "greater animated warriors" and seeing if it helps various issues
//- Also adding new scrolls to Keledros when I get them (and him) working right
{
	name_unique spawner1
}

#include keledrosruins/spawner_base

{ spawn_undead

	if ( ONE_IS_DEAD == 1 ) createnpc monsters/anim_archer $get(ent_me,origin) $get(ent_me,id)
	callexternal ent_lastcreated one_was_summoned
}