//Thothie - the dynamic weather via ms_npcscript for Avazool
//- should work... doesn't... Only responds to first event, subsequent ones don't even reach the script
//- (play with this some more) - try including it in amonster, or redoing the test map
{
  	const SCRIPT_SFX1		effects/sfx_lightning
	const LTNG_SND			weather/Storm_exclamation.wav
	precache SCRIPT_SFX1
	precache LTNG_SND

	const WEATHER_SPRITE rain.spr
	const SPRITE_SPLASH rain_splash.spr
	const SPRITE_MIST rain_mist.spr
	const SPRITE_RIPPLE rain_ripple.spr
	const SOUND_RAIN weather/rain.wav
	precache WEATHER_SPRITE
	precache SPRITE_SPLASH
	precache SPRITE_MIST
	precache SPRITE_RIPPLE
	precache SOUND_RAIN

	const WEATHER_SPRITE snow1.spr
	const SPRITE_BREATH char_breath.spr
	const SOUND_AMB amb/wind.wav
	precache WEATHER_SPRITE
	precache SPRITE_BREATH
	precache SOUND_AMB

}

{ rain 

	//dbg Got Rain Command
	callexternal all game_playercmd_setweather rain 1 1 0 0 0 0
}

{ snow 

	//dbg Got Snow Command
	callexternal all game_playercmd_setweather snow 1 1 0 0 0 0
}

{ storm 

	//dbg Got storm Command
	callexternal all game_playercmd_setweather storm 1 1 0 0 0 0
}

{ weather_clear 

	//dbg Got clear Command
	callexternal all game_playercmd_setweather clear 1 1 0 0 0 0
}