//Healer - sells weak potions and weak spells

{
	const SOUND_DEATH none			//base_npc

	//base_vendor
   	setvar STORE_NAME edana_healer
   	setvar STORE_TRIGGERTEXT "store trade buy sell purchase sale offer"
	setvar STORE_SELLMENU 1
	setvar EVIDENCE_FOUND 0
	const NO_JOB 1
}

#include monsters/base_npc
#include monsters/base_chat
#include monsters/base_npc_vendor
#include monsters/base_npc_vendor_confirm

{ npc_spawn

   hp 60
   gold 0
   name Hartold the Mage
   //ov 30
   width 32
   height 72
   race human
   roam 0
   setmodel    npc/balancepriest1.mdl
   invincible  1

   catchspeech say_hi hi hello hail greet  hey
   catchspeech say_rumor rumours rumor news happenings
}

{  [override] game_targeted_by_player

	callevent help_vendor_magic PARAM1
}

//call for sale
{
   repeatdelay 25

   if $cansee(player,256)

   saytext Puh-potions! I-I got potions!
}

{ say_hi
   saytext He- He- Howdy! How about so-some po-,po-,po-, healing items?
}


{ vendor_addstoreitems

   //           |Store name|  |Item name|  		|Quantity| 	|cost%|	
   addstoreitem  STORE_NAME    health_mpotion		 30		 100 0.1
   addstoreitem  STORE_NAME    health_lpotion		 30		 110 0.1
   addstoreitem  STORE_NAME    scroll_fire_dart		 $rand(0,1)	 120
   addstoreitem  STORE_NAME    scroll_lightning_weak	 $rand(0,1)	 120
   addstoreitem  STORE_NAME    scroll2_glow		 1		 120
   addstoreitem  STORE_NAME    mana_mpotion		 5  		 105 0.1
   addstoreitem  STORE_NAME    scroll_rejuvenate	 1  		 200	0.1
   addstoreitem  STORE_NAME    scroll2_rejuvenate	 1		 800	0.1
   addstoreitem  STORE_NAME    sheath_spellbook		 $rand(1,2)	 100	0.1

   if( $rand(1,3) == 1 ) addstoreitem  STORE_NAME     health_spotion   	 $rand(1,4)          100
}

//Rumours
{ say_rumor

  playanim once pondering
  callevent 1.5 say_rumour2
}
{ say_rumour2

  saytext I h-hear the fletcher will buy hawk f-feathers at a very high price.
  callevent 3 say_rumour3
}

{ say_rumour3
  if EVIDENCE_FOUND equals 1
  saytext Oh! A-and the may-o-r has be-en found a trai-tor!
}

{ worldevent_evidence_found

  setvar EVIDENCE_FOUND 1
}