//Master Priest Sembelbin rewrite 9:47 AM 7/13/2010 by Thothie

#scope server
{
	const IDLE_ANIMLIST "idle1;idle3;idle4;idle5;idle6;idle7" //(model has no idle2)

	const CHAT_DELAY 5.0
	const CHAT_AUTO_HAIL 1 //adds say_hi catchspeech and menu item
	const CHAT_AUTO_JOB 1 //adds say_job catchspeech and menu item
	const CHAT_AUTO_RUMOR 1 //adds say_rumor catchspeech and menu item

	const CHAT_NEVER_INTERRUPT 1

	const XMASS_OLD_GUY 1
}

#include monsters/base_chat_array
#include help/first_npc
#include monsters/base_xmass

{ [shared] game_spawn

	hp 1
	name Sembelbin
	width 32
	height 72
	race beloved
	roam 0
	setmodel npc/balancepriest1.mdl
	invincible 1
	nopush 1

	saytextrange 1024

	setidleanim idle1

	if game.serverside

	catchspeech say_hi hail hi j0 yo waddup wassup gweets greetings
	catchspeech say_rumor deed rumor rumour
	catchspeech say_job job work quest

	catchspeech say_apostles apostle
	catchspeech say_bloodrose blood
	catchspeech say_changes changes
	catchspeech say_city city cities
	catchspeech say_elves elve elf elve
	catchspeech say_forest forest sfor
	catchspeech say_history Undamael history
	catchspeech say_thornlands land
	catchspeech say_loreldians loreldians
	catchspeech say_malgor malgor "lor "
	catchspeech say_orcs orc orcs 
	catchspeech say_helena helena 
	catchspeech say_felewyn felewyn 
	catchspeech say_temple temple church
	catchspeech say_temple3x more
	catchspeech say_torkalath tork
	catchspeech say_undead undead
	catchspeech say_unbal unbalance
	catchspeech say_unquest unquest
	catchspeech say_pathos pathos
	catchspeech say_thelost lost fate
	catchspeech say_aob "age of"
	catchspeech say_urdual urdual
	catchspeech say_shad shad
	catchspeech say_maldora mald

	catchspeech say_pillarquest xyphemox ring rune runes
	catchspeech say_allIknow zahlon erste
	
	callevent load_chat

	callevent scan_for_players
}

{ scan_for_players

	if ( !DID_INTRO ) callevent 2.0 scan_for_players

	if !DID_INTRO

	if $cansee(player)
	if $get(ent_lastseen,maxhp) < 10

	setvard DID_INTRO 1
	callevent do_intro
}

{
repeatdelay $randf(8.0,12.0)
	if !CHAT_BUSY
	local N_IDLES $get_token_amt(IDLE_ANIMLIST)
	subtract N_IDLES 1
	local RND_IDLE $rand(0,N_IDLES)
	local RND_IDLE_ANIM $get_token(IDLE_ANIMLIST,RND_IDLE)
	playanim once RND_IDLE_ANIM
}

{ do_intro
	if !CHAT_BUSY
	callevent chat_now "Ahh, another adventurer! Please, come here and speak with me!" 3.0 gluonshow
}

{ load_chat

	//note, overflow happens around colum 100

	callevent chat_add_text say_intro "Ahh, another adventurer! Please, come here and speak with me!" 3.0 gluonshow
	callevent chat_add_text say_intro "I've been recently disturbed by the [changes] around the [Thornlands]."

	callevent chat_add_text say_hi "Greetings, young adventurer. What brings you here? I have knowledge of many things..." CHAT_DELAY talkright
	callevent chat_add_text say_hi "I can tell you of the [history], the [land], the [cities] and other places; and of the [Unbalance] that has recently reached our [temple]."

	callevent chat_add_text say_city "We are on the outskirts of Edana, the largest city in the Southeast. To the northeast is [Helena], on the borders of the plains of Daragoth." 6.0
	callevent chat_add_text say_city "Beyond those dangerous planes lies Deralia, the jewel of civilization and capital of the kingdom."
	callevent chat_add_text say_city "North of [Thornlands], past the nexus of [Bloodrose], lies the [Elven] city Kray Eldorad."
	callevent chat_add_text say_city "But troubles in the [Bloodrose] pass have made travel difficult, and thus sightings of [elves] are rare indeed."

	callevent chat_add_text say_bloodrose "Bloodrose lies beyond the [Thornlands], between the human lands, and those of the [elves]."
	callevent chat_add_text say_bloodrose "Strange troubles there have all but cut off the connections between our two peoples."

	callevent chat_add_text say_elves "The elves are the first of the Enlightened Races, most closely resembling the goddess who created them."
	callevent chat_add_text say_elves "They are a people of fierce honor, and wondrous majesty."

	callevent chat_add_text say_loreldians "The Loreldians, former keepers of this world, masters of a forbidden magic that nearly destroyed all that is."
	callevent chat_add_text say_loreldians "After the great Wars of Fate, only but a handful remained, and they vowed to banish themselves from this world."
	callevent chat_add_text say_loreldians "This, to save it from inevitable destruction at their own hands, for they had indeed become that powerful."
	callevent chat_add_text say_loreldians "Three were elected by [Pathos] to stay behind, and these are the great guardian gods we know today as The Triad:"
	callevent chat_add_text say_loreldians "[Felewyn] of Order, [Torkalath] of Chaos, and [Urdual] of Balance."

	callevent chat_add_text say_unbal "Recently, the [undead] have begun returning, plaguing the lands. Also, an alarming number of [orcs] have appeared."
	callevent chat_add_text say_unbal "These are all thought to be indications of a great imbalance, looming on the horizon."

	callevent chat_add_text say_pathos "The Golden God, the Shining One, the Guardian who awaits beyond The Gate of Dreams, many are the names of this most exalted, and most distant god of gods." 7.0
	callevent chat_add_text say_pathos "He has no temples, but each temple of The Triad has an aspect of Pathos within it, for it is He who chose our gods from among His people before leaving this world." 7.0
	callevent chat_add_text say_pathos "It is He who saved the world from the War of Fate through self-sacrifice and denial of His own desires and those of His own kin." 7.0
	callevent chat_add_text say_pathos "It is He who returned from The Beyond, for a time, to save us from destruction at the hands of the mad [Lor Malgoriand], ending the [Age of Blood]." 7.0
	callevent chat_add_text say_pathos "The Triad of gods he left to guard us complement one another and sustain the world. It is in His infinite wisdom that this diametric opposition was created." 7.0
	callevent chat_add_text say_pathos "For Pathos knew, while no [Loreldian] has within Himself the power to slay another, and it requires two to imprison a third..." 7.0
	callevent chat_add_text say_pathos "...it takes no less than three to destroy a forth forever."
	callevent chat_add_text say_pathos "Thus is the eternal reign of The Triad ensured, as is their eternal struggle, from which all progress is born."

	callevent chat_add_text say_temple "This temple is dedicated to Urdual, the venerable and wise deity of balance."
	callevent chat_add_text say_temple "Urdual's fate is to balance. Where there is too much order, he creates chaos. Where there is too much chaos, he creates order."
	callevent chat_add_text say_temple "It is he who forged the hearty Dwarves, who can live deep within the mountains, and thus separate themselves from the cycles of chaos and order."
	callevent chat_add_text say_temple "Do you wish to know [more] of the temple?"

	callevent chat_add_text say_temple_more "There's a reason for the somewhat 'unusual' way a temple of [Urdual] such as this is built."
	callevent chat_add_text say_temple_more "Each stone that forms this delicate structure has been blessed in another order's temple."
	callevent chat_add_text say_temple_more "The dark side of this temple is imbued with the strength of the god of chaos and freedom, [Torkalath]..."
	callevent chat_add_text say_temple_more "While the bright side is imbued with the power of order and law that emanates from [Felewyn's] shrines."
	callevent chat_add_text say_temple_more "The gold between them represents the founding power of [Pathos] which binds them together in common cause."
	callevent chat_add_text say_temple_more "It's a delicate balance. Would one side be slightly too weak or powerful, the entire temple may crack and crumble."
	callevent chat_add_text say_temple_more "If the power of chaos or order overwhelms an area, the nearby temples of [Urdual] often become asymmetric, and crack."
	callevent chat_add_text say_temple_more "Many such 'cracked' temples are scattered across the land..." 3.0
	callevent chat_add_text say_temple_more "Most are filled with monsters, bent on spawning yet more unbalance." 3.0
	callevent chat_add_text say_temple_more "Here, all is well enough, for now. But watch your step, for the paths of light and darkness are known to be a bit tricky."
	
	callevent chat_add_text say_history "Much of history is tainted by darkness, and amongst the darkest of these taints is the Lord Undamael."
	callevent chat_add_text say_history "The final abominable creation of [Lor Malgoriand], surviving even his master's defeat, he was eventually overcome by the power of a cabal of five powerful magi." 7.0
	callevent chat_add_text say_history "The army of [undead], which was under his command, has scattered. But some say the lord himself still lives on..."
	callevent chat_add_text say_history "It is said that it is he who causing the eternal night which has befallen the [forest] to the west."

	callevent chat_add_text say_forest "The forest to the west was once beautiful, but ever since the evil came, the place has been cursed."
	callevent chat_add_text say_forest "Now it is called Eswen Meldanual, meaning 'Forest of Midnight.'"
	
	callevent chat_add_text say_malgor "Ahh, Lor Malgoriand, as he was dubbed by the elves, litterally 'The Bringer of Darkness.'"
	callevent chat_add_text say_malgor "Hundreds of years ago he brought ruin and death to three quarters of the known world!"
	callevent chat_add_text say_malgor "If not for Lor Malgoriand, we would not have to deal with the [orcs] and mayhaps not even the [undead]."
	callevent chat_add_text say_malgor "Though he began as an [Apostle] of [Torkalath], tasked with restoring the balance, he had become infected with the madness of [The Lost]."
	callevent chat_add_text say_malgor "Though defeated by the [Apostles] after much bloodshed, his power and his minions still linger..."
	callevent chat_add_text say_malgor "...and there are many who believe he may one day return."

	callevent chat_add_text say_thelost "In times before man and dwarf and even elf, there were the Gods of Fate, known as [Loreldians], who banished themselves from this world."
	callevent chat_add_text say_thelost "But among these gods were those that refused to leave... Thus began the war of the gods, The Great War of Fate."
	callevent chat_add_text say_thelost "When the war concluded, those gods of hate and greed had their very existence stricken from all time and memory, and thus are forever known only as 'The Lost'." 7.0
	callevent chat_add_text say_thelost "But their power was such and their hate was so strong, that even with their souls shredded and scattered across the cosmos, the shadow of their evil remained." 7.0
	callevent chat_add_text say_thelost "That hate now infects the outermost edges of the very Threads of Fate, and is constantly searching for ways into our world."
	callevent chat_add_text say_thelost "Sometimes it succeeds and causes great disturbances, manifestations of pure violence and destruction. Mindless horrors beyond imagining." 7.0
	callevent chat_add_text say_thelost "Sometimes those truly lost in misery, hatred, or despair, find themselves possessed by the power of this ancient force."
	callevent chat_add_text say_thelost "Such was the case of [Lor Malgoriand], once a mighty [Apostle] of [Torakalath], he was seduced by the power of The Lost."
	callevent chat_add_text say_thelost "This was unbeknownst to all, until it was too late."

	callevent chat_add_text say_apostles "The Apostles are the warriors of Fate, patrons of the gods, their power drawn upon that of the [Loreldians] themselves."
	callevent chat_add_text say_apostles "None knows what became of those who helped defeat [Lor Malgoriand] at the close of the [Age of Blood]."
	callevent chat_add_text say_apostles "We only pray that they can be called upon once again when the need will arise, as there is no doubt it will."

	callevent chat_add_text say_rumor "Rumors? Well... I do know of one... Let me tell you a local story..."
	callevent chat_add_text say_rumor "Years ago, Deralia was ruled by a Tyrant-King. Only one man dared to challenge him: Kustrin, then mayor of Edana."
	callevent chat_add_text say_rumor "Kustrin was assassinated, which so infuriated his son that he went to Deralia to settle the score."
	callevent chat_add_text say_rumor "The king was arrogant, and not about to show fear of a little boy. He accepted the challenge to a duel."
	callevent chat_add_text say_rumor "What the king did not know was that the son had been studying swordplay all his life: thus the king was slain."
	callevent chat_add_text say_rumor "The boy's name?  You'll soon meet him if you haven't already.  But watch out, don't tread on his flowers!"

	callevent chat_add_text say_pq "Oh my, that ancient ring belonged to the legendary high priest Zahlon Erste."
	callevent chat_add_text say_pq "Xyphemox was his title name in the Order of Urdual." 3.0
	callevent chat_add_text say_pq "Legend has it that he was slain shortly after imprisoning the undead sorcerer [Shadahar]."
	callevent chat_add_text say_pq "It is foretold... That a fool of great power shall release [Shadahar] from his tomb."
	callevent chat_add_text say_pq "Thus marking the beginning of a great imbalance." 3.0
	callevent chat_add_text say_pq "Perhaps you are that fool?" 2.0 retina

	callevent chat_add_text say_allIknow "That is all I know on the subject, for I no longer venture beyond these halls."
	callevent chat_add_text say_allIknow "If there is more to discover, I'm afraid it is up to you to do so."

	callevent chat_add_text gave_ring "I suppose you are that fool after all." CHAT_DELAY idle4
	callevent chat_add_text gave_ring "The prophecy is clear, as is my duty, though I am loathed to perform it."
	callevent chat_add_text gave_ring "I shall restore the magic of this ring, and return it to you, as is ordained."
	callevent chat_add_text gave_ring "But woe is thee, for thou art the Ring Bearer, and harbinger of [Shadahar's] return." CHAT_DELAY gluonshow
	callevent chat_add_text gave_ring "Do with this ring as thou wilt, and I pray this evil shall yet be turned to good by your hand." CHAT_DELAY kneel

	callevent chat_add_text say_felewyn "Felewyn is the goddess of order and law. [Elves] worship her as their creator, save for those who serve [Torkalath] or [Urdual]."
	callevent chat_add_text say_felewyn "But those few are shunned, sometimes even hunted, by their more traditional kin."
	callevent chat_add_text say_felewyn "It is she who brought forth the herd animals and the hive-minded worker insects and other creatures of a calm and orderly nature in ages past..."
	callevent chat_add_text say_felewyn "She encourages those would uphold the law of the land over their own selfish desires, who protect the weak from the strong, and maintain discipline and order."

	callevent chat_add_text say_torkalath "Torkalath is the god of strength, of freedom, and of chaos. He believes in strengthening ones self through strife and struggle."
	callevent chat_add_text say_torkalath "He encourages those who defend their individuality, who resist conformity, and those who realize their fullest potential in whatever they may do."
	callevent chat_add_text say_torkalath "He created the great predatory beasts of the land during the recovery that followed the War of Fate, granting them strength, cunning, and grace."
	callevent chat_add_text say_torkalath "It is He who eventually forged the soul of man: ever striving and ever ambitious, flexible, adaptable, and clever."
	callevent chat_add_text say_torkalath "He gifted the [Orcs] to [Lor Malgoriand] at the beginning of the [Age of Blood], and created many of the other great warrior races that dot the lands."

	callevent chat_add_text say_urdual "Urdual is the god of balance." 3.0
	callevent chat_add_text say_urdual "The eldest of The Triad, His wisdom is sought after by the other two gods to determine the path of the ever-swinging pendulum of order and chaos."
	callevent chat_add_text say_urdual "[Torkalath] and [Felewyn] are at constant odds, and thus [Urdual] serves as the mediator between the two opposing forces of law and freedom."
	callevent chat_add_text say_urdual "After the War of Fate, it was He who established the never ending cycles of nature. May they endure eternally."
	callevent chat_add_text say_urdual "It is He who created the dwarven race, hearty and stoic, and as unshakable as the stones."
	callevent chat_add_text say_urdual "They dwell in the mountains that they may separate themselves from the constant conflicts of the lands. This allows them to play as impartial observers."
	callevent chat_add_text say_urdual "...Though it seems their quizzical nature rarely allows them to be exactly that."

	callevent chat_add_text say_aob "The Age of Blood of centuries past, describes the nearly two hundred year long war that ended The Crystal Eon of perfect order that came before it."
	callevent chat_add_text say_aob "It began at a time when order was so strong that all was stagnant, and they very freedom of thought itself was threatened!" 7.0
	callevent chat_add_text say_aob "But so violent was this war, that it broke beyond any new equilibrium, and into a terminal bloody chaos that threatened to engulf the world." 7.0
	callevent chat_add_text say_aob "[Lor Malgoriand], Torkalath's newest [Apostle], the strongest He had ever imbued with power, had been tasked with ending The Crystal Eon..." 7.0
	callevent chat_add_text say_aob "...but alas, he was mad with grief from the moment of his endowment."
	callevent chat_add_text say_aob "This made him vulnerable to the influence of [The Lost], and before even the gods themselves had known it, he was consumed by the harnessing of their power." 7.0
	callevent chat_add_text say_aob "It was for this reason that even when Torkalath revoked the power He had given His creation, [Lor Malgoriand] did not die."
	callevent chat_add_text say_aob "Instead, he grew only stronger, and more possessed of hatred."
	callevent chat_add_text say_aob "The war ended, with the return of the prophetic [Pathos], the rise of the [Apostle] Lanethan..."
	callevent chat_add_text say_aob "...and the eventual slaying of [Lor Malgoriand] at the hands of [Felewyn] Herself."
	callevent chat_add_text say_aob "[Pathos] has left us again, returning to his sleeping comrades, and the [Apostles] of that age have also vanished, but He promised that,"
	callevent chat_add_text say_aob "'In the The Beyond He dreams only of us, and thus He watches, and will return, should He be needed again."

	callevent chat_add_text say_orcs "The orcs were the first living, breathing tools of [Lor Malgoriand]."
	callevent chat_add_text say_orcs "The first were the ice dwelling Maragor tribe, but soon after came the heat loving Borsh, or the [Shadahar] Tribe, as they are now known..."
	callevent chat_add_text say_orcs "Lastly, he created the huge and all encompassing Black Hand tribe."
	callevent chat_add_text say_orcs "The Black Hand raids villages regularly in these parts to this day. It wasn't so long ago they nearly destroyed [Helena]."
	callevent chat_add_text say_orcs "Although the orcs and the [undead] were both tools of [Lor Malgoriand], without their master, it seems they are no longer willing to cooperate."
	callevent chat_add_text say_orcs "This is fortunate for us! Indeed, it is the main reason we've managed to maintain the kingdom for so long, despite the hardships."

	callevent chat_add_text say_undead "The undead and the [orcs] were among the many vile tools of [Lor Malgoriand] of [The Lost], amongst other evils."
	callevent chat_add_text say_undead "Recently, a great force of undead has begun clawing its way up through the ground."
	callevent chat_add_text say_undead "If you can find some way to slow their progress, I would be very grateful."
	callevent chat_add_text say_undead "Bring me any relics you can find upon their dismembered corpses, and I will judge their usefulness."

	callevent chat_add_text say_name_change "For a fee, I can submit for a change of name permit from the King of Deralia, and officially change your name throughout the lands."
	callevent chat_add_text say_name_change "Beware, however, this fee increases exponentially each time, beginning at 100 gold."
	callevent chat_add_text say_name_change "Do you really wish to have your name changed?"

	callevent chat_add_text say_shad "Shadahar was a feared necromancer just prior to the [Age of Blood]."
	callevent chat_add_text say_shad "Though his more ambitious activities were kept in check by the forces of order, that were so prevalent at the time, he built many great palaces." 7.0
	callevent chat_add_text say_shad "These were necropolises, where he stored armies of the dead, and other abominations, as he lie in wait for an age when he could rise to power." 7.0
	callevent chat_add_text say_shad "Before his dreams could be realized, however, he was imprisoned by the Xyphemox Zahlon Erste."
	callevent chat_add_text say_shad "His greatest palace, a hall of great majesty hidden somewhere in the Aluhandra desert, lay abandon for centuries."
	callevent chat_add_text say_shad "But at the end of the [Age of Blood], the Borsh [orc] tribe, having been soundly defeated by the [elves], took refuge within its walls." 7.0
	callevent chat_add_text say_shad "As they bided their time there, they were soon infected with its power."
	callevent chat_add_text say_shad "Their chief, the immortal Rungahr, together with his shamans, unlocked many of the necromancer's secrets."
	callevent chat_add_text say_shad "Under their chief's guidance, these enchanted orcs have become the most powerful in all the lands, and thus renamed themselves the tribe of Shadahar." 7.0
	callevent chat_add_text say_shad "Thankfully, however, they rarely wander very far from their home of Shadahar, for it is the source of their power."

	callevent chat_add_text say_maldora "Ah Maldora... He is a mysterious one. A powerful wizard indeed, some say he may even be the reincarnation of [Lor Malgoriand] himself." 7.0
	callevent chat_add_text say_maldora "There have been rumors of sightings of an ancient [Loreldian] flying fortress, at the very northern edges of the lands."
	callevent chat_add_text say_maldora "These same rumors claim that Maldora resides within that fortress."
	callevent chat_add_text say_maldora "Such fortresses have not been seen since the [Age of Blood] and even then, they were indeed rare."
	callevent chat_add_text say_maldora "Thus, if the rumors to be believed, then Maldora has achieved power almost beyond imagination. Who knows what evil he may bring upon us all?"
}

{ say_hi
	callevent chat_start_sequence say_hi
}

{ say_city
	callevent chat_start_sequence say_city
}

{ say_bloodrose
	callevent chat_start_sequence say_bloodrose
}

{ say_elves
	callevent chat_start_sequence say_elves
}

{ say_loreldians
	callevent chat_start_sequence say_loreldians
}

{ say_unbal
	callevent chat_start_sequence say_unbal
}

{ say_thornlands
	callevent chat_now "The Thornlands was once a beautiful place to visit, but the [unbalance] has destroyed its former luster."
}

{ say_changes
	callevent chat_now "The grass rots. Birds and beasts die. The land is sick. Something must be done to stop the [undead]."
}

{ say_job
	if ( CHAT_BUSY ) callevent chat_busy_message
	if !CHAT_BUSY
	callevent chat_now "Well newcomers often look into town for such matters."
	if EVIDENCE_FOUND
	callevent CHAT_DELAY say_job2 
}

{ say_job2
	callevent chat_now "Maybe you could become an errand runner for the next mayor?" 3.0 retina
}

{ worldevent_evidence_found
	setvard EVIDENCE_FOUND 1
}

{ say_pathos //new
	callevent chat_start_sequence say_pathos
}

{ say_temple
	callevent chat_start_sequence say_temple
}

{ say_temple3x
	callevent chat_start_sequence say_temple_more
}

{ say_history
	callevent chat_start_sequence say_history
}

{ say_forest
	callevent chat_start_sequence say_forest
}

{ say_malgor
	callevent chat_start_sequence say_malgor
}

{ say_thelost //new
	callevent chat_start_sequence say_thelost
}

{ say_apostles
	callevent chat_start_sequence say_apostles
}

{ say_rumor
	callevent chat_start_sequence say_rumor
}

{ say_pillarquest
	if ( $item_exists(ent_lastspoke,item_runicsymbol2) )
	{
		callevent chat_start_sequence say_allIknow
	}
	else
	{
		if $item_exists(ent_lastspoke,item_runicsymbol)
		setvard RING_EXPLAINED 1
		callevent chat_start_sequence say_pq
	}
}

{ show_ring
	setvard RING_EXPLAINED 1
	callevent chat_start_sequence say_pq
}

{ gave_ring
	
	setvard RING_BEARER PARAM1
	callevent chat_start_sequence gave_ring
	callevent 16.0 gave_ring2
}

{ gave_ring2
	offer RING_BEARER item_runicsymbol2
}

{ say_felewyn

	callevent chat_start_sequence say_felewyn
}

{ say_torkalath
	callevent chat_start_sequence say_torkalath
}

{ say_urdual
	callevent chat_start_sequence say_urdual
}

{ say_aob //new
	callevent chat_start_sequence say_aob
}

{ say_helena
	callevent chat_now "Helena is a trading outpost in the center of the human lands. Recently rebuilt, it still struggles to survive."
}

{ say_undead
	callevent chat_start_sequence say_undead
}

{ say_orcs
	callevent chat_start_sequence say_orcs
}

{ say_shad
	callevent chat_start_sequence say_shad
}

{ say_maldora
	callevent chat_start_sequence say_maldora 
}

//===========
{ say_unquest

	playanim critical magic
	infomsg ent_lastspoke DEBUG Quests data is being removed from your character.
	quest unset ent_lastspoke emote_sitting
	quest unset ent_lastspoke quest_ring
}

{ change_name_intro

	if ( CHAT_BUSY ) callevent chat_busy_message
	if !CHAT_BUSY

	if ( !$get(PARAM1,isplayer)	) setvard NAME_REQ_ID $get(ent_lastspoke,id)
	if ( $get(PARAM1,isplayer) ) setvard NAME_REQ_ID $get(PARAM1,id)

	callevent chat_start_sequence say_name_change
	callevent 12.0 send_name_change_menu

	setvard DID_CHANGE_INTRO 1
	setvard SENDING_YN 1
	setvard CHAT_MENU_ON 0
}

{ send_name_change_menu
	menu.open NAME_REQ_ID
}

{ game_menu_cancel

	if DID_CHANGE_INTRO
	setvard DID_CHANGE_INTRO 0
	setvard CHAT_MENU_ON 1
}

{ game_menu_getoptions

	setvard USER_ID PARAM1

	if !EXIT_SUB

	if ( !SENDING_YN )
	{
		if ( !DID_CHANGE_INTRO )
		{
			local reg.mitem.title 	"Change my name"
			local reg.mitem.type 	callback
			local reg.mitem.callback change_name_intro
			menuitem.register
		}

		if ( $item_exists(PARAM1,item_runicsymbol) )
		{
			if ( !RING_EXPLAINED )
			{
				local reg.mitem.title 	"Show the Expended Ring"
				local reg.mitem.type 	callback
				local reg.mitem.callback show_ring
				menuitem.register
			}
			else
			{
				local reg.mitem.title 	"Give the Expended Ring"
				local reg.mitem.type 	payment
				local reg.mitem.data 	item_runicsymbol
				local reg.mitem.callback gave_ring
				menuitem.register

			}
		}
	}

	if ( SENDING_YN )
	{

		local CHANGE_NAME_TIMES $get_quest_data(PARAM1,n)
		//dbg got_name_change_fee CHANGE_NAME_TIMES from $get(PARAM1,name)
		if ( CHANGE_NAME_TIMES == 0 ) local CHANGE_NAME_FEE 100
		if ( CHANGE_NAME_TIMES == 1 ) local CHANGE_NAME_FEE 1000
		if ( CHANGE_NAME_TIMES == 2 ) local CHANGE_NAME_FEE 10000
		if ( CHANGE_NAME_TIMES == 3 ) local CHANGE_NAME_FEE 100000
		if ( CHANGE_NAME_TIMES == 4 ) local CHANGE_NAME_FEE 1000000
		if ( CHANGE_NAME_TIMES >= 5 ) local CHANGE_NAME_FEE 10000000


		local reg.mitem.title 	"Yes"
		local reg.mitem.type 	payment
		local reg.mitem.data gold: CHANGE_NAME_FEE
		local reg.mitem.callback change_name_yes
		local reg.mitem.cb_failed change_name_payment_failed
		menuitem.register

		saytext The fee for this service, in your case, would be CHANGE_NAME_FEE gold.

		local reg.mitem.title 	"no"
		local reg.mitem.type 	callback
		local reg.mitem.callback change_name_no
		menuitem.register

		setvard SENDING_YN 0
		setvard CHAT_MENU_ON 1
	}
}

{ change_name_payment_failed
	playanim critical no
	callevent chat_now "I'm afraid you do not have sufficient funds to cover the king's fees." 3.0 none clear_que
	setvard DID_CHANGE_INTRO 0
	setvard CHAT_MENU_ON 1
}

{ change_name_no
	playanim critical yes
	callevent chat_now "That is quite all right, it is better to be certain of one's identity than to change it on a whim." 4.0 none clear_que
	setvard DID_CHANGE_INTRO 0
	setvard CHAT_MENU_ON 1
}

{ change_name_yes
	callevent chat_now "Speak forth the name you shall hence forth be known as..." 3.0 none clear_que
	setvard CHANGING_NAME 1
}

{ game_heardtext //PARAM1=text PARAM2=player_id (general catch for local speech)

	if CHANGING_NAME
	if ( G_DEVELOPER_MODE ) gplayermessage $get(PARAM2,id) Zomg $get(PARAM2,name) spoke to me! $get(ent_lastspoke,name)
	//ent_lastspoke not working in this context :\
	if ( $get(PARAM2,id) isnot NAME_REQ_ID ) saytext Shush, $get(NAME_REQ_ID,name) here is going to provide me with his new name.
	if $get(PARAM2,id) equals NAME_REQ_ID
	local L_NEW_NAME PARAM1
	local L_SPACE " "
	if ( $left(L_NEW_NAME,1) equals L_SPACE )
	{
		saytext I'm sorry, but you cannot begin your name with a space.
		local EXIT_SUB 1
	}
	if !EXIT_SUB

	if ( L_NEW_NAME isnot $alphanum(L_NEW_NAME,L_SPACE) )
	{
		saytext I'm sorry, but your name seems to have some characters in it that will not fit in the paperwork.
		infomsg NAME_REQ_ID "Alphanumerics and Spaces Only Please" "Otherwise, bad things would happen."
		local EXIT_SUB 1
	}
	if !EXIT_SUB

	if ( $len(L_NEW_NAME) > 30 )
	{
		saytext I'm sorry, but your name is too long.
		infomsg NAME_REQ_ID "Name must be under 30 characters" "Otherwise, bad things would happen."
		local EXIT_SUB 1
	}
	if !EXIT_SUB

	if ( L_NEW_NAME equals 'Saint Thoth' ) local L_NICE_TRY 1
	if ( L_NEW_NAME equals 'Thothie' ) local L_NICE_TRY 1
	if ( L_NEW_NAME equals 'Saint Thothie' ) local L_NICE_TRY 1

	if ( L_NICE_TRY )
	{
		saytext Yeeeaaah... No.
		playanim critical no
		exitevent
	}

	local L_NEW_NAME $alphanum(L_NEW_NAME,L_SPACE) //final sanitize

	local CHANGE_NAME_TIMES $get_quest_data(NAME_REQ_ID,n)
	local CHANGE_NAME_TIMES $int(CHANGE_NAME_TIMES)
	add CHANGE_NAME_TIMES 1
	quest set NAME_REQ_ID n CHANGE_NAME_TIMES
	local OLD_NAME $get(NAME_REQ_ID,name)
	playername NAME_REQ_ID L_NEW_NAME
	local MSG_TXT "From this day forth, "
	stradd MSG_TXT OLD_NAME
	stradd MSG_TXT " shall now be known as "
	stradd MSG_TXT L_NEW_NAME
	stradd MSG_TXT "!"

	infomsg all "A PROCLOMATION RINGS THROUGHOUT THE LAND!" MSG_TXT
	playanim critical talkright
	local OUT_STR "Very well, from this day forth your name shall be "
	stradd OUT_STR L_NEW_NAME
	callevent chat_now OUT_STR 3.0 none abort
	setvard DID_CHANGE_INTRO 0
	setvard CHANGING_NAME 0
	setvard CHAT_MENU_ON 1
}