//By greatguys1
//Best viewed in EditPlus with the ms.stx applied

//Races: (If the npc must survive, he will become human once the quest is activated, and go back to your defined race once the quest is complete.)
//	beloved	//Nothing will attack this race
//	human //Will be targetable by hostile enemies, but cannot be damaged by friendies or players

//Qitem codes: (The ap, bs, bp, ect. are the codes. The things in the quotes are the default names to them. They are renameable in quests that use these)	Ripped from other/qitems
//	ap - "a|Golden Apple"
//	bs - "a|Bag of Salt"
//	bp - "a|Bag of Pepper"
//	km - "a|Barrel of Mead"
//	la - "Sylphiel's Ladel"
//	tnt - "a stick of|Dwarven Explosives"
//	gen1 - "a|Package of Something" //(these use the generic item package model)
//	gen2 - "a|Package of Something" 
//	gen3 - "a|Package of Something"

//========================================================================vv Template editors, start here! vv========================================================================//
//A few things before you start. Anything after two slashes "//" makes the whole line a "comment." A comment is not executed by the game at all. It's for people like you and me to read
//so things don't get confusing. Anything contained in <> means that the options you have for certain settings are enclosed in that. You do not put the <> when filling out the template.
//Each option will have their own explanation. 1 or true always means on or active. 0 or false always means off or disabled. For those of you with the script archive, COPY THIS SOMEWHERE ELSE
//THEN START EDITING!
//
//Examples:
//	Options:
//		<1/2/3> Means you may only put either 1, 2, OR 3. 
//		<1|2|3> Means the same thing as ^
//		<"">	Means you have to enclose your option in quotes.
//		<''>	Same but with single quotes. It actually really shouldn't matter, if you don't know which one to use, or if you think it might cause issues, use single quotes.

//This quest is fetch_items. When the quest is activated, you either must look for a bunch of items, or one item in a randomly spawned location. Bringing back the items will complete the quest.

#scope server

{
	const QUEST_TYPE "fetch_items" //Don't touch this

	const QUEST_DATA1 "qitem_place"
	//<"info_target prefix"|"(x,y,z);(x,y,z)"> Where do the qitems spawn? If you want to use info_targets, you must name them a prefix and put a number after it. For example, I name the
	//info_targets "qitem_place". I need to add sequential numbers after it, so id have "qitem_place1" "qitem_place2" and so on in my map. My prefix is qitem_place.
	//Ex: const QUEST_DATA1 "qitem_place"

	const QUEST_DATA2 "km;a|Barrel of God knows what"
	//<"qitem code;qitem name"> Which qitem do you use? What do you wanna name the qitem?
	//Ex: const QUEST_DATA2 "bm;a|Barrel of Booze"

	const QUEST_DATA3 0
	//<0|1> Spawn one item at available random locations, rather than one item at each location. The option "1" will spawn only one item at a random location.

	//-----dq/templates/bases/dq_generic_reward-----//
	//vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv//

	const QUEST_REWARD_TYPE "gm"
	//<"gm"/"map"/"script"> What thing handles the reward event? Is it the game master, the map, or a custom event in this script? Dont put the mapname, you just put "map" if you want
	//the map to dish out the reward through a trigger. Case sensitive!
	//Ex: const QUEST_REWARD_TYPE "map"

	const QUEST_REWARD_EVENT "old_helena_warboss_died"
	//<"eventname"> The event that will be triggered on completion. This is either the name of a map trigger, a script event, or a game master event. PARAM1 passed to this event is the
	//player id of whoever is taking the reward, but only if QUEST_REWARD_TYPE is "gm" or "script". Case sensitive! (I think)
	//Ex: const QUEST_REWARD_EVENT "dwarf_quest_reward"

	const QUEST_REWARD_ALL 0
	//<0|1> Attempt to use the QUEST_REWARD_EVENT to reward everyone that was present at the start of the quest? Otherwise whoever took it first will be the only one rewarded.

	const QUEST_COMPLETE_TEXT "(Collect Reward)"
	//<"Turn in quest"> When you use an npc, a menu on the right side will show up with options you can click. This is the option for turning in the quest after the requirements
	//are completed.
	//Ex: const QUEST_COMPLETE_TEXT "Turn in"

	//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^//
	//-----End dq/templates/bases/dq_generic_reward-----//

	//-----dq/templates/bases/dq_generic_menus-----//
	//vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv//

	const QUEST_WAITING_TEXT "ZOMBIE!"
	//<"Hail"> When you use an npc, a menu on the right side will show up with options you can click. You're meeting the npc for the first time, what do you say?
	//Ex: const QUEST_WAITING_TEXT "Hi"

	const QUEST_ASKING_TEXT "As long as they're not mine..."
	//<"Accept"> When you use an npc, a menu on the right side will show up with options you can click. This is what one of those options say after the npc has offered you his quest.
	//Ex: const QUEST_ASKING_TEXT "Sure"

	const QUEST_ACTIVE_TEXT "(In Progress)"
	//<"(In progress)">When you use an npc, a menu on the right side will show up with options you can click, however, the quest isn't done yet. This is the greyed out text that will appear.
	//Ex: const QUEST_ACTIVE_TEXT "In progress"

	const QUEST_SHOW_PROGRESS 1
	//<0|1> Shows the progress of the quest next to the QUEST_ACTIVE_TEXT in the menu.
	//Ex: const QUEST_SHOW_PROGRESS 1

	const QUEST_PROGRESS_VAR QITEMS_FOUND //Don't touch this unless you know what you're doing.
	//<"Var that holds the count"> Don't touch this unless you know what you're doing.

	const QUEST_PROGRESS_MAX QITEM_ORIGIN_AMT //Don't touch this unless you know what you're doing.
	//<"Var that holds the requirement"> Don't touch this unless you know what you're doing.

	//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^//
	//-----End dq/templates/bases/dq_generic_menus-----//

	//-----dq/templates/bases/dq_generic_chat-----//
	//vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv//

	const QUEST_INTRO_CHAT "Me... Brainss... Me barrel'o'brainzz..."
	//<0|"Intro Text"> The npc speaks what the input is. This specific part is what the npc says after you say hi to him.
	//Ex: const QUEST_INTRO_CHAT "I need help with something!"

	const QUEST_INTRO_SOUND 0
	//<0|"sound_directory"> Putting in a sound directory will play the sound whenever the npc says what's above. If you don't want a sound, write 0.
	//Ex: const QUEST_INTRO_SOUND "voices/dwarf/vs_ndwarfm1_hit1.wav"

	const QUEST_ACTIVATE_CHAT 0
	//<0|"Quest accepted text"> The npc speaks what the input is. This specific part is what the npc says after you accept the quest.
	//Ex: const QUEST_ACTIVATE_CHAT "Come back here once you're done."

	const QUEST_ACTIVATE_SOUND "monsters/zombie1/zo_pain1.wav"
	//<0|"sound_directory"> Putting in a sound directory will play the sound whenever the npc says what's above. If you don't want a sound, write 0.
	//Ex: const QUEST_ACTIVATE_SOUND "voices/dwarf/vs_ndwarfm1_hit1.wav"

	const QUEST_FINISHED_CHAT "Brains..."
	//<0|"Quest finished text"> The npc speaks what the input is. This specific part is what the npc says immediately after you finish the conditions for the quest.
	//Ex: const QUEST_FINISHED_CHAT "You've done what's needed."

	const QUEST_FINISHED_SOUND 0
	//<0|"sound_directory"> Putting in a sound directory will play the sound whenever the npc says what's above. If you don't want a sound, write 0.
	//Ex: const QUEST_FINISHED_SOUND "voices/dwarf/vs_ndwarfm1_hit1.wav"

	const QUEST_COMPLETE_CHAT 0
	//<0|"Quest completed text"> The npc speaks what the input is. This specific part is what the npc says after you take the reward.
	//Ex: const QUEST_COMPLETE_CHAT "Thank you. Take this, for your troubles."

	const QUEST_COMPLETE_SOUND "monsters/zombie1/orc_zo_alert10.wav"
	//<0|"sound_directory"> Putting in a sound directory will play the sound whenever the npc says what's above. If you don't want a sound, write 0.
	//Ex: const QUEST_COMPLETE_SOUND "voices/dwarf/vs_ndwarfm1_hit1.wav"

	//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^//
	//-----End dq/templates/bases/dq_generic_chat-----//

	//-----dq/quests/bases/dq_base_quests-----//
	//vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv//

	const QUEST_FADE_ON_COMPLETE "fade"
	//<0|"fade"|"walk_fade"> On quest complete, do I fade? Do I walk while fading?
	//Ex: const QUEST_FADE_ON_COMPLETE "fade"

	const QUEST_GIVER_NAME "a|Zombified Dwarf"
	//<"name"> Change name from the default that your npc is using.
	//Ex: const QUEST_GIVER_NAME "a|Wounded Dwarven Miner"

	const NEW_RACE beloved
	//<race> A new race that you set to the npc. Races are located at the top of the script.
	//Ex: const NEW_RACE good

	const AM_INVINCIBLE 0
	//<0|1> Am I invincible? (May not be targeted as a result) This is disabled in quests that require the npc to survive when the quest is taken.
	//Ex: const AM_INVINCIBLE 0

	const NEW_WIDTH 32
	//<#> How wide is my collision box?
	//Ex: const NEW_WIDTH 32

	const NEW_HEIGHT 32
	//<#> How tall is my collision box?
	//Ex: const NEW_HEIGHT 48

	const MONSTER_MODEL 0
	//<0|"new_model"> Must be precached - must have matching animations or the anims must be redefined in top script. If you don't wanna change the model, leave blank or delete this line.
	//Ex: const MONSTER_MODEL "dwarf/male1.mdl"

	const SUBMODEL_GROUPS "0;2"
	//<"group#;subgroup#"> Sets submodel to use This one's a little wierd. Although Jed's half-life model viewer starts from the index 1, msc starts from 0. So take the model index and
	//subtract it by 1 when filling this out.
	//Ex: const SUBMODEL_GROUPS "0;2"

	const USE_SKIN 0
	//<#> Skin index to use for the mode. This one's a little wierd. Although Jed's half-life model viewer starts from the index 1, msc starts from 0. So take the model index and subtract
	//it by 1 when filling this out.
	//Ex: const USE_SKIN 4

	const SET_SIEGE_MODE 0
	//<0|1> The npc will become a CRITICAL_NPC target for all mobs on map when quest activated. Some quests require this. Monsters will try and target this npc.
	//Ex: const SET_SIEGE_MODE 1

	//-----monsters/base_monster_new-----// Your monster must have this included if you want these options to work.
	//vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv//

	const QUEST_COMBATANT 0
	//<0|1> Do I engage in combat or cower/flee?
	//Ex: const QUEST_COMBATANT 1

	const QUEST_ACTIVE_COMBATANT 0
	//<0|1> If active combatant, then fight before quest activation. (May die before players meet him unless specified in other options)

	//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^//
	//-----End monsters/base_monster_new-----//

	//-----monsters/base_battle_ally-----// Your monster must have this included if you want these options to work.
	//vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv//

	const QUEST_FOLLOWER 0
	//<0|1> The npc will follow whoever took the quest until he dies. If that happens, the npc will follow some other player.
	//Ex: const QUEST_FOLLOWER 1

	const IS_LEADER 0
	//<0|1> Instead of following player, will try to roam ahead to where he is facing.
	//Ex: const IS_LEADER 1

	//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^//
	//-----End monsters/base_battle_ally-----//

	//-----dq/quest_dwarf-----// Your monster must be this if you want these options to work.
	//vvvvvvvvvvvvvvvvvvvvvvvv//

	const USE_LANTERN 1
	//<0|1> Has lantern
	//Ex: const USE_LANTERN 1

	const LANTERN_COLOR "(128,64,0)"
	//<"(R,G,B)"> The color of the lantern using red green and blue. Defaults to (128,64,0)
	//Ex: const LANTERN_COLOR "(128,64,0)"

	setvar INIT_IDLE_MODE "sitting"
	//<"sitting"|"wounded"|"standing"> - defaults to <wounded> for non-combatants, and <sitting> for combatants based on QUEST_COMBATANT setting
	//Ex: setvar INIT_IDLE_MODE "sitting"

	const QUEST_EXPERT_COMBATANT 0
	//<0|1> If expert combatant, unlock a special stun attack.

	//^^^^^^^^^^^^^^^^^^^^^^^^^^^^//
	//-----End dq/quest_dwarf-----//

	//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^//
	//-----End dq/quests/bases/dq_base_quests-----//
}

#include dq/quests/dq_fetch_items //Don't touch this unless you know what you're doing

#include dq/templates/bases/dq_generic_reward //Don't touch this unless you know what you're doing
#include dq/templates/bases/dq_generic_menus //Don't touch this unless you know what you're doing
#include dq/templates/bases/dq_generic_chat //Don't touch this unless you know what you're doing

#include dq/quest_dwarf
//If you want a different npc to be handing out the quest, replace the dq/quest_dwarf with the directory of the preferred npc. Keep in mind though that some of the options up above
//might not work as a result!

{ do_chat_ext_recieve_quest_item

	if ( QUEST_MODE equals 'active' )
	{
		if ( !CHAT_BUSY )
		{
			callevent chat_now "More... Brains..."
			//<"NPC recieved item text"> The npc speaks what the input is. This specific part is what the npc says after you turn in a quest item. You may add more callevent
			//chat_now lines if you want the npc to say more that just one line of dialogue.
			//Ex: callevent chat_now "Thank you. Send over your friends if they have anything for me."

			playsound 2 10 none
			//<"sound_directory"> Putting in a sound directory will play the sound whenever the npc says what's above.
			//Ex: playsound 2 10 "voices/dwarf/vs_ndwarfm1_hit1.wav"
		}
	}
}

{ ext_receive_quest_item //Don't touch this

	callevent 0.1 do_chat_ext_recieve_quest_item
}
