#scope server
// Regorty's Supplier

{
   setvar SOUND_IDLE1 voices/human/male_idle4.wav
   setvar SOUND_IDLE2 voices/human/male_idle5.wav
   setvar SOUND_IDLE3 voices/human/male_idle6.wav
   const SOUND_DEATH none

   setvar STORE_NAME deralia_grocer      //base_vendor
   setvar STORE_TRIGGERTEXT store trade apple   //base_vendor
   
   const NO_JOB 1
}

#include monsters/base_npc
#include monsters/base_chat
#include monsters/base_npc_vendor
#include monsters/base_npc_vendor_confirm
#include monsters/base_civilian
#include monsters/base_xmass

{ npc_spawn

   hp      1/1
   gold      30
   name      Friendly grocer
   //fov      180
   width   32
   height   72
   race      human
   setmodelbody   1 3
   roam      0         //Don't go roaming around
   setmodel       npc/human1.mdl

   catchspeech say_hi hi hello hail greet   
   catchspeech say_apple apple
   catchspeech say_rumour rumours news happenings rumour

   calleventtimed 10 idle
}
{ say_rumor
   callevent say_rumour
}

   //Idling
{ idle

   repeatdelay 35
   volume 3
   playrandomsound 2 SOUND_IDLE1 SOUND_IDLE2 SOUND_IDLE3
}

{ say_hi

  saytext Hey there buddy, I got something to help take the edge off.
  setvar ASKED_APPLE 1
}
{
  //Advertise my apples
  repeatdelay 60

  see player 100

  saytext These apples are normally only sold to Regorty, but today is your lucky day!
}
{ gossip_1

  saytext I heard that there are going to be more variety of apples coming soon.
}

////////////// Shop //////////////////
{ trade_done

   saytext Enjoy and praise the Apple Lord!
}

{ vendor_addstoreitems

   //           |Store name|  |Item name|  |Quantity| |cost%|   
   addstoreitem  STORE_NAME     health_apple 420          100
}

//Rumours
{ say_rumour
   playanim once pondering
   saytext Regorty loves us this I know, for the apples tell me so.
}

{
   setvard NPC_NO_PLAYER_DMG 1
}

{ game_damaged //PARAM1=attacker PARAM2=dmg PARAM3=dmg_type

   if ( NPC_NO_PLAYER_DMG )
   {
      if $get(PARAM1,isplayer)
      setdmg dmg 0
      setdmg hit 0
      returndata 0
   }
}