{ gm_phobia_tele_bandits
	local BANDIT_ID $get_by_name(bandit_ralion)
	if ( $get(BANDIT_ID,isalive) ) setorigin BANDIT_ID $vec(328,2432,-272)
	local BANDIT_ID $get_by_name(bandit_betor)
	if ( $get(BANDIT_ID,isalive) ) setorigin BANDIT_ID $vec(448,2560,-272)
	local BANDIT_ID $get_by_name(bandit_skelr)
	if ( $get(BANDIT_ID,isalive) ) setorigin BANDIT_ID $vec(208,2560,-272)
}

{ gm_phobia_bandit_lights
	callexternal all bandit_ally_lights
}