//Thothie mscave almost entirely underground - no rail plzktnx
//Setup the map's weather
//
{ [shared]

	const MAP_NAME 		'ms_underworldv2'
	const MAP_WEATHER 	fog_red;fog_red;fog_red;fog_red;fog_red;fog_red
	const MAP_ALLOWNIGHT 	0

	setvarg G_MAP_NAME "Underworld"
	setvarg G_MAP_DESC "An old MS 1.35 map, converted for MS:C"
	setvarg G_MAP_DIFF "Levels 15-20 / 200-400hp"
	setvarg G_WARN_HP 200
	
	setvarg G_FORCE_SPAWN_WEATHER 'fog_red'
}

#include worlditems/map_startup
