name: manual dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: compile scripts
        run: pack_dev.bat

      - name: upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: dev binary
          path: ./sc.dll