#include chests/base_treasurechest

{ game_spawn

	local SUPER_ID $get_by_name(outpost_super)
	if ( !$get(SUPER_ID,exists) )
	{
		deleteent ent_me
		exitevent
	}

	callevent tc_add_artifact scroll_lightning_chain 15
	callevent tc_add_artifact scroll2_lightning_chain 15
	callevent tc_add_artifact mana_forget 15
}

{ chest_additems

	callevent add_gold $rand(200,1000) //add gold pouches to chest

	addstoreitem STORENAME mana_demon_blood 1 0
	addstoreitem STORENAME mana_mpotion 1 0
	addstoreitem STORENAME health_spotion 1 0
	addstoreitem STORENAME item_log 1 0

	addstoreitem STORENAME proj_arrow_silvertipped 30 0 0 30
	addstoreitem STORENAME proj_arrow_jagged 30 0 0 30
	addstoreitem STORENAME proj_arrow_fire 60 0 0 30
	addstoreitem STORENAME proj_arrow_poison 30 0 0 30
	addstoreitem STORENAME proj_arrow_frost 60 0 0 30
	addstoreitem STORENAME proj_arrow_holy 30 0 0 30

	if ( $rand(1,2) == 1 ) addstoreitem STORENAME proj_arrow_gholy 30 0 0 30
	
	addstoreitem STORENAME proj_bolt_fire 50 0 0 50
	addstoreitem STORENAME proj_bolt_iron 100 0 0 50
	addstoreitem STORENAME proj_bolt_silver 25 0 0 25
}